#config_version=5
  
game:
  balls_per_game: 3
  allow_start_with_ball_in_drain: true
  allow_start_with_loose_balls: true 
  
config:
- hardware.yaml
- keyboard.yaml
- shots.yaml
- videos.yaml

modes:
  - attract
  - base
  - skill_shot
  - music_player
#  - cellar
  - razorwire


window:
  width: 1366
  height: 768
  title: Mission Pinball Framework - SAW
  resizable: false
  fullscreen: false
  borderless: false
  exit_on_escape: true
  source_display: lcd

displays:
  lcd:
    width: 1366
    height: 768



sound_player:
  mode_attract_started:
    themesong:
      action: play
      loops: -1
  mode_attract_stopped:
    themesong:
      action: stop
  ball_starting: playagame
#  mode_razorwire_started:
#    razorwire:
#      action: play
      
    

      
sound_system:
    tracks:
       music:
          simultaneous_sounds: 3
          volume: 1.0
       voice:
          simultaneous_sounds: 1
          volume: 0.7
       sfx:
          simultaneous_sounds: 8
          volume: 0.9

sounds:

assets:
    sounds:
        default:
            load: preload
        music:
            track: music
        sfx:
            track: sfx
        voice:
            track: voice
    videos:
        default:
            load: preload
            
