#config_version=5
  
config:
- hardware.yaml

modes:
  - attract
  - base
#  - skill_shot


window:
  width: 1366
  height: 768
  title: Mission Pinball Framework - SAW
  resizable: false
  fullscreen: false
  borderless: false
  exit_on_escape: true
  source_display: lcd

displays:
  lcd:
    width: 1366
    height: 768
