#config_version=5
  
game:
  balls_per_game: 3
  allow_start_with_ball_in_drain: true
  allow_start_with_loose_balls: true 
  
config:
- hardware.yaml
- keyboard.yaml
- shots.yaml
- videos.yaml

modes:
  - attract
  - base
  - skillshot
  - music_player
  - cellar
  - selection_mode
  - razorwire
  - reversebeartrap


window:
  width: 1366
  height: 768
  title: Mission Pinball Framework - SAW
  resizable: false
  fullscreen: false
  borderless: false
  exit_on_escape: true
  source_display: lcd

displays:
  lcd:
    width: 1366
    height: 768



sound_player:
  mode_attract_started:
    themesong:
      action: play
      loops: -1
  mode_attract_stopped:
    themesong:
      action: stop
  ball_starting: playagame
  mode_razorwire_started:
    razorwire:
      action: play
  mode_razorwire_complete:
    trapcomplete:
      action: play
 
slides:
  trapcomplete:
    widgets:
    - type: Text
      text: You Survived
      color: AD1400
      font_name: TrajanProRegular
      font_size: 100
      x: 35%
      y: 50%
      animations:
       pre_show_slide:
        - property: opacity
          value: 0
          duration: 1s
        - property: opacity
          value: 1
          duration: 1s
          repeat: true
    - type: image
      image: trapcomplete 
   
  skillshotcomplete:
    widgets:
    - type: image
      image: billyskillshot  
       
slide_player: 
  slide_Spinner1_removed: 
    trapcomplete:
      priority: 400
      expire: 8s   

  mode_skillshot_complete:
    skillshotcomplete:
      action: play
      priority: 400
      expire: 3s

      
sound_system:
    tracks:
       music:
          simultaneous_sounds: 3
          volume: 1.0
       voice:
          simultaneous_sounds: 1
          volume: 1.0
       sfx:
          simultaneous_sounds: 8
          volume: 1.0

sounds:

assets:
    sounds:
        default:
            load: preload
        music:
            track: music
        sfx:
            track: sfx
        voice:
            track: voice
    videos:
        default:
            load: preload
            
