#config_version=5
keyboard:
  z:
    switch: s_left_flipper
  'x':
    switch: s_right_flipper
  s:
    switch: s_start
  1:
    switch: s_trough1
  2:
    switch: s_trough2 
  3:
    switch: s_trough3 
  f:
    switch: s_left_inlane
  g: 
    switch: s_lower_bank_drop_target_opto_upper
  h:
    switch: s_lower_bank_drop_target_opto_middle
  i:
    switch: s_lower_bank_drop_target_opto_lower
  4:
    switch: s_enter_left_ramp
  5:
    switch: s_left_ramp_score_top 
  6:
    switch: s_left_ramp_score_bottom
  n:
    switch: s_left_top_jet_bumper
  t:
    switch: s_right_cellar
  y:
    switch: s_spinner
  p:
    switch: s_plunger
    toggle: true
  7:
    switch: s_right_ramp_down
  8:
    switch: s_right_ramp_score_top
  9:
    switch: s_right_ramp_score_bottom
  0:
    switch: s_upper_bank_drop_target_opto
# temp for demo
  w:
    switch: s_left_bottom_jet_bumper
  e:
    switch: s_right_bottom_jet_bumper
  r:
    switch: s_upper_bottom_jet_bumper
  j:
    switch: s_left_top_jet_bumper
  k:
    switch: s_right_top_jet_bumper
  l:
    switch: s_lower_top_jet_bumper