#config_version=5
mode:
  start_events: mode_skillshot_stopped, mode_base_started, mode_razorwire_complete
  stop_events: 

##! mode: qualify
# mode: qualify
  

  
#shots:
#  cellar:
#    switch: s_right_cellar


variable_player:
  mode_cellar_complete:
    score: 300000
    
counters:
  cellar_qualify_counter:
    starting_count: 0
    count_complete_value: 2
    events_when_complete: mode_cellar_complete
#    reset_events: 
#    enable_events:
 #   disable_events: disable_qualify
#    start_enabled: true
#    persist_state: true
    reset_on_complete: true
    disable_on_complete: false
#    reset_events: mode_cellar_started, cellar_qualify_counter_started
#    restart_events: reset_qualify_modes, mode_cellar_started, cellar_qualify_counter_started
    count_events: cellar_hit
    
