#config_version=6
mode:
  start_events: slide_saw_collect_created
  stop_events: logicblock_cellar_qualify_counter_complete

##! mode: qualify
# mode: qualify
  

  
#shots:
#  cellar:
#    switch: s_right_cellar


variable_player:
  logicblock_cellar_qualify_counter_complete:
    score: 300000
    
counters:
  cellar_qualify_counter:
    starting_count: 0
    count_complete_value: 1
#    reset_events: 
#    enable_events:
 #   disable_events: disable_qualify
#    start_enabled: true
#    persist_state: true
#    reset_on_complete: true
    disable_on_complete: false
#    reset_events: mode_cellar_started, cellar_qualify_counter_started
#    restart_events: reset_qualify_modes, mode_cellar_started, cellar_qualify_counter_started
    count_events: sh_select_mode_hit


sound_player:
    mode_cellar_started:
      BaseMusic:
        action: stop
      ModeQualifiedShootScoop:
        action: play   
        loops: -1
    ball_ending:
      ModeQualifiedShootScoop:
        action: stop
