#config_version=6
mode:
  start_events: ball_starting, mode_skillshot_started, mode_razorwire_stopped, mode_drillchair_stopped, mode_flammablejelly_stopped, mode_quadshotgun_stopped, mode_reversebeartrap_stopped, mode_zeptest_stopped, mode_hacksaw_multiball_stopped, mode_jigsaw_multiball_stopped, mode_shackle_multiball_stopped, mode_jigsaw_multiball_complete, mode_hacksaw_multiball_complete, mode_shackle_multiball_complete, mode_hostage_stopped, mode_hostage_complete, mode_survival_instinct_stopped, mode_survival_instinct_complete, e_mb_mode_stopping, mode_puzzle_hurryup_stopped, mode_lil_billy_stopped
  stop_events: mode_selection_mode_started, mode_make_your_choice_hurryup_started, multiball_mb_jigsaw_started, multiball_mb_hacksaw_started, multiball_mb_shackle_started, mode_razorwire_started, mode_drillchair_started, mode_flammablejelly_started, mode_quadshotgun_started, mode_reversebeartrap_started, mode_zeptest_started, mode_hostage_started, mode_survival_instinct_started, e_mb_mode_active, e_mode_qualify_disabled, mode_puzzle_hurryup_started, mode_bonus_started, mode_lil_billy_started
  priority: 100

counters:
  minimode_pops_counter:
    starting_count: 20
    count_complete_value: 0
    direction: down
    start_enabled: true
#    persist_state: true
    reset_on_complete: true
    disable_on_complete: false    
    events_when_complete: minimode_pops_complete 
    count_events: sw_pops

  minimode_standups_counter:
    starting_count: 10
    count_complete_value: 0
    direction: down
    start_enabled: true
    reset_on_complete: true
    disable_on_complete: false
    events_when_complete: minimode_standups_complete 
    count_events: sw_standup  
    
  minimode_slings_counter:
    starting_count: 60
    count_complete_value: 0
    direction: down
    start_enabled: true
    reset_on_complete: true
    disable_on_complete: false    
    events_when_complete: minimode_slings_complete 
    count_events: sw_slingshot

  minimode_inlanes_counter:
    starting_count: 9
    count_complete_value: 0
    direction: down
    start_enabled: true
    reset_on_complete: true
    disable_on_complete: false    
    events_when_complete: minimode_inlanes_complete 
    count_events: sw_inlane    
    
  minimode_spinners_counter:
    starting_count: 40
    count_complete_value: 0
    direction: down
    start_enabled: true
    reset_on_complete: true
    disable_on_complete: false    
    events_when_complete: minimode_spinners_complete 
    count_events: spinner_spinner_hit 

  minimode_ramps_counter:
    starting_count: 5
    count_complete_value: 0
    direction: down
    start_enabled: true
#    persist_state: true
    reset_on_complete: true
    disable_on_complete: false    
    events_when_complete: minimode_ramps_complete 
    count_events: ssh_left_ramp_hit, ssh_right_ramp_hit
    
  minimode_loops_counter:
    starting_count: 5
    count_complete_value: 0
    direction: down
    start_enabled: true
    reset_on_complete: true
    disable_on_complete: false    
    events_when_complete: minimode_loops_complete 
    count_events: ssh_leftloop_hit, ssh_rightloop_hit, s_inner_loop_active

  minimode_drops_counter:
    starting_count: 8
    count_complete_value: 0
    direction: down
    start_enabled: true
    reset_on_complete: true
    disable_on_complete: false
    events_when_complete: minimode_drops_complete 
    count_events: sw_drop_target 