#config_version=6
mode:
  priority: 500
  start_events: game_ending, start_high_score
  use_wait_queue: true
high_score:
  _overwrite: true
  enter_initials_timeout: 90
  award_slide_display_time: 4s
  # define your high score categories and the awards
  categories:
    score:
        - GRAND CHAMPION
        - HIGH SCORE 1
        - HIGH SCORE 2
        - HIGH SCORE 3
        - HIGH SCORE 4
    loops:
        - LOOP CHAMPION
#    tilt_bonus:
#        - BONUS LOST
  # set the defaults
  defaults:
    score:
      - JWF: 1000000
      - ECK: 900000
      - ADC: 800000
      - SAW: 700000
      - SAW: 6000

    loops:
      - TST: 42
 #   tilt_bonus:
 #     - TST: 250000
# optional: change the slides (you can omit all the following)
slide_player:
  _overwrite: true   
  mode_high_score_started:  
    high_score_enter_initials:
      target: lcd


slides:
  _overwrite: true   
  high_score_enter_initials:

    - type: text
      font_size: 125
      font_name: Skilt Gothic W04 Thin
      text: PLAYER  (number)
      color: C2E3E0 
      x: center
      y: center + 300
      
    - type: text
      font_size: 100
      font_name: Skilt Gothic W04 Thin
      text: (player|award)
      color: red
      x: center
      y: center + 100

      
            
    - type: text
      font_name: sawesome
      font_size: 80
      text: (score)
      color: C2E3E0 
      number_grouping: true      
      x: center
      y: center - 300
      
    - type: text_input
      initial_char: A
      dynamic_x: false
      key: high_score
      font_size: 150
      font_name: sawesome
      max_chars: 3
      x: center
      y: center - 150
      shift_left_event: s_left_flipper_button_active
      shift_right_event: s_right_flipper_button_active
      select_event: s_action_button_active
      color: C2E3E0 
      
    - type: text
      text: '<          >'
      font_size: 120
      x: center
      y: center
      color: C2E3E0 
      
    - type: text
      text: ''
      key: high_score
      font_size: 100
      font_name: sawesome      
      x: center
      y: center
      color: C2E3E0 
    - type: image            
      image: billyskillshot
      opacity: 0.8

sound_player:
  s_left_flipper_button_active:
    LSling1:
      action: play
  s_right_flipper_button_active:
    LSling1:
      action: play
  s_action_button_active:
    OrbitWoosh6:
      action: play      
  mode_high_score_started: 
    initials:
      action: play
      loops: -1
    BaseMusic:
      action: stop
  mode_high_score_stopped:
    BaseMusic:
      action: stop
    initials:
      action: stop
