#config_version=6
mode:
  priority: 500
  start_events: game_ending, start_high_score
  use_wait_queue: true
high_score:
  _overwrite: true
  enter_initials_timeout: 30s
  award_slide_display_time: 2s
  # define your high score categories and the awards
  categories:
    score:
      - GRAND CHAMPION
      - HIGH SCORE 1
      - HIGH SCORE 2
      - HIGH SCORE 3
      - HIGH SCORE 4
    puzzle_pieces:
      - PUZZLE PIECE CHAMPION
    modes_completed:
      - TRAP COMPLETION CHAMPION
    modes_attempted:
      - TRAP ATTEMPT CHAMPION
    choice_hurryup_hits:
      - MAKE YOUR CHOICE CHAMPION
    items_collected:
      - ITEM HOARDING CHAMPION
    drillchair_points:
      - DRILL CHAIR CHAMPION
    flammablejelly_points:
      - FLAMMABLE JELLY CHAMPION
    quadshotgun_points:
      - QUAD SHOTGUN CHAMPION
    razorwire_points:
      - RAZORWIRE CHAMPION
    reversebeartrap_points:
      - REVERSE BEAR TRAP CHAMPION
    zeptest_points:
      - ZEP'S TEST CHAMPION
  defaults:
    score:
      - JWF: 1000000
      - ECK: 900000
      - ADC: 800000
      - SAW: 700000
      - TST: 6000

    puzzle_pieces:
      - TST: 0
    modes_completed:
      - TST: 0
    modes_attempted:
      - TST: 0
    choice_hurryup_hits:
      - TST: 0
    items_collected:
      - TST: 0
    drillchair_points:
      - TST: 0
    flammablejelly_points:
      - TST: 0
    quadshotgun_points:
      - TST: 0
    razorwire_points:
      - TST: 0
    reversebeartrap_points:
      - TST: 0
    zeptest_points:
      - TST: 0
  vars:
    puzzle_pieces:
      - player: puzzle_pieces
    modes_completed:
      - player: modes_completed
    modes_attempted:
      - player: modes_attempted
    choice_hurryup_hits:
      - player: choice_hurryup_hits
    items_collected:
      - player: items_collected
    drillchair_points:
      - player: drillchair_points
    flammablejelly_points:
      - player: flammablejelly_points
    quadshotgun_points:
      - player: quadshotgun_points
    razorwire_points:
      - player: razorwire_points
    reversebeartrap_points:
      - player: reversebeartrap_points
    zeptest_points:
      - player: zeptest_points
 #   tilt_bonus:
 #     - TST: 250000
# optional: change the slides (you can omit all the following)
slide_player:
  _overwrite: true   
  high_score_enter_initials: high_score_enter_initials
  high_score_award_display: high_score_award_display

slides:
  _overwrite: true   
  high_score_enter_initials:

    - type: text
      font_size: 65
      font_name: Skilt Gothic W04 Thin
      text: PLAYER  (player_num)
      color: C2E3E0 
      x: center
      y: center + 320
      outline_color: black
      outline_width: 9
      
    - type: text
      font_size: 80
      font_name: Skilt Gothic W04 Thin
      text: (award)
      color: red
      x: center
      y: center + 225
      outline_color: black
      outline_width: 9
            
    - type: text
      font_name: sawesome
      font_size: 80
      text: (score)
      color: C2E3E0 
      number_grouping: true      
      x: center
      y: center - 300
      outline_color: black
      outline_width: 7
      
    - type: text_input
      initial_char: A
      dynamic_x: false
      key: high_score
      font_size: 150
      font_name: sawesome
      max_chars: 3
      x: center
      y: center - 150
      z: 2
      shift_left_event: s_left_flipper_button_active
      shift_right_event: s_right_flipper_button_active
      select_event: s_action_button_active
      color: C2E3E0 
      
    - type: text
      text: '<          >'
      font_size: 120
      x: center
      y: center
      color: C2E3E0 
      
    - type: text
      text: ''
      key: high_score
      font_size: 100
      font_name: sawesome      
      x: center
      y: center
      z: 2
      color: C2E3E0   
      animations:
        show_slide:
          - property: opacity
            value: 1
            duration: 0.3s
            easing: in_out_quint
          - property: opacity
            value: 0
            duration: 0.3s
            repeat: true
            easing: in_out_quint
    - type: image            
      image: billyskillshot
      opacity: 0.8

  high_score_award_display:
    - type: text
      font_size: 100
      font_name: Skilt Gothic W04 Thin
      text: PLAYER  (player_name)
      color: C2E3E0 
      x: center
      y: center + 320
      outline_color: black
      outline_width: 9
      
    - type: text
      font_size: 100
      font_name: Skilt Gothic W04 Thin
      text: (award)
      color: red
      x: center
      y: center + 225
      outline_color: black
      outline_width: 9
            
    - type: text
      font_name: sawesome
      font_size: 100
      text: (value)
      color: C2E3E0 
      number_grouping: true      
      x: center
      y: center + 130
      outline_color: black
      outline_width: 7      
    - type: text
      text: ''
      key: high_score
      font_size: 100
      font_name: sawesome      
      x: center
      y: center
      color: C2E3E0   
    - type: image            
      image: billyskillshot
      opacity: 0.8

sound_player:
  s_left_flipper_button_active:
    LSling1:
      action: play
  s_right_flipper_button_active:
    LSling1:
      action: play
  s_action_button_active:
    OrbitWoosh6:
      action: play      
  mode_high_score_started: 
    BaseMusic:
      action: stop
    initials:
      priority: 500
      action: play
      loops: -1
  mode_high_score_stopped:
    BaseMusic:
      action: stop
    initials:
      action: stop
  mode_high_score_will_stop:
    initials:
      action: stop