#config_version=6

show_player:
  mode_attract_started: attract_display_loop
  mode_attract_started.1: attract_lightshows_loop_test

#ORIGINAL CODE. Changed since attract light show was not playing in sequence. 
#show_player:
#  mode_attract_started:
#    attract_display_loop:
#      speed: 1
#    attract_lightshows_loop:
#      speed: 4

sound_player:
  mode_attract_started:
    BaseMusic:
      action: stop  
    initials:
      action: stop    
    Shithole:
      action: play
      loops: 0
    #HelloZeppPt1:
    #  action: play
    #  loops: 3  