#config_version=5
mode:
  start_events: start_mode_mystery
  stop_events: stop_mode_mystery, ball_ended
  

event_player:
  mystery_hit: enable_mystery

ball_holds:
  mystery_scoop:
    balls_to_hold: 1
    hold_devices: bd_mystery
    enable_events: enable_mystery
    disable_events: end_mystery, multiball_active
    release_one_events: end_mystery