#config_version=5
mode:
  start_events: ball_starting, mode_skillshot_started
  priority: 100

slide_player:
  mode_razorwire_complete: 
    trapcomplete:
      priority: 400
      expire: 5s   #EK shortened to time with lightshow

  mode_drillchair_complete: 
    trapcomplete:
      priority: 400
      expire: 8s  

  mode_reversebeartrap_complete: 
    trapcomplete:
      priority: 400
      expire: 8s   
      
  mode_skillshot_complete:
    skillshotvideo:
      action: play
      priority: 400
      expire: 8s
  ballsavetemp_hit:
    ballsavevideo:
      action: play
      priority: 400
      expire: 8s
  tiltwarningtemp_hit:
    tiltwarningvideo:
      action: play
      priority: 400
      expire: 8s
  mysteryawardtemp_hit:
    mysteryawardvideo:
      action: play
      priority: 400
      expire: 8s
  extraballtemp_hit:
    extraballvideo:
      action: play
      priority: 400
      expire: 8s
      
  mode_base_started:
    widgets:

      - type: image
        image: spiral
        opacity: 0.7
        y: top-20
        x: right-165

      - type: text
        font_name: TrajanProRegular
        text: PLAYER (number)
        y: top-25
        x: left+105
        font_size: 38
        color: C2E3E0

      - type: image
        image: rustpipe2
        y: top-44
        x: left+95
        opacity: 0.5
        
      - type: text
        text: BALL (ball)
        font_name: TrajanProRegular
        y: top-25
        x: right-70
        color: C2E3E0
        font_size: 38
        
      - type: image
        image: rustpipe2
        y: top-44
        x: right-90
        opacity: 0.5
 
#player 1 
      - type: text
        text: (score)
        number_grouping: true
        y: 16
        x: 25
        font_size: 36
        anchor_x: left
        anchor_y: bottom
        font_name: TrajanProRegular
        color: C2E3E0
        
      - type: image
        image: hacksawUI
        opacity: 0.9
        y: 1
        x: 1
        anchor_x: left
        anchor_y: bottom
        
#player 2      
      - type: Text
        text: PRESS START
        font_name: TrajanProRegular
        font_size: 28
        y: 35
        x: left+490
        color: red
        animations:
          pre_show_slide:
          - property: opacity
            value: 0
            duration: 1.5s
          - property: opacity
            value: 1
            duration: 1.5s
            repeat: true
      - type: image
        image: hacksawUI
        opacity: 0.9
        y: 1
        x: left+520
        anchor_y: bottom
            
#player 3   
      - type: Text
        text: PRESS START
        font_name: TrajanProRegular
        font_size: 28
        y: 35
        x: left+840
        color: red
        animations:
          pre_show_slide:
          - property: opacity
            value: 0
            duration: 1.5s
          - property: opacity
            value: 1
            duration: 1.5s
            repeat: true 
      - type: image
        image: hacksawUI
        opacity: 0.9
        y: 1
        x: left+870
        anchor_y: bottom
       
#player 4   
      - type: Text
        text: PRESS START
        font_name: TrajanProRegular
        font_size: 28
        y: 35
        x: left+1180
        color: red
        animations:
          pre_show_slide:
          - property: opacity
            value: 0
            duration: 1.5s
          - property: opacity
            value: 1
            duration: 1.5s
            repeat: true 
      - type: image
        image: hacksawUI
        opacity: 0.9
        y: 1
        x: left+1210
        anchor_y: bottom

      - type: video
        video: gordonsaw 
        width: 1366
        height: 768
        end_behavior: loop
#      - type: image
#        image: gordonsaw


variable_player:
  left_ramp_hit:
    score: 75000
  right_ramp_hit:
    score: 115000
  upper_drop_target_hit:
    score: 145000
  left_top_pop_hit:
    score: 573
  cellar_hit:
    score: 100000
  spinner_hit:
    score: 5000
  left_inlane_hit:
    score: 1300
  left_outlane_hit:
    score: 1700

# EK testing lightshow on shot action
show_player:
#  mode_skillshot_complete:
  mode_base_started:   
    flash_token:
      loops: -1
      speed: 2
      show_tokens:
        led: arrow
        color1: ffffff

#  mode_base_started.1:       
#   flash_token2:
#      loops: -1
#      speed: 3
#     show_tokens:
#        led: l_left_return_lane
#        color1: red

  spinner_hit:
    flash_token:
      loops: 2
      speed: 8
      show_tokens:
        led: l_right_loop_arrow
        color1: 46eb34

  left_inlane_hit:
    flash_token:
      loops: 2
      speed: 8
      show_tokens:
        led: l_left_return_lane
        color1: red

  mysteryawardtemp_hit:
    mystery_flash:
       loops: 0
       show_tokens:
        led: insert, gi, jet_bumper, flasher
        color1: white

#  trap completed
  slide_trapcomplete_active:
    rw_complete:
      loops: 2
      speed: 25

 
 
sound_player:
  base_mode_started:
    playagame:
      action: play
  mode_razorwire_started:
    razorwire:
      action: play
  mode_razorwire_complete:
    trapcomplete:
      action: play

  mode_drillchair_started:
    drillchair:
      action: play  
  mode_drillchair_complete:
    trapcomplete:
      action: play

  mode_reversebeartrap_started:
    reversebeartrap:
      action: play
  mode_reversebeartrap_complete:
    trapcomplete:
      action: play
 
  mode_quadshotgun_complete:
    trapcomplete:
      action: play
 
slides:
#  trapcomplete:
#    widgets:
#    - type: Text
#      text: You Survived
#      color: AD1400
#      font_name: TrajanProRegular
#      font_size: 100
#      x: 35%
#      y: 50%
#      animations:
#       pre_show_slide:
#        - property: opacity
#          value: 0
#          duration: 1s
#        - property: opacity
#          value: 1
#          duration: 1s
#          repeat: true
#    - type: image
#      image: trapcomplete 
      
  trapcomplete:
    widgets:
    - type: video
      video: trapcomplete
      width: 1366
      height: 768      
      
  skillshotvideo:
    widgets:
    - type: video
      video: skillshotvideo
      width: 1366
      height: 768
      
  ballsavevideo:
    widgets:
    - type: video
      video: ballsave
      width: 1366
      height: 768
  tiltwarningvideo:
    widgets:
    - type: video
      video: tiltwarning
      width: 1366
      height: 768
  mysteryawardvideo:
    widgets:
    - type: video
      video: mysteryaward
      width: 1366
      height: 768
  extraballvideo:
    widgets:
    - type: video
      video: extraball
      width: 1366
      height: 768
       
