#config_version=6
##! mode: jigsaw_multiball

mode:
  start_events: startmode_jigsaw_multiball
  stop_events: stop_mode_jigsaw_multiball, mode_jigsaw_multiball_complete, player_turn_stopped, player_turn_ended
  priority: 155

multiballs:
  mb_jigsaw:
    ball_count: 3
    shoot_again: 15s
    start_events: logicblock_jigsaw_multiball_qualify_complete

variable_player:
  multiball_mb_jigsaw_started:
    score: 3000000

slides:
  sl_JigsawMB:
    widgets:
    - type: video
      video: JigsawMB

slide_player:
  multiball_mb_jigsaw_started:
    sl_JigsawMB:
      priority: 600
      expire: 6s
show_player:
  multiball_mb_jigsaw_started:
    disc_right_chase:
      loops: -1
      speed: 10
      show_tokens:
        color1: beartrap
    disc_middle_chase:
      loops: -1
      speed: 10
      show_tokens:
        color1: beartrap
    disc_left_chase:
      loops: -1
      speed: 10
      show_tokens:
        color1: beartrap
  mode_jigsaw_multiball_complete:
      disc_left_chase: stop
      disc_middle_chase: stop
      disc_right_chase: stop
  ball_ending:
      disc_left_chase: stop
      disc_middle_chase: stop
      disc_right_chase: stop
coil_player:
  multiball_mb_jigsaw_started:
    c_left_spin_disc:
      action: enable
      hold_power: 1.0
    c_middle_spin_disc:
      action: enable
      hold_power: 1.0
    c_right_spin_disc:
      action: enable
      hold_power: 1.0
  mode_jigsaw_multiball_complete:
    c_right_spin_disc:
      action: off
    c_middle_spin_disc:
      action: off
    c_left_spin_disc:
      action: off
  ball_ending:
    c_right_spin_disc:
      action: off
    c_middle_spin_disc:
      action: off
    c_left_spin_disc:
      action: off