#config_version=6
##! mode: jigsaw_multiball

mode:
  #start_events: startmode_jigsaw_multiball
  start_events: logicblock_jigsaw_multiball_qualify_complete
  stop_events: stop_mode_jigsaw_multiball, mode_jigsaw_multiball_complete, player_turn_stopped, player_turn_ended,  multiball_mb_jigsaw_ended
  priority: 183

multiballs:
  mb_jigsaw:
    ball_count: 3
    shoot_again: 10s
    start_events: start_jigsaw_multiball

variable_player:
  #multiball_mb_jigsaw_started:
  #  score: 3000000
  shot_jigsaw_left_loop_sp_jigsaw_mb_lit_hit:
    score: 750000 + (device.counters.cnt_jigsaw_jackpot_value.value * 75000)
  shot_jigsaw_inner_loop_sp_jigsaw_mb_lit_hit:
    score: 750000 + (device.counters.cnt_jigsaw_jackpot_value.value * 75000)
  shot_jigsaw_left_standup_rightramp_sp_jigsaw_mb_lit_hit:
    score: 750000 + (device.counters.cnt_jigsaw_jackpot_value.value * 75000)
  shot_jigsaw_right_standup_rightramp_sp_jigsaw_mb_lit_hit:
    score: 750000 + (device.counters.cnt_jigsaw_jackpot_value.value * 75000)
  shot_jigsaw_right_loop_sp_jigsaw_mb_lit_hit:
    score: 750000 + (device.counters.cnt_jigsaw_jackpot_value.value * 75000)

  shot_jigsaw_superjackpot1_sp_jigsaw_mb_lit_hit:
    score: 750000  + (device.counters.cnt_jigsaw_jackpot_value.value * 75000 * 3)

  start_jigsaw_multiball:
    jigsaw_value:
      int: 750000
      action: set
    jigsaw_super_value:
      int: 750000
      action: set
  e_jigsaw_jackpot_value:
    jigsaw_value:
      int: 750000 + (device.counters.cnt_jigsaw_jackpot_value.value * 75000)
      action: set
    jigsaw_super_value:
      int: 750000 + (device.counters.cnt_jigsaw_jackpot_value.value * 75000 * 3) 
      action: set
  
counters:
  cnt_jigsaw_mb_jackpot_p1:
    starting_count: 0
    count_complete_value: 5
    enable_events: slide_sl_JigsawMB_active
#    persist_state: true
    reset_on_complete: true
    disable_on_complete: false   
    count_events: shot_jigsaw_left_loop_sp_jigsaw_mb_lit_hit, shot_jigsaw_inner_loop_sp_jigsaw_mb_lit_hit, shot_jigsaw_left_standup_rightramp_sp_jigsaw_mb_lit_hit, shot_jigsaw_right_standup_rightramp_sp_jigsaw_mb_lit_hit, shot_jigsaw_right_loop_sp_jigsaw_mb_lit_hit
    events_when_complete: jigsaw_mb_jackpot_p1_complete

# currently set to jackpot set + super + jackpot set + super
  cnt_jigsaw_phase_tracking:
    starting_count: 0
    count_complete_value: 2
    start_enabled: true
    events_when_complete: e_jigsaw_phase2
    count_events: sg_jigsaw_p1_lit_complete
  cnt_jigsaw_phase1_tracking:
    starting_count: 0
    count_complete_value: 1
    start_enabled: true
    events_when_complete: e_jigsaw_phase1
    count_events: sg_jigsaw_p1_lit_complete

  cnt_jigsaw_jackpot_value:
    starting_count: 0
#    count_complete_value: 10
    start_enabled: true
#    events_when_complete: e_jigsaw_jackpot_max
    count_events: e_jigsaw_jackpot_value

slides:
  sl_JigsawMB:
    widgets:
    - type: video
      video: JigsawMB
  sl_JigsawMB_Jackpot:
    widgets:
    - type: video
      video: jackpot_jigsaw
  sl_JigsawMB_SuperJackpot:
    widgets:
    - type: video
      video: superjackpot_jigsaw

slide_player:
  multiball_mb_jigsaw_started:
    sl_JigsawMB:
      priority: 600
      expire: 6s
  sg_jigsaw_p1_lit_hit:
    sl_JigsawMB_Jackpot:
      priority: 600
      expire: 2.2s
  shot_jigsaw_superjackpot1_sp_jigsaw_mb_lit_hit:
    sl_JigsawMB_SuperJackpot:
      priority: 600
      expire: 2.2s
  shot_jigsaw_superjackpot2_sp_jigsaw_mb_lit_hit:
    sl_JigsawMB_SuperJackpot:
      priority: 600
      expire: 2.2s
show_player:
  multiball_mb_jigsaw_started:
    disc_right_chase:
      loops: -1
      speed: 10
      show_tokens:
        color1: beartrap
    sh_jigsaw_jackpot:
      speed: 1
      show_tokens: 
        leds: l_right_standup_arrow, bear_flasher
    disc_middle_chase:
      loops: -1
      speed: 10
      show_tokens:
        color1: beartrap
    disc_left_chase:
      loops: -1
      speed: 10
      show_tokens:
        color1: beartrap
  mode_jigsaw_multiball_complete:
      disc_left_chase: stop
      disc_middle_chase: stop
      disc_right_chase: stop
  ball_ending:
      disc_left_chase: stop
      disc_middle_chase: stop
      disc_right_chase: stop
  jigsaw_mb_jackpot_p1_complete:
      top_drop_chase:
        loops: -1
        speed: 20
        show_tokens:
          color1: beartrap
  sg_hacksaw_p1_lit_hit:
      colorwash_opposite_glitter:
        speed: 20
  shot_jigsaw_superjackpot1_sp_jigsaw_mb_lit_hit:
      top_drop_chase:
        loops: -1
        show_tokens:
          color1: off
      colorwash_opposite_glitter:
        speed: 20
  shot_jigsaw_superjackpot2_sp_jigsaw_mb_lit_hit:
      top_drop_chase:
        loops: -1
        show_tokens:
          color1: off
      colorwash_opposite_glitter:
        speed: 20
  e_jackpot_show_off:
      colorwash_opposite_glitter: stop
  start_jigsaw_multiball:
    mb_ballsave:
      loops: 9

  stop_mode_jigsaw_multiball: stop
coil_player:
  multiball_mb_jigsaw_started:
    c_left_spin_disc:
      action: enable
      hold_power: 1.0
    c_middle_spin_disc:
      action: enable
      hold_power: 1.0
    c_right_spin_disc:
      action: enable
      hold_power: 1.0
  mode_jigsaw_multiball_complete:
    c_right_spin_disc:
      action: off
    c_middle_spin_disc:
      action: off
    c_left_spin_disc:
      action: off
  ball_ending:
    c_right_spin_disc:
      action: off
    c_middle_spin_disc:
      action: off
    c_left_spin_disc:
      action: off

shots:
  shot_jigsaw_left_loop:
    reset_events: mode_jigsaw_multiball_stopped, player_turn_stopped, player_turn_ended
    switches: s_left_loop_bottom, s_left_loop_top
    profile: sp_jigsaw_mb
    show_tokens:
      leds: l_left_loop_arrow
    control_events:
      - events: ball_starting
        state: 0
      - events: slide_sl_JigsawMB_active
        state: 1
      - events: shot_jigsaw_left_loop_sp_jigsaw_mb_lit_hit
        state: 0
      - events: shot_jigsaw_superjackpot1_sp_jigsaw_mb_lit_hit
        state: 1
  shot_jigsaw_inner_loop:
    reset_events: mode_jigsaw_multiball_stopped, player_turn_stopped, player_turn_ended
    switches: s_inner_loop
    profile: sp_jigsaw_mb
    show_tokens:
      leds: l_inner_loop_arrow
    control_events:
      - events: ball_starting
        state: 0
      - events: slide_sl_JigsawMB_active
        state: 1
      - events: shot_jigsaw_inner_loop_sp_jigsaw_mb_lit_hit
        state: 0
      - events: shot_jigsaw_superjackpot1_sp_jigsaw_mb_lit_hit
        state: 1
  shot_jigsaw_left_standup_rightramp:
    reset_events: mode_jigsaw_multiball_stopped, player_turn_stopped, player_turn_ended
    switches: s_left_standup_right_ramp
    profile: sp_jigsaw_mb
    show_tokens:
      leds: l_left_standup_right_ramp_arrow
    control_events:
      - events: ball_starting
        state: 0
      - events: slide_sl_JigsawMB_active
        state: 1
      - events: shot_jigsaw_left_standup_rightramp_sp_jigsaw_mb_lit_hit
        state: 0
      - events: shot_jigsaw_superjackpot1_sp_jigsaw_mb_lit_hit
        state: 1
  shot_jigsaw_right_standup_rightramp:
    reset_events: mode_jigsaw_multiball_stopped, player_turn_stopped, player_turn_ended
    switches: s_right_standup_right_ramp
    profile: sp_jigsaw_mb
    show_tokens:
      leds: l_right_standup_right_ramp_arrow
    control_events:
      - events: ball_starting
        state: 0
      - events: slide_sl_JigsawMB_active
        state: 1
      - events: shot_jigsaw_right_standup_rightramp_sp_jigsaw_mb_lit_hit
        state: 0
      - events: shot_jigsaw_superjackpot1_sp_jigsaw_mb_lit_hit
        state: 1
  shot_jigsaw_right_loop:
    reset_events: mode_jigsaw_multiball_stopped, player_turn_stopped, player_turn_ended
    switches: s_right_loop_bottom, s_right_loop_top
    profile: sp_jigsaw_mb
    show_tokens:
      leds: l_right_loop_arrow
    control_events:
      - events: ball_starting
        state: 0
      - events: slide_sl_JigsawMB_active
        state: 1
      - events: shot_jigsaw_right_loop_sp_jigsaw_mb_lit_hit
        state: 0
      - events: shot_jigsaw_superjackpot1_sp_jigsaw_mb_lit_hit
        state: 1
  shot_jigsaw_superjackpot1:
    reset_events: mode_jigsaw_multiball_stopped, player_turn_stopped, player_turn_ended
    switches: s_upper_bank_drop_target_opto
    profile: sp_jigsaw_mb
    control_events:
      - events: ball_starting
        state: 0
      - events: e_jigsaw_phase1
        state: 1
      - events: shot_jigsaw_superjackpot1_sp_jigsaw_mb_lit_hit
        state: 0
  shot_jigsaw_superjackpot2:
    reset_events: mode_jigsaw_multiball_stopped, player_turn_stopped, player_turn_ended
    switches: s_upper_bank_drop_target_opto
    profile: sp_jigsaw_mb
    control_events:
      - events: ball_starting
        state: 0
      - events: e_jigsaw_phase2
        state: 1
      - events: shot_jigsaw_superjackpot2_sp_jigsaw_mb_lit_hit
        state: 0

shot_profiles:
  sp_jigsaw_mb:
    advance_on_hit: false
    states:
      - name: jigsaw_not_ready
        show: "sh_jigsaw_not_ready"
      - name: lit
        show: "sh_jigsaw_on"           # a default show to turn of the led. change if you want to do something on unlit shots
      #- name: collected
      #  show: "sh_jigsaw_off"               # a default show to turn of the led. change if you want to do something on unlit shots

shot_groups:
  sg_jigsaw_p1:
    shots: shot_jigsaw_left_loop, shot_jigsaw_left_standup_rightramp, shot_jigsaw_right_standup_rightramp, shot_jigsaw_right_loop, shot_jigsaw_inner_loop


shows:
  sh_jigsaw_on:    # define our show to indicate the state
    - duration: 0.3s
      lights:
        (leds): beartrap
    - duration: 0.3s
      lights:
        (leds): off
  sh_jigsaw_not_ready:    # define our show to indicate the state
    - duration: 0.3s
      lights:
        (leds): off
  sh_jigsaw_jackpot:
    - duration: 0.3s
      lights:
        (leds): shotgun
    - duration: 0.3s
      lights:
        (leds): off

sound_player:
  sg_jigsaw_p1_lit_hit:
    Jackpot:
      action: play
  shot_jigsaw_superjackpot1_sp_jigsaw_mb_lit_hit:
    SuperJackpot:
      action: play

widgets:
  w_jigsaw_multiball:
    - type: Text
      text: Jigsaw Multiball - Shoot RED ARROWS to collect JACKPOTS
      color: white
      x: 50%
      y: 95%
      z: 2
      font_size: 52
      font_name: Skilt Gothic W04 Thin
      outline_color: black
      outline_width: 7
  w_jigsaw_multiball_value:
    - type: text
      text: (player|jigsaw_value)
      number_grouping: true 
      x: 50%
      y: 28%
      z: 7
      font_size: 90
      font_name: Mustkill     
      outline_color: black
      outline_width: 7
  w_jigsaw_multiball_SuperJackpot_value:
    - type: text
      text: (player|jigsaw_super_value)
      number_grouping: true 
      x: 50%
      y: 28%
      z: 7
      font_size: 90
      font_name: Mustkill     
      outline_color: black
      outline_width: 7

widget_player:
  multiball_mb_jigsaw_started:
    w_jigsaw_multiball:
      slide: base_slide_main
      action: add
  stop_mode_jigsaw_multiball:
    w_jigsaw_multiball:
      action: remove
  mode_jigsaw_multiball_complete:
    w_jigsaw_multiball:  
      action: remove
  ball_ended:
    w_jigsaw_multiball:
      action: remove

  sg_jigsaw_p1_lit_hit:
    w_jigsaw_multiball_value:
      slide: sl_JigsawMB_Jackpot
      action: add
  #stop_jackpot_widget:
  #  w_jigsaw_multiball_value:
  #    action: remove
  #  w_jigsaw_multiball_SuperJackpot_value:
  #    action: remove
  shot_jigsaw_superjackpot1_sp_jigsaw_mb_lit_hit:
    w_jigsaw_multiball_SuperJackpot_value:
      slide: sl_JigsawMB_SuperJackpot
      action: add

event_player:
  mode_jigsaw_multiball_started: start_jigsaw_multiball|0.3s
  sg_jigsaw_p1_lit_hit: stop_jackpot_widget|2.3s
  shot_jigsaw_superjackpot1_sp_jigsaw_mb_lit_hit: stop_jackpot_widget|2.3s, e_jackpot_show_off|1s
  s_middle_standup_active: e_jigsaw_jackpot_value|0.2s
  s_right_standup_active: e_jigsaw_jackpot_value|0.2s
  sg_hacksaw_p1_lit_hit: e_jackpot_show_off|1s
  shot_jigsaw_superjackpot2_sp_jigsaw_mb_lit_hit: e_jackpot_show_off|1s