#config_version=6
##! mode: jigsaw_multiball

mode:
  start_events: startmode_jigsaw_multiball
  stop_events: stop_mode_jigsaw_multiball, mode_jigsaw_multiball_complete, player_turn_stopped, player_turn_ended
  priority: 155

multiballs:
  mb_jigsaw:
    ball_count: 2
    shoot_again: 15s
    start_events: logicblock_jigsaw_multiball_qualify_complete

variable_player:
  multiball_mb_jigsaw_started:
    score: 3000000

slides:
  sl_JigsawMB:
    widgets:
    - type: video
      video: JigsawMB

slide_player:
  multiball_mb_jigsaw_started:
    sl_JigsawMB:
      priority: 500
      expire: 6s
