#config_version=6
##! mode: shackle_multiball_qualify

mode:
  start_events: startmode_shackle_multiball_qualify, mode_razorwire_stopped, mode_drillchair_stopped, mode_flammablejelly_stopped, mode_quadshotgun_stopped, mode_reversebeartrap_stopped, mode_zeptest_stopped, mode_hacksaw_multiball_stopped, mode_jigsaw_multiball_stopped, mode_shackle_multiball_stopped, mode_make_your_choice_hurryup_stopped, mode_jigsaw_multiball_complete, mode_hacksaw_multiball_complete, mode_shackle_multiball_complete
  stop_events: mode_selection_mode_started, mode_make_your_choice_hurryup_started, multiball_mb_jigsaw_started, multiball_mb_hacksaw_started, multiball_mb_shackle_started, mode_razorwire_started, mode_drillchair_started, mode_flammablejelly_started, mode_quadshotgun_started, mode_reversebeartrap_started, mode_zeptest_started, mode_make_your_choice_hurryup_started
  priority: 183

accruals:
  acc_shackle_mb_qualify:
    events:
      - s_left_standup_active
      - s_right_standup_active
    reset_on_complete: false
    persist_state: true
    disable_on_complete: false
    reset_events: multiball_lock_mbl_shackle_locked_ball

counters:
  cnt_shackle_mb_counter:
    starting_count: 0
    count_complete_value: 2
    enable_events: 
    disable_events: 
    start_enabled: true
    persist_state: true
    reset_on_complete: true
    disable_on_complete: false   
    count_events: multiball_lock_mbl_shackle_locked_ball
    events_when_complete: logicblock_shackle_multiball_qualify_complete

  cnt_shackle_mb_lock1:
    starting_count: 0
    count_complete_value: 1
    start_enabled: true
    persist_state: true
    events_when_complete: e_shackle_lock1
    count_events: logicblock_cnt_shackle_mb_counter_updated{value==1}

  cnt_shackle_mb_lock2:
    starting_count: 0
    count_complete_value: 1
    start_enabled: true
    persist_state: true
    events_when_complete: e_shackle_lock2
    count_events: logicblock_cnt_shackle_mb_counter_updated{value==2}

multiball_locks:
  mbl_shackle:
    #debug: true
    balls_to_lock: 2
    lock_devices: bd_top_saucer
    enable_events: logicblock_acc_shackle_mb_qualify_complete 
      #disable_events: sg_lockshot_complete{state=="unlit"}
      #reset_count_for_current_player_events: multiball_lock_sword_multiball_lock_full

variable_player:
  logicblock_cnt_shackle_mb_counter_hit:
    shackle_mb_lock_counter:
      action: set
      int: (count) 
  logicblock_shackle_multiball_qualify_complete:
    shackle_mb_lock_counter:
      action: set
      int: 0

shows:
  sh_shackle_mb_qualify_hit_ready:
    - duration: -1
      shows:
        flash_color:
          show_tokens:
            color: color_hacksaw_mb
            leds: (leds)
          speed: 4
  sh_shackle_mb_qualify_hit_locked:
    - duration: -1
      lights:
        (leds): color_hacksaw_mb
  sh_shackle_mb_end:
    - duration: -1
      lights:
        (leds): off
  sh_shackle_mb_qualify_hit:
    - duration: 0.3s
      lights:
        (leds): color_hacksaw_mb
    - duration: 0.3s
      lights:
        (leds): off

show_player:
  logicblock_acc_shackle_mb_qualify_complete{device.multiball_locks.mbl_shackle.locked_balls == 0}:
    sh_shackle_mb_qualify_hit:
      show_tokens:
        leds: l_right_ramp_triangle1
  multiball_lock_mbl_shackle_locked_ball{device.multiball_locks.mbl_shackle.locked_balls == 1}:
    sh_shackle_mb_qualify_hit_locked:
      show_tokens:
        leds: l_right_ramp_triangle1
    shackle_mb_lock:
      loops: 0
      speed: 30
  logicblock_acc_shackle_mb_qualify_complete{device.multiball_locks.mbl_shackle.locked_balls == 1}:
    sh_shackle_mb_qualify_hit_locked:
      show_tokens:
        leds: l_right_ramp_triangle1
    sh_shackle_mb_qualify_hit:
      show_tokens:
        leds: l_right_ramp_triangle2
  multiball_lock_mbl_shackle_locked_ball{device.multiball_locks.mbl_shackle.locked_balls == 2}:
    sh_shackle_mb_qualify_hit_locked:
      show_tokens:
        leds: l_right_ramp_triangle1, l_right_ramp_triangle2
    shackle_mb_lock:
      loops: 0
      speed: 30
  #logicblock_acc_shackle_mb_qualify_complete{device.multiball_locks.mbl_shackle.locked_balls == 2}:
  #  sh_shackle_mb_qualify_hit_ready:
  #    show_tokens:
  #      leds: l_right_ramp_triangle2
  #multiball_lock_mbl_shackle_lock_locked_ball{device.multiball_locks.mbl_shackle.locked_balls == 3}:
  #  sh_shackle_mb_qualify_hit_locked:
  #    show_tokens:
  #      leds: l_right_ramp_triangle1, l_right_ramp_triangle2
  #  shackle_mb_lock:
  #    loops: 0
  #    speed: 30
  multiball_mb_shackle_ended:
    sh_shackle_mb_end:
      show_tokens:
        leds: l_right_ramp_triangle1, l_right_ramp_triangle2
  logicblock_acc_shackle_mb_qualify_hit{step==0}:
    sh_shackle_mb_qualify_hit:
      show_tokens:
        leds: l_left_standup_arrow
      speed: 4
      loops: 5
  logicblock_acc_shackle_mb_qualify_hit{step==1}:
    sh_shackle_mb_qualify_hit:
      show_tokens:
        leds: l_right_standup_arrow
      speed: 4
      loops: 5

  logicblock_cnt_shackle_mb_counter_updated{value==1}:
    sh_shackle_mb_qualify_hit_locked:
      show_tokens:
        leds: l_right_ramp_triangle1   
  logicblock_cnt_shackle_mb_counter_updated{value==2}:
    sh_shackle_mb_qualify_hit_locked:
      show_tokens:
        leds: l_right_ramp_triangle1, l_right_ramp_triangle2

sound_player:
  e_shackle_mb_qualify_hit_one:
    LockIsLit:
      action: play
  slide_sl_Shackle_locked_1_active:
    Ball1Locked:
      action: play
  slide_sl_Shackle_locked_2_active:
    Ball2Locked:
      action: play

slides:
  sl_Shackle_locked_1:
    widgets:
    - type: video
      video: shackle_lock1
      width: 1366
      height: 768 
  sl_Shackle_locked_2:
    widgets:
    - type: video
      video: shackle_lock2
      width: 1366
      height: 768 

slide_player:
  e_shackle_lock1:
    sl_Shackle_locked_1:
      priority: 500
      expire: 3s
  e_shackle_lock2:
    sl_Shackle_locked_2:
      priority: 500
      expire: 3s