#config_version=6                 
mode:
  start_events: selection_mode_zeptest_selected
  stop_events: stop_mode_zeptest, ball_ended, ball_will_end, player_zeptest_60s_zeptest_timer_tick{value < 1}
  priority: 181
 
ball_saves:
  bs_zeptest:
    active_time: 5s
    hurry_up_time: 2s
#    grace_period: 2s
#    enable_events: mode_base_started
#    disable_events2: ball_save_default_disabled
    timer_start_events: player_zeptest_60s_zeptest_timer_tick{value==60}
    early_ball_save_events: sw_outlane, s_trough6_active
    auto_launch: true
    balls_to_save: 1

sequences:
  zeptest:
    events:
      - sw_lower_drop_target
      - sw_lower_drop_target
      - sw_lower_drop_target
      - drop_target_dt_upper_drop1_down
      #- ssh_left_ramp_hit
      - machine_var_audits_switches_s_right_ramp_score_top
      - drop_target_dt_upper_drop1_down   
    reset_on_complete: false
    persist_state: true
    events_when_complete: mode_zeptest_complete, stop_mode_zeptest

timers:
  60s_zeptest_timer:
    start_value: 68
    end_value: 0
    direction: down
    control_events:
      - action: start
        event: mode_zeptest_started
        
variable_player:
  logicblock_zeptest_hit{step==3}:
    score: 2000000 + (current_player.syringes_used * 1000000)
  logicblock_zeptest_hit{step==4}:
    score: 1000000 + (current_player.syringes_used * 1000000)
  logicblock_zeptest_hit{step==5}:
    score: 1000000 + (current_player.syringes_used * 1000000)
  #logicblock_zeptest_hit{step==6}:
  #  score: 1000000    
  mode_zeptest_complete:
    score: 5000000 + (current_player.syringes_used * 1500000)
  timer_your_timer_tick:
    60s_zeptest_timer:
      int: device.timers.your_timer.ticks_remaining
      action: set        
    
slides:
  zeptestvideo:
    widgets:
    - type: video
      video: zeptestvideo 
      width: 1366
      height: 768      
  sl_mode_zeptest01:
    widgets:
    - type: video
      video: mode_zeptest01
      width: 1366
      height: 768
  sl_mode_zeptest02:
    widgets:
    - type: video
      video: mode_zeptest02
      width: 1366
      height: 768
  sl_mode_zeptest03:
    widgets:
    - type: video
      video: mode_zeptest03
      width: 1366
      height: 768
  sl_mode_zeptest04:
    widgets:
    - type: video
      video: mode_zeptest04
      width: 1366
      height: 768
  mode_zeptest_shot01:
    widgets:
    - type: video
      video: mode_zeptest_shot01
      width: 1366
      height: 768
  mode_zeptest_shot02:
    widgets:
    - type: video
      video: mode_zeptest_shot02
      width: 1366
      height: 768
  mode_zeptest_shot03:
    widgets:
    - type: video
      video: mode_zeptest_shot03
      width: 1366
      height: 768
      
  zeptestUI:
   widgets:
    - type: image
      image: hacksawUI
      opacity: 0.5
      y: 1
      x: 1
      anchor_x: left
      anchor_y: bottom
    - type: text
      text: (score)
      number_grouping: true
      y: 16
      x: 25
      font_size: 36
      anchor_x: left
      anchor_y: bottom
      font_name: TrajanProRegular
      color: B17BE3
    - type: Text
      text: (player|zeptest_60s_zeptest_timer_tick) Seconds Left
      font_size: 55
      font_name: TrajanProRegular
      color: CC8899
      y: 90%
      
    - type: Text
      text: "To find the Poison Antidote:"
      font_size: 50
      font_name: TrajanProRegular
      outline_color: black
      outline_width: 7
      color: AECCE4
      x: 50%
      y: 62%    
      z: 1      
    - type: Text
      text: "You Have 60 Seconds To Enable The Cameras"
      color: CC8899
      font_name: TrajanProRegular
      font_size: 35
      y: 145
      animations:
       pre_show_slide:
        - property: opacity
          value: 0
          duration: 1s
        - property: opacity
          value: 1
          duration: 1s
          repeat: true
    - type: Text
      text: "and Collect the Antidote"
      color: CC8899
      font_name: TrajanProRegular
      font_size: 35
      y: 110
      animations:
       pre_show_slide:
        - property: opacity
          value: 0
          duration: 1s
        - property: opacity
          value: 1
          duration: 1s
          repeat: true          
    - type: image
      image: zeptest
      opacity: 0.45
#      width: 1366
#      height: 768 
#    transition:
#     type: fade
#     duration: 0.2s

widgets:
   w_zeptestUI:
    - type: image
      image: hacksawUI
      opacity: 1.0
      y: 1
      x: 1
      z: 2
      anchor_x: left
      anchor_y: bottom
    - type: text
      text: (score)
      number_grouping: true
      y: 16
      x: 25
      z: 2
      font_size: 36
      anchor_x: left
      anchor_y: bottom
      font_name: TrajanProRegular
      color: B17BE3
    - type: Text
      text: 00:(player|zeptest_60s_zeptest_timer_tick)
      font_size: 100
      font_name: digitalclockfont
      color: red
      x: 50%
      y: 83.2%
      z: 2
    - type: rectangle
      width: 420
      height: 130
      x: 50%
      y: 84.5%
      z: 2
      corner_radius: 20
      corner_segments: 20
      color: black


   zep_shot_update1:
    - type: Text
      text: " Hit All 3 Drop Targets"
      font_size: 60
      font_name: TrajanProRegular
      outline_color: black
      outline_width: 7
      color: BDD5E7
      x: 50%
      y: 48%
      z: 1
      animations:
        add_to_slide:
          - property: opacity
            value: 0
          - property: opacity
            value: 1
            duration: 1000ms
            timing: after_previous
   zep_shot_update2:
    - type: Text
      text: " Hit X Marks the Spot"
      font_size: 60
      font_name: TrajanProRegular
      outline_color: black
      outline_width: 7
      color: BDD5E7
      x: 50%
      y: 48%   
      z: 1
      animations:
        add_to_slide:
          - property: opacity
            value: 0
          - property: opacity
            value: 1
            duration: 1000ms
            timing: after_previous
   #zep_shot_update3:
   # - type: Text
   #   text: " Hit the Left Ramp"
   #   font_size: 60
   #   font_name: TrajanProRegular
   #   color: BDD5E7
   #   x: 58%
   #   y: 48%   
   #   z: 1
   #   animations:
   #     add_to_slide:
   #       - property: opacity
   #         value: 0
   #       - property: opacity
   #         value: 1
   #         duration: 1000ms
   #         timing: after_previous
   zep_shot_update4:
    - type: Text
      text: " Hit the Right Ramp"
      font_size: 60
      font_name: TrajanProRegular
      color: BDD5E7
      x: 50%
      y: 48%        
      z: 1
      animations:
        add_to_slide:
          - property: opacity
            value: 0
          - property: opacity
            value: 1
            duration: 1000ms
            timing: after_previous
   zep_shot_update5:
    - type: Text
      text: " X marks the Spot to Collect the Antidote"
      font_size: 50
      font_name: TrajanProRegular
      outline_color: black
      outline_width: 7
      color: BDD5E7
      x: 50%
      y: 48%      
      z: 1
      animations:
        add_to_slide:
          - property: opacity
            value: 0
          - property: opacity
            value: 1
            duration: 1000ms
            timing: after_previous
   w_syringe_button:
    - type: image
      image: SyringeButtonImg
      x: 89%
      y: 22%
      z: 2      
    - type: Text
      text: Press To Spot Next Shot
      font_size: 45
      font_name: Mustkill
      outline_color: black
      outline_width: 7
      color: BDD5E7
      x: 83.8%
      y: 8%   
      z: 2
    - type: Text
      text: Shots Worth +250k
      font_size: 45
      font_name: Mustkill
      outline_color: black
      outline_width: 7
      color: BDD5E7
      x: 87%
      y: 3%   
      z: 2

    
 
widget_player:
 player_zeptest_60s_zeptest_timer_tick{value==60}:
   w_zeptestUI:
     slide: sl_mode_zeptest01
     action: add
 logicblock_zeptest_updated{value==3}: 
   w_zeptestUI:
     slide: sl_mode_zeptest02
     action: add
 logicblock_zeptest_updated{value==4}: 
   w_zeptestUI:
     slide: sl_mode_zeptest03
     action: add
 logicblock_zeptest_updated{value==5}:
   w_zeptestUI:
     slide: sl_mode_zeptest04
     action: add
 shot_zeptest_button_sp_zeptest_lit_hit:
  w_syringe_button:
    slide: sl_mode_zeptest01
    action: add
 slide_sl_mode_zeptest02_active{current_player.syringes_used==1}:
   w_syringe_button:
     slide: sl_mode_zeptest02
     action: add
 slide_sl_mode_zeptest03_active{current_player.syringes_used==1}:
   w_syringe_button:
     slide: sl_mode_zeptest03
     action: add 
 slide_sl_mode_zeptest04_active{current_player.syringes_used==1}:
   w_syringe_button:
     slide: sl_mode_zeptest04
     action: add 

slide_player:
  mode_zeptest_started: 
    zeptestvideo:
      priority: 500
      expire: 8s
  slide_zeptestvideo_removed: 
    sl_mode_zeptest01:
      priority: 400
      expire: 60.5s
  ball_save_bs_zeptest_saving_ball:
    ballsavevideo:
      action: play
      priority: 400
      expire: 5s

  logicblock_zeptest_updated{value==3}: 
    sl_mode_zeptest01:
      action: remove  
    sl_mode_zeptest02:
      priority: 400
      expire: 60s
  logicblock_zeptest_updated{value==4}: 
    sl_mode_zeptest02:
      action: remove 
    sl_mode_zeptest03:
      priority: 400
      expire: 60s
  logicblock_zeptest_updated{value==5}:
    sl_mode_zeptest03:
      action: remove 
    sl_mode_zeptest04:
      priority: 400
      expire: 60s

  logicblock_zeptest_hit{step==3}:
    mode_zeptest_shot01:
      priority: 401
      expire: 3s
  logicblock_zeptest_hit{step==4}:
    mode_zeptest_shot02:
      priority: 401
      expire: 3s
  logicblock_zeptest_hit{step==5}:
    mode_zeptest_shot03:
      priority: 401
      expire: 3s   
shows:
  sh_zeptest_ballsave:
    - duration: 0.5s
      lights:
        (leds): drillchair
    - duration: 0.5s
      lights:
        (leds): off
  sh_zeptest_ballsave_end:
    - duration: -1
      lights:
        (leds): off 
  zeptest_dropbank:    
    - duration: -1      
      lights:    
        (leds): (color1)
  zeptest_mode:
    - duration: 0.15s
      lights:
        (leds): zeptest
    - duration: 0.15s
      lights:
        (leds): off
show_player:
  player_zeptest_60s_zeptest_timer_tick{value==62}:
    mystery_flash:
      loops: 0
      speed: 5
      show_tokens:
        led: l_mystery_scoop
        color1: white
  player_zeptest_60s_zeptest_timer_tick{value==60}:
    sh_zeptest_ballsave:
      show_tokens:
        leds: l_live_again
      loops: 4
  ball_save_bs_zeptest_disabled:
    sh_zeptest_ballsave_end:
      show_tokens:
        leds: l_live_again
      loops: -1
  logicblock_zeptest_updated{value==0}:
      skillshot_chase:
        loops: -1
        speed: 5
        show_tokens:
          color1: zepstest
  logicblock_zeptest_updated{value==1}:
      skillshot_chase:
        loops: -1
        speed: 5
        show_tokens:
          color1: zepstest
        priority: 181
      zeptest_dropbank:
        loops: -1
        show_tokens:
          color1: zepstest
          leds: l_skill_shot3
        priority: 182
      starpost_cycle:
        loops: 1
        speed: 20
        show_tokens:
          color1: zepstest
        priority: 170
  logicblock_zeptest_updated{value==2}:
      skillshot_chase:
        loops: -1
        speed: 5
        show_tokens:
          color1: zepstest
        priority: 181
      zeptest_dropbank:
        loops: -1
        show_tokens:
          color1: zepstest
          leds: l_skill_shot2,l_skill_shot3
        priority: 182
      starpost_cycle:
        loops: 1
        speed: 20
        show_tokens:
          color1: zepstest
        priority: 170
  logicblock_zeptest_updated{value==3}:
      top_drop_chase:
        loops: -1
        speed: 14
        show_tokens:
          color1: zepstest
      zeptest_dropbank: 
        loops: -1
        show_tokens:
          leds: l_skill_shot2, l_skill_shot3
          color1: off
      skillshot_chase:
        loops: -1
        show_tokens:
          color1: off
      starpost_cycle:
        loops: 1
        speed: 20
        show_tokens:
          color1: zepstest
        priority: 170
  #logicblock_zeptest_hit{step==4}:
  #    left_ramp_chase:
  #      loops: -1
  #      speed: 5
  #      show_tokens:
  #        color1: zepstest
  #    top_drop_chase:
  #      loops: -1
  #      show_tokens:
  #        color1: off
  #    starpost_cycle:
  #      loops: 1
  #      speed: 20
  #      show_tokens:
  #        color1: zepstest
  #      priority: 170
  logicblock_zeptest_updated{value==4}:
      right_ramp_chase:
        loops: -1
        speed: 5
        show_tokens:
          color1: zepstest
      left_ramp_chase:
        loops: -1
        show_tokens:
          color1: off
      starpost_cycle:
        loops: 1
        speed: 20
        show_tokens:
          color1: zepstest
        priority: 170
      top_drop_chase:
        loops: -1
        show_tokens:
          color1: off
  logicblock_zeptest_updated{value==5}:
      top_drop_chase:
        loops: -1
        speed: 14
        show_tokens:
          color1: zepstest
      right_ramp_chase:
        loops: -1
        show_tokens:
          color1: off
      starpost_cycle:
        loops: 1
        speed: 20
        show_tokens:
          color1: zepstest
        priority: 170

  mode_zeptest_started:     
    gi_on:
      show_tokens:
        color1: zepstest
    zeptest_mode:
      show_tokens:
        leds: l_zeptest_mode
    starpost_on:
      show_tokens:
        color1: 6E6E6E   
      priority: 169
    speaker_heartbeat:
      show_tokens:
        color1: zepstest
    trough_on:
      show_tokens:
        color1: zepstest
    flipper_on:
      show_tokens:
        color1: zepstest
    cabinet_heartbeat:
      show_tokens:
        color1: zepstest
    topper_heartbeat:
      show_tokens:
        color1: zepstest

  player_zeptest_60s_zeptest_timer_tick{value==50}:
    speaker_heartbeat:
      speed: 2
      show_tokens:
        color1: zepstest
  player_zeptest_60s_zeptest_timer_tick{value==40}:
    speaker_heartbeat:
      speed: 3
      show_tokens:
        color1: zepstest
  player_zeptest_60s_zeptest_timer_tick{value==30}:
    speaker_heartbeat:
      speed: 4
      show_tokens:
        color1: zepstest
  player_zeptest_60s_zeptest_timer_tick{value==20}:
    speaker_heartbeat:
      speed: 5
      show_tokens:
        color1: zepstest
  player_zeptest_60s_zeptest_timer_tick{value==10}:
    speaker_heartbeat:
      speed: 6
      show_tokens:
        color1: zepstest
  player_zeptest_60s_zeptest_timer_tick{value==5}:
    speaker_heartbeat:
      speed: 9
      show_tokens:
        color1: zepstest

sound_player:
  mode_zeptest_started:
    ZepsTestIntro:
      action: play
  player_zeptest_60s_zeptest_timer_tick{value==60}:
    ZepsTestModeStart:
      action: play
  player_zeptest_60s_zeptest_timer_tick{value < 1}:
    ZepsTestModeStart:
      action: stop

event_player: 
  slide_sl_mode_zeptest01_active: e_primary_mode_active
  shot_zeptest_button_sp_zeptest_lit_hit{device.sequences.zeptest.value == 0}: 
    - sw_lower_drop_target|0.1s
    - sw_lower_drop_target|0.2s
    - sw_lower_drop_target|0.3s
  shot_zeptest_button_sp_zeptest_lit_hit{device.sequences.zeptest.value == 3}:
    - drop_target_dt_upper_drop1_down
  shot_zeptest_button_sp_zeptest_lit_hit{device.sequences.zeptest.value == 4}:
    - machine_var_audits_switches_s_right_ramp_score_top
  shot_zeptest_button_sp_zeptest_lit_hit{device.sequences.zeptest.value == 5}:
    - drop_target_dt_upper_drop1_down

  player_shot_shot_zeptest_button_enabled{change==1}: e_zeptest_action_button|1s