#config_version=6
mode:
  start_events: start_mystery_mode
  stop_events: ball_ended, e_release_mystery, sh_select_mode_hit, mode_hacksaw_multiball_started, mode_shackle_multiball_started, mode_jigsaw_multiball_started, mode_hostage_started, mode_make_your_choice_hurryup_started, mode_puzzle_hurryup_started, mode_survival_instinct_started
  priority: 182


event_player:
  sh_mystery_hit: e_enable_mystery
  slide_Mystery5Million_removed: e_release_mystery
  slide_MysteryMinus1Million_removed: e_release_mystery
  slide_MysteryExtraBallLit_removed: e_release_mystery
  slide_MysteryEscapeOutlane_removed: e_release_mystery
  slide_MysteryItemWorkshop_removed: e_release_mystery
  slide_MysteryBonusMultiplier_removed: e_release_mystery
  slide_MysteryPlayfieldMultiplier_removed: e_release_mystery
  slide_MysteryAddALetter_removed: e_release_mystery
  slide_MysteryAdvanceVirtualLock_removed: e_release_mystery

  e_mystery_5million: e_slide_5million|8s
  e_mystery_minus1million: e_slide_minus1million|8s
  e_mystery_extraballlit: e_slide_extraballlit|8s
  e_mystery_outlane: e_slide_outlane|8s
  e_mystery_workshop: e_slide_workshop|8s
  e_mystery_bonus: e_slide_bonus|8s
  e_mystery_playfield: e_slide_playfield|8s
  e_mystery_letter: e_slide_letter|8s
  e_mystery_mb_lock: e_slide_mb_lock|8s

#ball_holds:
#  mystery_scoop:
#    balls_to_hold: 1
#    hold_devices: bd_mystery
#    enable_events: enable_mystery
#    disable_events: end_mystery, multiball_active
#    release_one_events: slide_Mystery5Million_removed, slide_MysteryMinus5Million_removed, slide_MysteryExtraBall_removed


#EK added
# this is not working but I don't know why. The show in the base.yaml is working
shows:
  mystery_lit:
    - duration: 1.5s
      lights:
        (leds): jelly
    - duration: 1.5s
      lights:
        (leds): off
  mystery_off:
    - duration: -1
      lights:
        (leds): off

show_player:
  mode_mystery_started:
    mystery_lit:
      show_tokens:
        leds: l_mystery_scoop
      loops: -1
  sh_mystery_hit:
    mystery_off:
      show_tokens:
        leds: l_mystery_scoop
      loops: -1

# light show temporarily disabled as it was throwing c_mystery_scoop over 1.0 hold power almost every mystery award since neg. led value fix.
  e_enable_mystery:
    mystery_flash:
       loops: 0
       show_tokens:
        led: insert, gi, jet_bumper, flasher, l_mystery_scoop
        color1: white

random_event_player:
  sh_mystery_hit:
    events:
      e_mystery_5million: 12 #numbers show probability of event
      e_mystery_minus1million: 5
      e_mystery_extraballlit: 6
      e_mystery_outlane: 14
      e_mystery_workshop: 25
      e_mystery_bonus: 7
      e_mystery_playfield: 7
      e_mystery_letter{device.counters.cnt_saw_qualify.value<3}: 15
      e_mystery_mb_lock{device.counters.cnt_jigsaw_mb_qualify.value<3}: 9
#      mystery_award_3_event: 20
#      mystery_award_4_event: 30
    force_all: true
  e_mystery_workshop:
    events:
      minimode_pops_complete: 12.5
      minimode_standups_complete: 12.5 
      minimode_scoops_complete: 12.5
      minimode_inlanes_complete: 12.5
      minimode_spinners_complete: 12.5   
      minimode_ramps_complete: 12.5   
      minimode_loops_complete: 12.5
      minimode_drops_complete: 12.5
    force_all: true

variable_player:
  e_mystery_5million:
    score: 5000000
  e_mystery_minus1million:
    score: -1000000
  e_mystery_bonus:
    bonus_multiplier:
      int: 1
      action: add 
    bonus_x:
      int: 1
      action: add
  e_mystery_playfield:
    pf_multiplier:
      int: 1
      action: add    

# extra_balls:
#   mystery_extraball_award:
#     award_events: e_mystery_extraball

slides:
  Mystery5Million:
    widgets:
    - type: video
      video: Mystery5Million    
      width: 1366
      height: 768
  MysteryMinus1Million:
    widgets:
    - type: video
      video: MysteryMinus1Million    
      width: 1366
      height: 768
  MysteryExtraBallLit:
    widgets:
    - type: video
      video: ExtraBallIsLit
      width: 1366
      height: 768
  MysteryEscapeOutlane:
    widgets:
    - type: video
      video: MysteryEscapeOutlane 
      width: 1366
      height: 768
  MysteryItemWorkshop:
    widgets:
    - type: video
      video: MysteryItemWorkshop
      width: 1366
      height: 768
  MysteryBonusMultiplier:
    widgets:
    - type: video
      video: MysteryBonusMultiplier
      width: 1366
      height: 768
  MysteryPlayfieldMultiplier:
    widgets:
    - type: video
      video: MysteryPlayfieldMultiplier
      width: 1366
      height: 768
  MysteryAddALetter:
    widgets:
    - type: video
      video: MysteryAddALetter
      width: 1366
      height: 768
  MysteryAdvanceVirtualLock:
    widgets:
    - type: video
      video: MysteryAdvanceVirtualLock
      width: 1366
      height: 768

slide_player:
  e_enable_mystery:
    mysteryawardvideo:
      action: play
      priority: 192
      expire: 8s
  e_slide_5million: 
    # mysteryawardvideo:
    #   action: remove
    Mystery5Million:
      priority: 191
      expire: 3s
  e_slide_minus1million: 
    # mysteryawardvideo:
    #   action: remove
    MysteryMinus1Million:
      priority: 191
      expire: 3s
  e_slide_extraballlit: 
    # mysteryawardvideo:
    #   action: remove
    MysteryExtraBallLit:
      priority: 191
      expire: 5s
  e_slide_outlane: 
    # mysteryawardvideo:
    #   action: remove
    MysteryEscapeOutlane:
      priority: 191
      expire: 3s
  e_slide_workshop: 
    # mysteryawardvideo:
    #   action: remove
    MysteryItemWorkshop:
      priority: 191
      expire: 3s
  e_slide_bonus: 
    # mysteryawardvideo:
    #   action: remove
    MysteryBonusMultiplier:
      priority: 191
      expire: 3s
  e_slide_playfield: 
    # mysteryawardvideo:
    #   action: remove
    MysteryPlayfieldMultiplier:
      priority: 191
      expire: 3s
  e_slide_letter:
    # mysteryawardvideo:
    #   action: remove
    MysteryAddALetter:
      priority: 191
      expire: 3s
  e_slide_mb_lock:
    MysteryAdvanceVirtualLock:
      priority: 191
      expire: 3s

widgets:
  mystery_ready:
    - type: Text
      text: Mystery Is Lit
      color: jelly
      x: 50%
      y: 85%
      z: 2
      font_size: 55
      font_name: Mustkill
      animations:
        add_to_slide:
        - property: opacity
          value: 0
          duration: 1s
        - property: opacity
          value: 1
          duration: 1s
          repeat: true 

widget_player:
  player_shot_mystery_enabled{value==True}:
    mystery_ready:
      slide: base_slide_main
      action: add
  player_shot_mystery_enabled{value==False}:
    mystery_ready:
      slide: base_slide_main
      action: remove

shots:
  sh_mystery:
    switch: s_left_scoop
    disable_events: mode_trap_select_started, multiball_active
    enable_events: mode_mystery_started, mode_drillchair_stopped, mode_flammablejelly_stopped, mode_quadshotgun_stopped, mode_razorwire_stopped, mode_reversebeartrap_stopped, mode_zeptest_stopped