#config_version=6
mode:
  start_events: start_mystery_mode
  stop_events: ball_ended, e_release_mystery
  priority: 115


event_player:
  sh_mystery_hit: e_enable_mystery
  slide_Mystery5Million_removed: e_release_mystery
  slide_MysteryMinus5Million_removed: e_release_mystery
  slide_MysteryExtraBall_removed: e_release_mystery
  slide_MysteryEscapeOutlane_removed: e_release_mystery

#ball_holds:
#  mystery_scoop:
#    balls_to_hold: 1
#    hold_devices: bd_mystery
#    enable_events: enable_mystery
#    disable_events: end_mystery, multiball_active
#    release_one_events: slide_Mystery5Million_removed, slide_MysteryMinus5Million_removed, slide_MysteryExtraBall_removed


#EK added
# this is not working but I don't know why. The show in the base.yaml is working
shows:
  mystery_lit:
    - duration: 0.5s
      lights:
        (leds): jelly
    - duration: 0.5s
      lights:
        (leds): off
  mystery_off:
    - duration: -1
      lights:
        (leds): off

show_player:
  mode_mystery_started:
    mystery_lit:
      show_tokens:
        leds: l_mystery_scoop
      loops: -1
  sh_mystery_hit:
    mystery_off:
      show_tokens:
        leds: l_mystery_scoop
      loops: -1
  e_enable_mystery:
    mystery_flash:
       loops: 0
       show_tokens:
        led: insert, gi, jet_bumper, flasher, l_mystery_scoop
        color1: white

random_event_player:
  sh_mystery_hit:
    events:
      e_mystery_5million: 75 #numbers show probability of event
      e_mystery_minus5million: 5
      e_mystery_extraball: 5
      e_mystery_outlane: 15
#      mystery_award_3_event: 20
#      mystery_award_4_event: 30
    force_all: true

variable_player:
  e_mystery_5million:
    score: 5000000
  e_mystery_minus5million:
    score: -5000000

extra_balls:
  mystery_extraball_award:
    award_events: e_mystery_extraball

slides:
  Mystery5Million:
    widgets:
    - type: video
      video: Mystery5Million    
      width: 1366
      height: 768
  MysteryMinus5Million:
    widgets:
    - type: video
      video: MysteryMinus5Million    
      width: 1366
      height: 768
  MysteryExtraBall:
    widgets:
    - type: video
      video: MysteryExtraBall    
      width: 1366
      height: 768
  MysteryEscapeOutlane:
    widgets:
    - type: video
      video: MysteryEscapeOutlane 
      width: 1366
      height: 768

slide_player:
  e_mystery_5million: 
    Mystery5Million:
      expire: 11s
  e_mystery_minus5million: 
    MysteryMinus5Million:
      expire: 11s
  e_mystery_extraball: 
    MysteryExtraBall:
      expire: 11s
  e_mystery_outlane: 
    MysteryEscapeOutlane:
      expire: 11s


widgets:
  mystery_ready:
    - type: Text
      text: Mystery Is Lit
      color: jelly
      x: 50%
      y: 85%
      z: 2
      font_size: 55
      font_name: Mustkill
      animations:
        add_to_slide:
        - property: opacity
          value: 0
          duration: 1s
        - property: opacity
          value: 1
          duration: 1s
          repeat: true 

widget_player:
  player_shot_mystery_enabled{value==True}:
    mystery_ready:
      slide: base_slide_main
      action: add
  player_shot_mystery_enabled{value==False}:
    mystery_ready:
      slide: base_slide_main
      action: remove

shots:
  sh_mystery:
    switch: s_left_scoop
    disable_events: mode_trap_select_started, multiball_active
    enable_events: mode_mystery_started, mode_drillchair_stopped, mode_flammablejelly_stopped, mode_quadshotgun_stopped, mode_razorwire_stopped, mode_reversebeartrap_stopped, mode_zeptest_stopped