#config_version=6
##! mode: hacksaw_multiball

mode:
  start_events: startmode_hacksaw_multiball
  stop_events: stop_mode_hacksaw_multiball, mode_hacksaw_multiball_complete
  priority: 165

multiball_locks:
  hacksaw_multiball_lock:
    #debug: true
    balls_to_lock: 3
    balls_to_replace: 2
    lock_devices: bd_hacksaw
    enable_events: logicblock_hacksaw_mb_qualify_complete
      #disable_events: sg_lockshot_complete{state=="unlit"}
      #reset_count_for_current_player_events: multiball_lock_sword_multiball_lock_full

multiballs:
  hacksaw_multiball:
    ball_count: 3
    shoot_again: 15s
    start_events: multiball_lock_hacksaw_multiball_lock_full

slides:
  HacksawMB:
    widgets:
    - type: video
      video: HacksawMB

slide_player:
  multiball_hacksaw_multiball_started:
    HacksawMB:
      priority: 500
      expire: 8s
