#config_version=6
##! mode: hacksaw_multiball

mode:
  start_events: startmode_hacksaw_multiball
  stop_events: stop_mode_hacksaw_multiball, mode_hacksaw_multiball_complete
  priority: 165

multiball_locks:
  mbl_hacksaw:
    #debug: true
    balls_to_lock: 3
    balls_to_replace: 2
    lock_devices: bd_hacksaw
    enable_events: logicblock_acc_hacksaw_mb_qualify_complete
    disable_events: multiball_lock_mbl_hacksaw_locked_ball
    locked_ball_counting_strategy: physical_only
    reset_all_counts_events: multiball_lock_mbl_hacksaw_full 
      #disable_events: sg_lockshot_complete{state=="unlit"}
      #reset_count_for_current_player_events: multiball_lock_sword_multiball_lock_full

multiballs:
  mb_hacksaw:
    ball_count: 3
    ball_locks: bd_hacksaw
    shoot_again: 15s
    start_events: multiball_lock_mbl_hacksaw_full
    replace_balls_in_play: true

variable_player:
  multiball_mb_hacksaw_started:
    score: 3000000

slides:
  sl_HacksawMB:
    widgets:
    - type: video
      video: HacksawMB

slide_player:
  multiball_mb_hacksaw_started:
    sl_HacksawMB:
      priority: 500
      expire: 8s
