#config_version=6
mode_settings:
  display_delay_ms: 2.3s
  hurry_up_delay_ms: 0
  bonus_entries:
    - event: bonus_gears
      score: 450000 * (current_player.bonus_gears + 0)
    - event: bonus_syringes
      score: 450000 * (current_player.bonus_syringes + 0)
    - event: bonus_bathtubs
      score: 450000 * (current_player.bonus_bathtubs + 0)
    - event: bonus_taperecorders
      score: 450000 * (current_player.bonus_taperecorders + 0)
    - event: bonus_candles
      score: 450000 * (current_player.bonus_candles + 0)
    - event: bonus_hacksaws
      score: 450000 * (current_player.bonus_hacksaws + 0)
    - event: bonus_handguns
      score: 450000 * (current_player.bonus_handguns + 0)
    - event: bonus_keys
      score: 450000 * (current_player.bonus_keys + 0)      
variable_player: 
  mode_bonus_started:   
    gears_score_total: 450000 * (current_player.bonus_gears + 0)       
    syringes_score_total: 450000 * (current_player.bonus_syringes + 0) 
    bathtubs_score_total: 450000 * (current_player.bonus_bathtubs + 0)
    taperecorders_score_total: 450000 * (current_player.bonus_taperecorders + 0)
    candles_score_total: 450000 * (current_player.bonus_candles + 0)
    hacksaws_score_total: 450000 * (current_player.bonus_hacksaws+ 0)
    handguns_score_total: 450000 * (current_player.bonus_handguns + 0)
    keys_score_total: 450000 * (current_player.bonus_keys + 0)  
    bonus_x: 
      int: current_player.bonus_multiplier 
      action: set
    bonus_total: (((current_player.gears_score_total)+(current_player.syringes_score_total)+(current_player.bathtubs_score_total)+(current_player.taperecorders_score_total)+(current_player.candles_score_total)+(current_player.hacksaws_score_total)+(current_player.handguns_score_total)+(current_player.keys_score_total))*(current_player.bonus_x))
    total_score: 
      int: ((current_player.bonus_total)+(current_player.score))
      action: set

event_player:
  mode_bonus_started: display_gears|0.5s
  display_gears: display_syringes|0.4s
  display_syringes: display_bathtubs|0.4s
  display_bathtubs: display_taperecorders|0.4s
  display_taperecorders: display_candles|0.4s
  display_candles: display_hacksaws|0.4s
  display_hacksaws: display_handguns|0.4s
  display_handguns: display_keys|0.4s
  display_keys: display_multiplierbonus|0.4s
  display_multiplierbonus: display_totalscore|0.8s

slide_player:
  mode_bonus_started: bonus_start_slide

slides:
  bonus_start_slide:
    - type: text
      text: End of Ball Bonus
      font_name: sawesome
      font_size: 70
      color: yellow 
      outline_color: black
      outline_width: 7
      y: 92%
    - type: image
      image: lastgamescores
      opacity: 0.5



widgets:
  gears:
    - type: image
      image: IconGears
      x: 12%
      y: 82%
      z: 1
    - type: text
      text: "Gears: (player|bonus_gears)"
      font_name: Skilt Gothic W04 Thin
      font_size: 35
      bold: true      
      color: white
      outline_color: black
      outline_width: 6
      x: 372
      y: 82%   
      z: 1
    - type: text
      text: (player|gears_score_total)
      font_name: Skilt Gothic W04 Thin
      font_size: 35
      number_grouping: true         
      color: white
      outline_color: black 
      outline_width: 6      
      x: 60%
      y: 82%   
      z: 1


  syringes:
    - type: image
      image: IconSyringe
      x: 12%
      y: 74%
      z: 1
    - type: text
      #text: "Syringes: (player|bonus_syringes)"
      text: "Antidotes: (player|bonus_syringes)"
      font_name: Skilt Gothic W04 Thin
      font_size: 35
      bold: true      
      color: white
      outline_color: black
      outline_width: 6     
      x: 392
      y: 74%   
      z: 1
    - type: text
      text: (player|syringes_score_total) 
      font_name: Skilt Gothic W04 Thin
      font_size: 35
      number_grouping: true        
      color: white
      outline_color: black
      outline_width: 6     
      x: 60%
      y: 74%  
      z: 1
  bathtubs:
    - type: image
      image: IconBathtub
      x: 12%
      y: 66%
      z: 1
    - type: text
      text: "Bathtubs: (player|bonus_bathtubs)"
      font_name: Skilt Gothic W04 Thin
      font_size: 35
      bold: true      
      color: white
      outline_color: black
      outline_width: 6     
      x: 393
      y: 66%   
      z: 1
    - type: text
      text: (player|bathtubs_score_total) 
      font_name: Skilt Gothic W04 Thin
      font_size: 35
      number_grouping: true        
      color: white
      outline_color: black
      outline_width: 6    
      x: 60%
      y: 66%     
      z: 1
  taperecorders:
    - type: image
      image: IconTapeRecorder
      x: 12%
      y: 58%     
      z: 1
    - type: text
      text: "Tape Recorders: (player|bonus_taperecorders)"
      font_name: Skilt Gothic W04 Thin
      font_size: 35
      bold: true      
      color: white 
      outline_color: black
      outline_width: 6     
      x: 434
      y: 58%  
      z: 1
    - type: text
      text: (player|taperecorders_score_total) 
      font_name: Skilt Gothic W04 Thin
      font_size: 35
      number_grouping: true        
      color: white 
      outline_color: black
      outline_width: 6       
      x: 60%
      y: 58%     
      z: 1
  candles:
    - type: image
      image: IconCandle
      x: 12%
      y: 50%
      z: 1
    - type: text
      text: "Candles: (player|bonus_candles)"
      font_name: Skilt Gothic W04 Thin
      font_size: 35
      bold: true      
      color: white
      outline_color: black
      outline_width: 6     
      x: 385
      y: 50%   
      z: 1
    - type: text
      text: (player|candles_score_total) 
      font_name: Skilt Gothic W04 Thin
      font_size: 35
      number_grouping: true        
      color: white
      outline_color: black
      outline_width: 6      
      x: 60%
      y: 50%     
      z: 1
  hacksaws:
    - type: image
      image: IconHacksaw
      x: 12%
      y: 42%
      z: 1
    - type: text
      text: "Hacksaws: (player|bonus_hacksaws)"
      font_name: Skilt Gothic W04 Thin
      font_size: 35
      bold: true      
      color: white
      outline_color: black
      outline_width: 6    
      x: 400
      y: 42%  
      z: 1
    - type: text
      text: (player|hacksaws_score_total) 
      font_name: Skilt Gothic W04 Thin
      font_size: 35
      number_grouping: true        
      color: white
      outline_color: black
      outline_width: 6      
      x: 60%
      y: 42%     
      z: 1
  handguns:
    - type: image
      image: IconHandgun
      x: 12%
      y: 34%
      z: 1
    - type: text
      text: "Handguns: (player|bonus_handguns)"
      font_name: Skilt Gothic W04 Thin
      font_size: 35
      bold: true      
      color: white 
      outline_color: black
      outline_width: 6      
      x: 400
      y: 34%   
      z: 1
    - type: text
      text: (player|handguns_score_total) 
      font_name: Skilt Gothic W04 Thin
      font_size: 35
      number_grouping: true        
      color: white
      outline_color: black
      outline_width: 6       
      x: 60%
      y: 34%         
      z: 1
  keys:
    - type: image
      image: IconKey
      x: 12%
      y: 26%
      z: 1
    - type: text
      text: "Keys: (player|bonus_keys)"
      font_name: Skilt Gothic W04 Thin
      font_size: 35
      bold: true      
      color: white
      outline_color: black
      outline_width: 6      
      x: 364
      y: 26%   
      z: 1
    - type: text
      text: (player|keys_score_total) 
      font_name: Skilt Gothic W04 Thin
      font_size: 35
      number_grouping: true        
      color: white
      outline_color: black
      outline_width: 6         
      x: 60%
      y: 26%          
      z: 1
  multiplierbonus:
    - type: text
      text: "Bonus Multiplier: (player|bonus_x)X"
      font_name: Skilt Gothic W04 Thin
      bold: true
      font_size: 45
      color: white 
      outline_color: black
      outline_width: 6      
      x: 30%
      y: 18%       
      z: 1
    - type: text
      text: "Total Bonus: (player|bonus_total)"
      font_name: Skilt Gothic W04 Thin
      bold: true
      font_size: 45
      number_grouping: true        
      color: white
      outline_color: black
      outline_width: 6      
      x: 60%
      y: 18%   
      z: 1
  totalscore:
    - type: text
      text: "Total Score: (player|total_score)"
      font_name: Skilt Gothic W04 Thin
      bold: true
      font_size: 45
      number_grouping: true        
      color: white
      outline_color: black
      outline_width: 6     
      y: 8%   
      z: 1

widget_player:
  display_gears:
    gears:
      slide: bonus_start_slide
      action: add
  display_syringes:
    syringes:
      slide: bonus_start_slide
      action: add
  display_bathtubs:
    bathtubs:
      slide: bonus_start_slide
      action: add
  display_taperecorders:
    taperecorders:
      slide: bonus_start_slide
      action: add      
  display_candles:
    candles:
      slide: bonus_start_slide
      action: add      
  display_hacksaws:
    hacksaws:
      slide: bonus_start_slide
      action: add      
  display_handguns:
    handguns:
      slide: bonus_start_slide
      action: add      
  display_keys:
    keys:
      slide: bonus_start_slide
      action: add  
  display_multiplierbonus:
    multiplierbonus:
      slide: bonus_start_slide
      action: add      
  display_totalscore:
    totalscore:
      slide: bonus_start_slide
      action: add      


#sound_player:
#  mode_bonus_started:
#    initials:
#      action: play
#  mode_bonus_stopped:
#    initials:
#      action: stop
sound_player:
  display_gears:
    FleshCrushSquelch4:
      action: play
  display_syringes:
    FleshCrushSquelch4:
      action: play
  display_bathtubs:
    FleshCrushSquelch4:
      action: play
  display_taperecorders:
    FleshCrushSquelch4:
      action: play
  display_candles:
    FleshCrushSquelch4:
      action: play
  display_hacksaws:
    FleshCrushSquelch4:
      action: play
  display_handguns:
    FleshCrushSquelch4:
      action: play
  display_keys:
    FleshCrushSquelch4:
      action: play
  display_multiplierbonus:
    FleshCrushSquelch4:
      action: play
  display_totalscore:
    SwordSlashA:
      action: play
  mode_bonus_started:
    BaseMusic:
      action: stop

show_player:
  display_gears:   
   jw_bonus_gears:
     loops: 0
     speed: 8
     show_tokens:
       color1: beartrap
  display_syringes:
   jw_bonus_syringe:
     loops: 0
     speed: 8
     show_tokens:
       color1: beartrap
  display_bathtubs:
   jw_bonus_bathtub:
     loops: 0
     speed: 8
     show_tokens:
       color1: beartrap
  display_taperecorders:
   jw_bonus_taperecorder:
     loops: 0
     speed: 8
     show_tokens:
       color1: beartrap    
  display_candles:
   jw_bonus_candle: 
     loops: 0
     speed: 8
     show_tokens:
       color1: beartrap    
  display_hacksaws:
   jw_bonus_hacksaw:
     loops: 0
     speed: 8
     show_tokens:
       color1: beartrap     
  display_handguns:
   jw_bonus_gun:
     loops: 0
     speed: 8
     show_tokens:
       color1: beartrap     
  display_keys:
   jw_bonus_key:
     loops: 0
     speed: 8
     show_tokens:
       color1: beartrap