#config_version=6                 
mode:
  start_events: selection_mode_survivalinstinct_selected
  stop_events: stop_mode_survival_instinct, mode_survival_instinct_complete, ball_ended, ball_will_end, multiball_mb_survival_instinct_2ball_ended, multiball_mb_survival_instinct_3ball_ended, multiball_mb_survival_instinct_4ball_ended, multiball_mb_survival_instinct_5ball_ended
  priority: 181

multiballs:
  mb_survival_instinct_2ball:
    ball_count: 2
    shoot_again: 10s
    enable_events: player_puzzle_pieces{value==2}
    start_events: player_puzzle_pieces{value==2}
    disable_events: player_puzzle_pieces{value==3}, player_puzzle_pieces{value==4}, player_puzzle_pieces{value==5}
  mb_survival_instinct_3ball:
    ball_count: 3
    shoot_again: 10s
    enable_events: player_puzzle_pieces{value==3}
    start_events: player_puzzle_pieces{value==3}
    disable_events: player_puzzle_pieces{value==2}, player_puzzle_pieces{value==4}, player_puzzle_pieces{value==5}
  mb_survival_instinct_4ball:
    ball_count: 4
    shoot_again: 10s
    enable_events: player_puzzle_pieces{value==4}
    start_events: player_puzzle_pieces{value==4}
    disable_events: player_puzzle_pieces{value==2}, player_puzzle_pieces{value==3}, player_puzzle_pieces{value==5}
  mb_survival_instinct_5ball:
    ball_count: 5
    shoot_again: 10s
    enable_events: player_puzzle_pieces{value==5}
    start_events: player_puzzle_pieces{value==5}
    disable_events: player_puzzle_pieces{value==2}, player_puzzle_pieces{value==3}, player_puzzle_pieces{value==4}

variable_player:
  mode_survival_instinct_started:
    survival_instinct_value:
      int: 2000000 * (current_player.pf_multiplier)
      action: set
    puzzle_pieces:
      int: 10
      action: add
    update_puzzle_count_trigger:
      int: 1
      action: set
  player_update_puzzle_count_trigger:
    puzzle_pieces:
      int: -10
      action: add
  counter_cnt_survival_instinct_jackpot_hit:
    survival_instinct_jackpot:
      int: 1
      action: add
    survival_instinct_value:
      int: 1500000 * (current_player.pf_multiplier) * (current_player.survival_instinct_jackpot)
      action: add
  shot_survival_instinct_superjackpot_sp_survival_instinct_jackpot_hit:
    score: (current_player.survival_instinct_value)
    survival_instinct_jackpot:
      int: 0
      action: set
    survival_instinct_value:
      int: 2000000 * (current_player.pf_multiplier)
      action: set
  
counters:
  cnt_survival_instinct_jackpot:
    starting_count: 0
    enable_events: mode_survival_instinct_started
#    persist_state: true
    reset_on_complete: true
    disable_on_complete: false   
    count_events: shot_survival_instinct_bottom_pops_sp_survival_instinct_lit_hit, shot_survival_instinct_top_pops_sp_survival_instinct_lit_hit, shot_survival_instinct_right_loop_sp_survival_instinct_lit_hit, shot_survival_instinct_middle_standup_sp_survival_instinct_lit_hit, shot_survival_instinct_drop_bank_sp_survival_instinct_lit_hit
      
slides:
  sl_survival_instinctUI:
    widgets:
    - type: video
      video: mode_survivalinstinct01
      width: 1366
      height: 768
#   sl_ShackleMB:
#     widgets:
#     - type: video
#       video: shackleMB
#       width: 1366
#       height: 768 
#   sl_ShackleMB_Jackpot:
#     widgets:
#     - type: video
#       video: jackpot_shackle
#   sl_ShackleMB_SuperJackpot:
#     widgets:
#     - type: video
#       video: superjackpot_shackle

slide_player:
  mode_survival_instinct_started:
    sl_survival_instinctUI:
      priority: 400
#     sl_ShackleMB:
#       priority: 600
#       expire: 7s
#   sg_shackle_p1_lit_hit:
#     sl_ShackleMB_Jackpot:
#       priority: 600
#       expire: 2.2s
#   shot_shackle_superjackpot1_sp_shackle_mb_lit_hit:
#     sl_ShackleMB_SuperJackpot:
#       priority: 600
#       expire: 2.2s
#   shot_shackle_superjackpot2_sp_shackle_mb_lit_hit:
#     sl_ShackleMB_SuperJackpot:
#       priority: 600
#       expire: 2.2s

show_player:
  mode_survival_instinct_started:     
    gi_on:
      show_tokens:
        color1: beartrap
    starpost_on:
      show_tokens:
        color1: 6E6E6E   
      priority: 169
    flipper_on:
      show_tokens:
        color1: beartrap
    speaker_heartbeat:
      show_tokens:
        color1: beartrap
    trough_on:
      show_tokens:
        color1: beartrap
    cabinet_heartbeat:
      show_tokens:
        color1: beartrap
    topper_heartbeat:
      show_tokens:
        color1: beartrap
    left_ramp_chase:
      speed: 5
      show_tokens:
        color1: shotgun
    right_ramp_chase:
      speed: 5
      show_tokens:
        color1: shotgun
    mb_ballsave:
      loops: 9
# coil_player:
#   mode_survival_instinct_started:
#     c_left_spin_disc:
#       action: enable
#       hold_power: 1.0
#     c_middle_spin_disc:
#       action: enable
#       hold_power: 1.0
#     c_right_spin_disc:
#       action: enable
#       hold_power: 1.0
#   mode_survival_instinct_complete:
#     c_right_spin_disc:
#       action: off
#     c_middle_spin_disc:
#       action: off
#     c_left_spin_disc:
#       action: off
#   ball_ending:
#     c_right_spin_disc:
#       action: off
#     c_middle_spin_disc:
#       action: off
#     c_left_spin_disc:
#       action: off

shots:
  shot_survival_instinct_bottom_pops:
    reset_events: mode_survival_instinct_stopped, player_turn_stopped, player_turn_ended
    switches: s_left_bottom_jet_bumper, s_right_bottom_jet_bumper, s_upper_bottom_jet_bumper
    profile: sp_survival_instinct
    show_tokens:
      leds: bottom_bumper, drill_flasher
    control_events:
      - events: ball_starting
        state: 0
      - events: mode_survival_instinct_started
        state: 1
      - events: shot_survival_instinct_bottom_pops_sp_survival_instinct_lit_hit
        state: 0
      - events: shot_survival_instinct_top_pops_sp_survival_instinct_lit_hit
        state: 1
      - events: shot_survival_instinct_right_loop_sp_survival_instinct_lit_hit
        state: 1
      - events: shot_survival_instinct_middle_standup_sp_survival_instinct_lit_hit
        state: 1
      - events: shot_survival_instinct_drop_bank_sp_survival_instinct_lit_hit
        state: 1
  shot_survival_instinct_top_pops:
    reset_events: mode_survival_instinct_stopped, player_turn_stopped, player_turn_ended
    switches: s_left_top_jet_bumper, s_right_top_jet_bumper, s_lower_top_jet_bumper
    profile: sp_survival_instinct
    show_tokens:
      leds: top_bumper, razorwire_flasher
    control_events:
      - events: ball_starting
        state: 0
      - events: mode_survival_instinct_started
        state: 1
      - events: shot_survival_instinct_top_pops_sp_survival_instinct_lit_hit
        state: 0
      - events: shot_survival_instinct_bottom_pops_sp_survival_instinct_lit_hit
        state: 1
      - events: shot_survival_instinct_right_loop_sp_survival_instinct_lit_hit
        state: 1
      - events: shot_survival_instinct_middle_standup_sp_survival_instinct_lit_hit
        state: 1
      - events: shot_survival_instinct_drop_bank_sp_survival_instinct_lit_hit
        state: 1
  shot_survival_instinct_right_loop:
    reset_events: mode_survival_instinct_stopped, player_turn_stopped, player_turn_ended
    switches: s_right_loop_bottom
    profile: sp_survival_instinct
    show_tokens:
      leds: shotgun_flasher
    control_events:
      - events: ball_starting
        state: 0
      - events: mode_survival_instinct_started
        state: 1
      - events: shot_survival_instinct_right_loop_sp_survival_instinct_lit_hit
        state: 0
      - events: shot_survival_instinct_top_pops_sp_survival_instinct_lit_hit
        state: 1
      - events: shot_survival_instinct_bottom_pops_sp_survival_instinct_lit_hit
        state: 1
      - events: shot_survival_instinct_middle_standup_sp_survival_instinct_lit_hit
        state: 1
      - events: shot_survival_instinct_drop_bank_sp_survival_instinct_lit_hit
        state: 1
  shot_survival_instinct_middle_standup:
    reset_events: mode_survival_instinct_stopped, player_turn_stopped, player_turn_ended
    switches: s_middle_standup
    profile: sp_survival_instinct
    show_tokens:
      leds: bear_flasher
    control_events:
      - events: ball_starting
        state: 0
      - events: mode_survival_instinct_started
        state: 1
      - events: shot_survival_instinct_middle_standup_sp_survival_instinct_lit_hit
        state: 0
      - events: shot_survival_instinct_top_pops_sp_survival_instinct_lit_hit
        state: 1
      - events: shot_survival_instinct_right_loop_sp_survival_instinct_lit_hit
        state: 1
      - events: shot_survival_instinct_bottom_pops_sp_survival_instinct_lit_hit
        state: 1
      - events: shot_survival_instinct_drop_bank_sp_survival_instinct_lit_hit
        state: 1
  shot_survival_instinct_drop_bank:
    reset_events: mode_survival_instinct_stopped, player_turn_stopped, player_turn_ended
    switches: s_lower_bank_drop_target_opto_upper, s_lower_bank_drop_target_opto_middle, s_lower_bank_drop_target_opto_lower
    profile: sp_survival_instinct
    show_tokens:
      leds: zep_flasher
    control_events:
      - events: ball_starting
        state: 0
      - events: mode_survival_instinct_started
        state: 1
      - events: shot_survival_instinct_drop_bank_sp_survival_instinct_lit_hit
        state: 0
      - events: shot_survival_instinct_top_pops_sp_survival_instinct_lit_hit
        state: 1
      - events: shot_survival_instinct_right_loop_sp_survival_instinct_lit_hit
        state: 1
      - events: shot_survival_instinct_middle_standup_sp_survival_instinct_lit_hit
        state: 1
      - events: shot_survival_instinct_bottom_pops_sp_survival_instinct_lit_hit
        state: 1
  shot_survival_instinct_superjackpot:
    reset_events: mode_survival_instinct_stopped, player_turn_stopped, player_turn_ended
    switches: s_left_ramp_score_top, s_right_ramp_score_top
    profile: sp_survival_instinct
#    show_tokens:
#      leds: l_left_ramp_triangle1, l_left_ramp_triangle2, l_left_ramp_triangle3, l_right_ramp_triangle1, l_right_ramp_triangle2
    control_events:
      - events: ball_starting
        state: 0
      - events: mode_survival_instinct_started
        state: 2
      # - events: shot_survival_instinct_superjackpot_sp_survival_instinct_lit_hit
      #   state: 0

shot_profiles:
  sp_survival_instinct:
    advance_on_hit: false
    states:
      - name: survival_instinct_not_ready
        show: "sh_survival_instinct_not_ready"
      - name: lit
        show: "sh_survival_instinct_on"
      - name: jackpot
        show: "sh_survival_instinct_jackpot"

shot_groups:
  sg_survival_instinct:
    shots: shot_survival_instinct_bottom_pops, shot_survival_instinct_top_pops, shot_survival_instinct_right_loop, shot_survival_instinct_middle_standup, shot_survival_instinct_drop_bank


shows:
  sh_survival_instinct_on:
    - duration: 0.3s
      lights:
        (leds): beartrap
    - duration: 0.3s
      lights:
        (leds): off
  sh_survival_instinct_not_ready:
    - duration: 0.3s
      lights:
        (leds): off
  sh_survival_instinct_jackpot:
    - duration: 0.3s
      lights:
        (leds): shotgun
    - duration: 0.3s
      lights:
        (leds): off

sound_player:
  multiball_mb_survival_instinct_2ball_started:
    PuzzlePiece2BallModeSong:
      action: play
      loops: -1
  multiball_mb_survival_instinct_3ball_started:
    PuzzlePiece3BallModeSong:
      action: play
      loops: -1
  multiball_mb_survival_instinct_4ball_started:
    PuzzlePiece3BallModeSong:
      action: play
      loops: -1
  multiball_mb_survival_instinct_5ball_started:
    PuzzlePiece3BallModeSong:
      action: play
      loops: -1
  mode_survival_instinct_stopping:
    PuzzlePiece2BallModeSong:
      action: stop
    PuzzlePiece3BallModeSong:
      action: stop
  shot_survival_instinct_superjackpot_sp_survival_instinct_jackpot_hit:
    Jackpot:
      action: play

widgets:
  w_survival_instinct_value:
    - type: text
      text: (player|survival_instinct_value)
      number_grouping: true 
      x: 75%
      y: 28%
      z: 7
      font_size: 90
      font_name: Mustkill     
      outline_color: black
      outline_width: 9
      color: beartrap
    - type: image
      image: BottomFrame
      y: 85
      # x: 1
      z: 2
#player 1 widget
    - type: text
      text: (player1|score)
      number_grouping: true  
   #   y: 36
      y: 37
      x: 252
      z: 8
      font_size: 36
      anchor_x: right
      anchor_y: bottom
      font_name: AeroMaticsDisplaRegular
      color: black
    - type: text
      text: (player1|score)
      number_grouping: true  
      y: 36
      x: 253
      z: 8
      font_size: 36
      anchor_x: right
      anchor_y: bottom
      font_name: AeroMaticsDisplaRegular
      outline_color: f0cfab
      outline_width: 2
#player 2 widget     
    - type: text
      text: (player2|score)
      number_grouping: true
      y: 37
      x: left+579
      z: 8
      font_size: 36
      anchor_x: right
      anchor_y: bottom
      font_name: AeroMaticsDisplaRegular
      color: black
    - type: text
      text: (player2|score)
      number_grouping: true
      y: 36
      x: left+580
      z: 7
      font_size: 36
      anchor_x: right
      anchor_y: bottom
      font_name: AeroMaticsDisplaRegular
      outline_color: f0cfab
      outline_width: 2
#player 3 widget
    - type: Text
      text: (player3|score)
      number_grouping: true   
      font_name: AeroMaticsDisplaRegular
      font_size: 36
      anchor_x: right
      anchor_y: bottom
      y: 37
      x: left+908
      z: 8
      color: black
    - type: Text
      text: (player3|score)
      number_grouping: true   
      font_name: AeroMaticsDisplaRegular
      font_size: 36
      anchor_x: right
      anchor_y: bottom
      y: 36
      x: left+909
      z: 7
      outline_color: f0cfab
      outline_width: 2
#player 4 widget
    - type: Text
      text: (player4|score)
      number_grouping: true       
      font_name: AeroMaticsDisplaRegular
      font_size: 36
      anchor_x: right
      anchor_y: bottom
      y: 37
      x: left+1239
      z: 8
      color: black
    - type: Text
      text: (player4|score)
      number_grouping: true       
      font_name: AeroMaticsDisplaRegular
      font_size: 36
      anchor_x: right
      anchor_y: bottom
      y: 36
      x: left+1240
      z: 7
      outline_color: f0cfab
      outline_width: 2
#current player widget
  w_current_player1:
    - type: image
      image: Player1Hacksaw
      opacity: 1.0
      y: 4
      x: 35
      z: 3
      anchor_x: left
      anchor_y: bottom
  w_current_player2:
    - type: image
      image: Player2Hacksaw
      opacity: 1.0
      y: 4
      x: left+515
      z: 3
      anchor_y: bottom  
  w_current_player3:
    - type: image
      image: Player3Hacksaw
      opacity: 1.0
      y: 4
      x: left+844
      z: 3
      anchor_y: bottom  
  w_current_player4:
    - type: image
      image: Player4Hacksaw
      opacity: 1.0
      y: 4
      x: left+1174
      z: 3
      anchor_y: bottom

widget_player:
  mode_survival_instinct_started:
    w_survival_instinct_value:
      slide: sl_survival_instinctUI
      action: add
  stop_mode_survival_instinct:
    w_survival_instinct_value:
      action: remove
  mode_survival_instinct_complete:
    w_survival_instinct_value:
      action: remove  
  ball_ended:
    w_survival_instinct_value:
      action: remove  
  e_survival_instinct_widget:
    w_survival_instinct_value:
      slide: sl_survival_instinctUI
      action: add
#current player widgets
  mode_survival_instinct_started{current_player.v_current_player==1}:
    w_current_player1:
      slide: sl_survival_instinctUI
      action: add
  mode_survival_instinct_started{current_player.v_current_player==2}:
    w_current_player2:
      slide: sl_survival_instinctUI
      action: add
  mode_survival_instinct_started{current_player.v_current_player==3}:
    w_current_player3:
      slide: sl_survival_instinctUI
      action: add
  mode_survival_instinct_started{current_player.v_current_player==4}:
    w_current_player4:
      slide: sl_survival_instinctUI
      action: add

event_player: 
  slide_sl_survival_instinctUI_active: e_primary_mode_active
  counter_cnt_survival_instinct_jackpot_hit: e_survival_instinct_widget|0.1s