#config_version=6
##! mode: trap_select

mode:
  start_events: slide_saw_collect_created
  stop_events: logicblock_trap_select_qualify_counter_complete
  priority: 120
  restart_on_next_ball: true

# variable_player:
#   logicblock_trap_select_qualify_counter_complete:
#     score: 300000
    
event_player:   
  mode_trap_select_started: mode_qualified_sidestep2|0.5s

counters:
  trap_select_qualify_counter:
    starting_count: 0
    count_complete_value: 1
    disable_on_complete: false
    count_events: sh_select_mode_hit, s_right_scoop_active
    disable_events: e_primary_mode_active, start_jigsaw_multiball, start_hacksaw_multiball, start_shackle_multiball
    enable_events: logicblock_cnt_saw_qualify_complete, mode_qualified_sidestep, mode_qualified_sidestep2


sound_player:
    mode_trap_select_started:
      BaseMusic:
        action: stop
      DrillAndTapp:
        action: stop
      OutOfTime:
        action: stop
      Jonas:
        action: stop
      TheRules:
        action: stop
      FuckThisShit:
        action: stop
      ModeQualifiedShootScoop:
        action: play   
        loops: -1
    ball_ending:
      ModeQualifiedShootScoop:
        action: stop

shows:
  mode_lit:
    - duration: 1.5s
      lights:
        (leds): razorwire
    - duration: 1.5s
      lights:
        (leds): off

show_player:
  logicblock_trap_select_qualify_counter_updated{enabled==True}:
    mode_lit:
      show_tokens:
        leds: l_mode_scoop
      loops: -1
  logicblock_trap_select_qualify_counter_updated{enabled==False}:
    mode_lit: stop
  sh_mystery_hit:
    mode_lit: stop