#config_version=6                 
mode:
  start_events: e_puzzle_start
  stop_events: mode_puzzle_hurryup_complete, stop_mode_puzzle_hurryup, ball_ended, ball_will_end, player_puzzle_hurryup_t_puzzle_timer_tick{value < 1}, mode_qualified_sidestep, mode_selection_mode_started, multiball_mb_jigsaw_started, multiball_mb_hacksaw_started, multiball_mb_shackle_started, mode_razorwire_started, mode_drillchair_started, mode_flammablejelly_started, mode_quadshotgun_started, mode_reversebeartrap_started, mode_zeptest_started, mode_make_your_choice_hurryup_started
  priority: 185

timers:
  t_puzzle_timer:
    start_value: 23
    end_value: 0
    direction: down
    control_events:
      - action: start
        event: mode_puzzle_hurryup_started

variable_player:
  player_puzzle_hurryup_t_puzzle_timer_tick:
    puzzle_countdown:
      int: device.timers.t_puzzle_timer.ticks
      action: set
  mode_puzzle_hurryup_complete:
    score: 3000000


counters:
  cnt_puzzle_razorwire_hurryup:
    starting_count: 0
    count_complete_value: 1
    enable_events: e_razorwire_puzzle
    events_when_complete: mode_puzzle_hurryup_complete, razorwire_puzzle_complete
    count_events: sw_top_pops
  cnt_puzzle_drillchair_hurryup:
    starting_count: 0
    count_complete_value: 1
    enable_events: e_drillchair_puzzle
    events_when_complete: mode_puzzle_hurryup_complete, drillchair_puzzle_complete
    count_events: sw_bottom_pops
  cnt_puzzle_quadshotgun_hurryup:
    starting_count: 0
    count_complete_value: 1
    enable_events: e_quadshotgun_puzzle
    events_when_complete: mode_puzzle_hurryup_complete, quadshotgun_puzzle_complete
    count_events: sw_spinner
  cnt_puzzle_flammablejelly_hurryup:
    starting_count: 0
    count_complete_value: 1
    enable_events: e_flammablejelly_puzzle
    events_when_complete: mode_puzzle_hurryup_complete, flammablejelly_puzzle_complete  
    count_events: sw_middle_standup
  cnt_puzzle_zeptest_hurryup:
    starting_count: 0
    count_complete_value: 1
    enable_events: e_zeptest_puzzle
    events_when_complete: mode_puzzle_hurryup_complete, zeptest_puzzle_complete 
    count_events: sw_lower_drop_target

widgets:
  w_puzzle_UI:
    - type: Text
      text: 00:(player|puzzle_hurryup_t_puzzle_timer_tick)
      font_size: 50
      font_name: digitalclockfont
      color: red
      x: 50%
      y: 83.2%
      z: 7
    - type: rectangle
      width: 210
      height: 65
      x: 50%
      y: 84.5%
      z: 7
      corner_radius: 20
      corner_segments: 20
      color: black        
    - type: text
      text: Collect the Puzzle Piece!
      x: 50%
      y: 73.2%
      z: 7
      font_size: 60
      font_name: Mustkill    
      outline_color: black
      outline_width: 5

widget_player:
  mode_puzzle_hurryup_started: 
    w_puzzle_UI:
      slide: base_slide_main
      action: add
  mode_puzzle_hurryup_complete:
    w_puzzle_UI:
      action: remove
  player_puzzle_hurryup_t_puzzle_timer_tick{value==1}:
    w_puzzle_UI:
      action: remove

shows:
# mode attempt for puzzle insert
  sh_razorwire_hurryup:
    - duration: 0.5s
      lights:
        (leds): beartrap
    - duration: 0.5s
      lights:
        (leds): off
  sh_drillchair_hurryup:
    - duration: 0.5s
      lights:
        (leds): beartrap
    - duration: 0.5s
      lights:
        (leds): off
  sh_flammablejelly_hurryup:
    - duration: 0.5s
      lights:
        (leds): beartrap
    - duration: 0.5s
      lights:
        (leds): off
  sh_zeptest_hurryup:
    - duration: 0.5s
      lights:
        (leds): beartrap
    - duration: 0.5s
      lights:
        (leds): off
  sh_quadshotgun_hurryup:
    - duration: 0.5s
      lights:
        (leds): beartrap
    - duration: 0.5s
      lights:
        (leds): off

show_player:
# mode attempt for puzzle insert 
  e_razorwire_puzzle:
    sh_razorwire_hurryup:
      show_tokens:
        leds: razorwire_flasher
      loops: 90
      speed: 4
  e_flammablejelly_puzzle:
    sh_flammablejelly_hurryup:
      show_tokens:
        leds: bear_flasher
      loops: 90
      speed: 4
  e_quadshotgun_puzzle:
    sh_quadshotgun_hurryup:
      show_tokens:
        leds: shotgun_flasher
      loops: 90
      speed: 4
  e_drillchair_puzzle:
    sh_drillchair_hurryup:
      show_tokens:
        leds: drill_flasher
      loops: 90
      speed: 4
  e_zeptest_puzzle:
    sh_zeptest_hurryup:
      show_tokens:
        leds: zep_flasher
      loops: 90
      speed: 4

event_player:
  mode_puzzle_hurryup_started: e_puzzle_music_start|5.5s