#config_version=5
mode:
  start_events: ball_starting
  priority: 100

#variable_player:
#  my_first_shot_my_first_profile_unlit_hit:
#    score: 100
#  my_first_shot_my_first_profile_flashing_hit:
#    score: 1000
#  s_flipper_lower_left_active:
#    score: 1000  
#  s_flipper_lower_right_active:
#    score: 100

#shots:
#  my_first_shot:
#    switch: s_left_inlane  # pick a switch that's valid in your machine
#    show_tokens:
#        led: l_led1 # pick an LED that's valid in your machine
#    profile: my_first_profile 

    
#shot_profiles:
#  my_first_profile:
#    states:
#      - name: unlit  # step 1
#        show: off
#      - name: flashing  # step 2
#        show: flash
#      - name: lit  # step 3
#        show: on
#    loop: true

#show_player:
#  mode_skill_shot_started:
#    skillshot_timing_crawl:
#      loops: -1
#      speed: 4
#  skillshot_failed:
#    skillshot_timing_crawl:
#      action: stop
  

slide_player:
  mode_base_started:
    widgets:
      - type: text
        text: (score)
        number_grouping: true
        min_digits: 2
        font_size: 100
      - type: text
        font_name: TrajanProRegular
        text: PLAYER (number)
        y: 10
        x: 10
        font_size: 50
        anchor_x: left
        anchor_y: bottom
      - type: text
        text: BALL (ball)
        font_name: TrajanProRegular
        y: 10
        x: right-10
        anchor_x: right
        anchor_y: bottom
        font_size: 50
      - type: text
        font_name: TrajanProRegular
        text: 'Current Score:'
        font_size: 70
        y: 40%
