#config_version=5
mode:
  start_events: ball_starting, mode_skillshot_started
  priority: 100

slide_player:
  mode_base_started:
    widgets:

      - type: image
        image: spiral
        opacity: 0.7
        y: top-20
        x: right-165

      - type: text
        font_name: TrajanProRegular
        text: PLAYER (number)
        y: top-25
        x: left+105
        font_size: 38
        color: C2E3E0

      - type: image
        image: rustpipe2
        y: top-44
        x: left+95
        opacity: 0.5
        
      - type: text
        text: BALL (ball)
        font_name: TrajanProRegular
        y: top-25
        x: right-70
        color: C2E3E0
        font_size: 38
        
      - type: image
        image: rustpipe2
        y: top-44
        x: right-90
        opacity: 0.5
 
#player 1 
      - type: text
        text: (score)
        number_grouping: true
        y: 16
        x: 25
        font_size: 36
        anchor_x: left
        anchor_y: bottom
        font_name: TrajanProRegular
        color: C2E3E0
        
      - type: image
        image: hacksawUI
        opacity: 0.9
        y: 1
        x: 1
        anchor_x: left
        anchor_y: bottom
        
#player 2      
      - type: Text
        text: PRESS START
        font_name: TrajanProRegular
        font_size: 28
        y: 35
        x: left+490
        color: red
        animations:
          pre_show_slide:
          - property: opacity
            value: 0
            duration: 1.5s
          - property: opacity
            value: 1
            duration: 1.5s
            repeat: true
      - type: image
        image: hacksawUI
        opacity: 0.9
        y: 1
        x: left+520
        anchor_y: bottom
            
#player 3   
      - type: Text
        text: PRESS START
        font_name: TrajanProRegular
        font_size: 28
        y: 35
        x: left+840
        color: red
        animations:
          pre_show_slide:
          - property: opacity
            value: 0
            duration: 1.5s
          - property: opacity
            value: 1
            duration: 1.5s
            repeat: true 
      - type: image
        image: hacksawUI
        opacity: 0.9
        y: 1
        x: left+870
        anchor_y: bottom
       
#player 4   
      - type: Text
        text: PRESS START
        font_name: TrajanProRegular
        font_size: 28
        y: 35
        x: left+1180
        color: red
        animations:
          pre_show_slide:
          - property: opacity
            value: 0
            duration: 1.5s
          - property: opacity
            value: 1
            duration: 1.5s
            repeat: true 
      - type: image
        image: hacksawUI
        opacity: 0.9
        y: 1
        x: left+1210
        anchor_y: bottom
        
      - type: image
        image: gordonsaw


variable_player:
  left_ramp_hit:
    score: 75000
  right_ramp_hit:
    score: 115000
  upper_drop_target_hit:
    score: 145000
  left_top_pop_hit:
    score: 573
  cellar_hit:
    score: 100000
  spinner_hit:
    score: 5000
 
