#config_version=5
mode:
  start_events: ball_starting
  priority: 100

variable_player:
  my_first_shot_my_first_profile_unlit_hit:
    score: 100
  my_first_shot_my_first_profile_flashing_hit:
    score: 1000
  s_flipper_lower_left_active:
    score: 1000  
  s_flipper_lower_right_active:
    score: 100

shots:
  my_first_shot:
    switch: s_left_inlane  # pick a switch that's valid in your machine
    show_tokens:
      led: l_led1 # pick an LED that's valid in your machine
    profile: my_first_profile
shot_profiles:
  my_first_profile:
    states:
      - name: unlit  # step 1
        show: off
      - name: flashing  # step 2
        show: flash
      - name: lit  # step 3
        show: on
    loop: true


#standups 1-3 are not working to get the skillshot mode functional      
#  standup_1:
#   switch: s_lower_bank_drop_target_opto_upper
#     show_tokens:
#     light: l_3_bank_drop_target_opto_upper
# standup_2:
#   switch: s_lower_bank_drop_target_opto_middle
#     show_tokens:
#      light: l_3_bank_drop_target_opto_middle
#  standup_3:
#    switch: s_lower_bank_drop_target_opto_lower
#      show_tokens:
#      light: l_3_bank_drop_target_opto_lower


slide_player:
  mode_base_started:
    widgets:
      - type: text
        text: (score)
        number_grouping: true
        min_digits: 2
        font_size: 100
      - type: text
        font_name: TrajanProRegular
        text: PLAYER (number)
        y: 10
        x: 10
        font_size: 50
        anchor_x: left
        anchor_y: bottom
      - type: text
        text: BALL (ball)
        font_name: TrajanProRegular
        y: 10
        x: right-10
        anchor_x: right
        anchor_y: bottom
        font_size: 50
      - type: text
        font_name: TrajanProRegular
        text: 'Current Score:'
        font_size: 70
        y: 40%
