#config_version=5
mode:
  start_events: ball_starting
  priority: 100

slide_player:
  mode_base_started:
    widgets:
      - type: text
        text: (score)
        number_grouping: true
        min_digits: 2
        font_size: 100
      - type: text
        font_name: TrajanProRegular
        text: PLAYER (number)
        y: 10
        x: 10
        font_size: 50
        anchor_x: left
        anchor_y: bottom
      - type: text
        text: BALL (ball)
        font_name: TrajanProRegular
        y: 10
        x: right-10
        anchor_x: right
        anchor_y: bottom
        font_size: 50
      - type: text
        font_name: TrajanProRegular
        text: 'Current Score:'
        font_size: 70
        y: 40%
      - type: image
        image: gordonsaw


variable_player:
  left_ramp_hit:
    score: 75000
  left_top_pop_hit:
    score: 573
