#config_version=6

game:
  balls_per_game: 3
  max_players: 4
    #allow_start_with_ball_in_drain: true
    #allow_start_with_loose_balls: true

config:
- hardware.yaml
- keyboard.yaml
- shots.yaml
- videos.yaml
- lights.yaml

modes:
  - attract
  - base
  - skillshot
  - super_skillshot
  - music_player
  - trap_select
  - selection_mode
  - razorwire
  - drillchair
  - quadshotgun
  - flammablejelly
  - reversebeartrap
  - zeptest
  - tilt
  - mystery
  - saw_qualify
  - mode_tracking
  - jigsaw_multiball
  - jigsaw_multiball_qualify
  - hacksaw_multiball
  - hacksaw_multiball_qualify
  - shackle_multiball
  - shackle_multiball_qualify
  - high_score
  - bonus
  - stop_game

window:
  width: 1366
  height: 768
  title: Mission Pinball Framework - SAW
  resizable: true
  fullscreen: false
  borderless: true
  exit_on_escape: true
  source_display: lcd
displays:
  lcd:
    width: 1366
    height: 768

sound_system:
    tracks:
       music:
          simultaneous_sounds: 1
          volume: 0.8
       voice:
          simultaneous_sounds: 1
          volume: 1.0
       sfx:
          simultaneous_sounds: 10
          volume: 1.0
sounds:
assets:
    sounds:
        default:
            load: preload
        music:
            track: music
        sfx:
            track: sfx
        voice:
            track: voice
    videos:
        default:
            load: preload
