#config_version=6

game:
  balls_per_game: 3
  max_players: 4
    #allow_start_with_ball_in_drain: true
    #allow_start_with_loose_balls: true

config:
- hardware.yaml
- keyboard.yaml
- shots.yaml
- videos.yaml
- lights.yaml

modes:
  - attract
  - base
  - skillshot
  - music_player
  - cellar
  - selection_mode
  - razorwire
  - drillchair
  - quadshotgun
  - flammablejelly
  - reversebeartrap
  - zeptest
  - tilt
  - mystery
  - saw_qualify
  - mode_tracking
  - jigsaw_multiball
  - hacksaw_multiball
  - high_score
  - bonus

window:
  width: 1366
  height: 768
  title: Mission Pinball Framework - SAW
  resizable: true
  fullscreen: false
  borderless: true
  exit_on_escape: true
  source_display: lcd
displays:
  lcd:
    width: 1366
    height: 768

sound_player:
  mode_attract_started:
    HelloZeppPt1:
      action: play
      loops: 3
    BaseMusic:
      action: stop
  mode_attract_stopped:
    HelloZeppPt1:
      action: stop
  mode_game_stopping:
    initials:
      action: stop
  mode_high_score_started:
    BaseMusic:
      action: stop

sound_system:
    tracks:
       music:
          simultaneous_sounds: 8
          volume: 1.0
       voice:
          simultaneous_sounds: 8
          volume: 1.0
       sfx:
          simultaneous_sounds: 16
          volume: 1.0
sounds:
assets:
    sounds:
        default:
            load: preload
        music:
            track: music
        sfx:
            track: sfx
        voice:
            track: voice
    videos:
        default:
            load: preload
