#config_version=6

game:
  balls_per_game: 3
  max_players: 4
    #allow_start_with_ball_in_drain: true
    #allow_start_with_loose_balls: true

config:
- hardware.yaml
- keyboard.yaml
- shots.yaml
- videos.yaml
- lights.yaml

modes:
  - attract
  - base
  - skillshot
  - super_skillshot
  - music_player
  - trap_select
  - selection_mode
  - razorwire
  - drillchair
  - quadshotgun
  - flammablejelly
  - reversebeartrap
  - zeptest
  - tilt
  - make_your_choice_hurryup
  - puzzle_hurryup
  - hostage
  - survival_instinct
#  - the_key_to_freedom 
  - mystery
  - saw_qualify
  - mode_tracking
  - jigsaw_multiball
  - jigsaw_multiball_qualify
  - hacksaw_multiball
  - hacksaw_multiball_qualify
  - shackle_multiball
  - shackle_multiball_qualify
  - high_score
  - bonus
  - stop_game

window:
  width: 1366
  height: 768
  title: Mission Pinball Framework - SAW
  resizable: true
#  fullscreen: true
  fullscreen: false
  borderless: true
  exit_on_escape: true
  source_display: lcd
displays:
  lcd:
    width: 1366
    height: 768

mpf:
    report_crashes: never

sound_system:
    tracks:
       music:
          simultaneous_sounds: 1
          volume: 0.8
       voice:
          simultaneous_sounds: 1
          volume: 1.0
       sfx:
          simultaneous_sounds: 10
          volume: 1.0
sounds:
  OrbitWoosh6:
    file: OrbitWoosh6.wav
    volume: 0.1
# cher/amanda callouts volume lowered
  Antidote1:
    file: Antidote1.wav
    volume: 0.2
  Antidote2:
    file: Antidote2.wav
    volume: 0.2
  Antidote3:
    file: Antidote3.wav
    volume: 0.2
  Antidote4:
    file: Antidote4.wav
    volume: 0.2
  Ball1Locked1:
    file: Ball1Locked1.wav
    volume: 0.2
  Ball1Locked2:
    file: Ball1Locked2.wav
    volume: 0.2
  Ball2Locked1:
    file: Ball2Locked1.wav
    volume: 0.2
  Ball2Locked2:
    file: Ball2Locked2.wav
    volume: 0.2
  Ball2Locked3:
    file: Ball2Locked3.wav
    volume: 0.2
  Bathtub1:
    file: Bathtub1.wav
    volume: 0.2
  Bathtub2:
    file: Bathtub2.wav
    volume: 0.2
  Bathtub3:
    file: Bathtub3.wav
    volume: 0.2
  Bathtub4:
    file: Bathtub4.wav
    volume: 0.2
  Bathtub5:
    file: Bathtub5.wav
    volume: 0.2
  Candle1:
    file: Candle1.wav
    volume: 0.2
  Candle2:
    file: Candle2.wav
    volume: 0.2
  Candle3:
    file: Candle3.wav
    volume: 0.2
  Candle4:
    file: Candle4.wav
    volume: 0.2
  Candle5:
    file: Candle5.wav
    volume: 0.2
  ExtraBall:
    file: ExtraBall.wav
    volume: 0.2
  ExtraBallIsLit1:
    file: ExtraBallIsLit1.wav
    volume: 0.2
  ExtraBallIsLit2:
    file: ExtraBallIsLit2.wav
    volume: 0.2
  Gears1:
    file: Gears1.wav
    volume: 0.2
  Gears2:
    file: Gears2.wav
    volume: 0.2
  Gears3:
    file: Gears3.wav
    volume: 0.2
  Gears4:
    file: Gears4.wav
    volume: 0.2
  Gears5:
    file: Gears5.wav
    volume: 0.2
  Gun1:
    file: Gun1.wav
    volume: 0.2
  Gun2:
    file: Gun2.wav
    volume: 0.2
  Gun3:
    file: Gun3.wav
    volume: 0.2
  Gun4:
    file: Gun4.wav
    volume: 0.2
  Gun5:
    file: Gun5.wav
    volume: 0.2
  Hacksaw1:
    file: Hacksaw1.wav
    volume: 0.2
  Hacksaw2:
    file: Hacksaw2.wav
    volume: 0.2
  Hacksaw3:
    file: Hacksaw3.wav
    volume: 0.2
  Hacksaw4:
    file: Hacksaw4.wav
    volume: 0.2
  Hacksaw5:
    file: Hacksaw5.wav
    volume: 0.2
  HeHelpedMe:
    file: HeHelpedMe.wav
    volume: 0.2
  Jackpot1:
    file: Jackpot1.wav
    volume: 0.2
  Jackpot2:
    file: Jackpot2.wav
    volume: 0.2
  Jackpot3:
    file: Jackpot3.wav
    volume: 0.2
  Jackpot4:
    file: Jackpot4.wav
    volume: 0.2
  Jackpot5:
    file: Jackpot5.wav
    volume: 0.2
  Key1:
    file: Key1.wav
    volume: 0.2
  Key2:
    file: Key2.wav
    volume: 0.2
  Key3:
    file: Key3.wav
    volume: 0.2
  Key4:
    file: Key4.wav
    volume: 0.2
  Key5:
    file: Key5.wav
    volume: 0.2
  LockIsLit1:
    file: LockisLit1.wav
    volume: 0.2
  LockIsLit2:
    file: LockisLit2.wav
    volume: 0.2
  LockIsLit3:
    file: LockisLit3.wav
    volume: 0.2
  LockIsLit4:
    file: LockisLit4.wav
    volume: 0.2
  PuzzlePiece1:
    file: PuzzlePiece1.wav
    volume: 0.2
  PuzzlePiece2:
    file: PuzzlePiece2.wav
    volume: 0.2
  PuzzlePiece3:
    file: PuzzlePiece3.wav
    volume: 0.2
  PuzzlePiece4:
    file: PuzzlePiece4.wav
    volume: 0.2
  PuzzlePiece5:
    file: PuzzlePiece5.wav
    volume: 0.2
  TapeRecorder1:
    file: TapeRecorder1.wav
    volume: 0.2
  TapeRecorder2:
    file: TapeRecorder2.wav
    volume: 0.2
  TapeRecorder3:
    file: TapeRecorder3.wav
    volume: 0.2
  TapeRecorder4:
    file: TapeRecorder4.wav
    volume: 0.2
  TapeRecorder5:
    file: TapeRecorder5.wav
    volume: 0.2
  SuperJackpot:
    file: SuperJackpot.wav
    volume: 0.2
  SuperJackpot3:
    file: SuperJackpot3.wav
    volume: 0.2
  SuperJackpot5:
    file: SuperJackpot5.wav
    volume: 0.2
  AddABall:
    file: AddABall.wav
    volume: 0.2
  ShootRRToLockABall:
    file: ShootRRToLockABall.wav
    volume: 0.2
  ShootTheRRToLockABall2:
    file: ShootTheRRToLockABall2.wav
    volume: 0.2
  ToLockaBallShootTheRR1:
    file: ToLockaBallShootTheRR1.wav
    volume: 0.2
  ToLockaBallShootTheRR2:
    file: ToLockaBallShootTheRR2.wav
    volume: 0.2
  GetTheSuperJackpot:
    file: GetTheSuperJackpot.wav
    volume: 0.2
  LL1:
    file: LL1.wav
    volume: 0.2
  LL2:
    file: LL2.wav
    volume: 0.2
  LL3: 
    file: LL3.wav
    volume: 0.2
  ShootLRToLockaBall1:
    file: ShootLRToLockaBall1.wav
    volume: 0.2
  ShootLRToLockaBall2:
    file: ShootLRToLockaBall2.wav
    volume: 0.2
  ShootLRToLockaBall3:
    file: ShootLRToLockaBall3.wav
    volume: 0.2
  DSSS1:
    file: DSSS1.wav
    volume: 0.2
  DSSS2:
    file: DSSS2.wav
    volume: 0.2
  DSSS4:
    file: DSSS4.wav
    volume: 0.2
  SkillShot1:
    file: SkillShot1.wav
    volume: 0.2
  SkillShot2:
    file: SkillShot2.wav
    volume: 0.2
  SkillShot3:
    file: SkillShot3.wav
    volume: 0.2
  SkillShot4:
    file: SkillShot4.wav
    volume: 0.2
  SSS1:
    file: SSS1.wav
    volume: 0.2
  SSS2:
    file: SSS2.wav
    volume: 0.2
  SSS4:
    file: SSS4.wav
    volume: 0.2
  SSS5:
    file: SSS5.wav
    volume: 0.2
  SuperSkillShot1:
    file: SuperSkillShot1.wav
    volume: 0.2
  SuperSkillShot2:
    file: SuperSkillShot2.wav
    volume: 0.2
  SuperSkillShot3:
    file: SuperSkillShot3.wav
    volume: 0.2
  SuperSkillShot4:
    file: SuperSkillShot4.wav
    volume: 0.2
  SuperSkillShot5:
    file: SuperSkillShot5.wav
    volume: 0.2
  GetToTheBathroom:
    file: GetToTheBathroom.wav
    volume: 0.2
  GetToTheBathroom2:
    file: GetToTheBathroom2.wav
    volume: 0.2
  ShootTheRightScoopToStartATrap2:
    file: ShootTheRightScoopToStartATrap2.wav
    volume: 0.2
  ShootTheRightScoopToStartATrap:
    file: ShootTheRightScoopToStartATrap.wav
    volume: 0.2
  ShootWhiteArrows:
    file: ShootWhiteArrows.wav
    volume: 0.2
  ShootWhiteArrows1:
    file: ShootWhiteArrows1.wav
    volume: 0.2
  ToStartATrapShootTheRightScoop:
    file: ToStartATrapShootTheRightScoop.wav
    volume: 0.2
  FirstDrillDestroyed:
    file: FirstDrillDestroyed.wav
    volume: 0.2
  ShootLeftOrbit:
    file: ShootLeftOrbit.wav
    volume: 0.2
  YouNeedTheLowerPops:
    file: YouNeedTheLowerPops.wav
    volume: 0.2
  HitTheDropTargetNOW:
    file: HitTheDropTargetNOW.wav
    volume: 0.2
  NiceShotNowTheOrbit:
    file: NiceShotNowTheOrbit.wav
    volume: 0.2
  RipTheSpinner:
    file: RipTheSpinner.wav
    volume: 0.2
  YouJustNeedTheLeftOrbit:
    file: YouJustNeedTheLeftOrbit.wav
    volume: 0.2
  GetToTheUpperPops:
    file: GetToTheUpperPops.wav
    volume: 0.2
  ShootTheLeftRampToLive:
    file: ShootTheLeftRampToLive.wav
    volume: 0.2
  ShootAllTheStandupTargets:
    file: ShootAllTheStandupTargets.wav
    volume: 0.2
  ShootTheCombos:
    file: ShootTheCombos.wav
    volume: 0.2
  ShootTheCombos2:
    file: ShootTheCombos2.wav
    volume: 0.2
  ShootTheDropTargetToEscape:
    file: ShootTheDropTargetToEscape.wav
    volume: 0.2
  CompleteTheLowerDrops:
    file: CompleteTheLowerDrops.wav
    volume: 0.2
  HitTheRightRamp:
    file: HitTheRightRamp.wav
    volume: 0.2
  QuicklyShotTheDropTarget:
    file: QuicklyShotTheDropTarget.wav
    volume: 0.2
  ShootTheLeftRamp:
    file: ShootTheLeftRamp.wav
    volume: 0.2

#spinner sound
  Spinner3:
    file: Spinner3.wav
    volume: 0.4

assets:
    sounds:
        default:
            load: preload
        music:
            track: music
        sfx:
            track: sfx
        voice:
            track: voice
    videos:
        default:
            load: preload


#end of ball 3 event that lives outside base mode
# involves door slam video + light effect then topper actuates
slides:
  gameovervideo:
    widgets:
    - type: video
      video: GameOverVideo
      width: 1366
      height: 768
  ShootAgain:
    widgets:
    - type: video
      video: ShootAgain
      width: 1366
      height: 768
  extraballvideo:
    widgets:
    - type: video
      video: extraball
      width: 1366
      height: 768
slide_player:
  ball_will_end{current_player.ball==3 and is_extra_ball==False}:
    gameovervideo:
      action: play
      priority: 600
      expire: 2.5s
  e_shoot_again:
    ShootAgain:
      priority: 400
      expire: 5s
  shot_extraball_sp_extraball_lit_hit:
    extraballvideo:
      priority: 400
      expire: 8s
  player_modes_completed{value==2}: 
     extraballvideo:
      priority: 400
      expire: 8s 
  player_puzzle_pieces{value==3}: 
    extraballvideo:
      priority: 400
      expire: 8s  
  player_combo_progress{value==4}:
    extraballvideo:
      priority: 400
      expire: 8s
  
show_player:
# end of ball 3
  ball_will_end{current_player.ball==3}:
    game_over:
      loops: 0
      speed: 8
  e_topper_trigger:
    topper_trigger_on:
      loops: 0
      speed: 9
  mode_reversebeartrap_stopping{current_player.ball<3}:
    topper_trigger_on:
      loops: 0
      speed: 9
  shot_left_outlane_hit{state=="ball_save_not_ready"}:
      billy_laugh:
        loops: 7
        speed: 4
      spotlight_taperecorder_on:
        show_tokens:
          color1: white
  shot_right_outlane_hit{state=="ball_save_not_ready"}:
      billy_laugh:
        loops: 7
        speed: 4
      spotlight_taperecorder_on:
        show_tokens:
          color1: white
  e_mystery_extraballlit:
      extra_ball_is_lit:
        loops: -1
        show_tokens:
          color1: drillchair
event_player:
  ball_starting{is_extra_ball==True}: e_shoot_again    