#config_version=6

hardware:
#    platform: smart_virtual
    platform: fast

fast:
  net:
    controller: neuron
    io_loop:
      "0804":
        model: FP-I/O-0804
        order: 1
      "1616_1":
        model: FP-I/O-1616
        order: 2
      "1616_2":
        model: FP-I/O-1616
        order: 3
      "3208":
        model: FP-I/O-3208
        order: 4
  exp:
    boards:
      led256:
        model: FP-EXP-0081
      led128:
        model: FP-EXP-0071
      ledneuron:
        model: FP-EXP-2000
          #debug: true
machine:
  #min_balls: 3

switches:
  # s_plumb_bob_tilt:
  #   number: 0808-1
  #   tags: tilt_bob
  s_left_flipper_eos:
    number: 3208-30
    tags: left_flipper
  s_right_flipper_eos:
    number: 3208-31
    tags: right_flipper
  s_left_flipper_button:
    number: 0804-0
    tags: left_flipper
  s_right_flipper_button:
    number: 0804-1
    tags: right_flipper   
  s_upper_right_flipper_eos:
    number: 1616_2-8
    tags: upper_right_flipper
  s_upper_right_flipper_button:
    number: 0804-2
    tags: upper_right_flipper
  s_trough1:
    number: 3208-18
    type: 'NC'
  s_trough2:
    number: 3208-19
  s_trough3:
    number: 3208-20
  s_trough4:
    number: 3208-21
  s_trough5:
    number: 3208-22
  s_trough6:
    number: 3208-23
  s_trough_jam:
    number: 3208-17
    type: 'NC'
  s_start:
    number: 0804-3
    tags: start
  s_action_button:
    number: 0804-4
    tags: action
  s_left_inlane:
    number: 3208-25
    tags: left_return_lane, playfield_active, inlane, switch_hit
  s_left_outlane:
    number: 3208-26
    tags: left_out_lane, playfield_active, outlane, switch_hit
  s_right_inlane:
    number: 3208-1
    tags: right_return_lane, playfield_active, inlane, switch_hit
  s_right_outlane:
    number: 3208-0
    tags: right_out_lane, playfield_active, outlane, switch_hit
  s_right_cellar:
    number: 1616_1-13
    tags: right_cellar, switch_hit
  s_left_cellar:
    number: 1616_1-14
    tags: left_cellar, switch_hit
  s_left_standup:
    number: 1616_1-12
    tags: left_standup, standup, switch_hit
# Left Lock 1 (lwr)
  s_left_lock_1:
    number: 3208-29
    tags: left_lock_1 , left_lock
# Left Lock 2 (mid)
  s_left_lock_2:
    number: 3208-28
    tags: left_lock_2, left_lock
# Left Lock 3 (upr)
  s_left_lock_3:
    number: 3208-27
    tags: left_lock_3, left_lock
  s_right_standup:
    number: 1616_2-7
    tags: right_standup, standup, switch_hit
  s_upper_bank_drop_target_opto:
    number: 1616_2-6
    tags: drop_target, switch_hit
    # type: 'NC'
  s_lower_bank_drop_target_opto_upper:
    number: 3208-10
    tags: drop_target, switch_hit, lower_drop_target
    # type: 'NC'
  s_lower_bank_drop_target_opto_middle:
    number: 3208-9
    tags: drop_target, switch_hit, lower_drop_target
    # type: 'NC'
  s_lower_bank_drop_target_opto_lower:
    number: 3208-8
    tags: drop_target, switch_hit, lower_drop_target
    # type: 'NC'
  s_middle_standup:
    number: 1616_1-5
    tags: middle_standup, standup, switch_hit
  s_enter_left_ramp:
    number: 1616_1-6
    tags: left_ramp, ramp_hit, switch_hit, ramp
  s_left_ramp_score_top:
    number: 3208-7
    tags: left_ramp, ramp_hit, switch_hit, ramp
  s_left_ramp_score_bottom:
    number: 1616_2-1
    tags: left_ramp, ramp_hit, switch_hit, ramp
  s_left_loop_top:
    number: 1616_1-0
    tags: left_loop, loop_hit, switch_hit, loop
  s_left_loop_bottom:
    number: 1616_1-1
    tags: left_loop, loop_hit, switch_hit, loop
  s_right_loop_top:
    number: 1616_2-15
    tags: right_loop, loop_hit, switch_hit, loop
  s_right_loop_bottom:
    number: 1616_2-14
    tags: right_loop, loop_hit, switch_hit, loop
  s_inner_loop:
    number: 1616_1-8
    tags: inner_loop, loop_hit, switch_hit, loop
  s_spinner:
    number: 1616_2-9
    tags: spinner
  s_right_ramp_down:
    number: 1616_2-12
    tags: right_ramp, ramp_hit, switch_hit, ramp
  s_top_right_reject:
    number: 1616_2-13
    tags: right_ramp, ramp_hit, switch_hit
  s_right_ramp_score_top:
    number: 1616_1-7
    tags: right_ramp, ramp_hit, switch_hit, ramp
  s_right_ramp_score_bottom:
    number: 1616_2-0
    tags: right_ramp, switch_hit, switch_hit, ramp
  s_left_standup_right_ramp:
    number: 1616_2-10
    tags: standup, switch_hit
  s_right_standup_right_ramp:
    number: 1616_2-11
    tags: standup, switch_hit
  s_left_110_point:
    number: 3208-14
    tags: standup, switch_hit
  s_right_110_point:
    number: 3208-6
    tags: standup, switch_hit
  s_left_top_jet_bumper:
    number: 1616_1-2
    tags: top_pops, pops, switch_hit
  s_right_top_jet_bumper:
    number: 1616_1-3
    tags: top_pops, pops, switch_hit
  s_lower_top_jet_bumper:
    number: 1616_1-4
    tags: top_pops, pops, switch_hit
  s_left_bottom_jet_bumper:
    number: 1616_1-11
    tags: bottom_pops, pops, switch_hit
  s_right_bottom_jet_bumper:
    number: 1616_1-10
    tags: bottom_pops, pops, switch_hit
  s_upper_bottom_jet_bumper:
    number: 1616_1-9
    tags: bottom_pops, pops, switch_hit
  s_ball_shooter_lane:
    number: 3208-16
  s_left_slingshot:
    number: 3208-24
    tags: slingshot
  s_right_slingshot:
    number: 3208-2
    tags: slingshot

virtual_platform_start_active_switches:
  - s_trough1
  - s_trough2
  - s_trough3
  - s_trough4
  - s_trough5
  - s_trough6

coils:
  c_flipper_left_main:
    number: 3208-6
    default_pulse_ms: 20
    tags: coils
  c_flipper_left_hold:
    number: 3208-5
    default_pulse_ms: 20
    default_hold_power: 0.2
    tags: coils
  c_flipper_right_main:
    number: 3208-3
    default_pulse_ms: 20
    tags: coils
  c_flipper_right_hold:
    number: 3208-4
    default_pulse_ms: 20
    default_hold_power: 0.2
    tags: coils
  c_flipper_upper_right_main:
    number: 1616_2-9
    default_pulse_ms: 20
    tags: coils
  c_flipper_upper_right_hold:
    number: 1616_2-8
    default_pulse_ms: 20
    default_hold_power: 0.2
    tags: coils
  c_trough_eject:
    number: 3208-1
    default_pulse_ms: 20
    default_pulse_power: 0.9
  c_auto_plunger:
    number: 3208-0
    default_pulse_ms: 20
  c_diverter:
    number: 1616_1-14
    default_pulse_ms: 20
    default_pulse_power: 0.5
  c_top_eject:
    number: 1616_2-12
    default_pulse_ms: 20
    default_pulse_power: 0.9
  c_mystery_eject:
    number: 1616_1-15
    default_pulse_ms: 20
  c_right_ramp_lift:
    number: 1616_2-10
    default_pulse_ms: 20
    default_pulse_power: 0.5
  c_right_ramp_down:
    number: 1616_2-11
    default_pulse_ms: 20
    default_pulse_power: 0.5
  c_left_spin_disc:
    number: 1616_2-2
    default_hold_power: 0.5
  c_middle_spin_disc:
    number: 1616_2-1
    default_hold_power: 0.5
  c_right_spin_disc:
    number: 1616_2-0
    default_hold_power: 0.5
  c_left_lock_kickback:
    number: 1616_1-12
    default_pulse_ms: 20
  c_left_top_jet_bumper:
    number: 1616_1-2
    default_pulse_ms: 20
  c_right_top_jet_bumper:
    number: 1616_1-1
    default_pulse_ms: 20
  c_lower_top_jet_bumper:
    number: 1616_1-3
    default_pulse_ms: 20
  c_left_bottom_jet_bumper:
    number: 1616_1-6
    default_pulse_ms: 20
  c_right_bottom_jet_bumper:
    number: 1616_1-5
    default_pulse_ms: 20
  c_upper_bottom_jet_bumper:
    number: 1616_1-4
    default_pulse_ms: 20
  c_left_slingshot:
    number: 3208-7
    default_pulse_ms: 20
  c_right_slingshot:
    number: 3208-2
    default_pulse_ms: 20
  c_lower_droptargetreset:
    number: 1616_1-13
    default_pulse_ms: 20
  c_upper_droptargetreset:
    number: 1616_1-0
    default_pulse_ms: 20
    default_pulse_power: 0.9

drop_targets:
  dt_upper_drop1:
    switch: s_upper_bank_drop_target_opto
  dt_lower_drop1:
    switch: s_lower_bank_drop_target_opto_upper
  dt_lower_drop2:
    switch: s_lower_bank_drop_target_opto_middle
  dt_lower_drop3:
    switch: s_lower_bank_drop_target_opto_lower

drop_target_banks:
  lower_dropbank:
    drop_targets:
      - dt_lower_drop1
      - dt_lower_drop2
      - dt_lower_drop3
    reset_on_complete: 1s
    reset_coils: c_lower_droptargetreset
    reset_events:
      ball_started.1: 0
      ball_started.2: 1s
      ball_started.3: 2s
      machine_reset_phase_3: 0 
  upper_dropbank:
    drop_targets:
      - dt_upper_drop1
    reset_on_complete: 1s
    reset_coils: c_upper_droptargetreset
    reset_events: 
      ball_started.1: 0
      ball_started.2: 1s
      ball_started.3: 2s
      machine_reset_phase_3: 0 

ball_devices:
  bd_trough:
    ball_switches: s_trough1, s_trough2, s_trough3, s_trough4, s_trough5, s_trough6
    eject_coil: c_trough_eject
    tags: trough, home, drain
    jam_switch: s_trough_jam
    eject_coil_jam_pulse: 15ms
    eject_targets: bd_plunger
    debug: false
    eject_timeouts: 3s

  bd_plunger:
    ball_switches: s_ball_shooter_lane
    eject_coil: c_auto_plunger
    mechanical_eject: true
    eject_timeouts: 5s
    player_controlled_eject_event: s_action_button_active

  bd_mystery:
    ball_switches: s_left_cellar
    eject_coil: c_mystery_eject
    mechanical_eject: true
    eject_timeouts: 8000ms

  bd_bathroom:
    ball_switches: s_right_cellar
    eject_coil: c_mystery_eject
    mechanical_eject: true
    eject_timeouts: 8000ms

  bd_top_saucer:
    ball_switches: s_top_right_reject
    eject_coil: c_top_eject
    mechanical_eject: true
    eject_timeouts: 1.5s

playfields:
  playfield:
    tags: default
    default_source_device: bd_plunger
    enable_ball_search: True
    ball_search_timeout: 20s
    ball_search_wait_after_iteration: 10s
    ball_search_interval: 250ms

flippers:
  left_flipper:
    main_coil: c_flipper_left_main
    hold_coil: c_flipper_left_hold
    activation_switch: s_left_flipper_button
  right_flipper:
    main_coil: c_flipper_right_main
    hold_coil: c_flipper_right_hold
    activation_switch: s_right_flipper_button
  upper_right_flipper:
    main_coil: c_flipper_upper_right_main
    hold_coil: c_flipper_upper_right_hold
    activation_switch: s_upper_right_flipper_button

autofire_coils:
  left_slingshot:
    coil: c_left_slingshot
    switch: s_left_slingshot
  right_slingshot:
    coil: c_right_slingshot
    switch: s_right_slingshot
  left_top_bumper:
    coil: c_left_top_jet_bumper
    switch: s_left_top_jet_bumper
  right_top_bumper:
    coil: c_right_top_jet_bumper
    switch: s_right_top_jet_bumper
  lower_top_bumper:
    coil: c_lower_top_jet_bumper
    switch: s_lower_top_jet_bumper
  left_bottom_bumper:
    coil: c_left_bottom_jet_bumper
    switch: s_left_bottom_jet_bumper
  right_bottom_bumper:
    coil: c_right_bottom_jet_bumper
    switch: s_right_bottom_jet_bumper
  upper_bottom_bumper:
    coil: c_upper_bottom_jet_bumper
    switch: s_upper_bottom_jet_bumper
  mystery_scoop:
    coil: c_mystery_eject
    switch: s_left_cellar

  left_kickback_test:
    coil: c_left_lock_kickback
    switch: s_left_lock_1
  right_ramp_lift_test:
    coil: c_right_ramp_lift
    switch: s_right_loop_bottom

diverters:
  right_ramp_diverter:
    activation_coil: c_right_ramp_lift
    deactivation_coil: c_right_ramp_down
    type: pulse
