#config_version=5

hardware:
    platform: smart_virtual

#   fast:
#     net:
#       controller: neuron
#       port: /dev/tty.usbmodem11101
#     exp:
#       port: /dev/tty.usbmodem11102
#       boards:
#         LED_256:
#           model: FP-EXP-0081
#           order: 1

machine:
  min_balls: 3

switches:
  s_plumb_bob_tilt:
    number:
    tags: tilt_bob
  s_left_flipper:
    number:
    tags: left_flipper
  s_right_flipper:
    number:
    tags: right_flipper
  s_upper_right_flipper:
    number:
    tags: upper_right_flipper
  #Ball Trough #1 (left)
  s_trough1:
    number:
    tags: left_trough
  #Ball Trough #2 (mdl)
  s_trough2:
    number:
    tags: middle_trough
  #Ball Trough #3 (right)
  s_trough3:
    number:
    tags: right_trough
  s_trough_jam:
    number:
  s_outhole:
    number:
  s_start:
    number:
    tags: start
  s_action_button:
    number:
    tags: action
  s_left_inlane:
    number: 18
    tags: left_return_lane, playfield_active, inlane, switch_hit
  s_left_outlane:
    number: 17
    tags: left_out_lane, playfield_active, outlane, switch_hit
  s_right_inlane:
    number: 15
    tags: right_return_lane, playfield_active, inlane, switch_hit
  s_right_outlane:
    number: 16
    tags: right_out_lane, playfield_active, outlane, switch_hit
  s_right_cellar:
    number: 19
    tags: right_cellar, switch_hit
  s_left_cellar:
    number: 20
    tags: left_cellar, switch_hit
  s_left_standup:
    number: 21
    tags: left_standup, standup, switch_hit
# Left Lock 1 (lwr)
  s_left_lock_1:
    number: 22
    tags: left_lock_1 , left_lock
# Left Lock 2 (mid)
  s_left_lock_2:
    number: 23
    tags: left_lock_2, left_lock
# Left Lock 3 (upr)
  s_left_lock_3:
    number: 24
    tags: left_lock_3, left_lock
  s_right_standup:
    number: 25
    tags: right_standup, standup, switch_hit
  s_upper_bank_drop_target_opto:
    number: 26
    tags: drop_target, switch_hit
  s_lower_bank_drop_target_opto_upper:
    number: 27
    tags: drop_target, switch_hit
  s_lower_bank_drop_target_opto_middle:
    number: 28
    tags: drop_target, switch_hit
  s_lower_bank_drop_target_opto_lower:
    number: 29
    tags: drop_target, switch_hit
  s_middle_standup:
    number: 30
    tags: middle_standup, standup, switch_hit
  s_enter_left_ramp:
    number: 33
    tags: left_ramp, ramp_hit, switch_hit, ramp
  s_left_ramp_score_top:
    number: 34
    tags: left_ramp, ramp_hit, switch_hit, ramp
  s_left_ramp_score_bottom:
    number: 35
    tags: left_ramp, ramp_hit, switch_hit, ramp
  s_left_loop_top:
    number: 36
    tags: left_loop, loop_hit, switch_hit, loop
  s_left_loop_bottom:
    number: 37
    tags: left_loop, loop_hit, switch_hit, loop
  s_right_loop_top:
    number: 38
    tags: right_loop, loop_hit, switch_hit, loop
  s_right_loop_bottom:
    number: 39
    tags: right_loop, loop_hit, switch_hit, loop
  s_inner_loop:
    number: 40
    tags: inner_loop, loop_hit, switch_hit, loop
  s_spinner:
    number: 41
    tags: spinner
  s_right_ramp_down:
    number: 42
    tags: right_ramp, ramp_hit, switch_hit, ramp
  s_top_right_reject:
    number: 43
    tags: right_ramp, ramp_hit, switch_hit
  s_right_ramp_score_top:
    number: 44
    tags: right_ramp, ramp_hit, switch_hit, ramp
  s_right_ramp_score_bottom:
    number: 45
    tags: right_ramp, switch_hit, switch_hit, ramp
  s_left_standup_right_ramp:
    number: 47
    tags: standup, switch_hit
  s_right_standup_right_ramp:
    number: 48
    tags: standup, switch_hit
  s_left_110_point:
    number:
    tags: standup, switch_hit
  s_right_110_point:
    number:
    tags: standup, switch_hit
  s_left_top_jet_bumper:
    number: 49
    tags: top_pops, pops, switch_hit
  s_right_top_jet_bumper:
    number: 50
    tags: top_pops, pops, switch_hit
  s_lower_top_jet_bumper:
    number: 51
    tags: top_pops, pops, switch_hit
  s_left_bottom_jet_bumper:
    number: 52
    tags: bottom_pops, pops, switch_hit
  s_right_bottom_jet_bumper:
    number: 53
    tags: bottom_pops, pops, switch_hit
  s_upper_bottom_jet_bumper:
    number: 54
    tags: bottom_pops, pops, switch_hit
  s_ball_shooter_lane:
    number: 59
  s_left_slingshot:
    number:
    tags: slingshot
  s_right_slingshot:
    number:
    tags: slingshot

virtual_platform_start_active_switches:
  - s_trough1
  - s_trough2
  - s_trough3

coils:
  c_flipper_left_main:
    number:
    default_pulse_ms: 20
    tags: coils
  c_flipper_left_hold:
    number:
    default_pulse_ms: 20
    default_hold_power: 1.0
    tags: coils
  c_flipper_right_main:
    number:
    default_pulse_ms: 80
    tags: coils
  c_flipper_right_hold:
    number:
    default_pulse_ms: 20
    default_hold_power: 1.0
    tags: coils
  c_flipper_upper_right_main:
    number:
    default_pulse_ms: 80
    tags: coils
  c_flipper_upper_right_hold:
    number:
    default_pulse_ms: 20
    default_hold_power: 1.0
    tags: coils
  c_draineject:
    number:
    default_pulse_ms: 20
    default_hold_power: 1.0
  c_trough_eject:
    number:
  c_diverter:
    number:
  c_top_eject:
    number:
  c_mystery_eject:
    number:
  c_right_ramp_lift:
    number:
  c_right_ramp_down:
    number:
  c_left_spin_disc:
    number:
  c_middle_spin_disc:
    number:
  c_right_spin_disc:
    number:
  c_left_lock_kickback:
    number:
  c_left_top_jet_bumper:
    number:
  c_right_top_jet_bumper:
    number:
  c_lower_top_jet_bumper:
    number:
  c_left_bottom_jet_bumper:
    number:
  c_right_bottom_jet_bumper:
    number:
  c_upper_bottom_jet_bumper:
    number:
  c_left_slingshot:
    number:
  c_right_slingshot:
    number:
  c_lower_droptargetreset:
    number: 12
    default_pulse_ms: 250
  c_upper_droptargetreset:
    number:
  flasher_c_bottom_right:
    number:
    allow_enable: true
  flasher_c_spinner:
    number:
    allow_enable: true
  flasher_c_right_ramp_top:
    number:
    allow_enable: true
  flasher_c_right_ramp_upr_mid:
    number:
    allow_enable: true
  flasher_c_right_ramp_lwr_mid:
    number:
    allow_enable: true
  flasher_c_right_ramp_bottom:
    number:
    allow_enable: true
  flasher_c_lower_drop:
    number:
    allow_enable: true
  flasher_c_compass:
    number:
    allow_enable: true
  flasher_c_bp_left:
    number:
    allow_enable: true
  flasher_c_bp_mid:
    number:
    allow_enable: true
  flasher_c_bp_right:
    number:
    allow_enable: true

drop_targets:
  dt_upper_drop1:
    switch: s_upper_bank_drop_target_opto
  dt_lower_drop1:
    switch: s_lower_bank_drop_target_opto_upper
  dt_lower_drop2:
    switch: s_lower_bank_drop_target_opto_middle
  dt_lower_drop3:
    switch: s_lower_bank_drop_target_opto_lower

drop_target_banks:
  lower_dropbank:
    drop_targets:
      - dt_lower_drop1
      - dt_lower_drop2
      - dt_lower_drop3
    reset_on_complete: 1s
    reset_coils: c_lower_droptargetreset
    reset_events: ball_starting
  upper_dropbank:
    drop_targets:
      - dt_upper_drop1
    reset_on_complete: 1s
    reset_coils: c_upper_droptargetreset
    reset_events: ball_starting

ball_devices:
  bd_drain:
    ball_switches: s_outhole
    eject_coil: c_draineject
    eject_targets: bd_trough
    eject_timeouts: 1s
    confirm_eject_type: target
    tags: drain
    debug: true
    ball_search_order: 1

  bd_trough:
    ball_switches: s_trough1, s_trough2, s_trough3, s_trough_jam
    eject_coil: c_trough_eject
    tags: trough, home
    jam_switch: s_trough_jam
    eject_coil_jam_pulse: 15ms
    eject_targets: bd_plunger
    debug: true

  bd_plunger:
    ball_switches: s_ball_shooter_lane
    mechanical_eject: true

  bd_mystery:
    ball_switches: s_left_cellar
    eject_coil: c_mystery_eject
    mechanical_eject: true
    eject_timeouts: 8000ms

playfields:
  playfield:
    tags: default
    default_source_device: bd_plunger
    enable_ball_search: True
    ball_search_timeout: 20s
    ball_search_wait_after_iteration: 10s
    ball_search_interval: 250ms

flippers:
  left_flipper:
    main_coil: c_flipper_left_main
    hold_coil: c_flipper_left_hold
    activation_switch: s_left_flipper
  right_flipper:
    main_coil: c_flipper_right_main
    hold_coil: c_flipper_right_hold
    activation_switch: s_right_flipper

autofire_coils:
  left_slingshot:
    coil: c_left_slingshot
    switch: s_left_slingshot
  right_slingshot:
    coil: c_right_slingshot
    switch: s_right_slingshot
