#config_version=5

hardware:
    platform: fast

fast:
    net:
        controller: neuron
        port: /dev/tty.usbmodem14401
    exp:
        port: /dev/tty.usbmodem14403
        boards:
            upperled:
                model: FP-EXP-0071
        debug: true
