#config_version=6

hardware:
#    platform: smart_virtual
    platform: fast

fast:
  net:
    controller: neuron
    io_loop:
      "0804":
        model: FP-I/O-0804
        order: 1
      "1616_1":
        model: FP-I/O-1616
        order: 2
      "1616_2":
        model: FP-I/O-1616
        order: 3
      "3208":
        model: FP-I/O-3208
        order: 4
  exp:
    boards:
      led256:
        model: FP-EXP-0081
        address: 84
        ignore_led_errors: true
      led128:
        model: FP-EXP-0081
        address: 85
        ignore_led_errors: true
      led256bb:
        model: FP-EXP-0081
        address: 86
        ignore_led_errors: true
      ledneuron:
        model: FP-EXP-2000
        address: 48
        ignore_led_errors: true
mpf: 
  rgbw_white_behavior: duck_rgb

machine:
  balls_installed: 6 #How many balls are physically in your game
  min_balls: 5 #How few balls can be accounted for before you can start a game

switches:
  s_plumb_bob_tilt:
    number: 0804-5
    tags: tilt_bob, tilt_warning
  s_left_flipper_eos:
    number: 3208-30
    tags: left_flipper
    type: 'NC'
  s_right_flipper_eos:
    number: 3208-31
    tags: right_flipper
    type: 'NC'
  s_left_flipper_button:
    number: 0804-0
    tags: left_flipper
  s_right_flipper_button:
    number: 0804-7
    tags: right_flipper   
  s_upper_right_flipper_eos:
    number: 1616_2-8
    tags: upper_right_flipper
    type: 'NC'
  s_upper_right_flipper_button:
    number: 0804-2
    tags: upper_right_flipper
  s_trough1:
    number: 3208-18
    type: 'NC'
  s_trough2:
    number: 3208-19
  s_trough3:
    number: 3208-20
  s_trough4:
    number: 3208-21
  s_trough5:
    number: 3208-22
  s_trough6:
    number: 3208-23
  s_trough_jam:
    number: 3208-17
    type: 'NC'
  s_start:
    number: 0804-3
    tags: start
  s_action_button:
    number: 0804-4
    tags: action
  s_left_inlane:
    number: 3208-25
    tags: left_return_lane, playfield_active, inlane, switch_hit
  s_left_outlane:
    number: 3208-26
    tags: left_out_lane, playfield_active, outlane, switch_hit
  s_right_inlane:
    number: 3208-1
    tags: right_return_lane, playfield_active, inlane, switch_hit
  s_right_outlane:
    number: 3208-0
    tags: right_out_lane, playfield_active, outlane, switch_hit
  s_right_scoop:
    number: 1616_1-13
    tags: right_scoop, switch_hit
  s_left_scoop:
    number: 1616_1-14
    tags: left_scoop, switch_hit
  s_left_standup:
    number: 1616_1-12
    tags: left_standup, playfield_active, standup, switch_hit
# Left Lock 1 (lwr)
  s_left_lock_1:
    number: 3208-29
    tags: left_lock_1 , left_lock
# Left Lock 2 (mid)
  s_left_lock_2:
    number: 3208-28
    tags: left_lock_2, left_lock
# Left Lock 3 (upr)
  s_left_lock_3:
    number: 3208-27
    tags: left_lock_3, left_lock
  s_right_standup:
    number: 1616_2-7
    tags: right_standup, playfield_active, standup, switch_hit
  s_upper_bank_drop_target_opto:
    number: 1616_2-6
    tags: drop_target, switch_hit
    # type: 'NC'
  s_lower_bank_drop_target_opto_upper:
    number: 3208-10
    tags: drop_target, switch_hit, lower_drop_target
    # type: 'NC'
  s_lower_bank_drop_target_opto_middle:
    number: 3208-9
    tags: drop_target, switch_hit, lower_drop_target
    # type: 'NC'
  s_lower_bank_drop_target_opto_lower:
    number: 3208-8
    tags: drop_target, switch_hit, lower_drop_target
    # type: 'NC'
  s_middle_standup:
    number: 1616_1-5
    tags: middle_standup, playfield_active, standup, switch_hit
  s_enter_left_ramp:
    number: 1616_2-3
    tags: left_ramp, ramp_hit, playfield_active, switch_hit, ramp
  s_left_ramp_score_top:
    number: 1616_2-0
    tags: left_ramp, ramp_hit, playfield_active, switch_hit, ramp
  s_left_ramp_score_bottom:
    number: 1616_2-2
    tags: left_ramp, ramp_hit, playfield_active, switch_hit, ramp
  s_left_loop_top:
    number: 1616_1-0
    tags: left_loop, loop_hit, playfield_active, switch_hit, loop
  s_left_loop_bottom:
    number: 1616_1-1
    tags: left_loop, loop_hit, playfield_active, switch_hit, loop
  s_right_loop_top:
    number: 1616_2-15
    tags: right_loop, loop_hit, playfield_active, switch_hit, loop
  s_right_loop_bottom:
    number: 1616_2-14
    tags: right_loop, loop_hit, playfield_active, switch_hit, loop
  s_inner_loop:
    number: 1616_1-8
    tags: inner_loop, loop_hit, playfield_active, switch_hit, loop
  s_spinner:
    number: 1616_2-9
    tags: spinner, playfield_active
  s_right_ramp_down:
    number: 1616_2-12
    tags: right_ramp, ramp_hit, switch_hit, ramp
  s_top_right_reject:
    number: 1616_2-13
    tags: right_ramp, ramp_hit, switch_hit
  s_right_ramp_score_top:
    number: 1616_2-5
    tags: right_ramp, ramp_hit, playfield_active, switch_hit, ramp
  s_right_ramp_score_bottom:
    number: 1616_2-4
    tags: right_ramp, switch_hit, playfield_active, switch_hit, ramp
  s_left_standup_right_ramp:
    number: 1616_2-10
    tags: standup, switch_hit, playfield_active
  s_right_standup_right_ramp:
    number: 1616_2-11
    tags: standup, switch_hit, playfield_active
  s_left_110_point:
    number: 3208-12
    tags: switch_hit, 110, slingshot, playfield_active
  s_right_110_point:
    number: 3208-11
    tags: switch_hit, 110, slingshot, playfield_active
  s_left_top_jet_bumper:
    number: 1616_1-2
    tags: top_pops, pops, switch_hit
  s_right_top_jet_bumper:
    number: 1616_1-3
    tags: top_pops, pops, switch_hit
  s_lower_top_jet_bumper:
    number: 1616_1-4
    tags: top_pops, pops, switch_hit
  s_left_bottom_jet_bumper:
    number: 1616_1-11
    tags: bottom_pops, pops, switch_hit
  s_right_bottom_jet_bumper:
    number: 1616_1-10
    tags: bottom_pops, pops, switch_hit
  s_upper_bottom_jet_bumper:
    number: 1616_1-9
    tags: bottom_pops, pops, switch_hit
  s_ball_shooter_lane:
    number: 3208-16
  s_left_slingshot:
    number: 3208-24
    tags: slingshot
  s_right_slingshot:
    number: 3208-2
    tags: slingshot

virtual_platform_start_active_switches:
  - s_trough1
  - s_trough2
  - s_trough3
  - s_trough4
  - s_trough5
  - s_trough6

coils:
  c_flipper_left_main:
    number: 3208-6
    default_pulse_ms: 25
    default_hold_power: 0.3
    tags: coils
  c_flipper_left_hold:
    number: 3208-5
    default_pulse_ms: 5
    default_hold_power: 0.6
    allow_enable: true
    tags: coils
  c_flipper_right_main:
    number: 3208-3
    default_pulse_ms: 25
    default_hold_power: 0.3
    tags: coils
  c_flipper_right_hold:
    number: 3208-4
    default_pulse_ms: 5
    default_hold_power: 0.6
    allow_enable: true
    tags: coils
  c_flipper_upper_right_main:
    number: 1616_2-9
    default_pulse_ms: 30
    default_hold_power: 0.3
    tags: coils
  c_flipper_upper_right_hold:
    number: 1616_2-8
    default_pulse_ms: 5
    default_hold_power: 0.8
    allow_enable: true    
    tags: coils
  c_trough_eject:
    number: 3208-1
    default_pulse_ms: 20
    default_pulse_power: 0.85
  c_auto_plunger:
    number: 3208-0
    default_pulse_ms: 20
    default_pulse_power: 1.0
  c_diverter:
    number: 1616_1-14
    default_pulse_ms: 20
    default_pulse_power: 0.5
    default_hold_power: 0.3
  c_top_eject:
    number: 1616_2-12
    default_pulse_ms: 20
    default_pulse_power: 0.7
  c_mystery_eject:
    number: 1616_1-15
    default_pulse_ms: 100
  c_right_ramp_lift:
    number: 1616_2-11
    default_pulse_ms: 40
    default_pulse_power: 0.5
  c_right_ramp_down:
    number: 1616_2-10
    default_pulse_ms: 20
    default_pulse_power: 0.5
  c_left_spin_disc:
    number: 1616_2-2
    default_hold_power: 0.5
    allow_enable: true
  c_middle_spin_disc:
    number: 1616_2-1
    default_hold_power: 0.5
    allow_enable: true
  c_right_spin_disc:
    number: 1616_2-0
    default_hold_power: 0.5
    allow_enable: true
  c_left_lock_kickback:
    number: 1616_1-12
    default_pulse_ms: 20
    default_pulse_power: 0.8
  c_left_top_jet_bumper:
    number: 1616_1-2
    default_pulse_ms: 20
    default_pulse_power: 0.7
#    default_pulse_power: 0.9
    max_hold_duration: 1s
  c_right_top_jet_bumper:
    number: 1616_1-1
    default_pulse_ms: 20
    default_pulse_power: 0.7
#    default_pulse_power: 0.9
    max_hold_duration: 1s
  c_lower_top_jet_bumper:
    number: 1616_1-3
    default_pulse_ms: 20
    default_pulse_power: 0.9
    max_hold_duration: 1s
  c_left_bottom_jet_bumper:
    number: 1616_1-6
    default_pulse_ms: 20
    default_pulse_power: 0.9
    max_hold_duration: 1s
  c_right_bottom_jet_bumper:
    number: 1616_1-5
    default_pulse_ms: 20
    default_pulse_power: 0.9
    max_hold_duration: 1s
  c_upper_bottom_jet_bumper:
    number: 1616_1-4
    default_pulse_ms: 20
    default_pulse_power: 0.7
#    default_pulse_power: 0.9
    max_hold_duration: 1s
  c_left_slingshot:
    number: 3208-7
    default_pulse_ms: 35
  c_right_slingshot:
    number: 3208-2
    default_pulse_ms: 35
  c_lower_droptargetreset:
    number: 1616_1-13
    default_pulse_ms: 20
  c_upper_droptargetreset:
    number: 1616_1-0
    default_pulse_ms: 20
    default_pulse_power: 0.9
  c_left_spotlight:
    number: 1616_2-4
    default_hold_power: 0.9
    allow_enable: true
  c_right_spotlight:
    number: 1616_2-3
    default_hold_power: 0.9
    allow_enable: true
  c_tape_spotlight:
    number: 1616_2-5
    default_hold_power: 0.9
    allow_enable: true
  c_domes:
    number: 1616_2-6
    default_hold_power: 0.2
    allow_enable: true
  c_billy:
    number: 1616_2-7
    allow_enable: true
    default_hold_power: 0.25
    max_hold_power: 1.0
  c_mode_scoop:
    number: 1616_1-10
    #default_hold_power: 0.9
    default_hold_power: 0.95
    max_hold_power: 1.0
    allow_enable: true
  c_mystery_scoop:
    number: 1616_1-11
    #default_hold_power: 0.9
    default_hold_power: 0.95
    max_hold_power: 1.0
    allow_enable: true
  c_topper:
    number: 0804-3
    default_hold_power: 1.0
    max_hold_power: 1.0
    allow_enable: true
  c_start_light:
    number: 0804-0
    default_hold_power: 0.9
    allow_enable: true

drop_targets:
  dt_upper_drop1:
    switch: s_upper_bank_drop_target_opto
  dt_lower_drop1:
    switch: s_lower_bank_drop_target_opto_upper
  dt_lower_drop2:
    switch: s_lower_bank_drop_target_opto_middle
  dt_lower_drop3:
    switch: s_lower_bank_drop_target_opto_lower

drop_target_banks:
  lower_dropbank:
    drop_targets:
      - dt_lower_drop1
      - dt_lower_drop2
      - dt_lower_drop3
    reset_on_complete: 1s
    reset_coils: c_lower_droptargetreset
    reset_events:
      ball_started.1: 0
      ball_started.2: 1s
      ball_started.3: 2s
      machine_reset_phase_3: 0 
      mode_zeptest_started: 0
  upper_dropbank:
    drop_targets:
      - dt_upper_drop1
    reset_on_complete: 1s
    reset_coils: c_upper_droptargetreset
    reset_events: 
      ball_started.1: 0
      ball_started.2: 1s
      ball_started.3: 2s
      machine_reset_phase_3: 0 
      mode_make_your_choice_hurryup_started: 0
      lil_billy_drops_hit: 0

ball_devices:
  bd_trough:
    ball_switches: s_trough1, s_trough2, s_trough3, s_trough4, s_trough5, s_trough6
    eject_coil: c_trough_eject
    tags: trough, home, drain
    jam_switch: s_trough_jam
    eject_coil_jam_pulse: 15ms
    eject_targets: bd_plunger
    eject_timeouts: 3s

  bd_plunger:
    ball_switches: s_ball_shooter_lane
    eject_coil: c_auto_plunger
    mechanical_eject: true
    eject_timeouts: 5s
    player_controlled_eject_event: s_action_button_active

  bd_scoop:
    ball_switches: s_left_scoop
    eject_coil: c_mystery_eject
    eject_timeouts: 4s

  #bd_bathroom:
  #  ball_switches: s_right_scoop
  #  eject_coil: c_mystery_eject
  #  mechanical_eject: true
  #  eject_timeouts: 1.5s

  bd_top_saucer:
    ball_switches: s_top_right_reject
    eject_coil: c_top_eject
    eject_timeouts: 1.5s

  bd_hacksaw:
    ball_switches: s_left_lock_1
    eject_coil: c_left_lock_kickback
    idle_missing_ball_timeout: 3s 
    eject_timeouts: 5s
    exit_count_delay: 500ms
#physical mb commented out until later mpf fix 
  # bd_hacksaw:
  #   ball_switches: s_left_lock_3, s_left_lock_2, s_left_lock_1
  #   eject_coil: c_left_lock_kickback
  #   idle_missing_ball_timeout: 3s 
  #   eject_timeouts: 5s
  #   exit_count_delay: 500ms

playfields:
  playfield:
    tags: default
    default_source_device: bd_plunger
    enable_ball_search: True
    ball_search_phase_1_searches: 0
    ball_search_phase_2_searches: 0
    ball_search_phase_3_searches: 3
    ball_search_timeout: 8s
    ball_search_wait_after_iteration: 10s
    ball_search_interval: 250ms
    #debug: true 

flippers:
  left_flipper:
    main_coil: c_flipper_left_main
    hold_coil: c_flipper_left_hold
    activation_switch: s_left_flipper_button
    disable_events: ball_will_end, flippers_off
    enable_events: ball_started, flippers_on
    #eos_switch: s_left_flipper_eos
    #use_eos: true
    #repulse_on_eos_open: true
    #eos_active_ms_before_repulse: 500
  right_flipper:
    main_coil: c_flipper_right_main
    hold_coil: c_flipper_right_hold
    activation_switch: s_right_flipper_button
    disable_events: ball_will_end, flippers_off
    enable_events: ball_started, flippers_on
#    eos_switch: s_right_flipper_eos
    #use_eos: true
    #repulse_on_eos_open: true
    #eos_active_ms_before_repulse: 500
  upper_right_flipper:
    main_coil: c_flipper_upper_right_main
    hold_coil: c_flipper_upper_right_hold
    activation_switch: s_upper_right_flipper_button
    disable_events: ball_will_end, flippers_off
    enable_events: ball_started, flippers_on

autofire_coils:
  left_slingshot:
    coil: c_left_slingshot
    switch: s_left_slingshot
  right_slingshot:
    coil: c_right_slingshot
    switch: s_right_slingshot
  left_top_bumper:
    coil: c_left_top_jet_bumper
    switch: s_left_top_jet_bumper
  right_top_bumper:
    coil: c_right_top_jet_bumper
    switch: s_right_top_jet_bumper
  lower_top_bumper:
    coil: c_lower_top_jet_bumper
    switch: s_lower_top_jet_bumper
  left_bottom_bumper:
    coil: c_left_bottom_jet_bumper
    switch: s_left_bottom_jet_bumper
  right_bottom_bumper:
    coil: c_right_bottom_jet_bumper
    switch: s_right_bottom_jet_bumper
  upper_bottom_bumper:
    coil: c_upper_bottom_jet_bumper
    switch: s_upper_bottom_jet_bumper

diverters:
#TODO need some error handling for this diverter if the switch is on like at ball start
  dv_right_ramp_diverter:
    activation_coil: c_right_ramp_lift
    deactivation_coil: c_right_ramp_down
    targets_when_active: bd_top_saucer
    targets_when_inactive: playfield
    enable_events: ball_starting
    activate_events: logicblock_acc_shackle_mb_qualify_complete
    deactivate_events: balldevice_bd_top_saucer_ball_entered, ball_started, mode_selection_mode_started, mode_make_your_choice_hurryup_started, multiball_mb_jigsaw_started, multiball_mb_hacksaw_started, multiball_mb_shackle_started, mode_razorwire_started, mode_drillchair_started, mode_flammablejelly_started, mode_quadshotgun_started, mode_reversebeartrap_stopped, mode_reversebeartrap_started, mode_zeptest_started, mode_make_your_choice_hurryup_started, mode_survival_instinct_started
    type: pulse
    ball_search_hold_time: 2.2s
    ball_search_order: 1

  dv_hacksaw_lock_diverter:
    activation_coil: c_diverter
    type: hold
    activation_time: 3s
    activation_switches: s_right_ramp_score_bottom
    enable_events: logicblock_acc_hacksaw_mb_qualify_complete
    disable_events: ball_ended, multiball_lock_mbl_hacksaw_locked_ball
                    #, mode_selection_mode_started
    targets_when_active: bd_hacksaw
    targets_when_inactive: playfield

spinners:
  spinner:
    switch: s_spinner
    active_ms: 500
# flipper cancel default is left_flipper + right_flipper tag. this overrides and generates a different default event
combo_switches:
  both_flippers:
    tag_1: left_flipper
    tag_2: right_flipper
    events_when_both: flipper_cancel_removed
    max_offset_time: 0ms