#config_version=5

hardware:
    platform: fast

fast:
    net:
        controller: neuron
        port: /dev/tty.usbmodem14101
    exp:
        port: /dev/tty.usbmodem14103
        boards:
            led128:
                model: FP-EXP-0071
            led256:
                model: FP-EXP-0081
