#config_version=5

lights:
  l_middle_standup:
    number: 1
    type: grb
    tags: insert
  l_left_outlane:
    number: 9
    type: grb
    tags: insert
  l_right_outlane:
    number: 10
    type: grb
    tags: insert
  l_top_drop1:
    number: 11
    type: grb
    tags: insert
  l_top_drop2:
    number: 12
    type: grb
    tags: insert
  l_top_drop3:
    number: 13
    type: grb
    tags: insert
  l_top_drop4:
    number: 14
    type: grb
    tags: insert
  l_top_drop5:
    number: 15
    type: grb
    tags: insert
  l_top_drop_triangle:
    number: 16
    type: grb
    tags: insert

# circle of 8 round inserts
  l_circle1:
    number: 25
    type: grb
    tags: insert
  l_circle2:
    number: 26
    type: grb
    tags: insert
  l_circle3:
    number: 27
    type: grb
    tags: insert
  l_circle4:
    number: 28
    type: grb
    tags: insert
  l_circle5:
    number: 29
    type: grb
    tags: insert
  l_circle6:
    number: 30
    type: grb
    tags: insert
  l_circle7:
    number: 31
    type: grb
    tags: insert
  l_circle8:
    number: 32
    type: grb
    tags: insert

# jet bumpers
  l_left_bottom_bumper:
    number: 33
    type: grb
    tags: jet_bumper, bottom_bumper, left_bottom_bumper
  l_left_bottom_bumper_1:
    number: 
    type: grb
    tags: jet_bumper, bottom_bumper, left_bottom_bumper
  l_left_bottom_bumper_2:
    number: 
    type: grb
    tags: jet_bumper, bottom_bumper, left_bottom_bumper
  l_left_bottom_bumper_3:
    number: 
    type: grb
    tags: jet_bumper, bottom_bumper, left_bottom_bumper
  l_left_bottom_bumper_4:
    number: 
    type: grb
    tags: jet_bumper, bottom_bumper, left_bottom_bumper
  l_left_bottom_bumper_5:
    number: 
    type: grb
    tags: jet_bumper, bottom_bumper, left_bottom_bumper
  l_left_bottom_bumper_6:
    number: 
    type: grb
    tags: jet_bumper, bottom_bumper, left_bottom_bumper
  l_left_bottom_bumper_7:
    number: 
    type: grb
    tags: jet_bumper, bottom_bumper, left_bottom_bumper
  l_left_bottom_bumper_8:
    number: 
    type: grb
    tags: jet_bumper, bottom_bumper, left_bottom_bumper
  l_left_bottom_bumper_9:
    number: 
    type: grb
    tags: jet_bumper, bottom_bumper, left_bottom_bumper
  l_left_bottom_bumper_10:
    number: 
    type: grb
    tags: jet_bumper, bottom_bumper, left_bottom_bumper
  l_left_bottom_bumper_11:
    number: 
    type: grb
    tags: jet_bumper, bottom_bumper, left_bottom_bumper
  l_left_bottom_bumper_12:
    number: 
    type: grb
    tags: jet_bumper, bottom_bumper, left_bottom_bumper
  l_left_bottom_bumper_13:
    number: 
    type: grb
    tags: jet_bumper, bottom_bumper, left_bottom_bumper
  l_left_bottom_bumper_14:
    number: 
    type: grb
    tags: jet_bumper, bottom_bumper, left_bottom_bumper
  l_left_bottom_bumper_15:
    number: 
    type: grb
    tags: jet_bumper, bottom_bumper, left_bottom_bumper
  l_left_bottom_bumper_16:
    number: 
    type: grb
    tags: jet_bumper, bottom_bumper, left_bottom_bumper


  l_top_bottom_bumper:
    number: 34
    type: grb
    tags: jet_bumper, bottom_bumper
  l_top_bottom_bumper_1:
    number: 
    type: grb
    tags: jet_bumper, bottom_bumper, top_bottom_bumper
  l_top_bottom_bumper_2:
    number: 
    type: grb
    tags: jet_bumper, bottom_bumper, top_bottom_bumper
  l_top_bottom_bumper_3:
    number: 
    type: grb
    tags: jet_bumper, bottom_bumper, top_bottom_bumper
  l_top_bottom_bumper_4:
    number: 
    type: grb
    tags: jet_bumper, bottom_bumper, top_bottom_bumper
  l_top_bottom_bumper_5:
    number: 
    type: grb
    tags: jet_bumper, bottom_bumper, top_bottom_bumper
  l_top_bottom_bumper_6:
    number: 
    type: grb
    tags: jet_bumper, bottom_bumper, top_bottom_bumper
  l_top_bottom_bumper_7:
    number: 
    type: grb
    tags: jet_bumper, bottom_bumper, top_bottom_bumper
  l_top_bottom_bumper_8:
    number: 
    type: grb
    tags: jet_bumper, bottom_bumper, top_bottom_bumper
  l_top_bottom_bumper_9:
    number: 
    type: grb
    tags: jet_bumper, bottom_bumper, top_bottom_bumper
  l_top_bottom_bumper_10:
    number: 
    type: grb
    tags: jet_bumper, bottom_bumper, top_bottom_bumper
  l_top_bottom_bumper_11:
    number: 
    type: grb
    tags: jet_bumper, bottom_bumper, top_bottom_bumper
  l_top_bottom_bumper_12:
    number: 
    type: grb
    tags: jet_bumper, bottom_bumper, top_bottom_bumper
  l_top_bottom_bumper_13:
    number: 
    type: grb
    tags: jet_bumper, bottom_bumper, top_bottom_bumper
  l_top_bottom_bumper_14:
    number: 
    type: grb
    tags: jet_bumper, bottom_bumper, top_bottom_bumper
  l_top_bottom_bumper_15:
    number: 
    type: grb
    tags: jet_bumper, bottom_bumper, top_bottom_bumper
  l_top_bottom_bumper_16:
    number: 
    type: grb
    tags: jet_bumper, bottom_bumper, top_bottom_bumper


  l_right_bottom_bumper:
    number: 35
    type: grb
    tags: jet_bumper, bottom_bumper
  l_right_bottom_bumper_1:
    number: 
    type: grb
    tags: jet_bumper, bottom_bumper, right_bottom_bumper
  l_right_bottom_bumper_2:
    number: 
    type: grb
    tags: jet_bumper, bottom_bumper, right_bottom_bumper
  l_right_bottom_bumper_3:
    number: 
    type: grb
    tags: jet_bumper, bottom_bumper, right_bottom_bumper    
  l_right_bottom_bumper_4:
    number: 
    type: grb
    tags: jet_bumper, bottom_bumper, right_bottom_bumper
  l_right_bottom_bumper_5:
    number: 
    type: grb
    tags: jet_bumper, bottom_bumper, right_bottom_bumper
  l_right_bottom_bumper_6:
    number: 
    type: grb
    tags: jet_bumper, bottom_bumper, right_bottom_bumper
  l_right_bottom_bumper_7:
    number: 
    type: grb
    tags: jet_bumper, bottom_bumper, right_bottom_bumper
  l_right_bottom_bumper_8:
    number: 
    type: grb
    tags: jet_bumper, bottom_bumper, right_bottom_bumper
  l_right_bottom_bumper_9:
    number: 
    type: grb
    tags: jet_bumper, bottom_bumper, right_bottom_bumper
  l_right_bottom_bumper_10:
    number: 
    type: grb
    tags: jet_bumper, bottom_bumper, right_bottom_bumper
  l_right_bottom_bumper_11:
    number: 
    type: grb
    tags: jet_bumper, bottom_bumper, right_bottom_bumper
  l_right_bottom_bumper_12:
    number: 
    type: grb
    tags: jet_bumper, bottom_bumper, right_bottom_bumper
  l_right_bottom_bumper_13:
    number: 
    type: grb
    tags: jet_bumper, bottom_bumper, right_bottom_bumper
  l_right_bottom_bumper_14:
    number: 
    type: grb
    tags: jet_bumper, bottom_bumper, right_bottom_bumper
  l_right_bottom_bumper_15:
    number: 
    type: grb
    tags: jet_bumper, bottom_bumper, right_bottom_bumper
  l_right_bottom_bumper_16:
    number: 
    type: grb
    tags: jet_bumper, bottom_bumper, right_bottom_bumper


  l_left_top_bumper:
    number: 36
    type: grb
    tags: jet_bumper, top_bumper
  l_left_top_bumper_1:
    number: 
    type: grb
    tags: jet_bumper, top_bumper, left_top_bumper
  l_left_top_bumper_2:
    number: 
    type: grb
    tags: jet_bumper, top_bumper, left_top_bumper
  l_left_top_bumper_3:
    number: 
    type: grb
    tags: jet_bumper, top_bumper, left_top_bumper
  l_left_top_bumper_4:
    number: 
    type: grb
    tags: jet_bumper, top_bumper, left_top_bumper
  l_left_top_bumper_5:
    number: 
    type: grb
    tags: jet_bumper, top_bumper, left_top_bumper
  l_left_top_bumper_6:
    number: 
    type: grb
    tags: jet_bumper, top_bumper, left_top_bumper
  l_left_top_bumper_7:
    number: 
    type: grb
    tags: jet_bumper, top_bumper, left_top_bumper
  l_left_top_bumper_8:
    number: 
    type: grb
    tags: jet_bumper, top_bumper, left_top_bumper
  l_left_top_bumper_9:
    number: 
    type: grb
    tags: jet_bumper, top_bumper, left_top_bumper
  l_left_top_bumper_10:
    number: 
    type: grb
    tags: jet_bumper, top_bumper, left_top_bumper
  l_left_top_bumper_11:
    number: 
    type: grb
    tags: jet_bumper, top_bumper, left_top_bumper
  l_left_top_bumper_12:
    number: 
    type: grb
    tags: jet_bumper, top_bumper, left_top_bumper
  l_left_top_bumper_13:
    number: 
    type: grb
    tags: jet_bumper, top_bumper, left_top_bumper
  l_left_top_bumper_14:
    number: 
    type: grb
    tags: jet_bumper, top_bumper, left_top_bumper
  l_left_top_bumper_15:
    number: 
    type: grb
    tags: jet_bumper, top_bumper, left_top_bumper
  l_left_top_bumper_16:
    number: 
    type: grb
    tags: jet_bumper, top_bumper, left_top_bumper


  l_right_top_bumper:
    number: 37
    type: grb
    tags: jet_bumper, top_bumper
  l_right_top_bumper_1:
    number: 
    type: grb
    tags: jet_bumper, top_bumper, right_top_bumper
  l_right_top_bumper_2:
    number: 
    type: grb
    tags: jet_bumper, top_bumper, right_top_bumper
  l_right_top_bumper_3:
    number: 
    type: grb
    tags: jet_bumper, top_bumper, right_top_bumper
  l_right_top_bumper_4:
    number: 
    type: grb
    tags: jet_bumper, top_bumper, right_top_bumper
  l_right_top_bumper_5:
    number: 
    type: grb
    tags: jet_bumper, top_bumper, right_top_bumper
  l_right_top_bumper_6:
    number: 
    type: grb
    tags: jet_bumper, top_bumper, right_top_bumper
  l_right_top_bumper_7:
    number: 
    type: grb
    tags: jet_bumper, top_bumper, right_top_bumper
  l_right_top_bumper_8:
    number: 
    type: grb
    tags: jet_bumper, top_bumper, right_top_bumper
  l_right_top_bumper_9:
    number: 
    type: grb
    tags: jet_bumper, top_bumper, right_top_bumper
  l_right_top_bumper_10:
    number: 
    type: grb
    tags: jet_bumper, top_bumper, right_top_bumper
  l_right_top_bumper_11:
    number: 
    type: grb
    tags: jet_bumper, top_bumper, right_top_bumper
  l_right_top_bumper_12:
    number: 
    type: grb
    tags: jet_bumper, top_bumper, right_top_bumper
  l_right_top_bumper_13:
    number: 
    type: grb
    tags: jet_bumper, top_bumper, right_top_bumper
  l_right_top_bumper_14:
    number: 
    type: grb
    tags: jet_bumper, top_bumper, right_top_bumper
  l_right_top_bumper_15:
    number: 
    type: grb
    tags: jet_bumper, top_bumper, right_top_bumper
  l_right_top_bumper_16:
    number: 
    type: grb
    tags: jet_bumper, top_bumper, right_top_bumper


  l_lower_top_bumper:
    number: 38
    type: grb
    tags: jet_bumper, top_bumper
  l_lower_top_bumper_1:
    number: 
    type: grb
    tags: jet_bumper, top_bumper, lower_bottom_bumper
  l_lower_top_bumper_2:
    number: 
    type: grb
    tags: jet_bumper, top_bumper, lower_bottom_bumper
  l_lower_top_bumper_3:
    number: 
    type: grb
    tags: jet_bumper, top_bumper, lower_bottom_bumper
  l_lower_top_bumper_4:
    number: 
    type: grb
    tags: jet_bumper, top_bumper, lower_bottom_bumper
  l_lower_top_bumper_5:
    number: 
    type: grb
    tags: jet_bumper, top_bumper, lower_bottom_bumper
  l_lower_top_bumper_6:
    number: 
    type: grb
    tags: jet_bumper, top_bumper, lower_bottom_bumper
  l_lower_top_bumper_7:
    number: 
    type: grb
    tags: jet_bumper, top_bumper, lower_bottom_bumper
  l_lower_top_bumper_8:
    number: 
    type: grb
    tags: jet_bumper, top_bumper, lower_bottom_bumper
  l_lower_top_bumper_9:
    number: 
    type: grb
    tags: jet_bumper, top_bumper, lower_bottom_bumper
  l_lower_top_bumper_10:
    number: 
    type: grb
    tags: jet_bumper, top_bumper, lower_bottom_bumper
  l_lower_top_bumper_11:
    number: 
    type: grb
    tags: jet_bumper, top_bumper, lower_bottom_bumper
  l_lower_top_bumper_12:
    number: 
    type: grb
    tags: jet_bumper, top_bumper, lower_bottom_bumper
  l_lower_top_bumper_13:
    number: 
    type: grb
    tags: jet_bumper, top_bumper, lower_bottom_bumper
  l_lower_top_bumper_14:
    number: 
    type: grb
    tags: jet_bumper, top_bumper, lower_bottom_bumper
  l_lower_top_bumper_15:
    number: 
    type: grb
    tags: jet_bumper, top_bumper, lower_bottom_bumper
  l_lower_top_bumper_16:
    number: 
    type: grb
    tags: jet_bumper, top_bumper, lower_bottom_bumper


  l_left_cellar_sign:
    number: 39
    type: grb
    tags: 
  l_right_cellar_sign:
    number: 40
    type: grb
    tags: 

  l_right_ramp_triangle1:
    number: 41
    type: grb
    tags: insert
  l_right_ramp_triangle2:
    number: 42
    type: grb
    tags: insert
  l_left_ramp_triangle1:
    number: 43
    type: grb
    tags: insert
  l_left_ramp_triangle2:
    number: 44
    type: grb
    tags: insert
  l_left_ramp_triangle3:
    number: 45
    type: grb
    tags: insert

# skillshot lights
  l_skill_shot1:
    number: 46
    type: grb
    tags: insert
  l_skill_shot2:
    number: 47
    type: grb
    tags: insert
  l_skill_shot3:
    number: 48
    type: grb
    tags: insert

  l_left_return_lane:
    number: 49
    type: grb
    tags: insert
  l_left_loop_arrow:
    number: 50
    type: grb
    tags: insert, arrow
  l_left_standup_arrow:
    number: 51
    type: grb
    tags: insert, arrow
  l_inner_loop_arrow:
    number: 52
    type: grb
    tags: insert, arrow
  l_left_standup_right_ramp_arrow:
    number: 53
    type: grb
    tags: insert, arrow
  l_right_standup_right_ramp_arrow:
    number: 54
    type: grb
    tags: insert, arrow
  l_right_loop_arrow:
    number: 55
    type: grb
    tags: insert, arrow
  l_right_standup_arrow:
    number: 56
    type: grb
    tags: insert, arrow
  l_shoot_again:
    number: 57
    type: grb
    tags: insert

 # trap lights
  l_drillchair:
    number: 58
    type: grb
    tags: insert, trap
  l_beartrap:
    number: 59
    type: grb
    tags: insert, trap
  l_zeptest:
    number: 60
    type: grb
    tags: insert, trap
  l_jelly:
    number: 61
    type: grb
    tags: insert, trap
  l_quadshotgun:
    number: 62
    type: grb
    tags: insert, trap
  l_razorwire:
    number: 63
    type: grb
    tags: insert, trap

# gi lights

# left_inlane_plastic:
  l_gi_1:
    number: 101
    type: grb
    tags: gi, gi_left, gi_lower, gi_left_inlane
  l_gi_2:
    number: 102
    type: grb
    tags: gi, gi_left, gi_lower, gi_left_inlane

# left_slingshot_plastic:
  l_gi_3:
    number: 103
    type: grb
    tags: gi, gi_left, gi_lower, gi_left_sling    

# left_side_middle:
  l_gi_4:
    number: 104
    type: grb
    tags: gi, gi_left, gi_middle
  l_gi_5:
    number: 105
    type: grb
    tags: gi, gi_left, gi_middle
  l_gi_6:
    number: 106
    type: grb
    tags: gi, gi_left, gi_middle

# left_side_top:
  l_gi_7:
    number: 107
    type: grb
    tags: gi, gi_left, gi_top
  l_gi_8:
    number: 108
    type: grb
    tags: gi, gi_left, gi_top
  l_gi_9:
    number: 109
    type: grb
    tags: gi, gi_left, gi_top
  l_gi_10:
    number: 110
    type: grb
    tags: gi, gi_left, gi_top
  l_gi_11:
    number: 111
    type: grb
    tags: gi, gi_left, gi_top

# right_side_top:
  l_gi_12:
    number: 112
    type: grb
    tags: gi, gi_right, gi_top
  l_gi_13:
    number: 113
    type: grb
    tags: gi, gi_right, gi_top
  l_gi_14:
    number: 114
    type: grb
    tags: gi, gi_right, gi_top
  l_gi_15:
    number: 115
    type: grb
    tags: gi, gi_right, gi_top
  l_gi_16:
    number: 116
    type: grb
    tags: gi, gi_left, gi_top

# right_side_middle:
  l_gi_17:
    number: 117
    type: grb
    tags: gi, gi_right, gi_middle
  l_gi_18:
    number: 118
    type: grb
    tags: gi, gi_right, gi_middle
  l_gi_19:
    number: 119
    type: grb
    tags: gi, gi_right, gi_middle

# right_slingshot_plastic:
  l_gi_20:
    number: 120
    type: grb
    tags: gi, gi_right, gi_lower, gi_right_sling

# right_inlane_plastic:
  l_gi_21:
    number: 121
    type: grb
    tags: gi, gi_right, gi_lower, gi_right_inlane
  l_gi_22:
    number: 122
    type: grb
    tags: gi, gi_right, gi_lower, gi_right_inlane

# flashers

  l_flasher_1:
    number: 201
    type: grb
    tags: flasher
  l_flasher_2:
    number: 202
    type: grb
    tags: flasher
  l_flasher_3:
    number: 203
    type: grb
    tags: flasher
  l_flasher_4:
    number: 204
    type: grb
    tags: flasher
  l_flasher_5:
    number: 205
    type: grb
    tags: flasher

# playfield toys
  l_tape_reel:
    number: 
    type: grb
    tags: tape
  l_tape_speaker:
    number: 
    type: grb
    tags: tape

  l_mode_scoop:
    number: 
    type: grb
    tags: 
  l_mb_lock_scoop:
    number: 
    type: grb
    tags: 
  l_mystery_scoop:
    number: 
    type: grb
    tags: 

# ball trough
  l_trough_1:
    number: 
    type: grb
    tags: trough
  l_trough_2:
    number: 
    type: grb
    tags: trough
  l_trough_3:
    number: 
    type: grb
    tags: trough
  l_trough_4:
    number: 
    type: grb
    tags: trough
  l_trough_5:
    number: 
    type: grb
    tags: trough
  l_trough_6:
    number: 
    type: grb
    tags: trough
  l_trough_7:
    number: 
    type: grb
    tags: trough
  l_trough_8:
    number: 
    type: grb
    tags: trough

# spinning discs
  l_left_disc_1:
    number: 
    type: grb
    tags: left_disc
  l_left_disc_2:
    number: 
    type: grb
    tags: left_disc
  l_left_disc_3:
    number: 
    type: grb
    tags: left_disc
  l_left_disc_4:
    number: 
    type: grb
    tags: left_disc
  l_left_disc_5:
    number: 
    type: grb
    tags: left_disc
  l_left_disc_6:
    number: 
    type: grb
    tags: left_disc
  l_left_disc_7:
    number: 
    type: grb
    tags: left_disc
  l_left_disc_8:
    number: 
    type: grb
    tags: left_disc

  l_middle_disc_1:
    number: 
    type: grb
    tags: middle_disc
  l_middle_disc_2:
    number: 
    type: grb
    tags: middle_disc
  l_middle_disc_3:
    number: 
    type: grb
    tags: middle_disc
  l_middle_disc_4:
    number: 
    type: grb
    tags: middle_disc
  l_middle_disc_5:
    number: 
    type: grb
    tags: middle_disc
  l_middle_disc_6:
    number: 
    type: grb
    tags: middle_disc
  l_middle_disc_7:
    number: 
    type: grb
    tags: middle_disc
  l_middle_disc_8:
    number: 
    type: grb
    tags: middle_disc
  l_middle_disc_9:
    number: 
    type: grb
    tags: middle_disc
  l_middle_disc_10:
    number: 
    type: grb
    tags: middle_disc
  l_middle_disc_11:
    number: 
    type: grb
    tags: middle_disc
  l_middle_disc_12:
    number: 
    type: grb
    tags: middle_disc
  l_middle_disc_13:
    number: 
    type: grb
    tags: middle_disc
  l_middle_disc_14:
    number: 
    type: grb
    tags: middle_disc
  l_middle_disc_15:
    number: 
    type: grb
    tags: middle_disc
  l_middle_disc_16:
    number: 
    type: grb
    tags: middle_disc

  l_right_disc_1:
    number: 
    type: grb
    tags: right_disc
  l_right_disc_2:
    number: 
    type: grb
    tags: right_disc
  l_right_disc_3:
    number: 
    type: grb
    tags: right_disc
  l_right_disc_4:
    number: 
    type: grb
    tags: right_disc
  l_right_disc_5:
    number: 
    type: grb
    tags: right_disc
  l_right_disc_6:
    number: 
    type: grb
    tags: right_disc
  l_right_disc_7:
    number: 
    type: grb
    tags: right_disc
  l_right_disc_8:
    number: 
    type: grb
    tags: right_disc


# hacksaw multiball locks
  l_hmb_lock_1:
    number: 
    type: grb
    tags: hmb_locks
  l_hmb_lock_2:
    number: 
    type: grb
    tags: hmb_locks
  l_hmb_lock_3:
    number: 
    type: grb
    tags: hmb_locks


# spotlights
  l_tape_spotlight:
    number: 
    type: grb
    tags: spotlights   
  l_left_spotlight:
    number: 
    type: grb
    tags: spotlights
  l_right_spotlight:
    number: 
    type: grb
    tags: spotlights   