#config_version=6
sequence_shots:
  ssh_left_ramp:
    switch_sequence: s_enter_left_ramp, s_left_ramp_score_bottom, s_left_ramp_score_top
    sequence_timeout: 4s
  ssh_right_ramp:
    switch_sequence: s_right_ramp_down, s_right_ramp_score_bottom, s_right_ramp_score_top
    sequence_timeout: 4s
  ssh_right_orbit:
    switch_sequence: s_right_loop_bottom, s_right_loop_top
    sequence_timeout: 2s
  ssh_left_orbit:
    switch_sequence: s_left_loop_bottom, s_left_loop_top
    sequence_timeout: 2s
  ssh_leftloop_leftramp_combo:
    switch_sequence: s_left_loop_bottom, s_left_loop_top, s_enter_left_ramp, s_left_ramp_score_bottom, s_left_ramp_score_top
    sequence_timeout: 6s
  ssh_rightramp_rightloop_combo:
    switch_sequence: s_right_ramp_score_bottom, s_right_ramp_score_top, s_right_loop_bottom, s_right_loop_top
    sequence_timeout: 7s
  ssh_leftloop_innerloop_combo:
    switch_sequence: s_left_loop_bottom, s_left_loop_top, s_inner_loop
    sequence_timeout: 6s
  ssh_leftloop:
    switch_sequence: s_left_loop_bottom, s_left_loop_top
    sequence_timeout: 3s
  ssh_rightloop:
    switch_sequence: s_right_loop_bottom, s_right_loop_top
    sequence_timeout: 3s
  ssh_rightloop_rightramp_combo:
    switch_sequence: s_right_loop_bottom, s_right_loop_top, s_right_ramp_score_bottom, s_right_ramp_score_top
    sequence_timeout: 6s
  ssh_leftloop_leftramp_leftramp_combo:
    switch_sequence: s_left_loop_bottom, s_left_loop_top, s_enter_left_ramp, s_left_ramp_score_bottom, s_left_ramp_score_top, s_enter_left_ramp, s_left_ramp_score_bottom, s_left_ramp_score_top
    sequence_timeout: 10s
  ssh_leftloop_leftramp_innerloop_combo:
    switch_sequence: s_left_loop_bottom, s_left_loop_top, s_enter_left_ramp, s_left_ramp_score_bottom, s_left_ramp_score_top, s_inner_loop
    sequence_timeout: 8s
