#config_version=6
sequence_shots:
  ssh_left_ramp:
    switch_sequence: s_enter_left_ramp, s_left_ramp_score_bottom, s_left_ramp_score_top
    sequence_timeout: 4s
  ssh_right_ramp:
    switch_sequence: s_right_ramp_score_bottom, s_right_ramp_score_top
    sequence_timeout: 4s
  ssh_leftloop:
    switch_sequence: s_left_loop_bottom, s_left_loop_top
    sequence_timeout: 4s
  ssh_rightloop:
    switch_sequence: s_right_loop_bottom, s_right_loop_top
    sequence_timeout: 4s
  #combos
  ssh_leftloop_leftramp_combo:
    switch_sequence: s_left_loop_bottom, s_left_loop_top, s_enter_left_ramp, s_left_ramp_score_bottom, s_left_ramp_score_top
    sequence_timeout: 6s
  ssh_leftloop_innerloop_combo:
    switch_sequence: s_left_loop_bottom, s_left_loop_top, s_inner_loop
    sequence_timeout: 6s
  ssh_leftloop_innerloop_leftramp_combo:
    switch_sequence: s_left_loop_bottom, s_left_loop_top, s_inner_loop, s_enter_left_ramp, s_left_ramp_score_bottom, s_left_ramp_score_top
    sequence_timeout: 12s
  ssh_rightramp_xdrop_combo:
    switch_sequence: s_right_ramp_score_bottom, s_right_ramp_score_top, s_upper_bank_drop_target_opto
    sequence_timeout: 7s
  ssh_saucer_innerloop_combo:
    switch_sequence: s_top_right_reject, s_inner_loop
    sequence_timeout: 7s
  ssh_saucer_leftramp_combo:
    switch_sequence: s_top_right_reject, s_enter_left_ramp, s_left_loop_bottom, s_left_loop_top
    sequence_timeout: 9s