#config_version=6
mode:
  start_events: ball_starting, start_mode_super_skillshot
  stop_events: stop_mode_super_skillshot, droptargets_skill_hit
  priority: 100

timers:
  mode_super_skillshot_timer:
    start_value: 8
    end_value: 0
    direction: down
    tick_interval: 1s
    control_events:
    - event: balldevice_playfield_ball_enter
      action: start
    start_running: false

variable_player:
  ssh_skillshot_leftorbit_innerorbit_hit:
    score: 8000000
  ssh_skillshot_innerorbit_leftramp_hit:
    score: 5000000


event_player:
  ssh_skillshot_leftorbit_innerorbit_hit: mode_super_skillshot_complete
  ssh_skillshot_innerorbit_leftramp_hit: mode_super_skillshot_complete
  playfield_active: stop_mode_super_skillshot|6.5s
  balldevice_bd_plunger_ball_eject_success: stop_mode_super_skillshot|8s
 
  
sequence_shots:
  ssh_skillshot_leftorbit_innerorbit:
    switch_sequence: s_left_loop_bottom, s_left_loop_top, s_inner_loop
    sequence_timeout: 5s
  ssh_skillshot_innerorbit_leftramp:
    switch_sequence: s_inner_loop, s_enter_left_ramp, s_left_ramp_score_bottom, s_left_ramp_score_top
    sequence_timeout: 5s

slides:
  superskillshot:
    widgets:
    - type: video
      video: superskillshot
      width: 1366
      height: 768   

#slide_player:
#  ssh_skillshot_leftorbit_innerorbit_hit: 
#    superskillshot:
#      priority: 500
#      expire: 4s