#config_version=5
mode:
  start_events: mode_skill_shot_stopped
  stop_events: stop_mode_cellar, stop_cellar_qualify_counter, mode_selection_mode_started

##! mode: qualify
# mode: qualify
  

  
#shots:
#  cellar:
#    switch: s_right_cellar


variable_player:
  mode_cellar_complete:
    score: 300000
    
counters:
  cellar_qualify_counter:
    starting_count: 0
    count_complete_value: 2
    events_when_complete: mode_cellar_complete
    enable_events: enable_qualify
    disable_events: disable_qualify
    start_enabled: true
#    persist_state: true
    reset_on_complete: false
#    restart_events: reset_qualify_modes
    count_events: cellar_hit
    
