#config_version=6
mode:
  start_events: logicblock_cnt_negative_shot_counter_updated{value==3}
  stop_events: ball_ended, ball_ending, ball_will_end, mode_hacksaw_multiball_started, mode_shackle_multiball_started, mode_jigsaw_multiball_started, mode_hostage_complete, player_hostage_hostage_75s_timer_tick{value < 1}
  priority: 181

timers:
  hostage_75s_timer:
    start_value: 76
    end_value: 0
    direction: down
    control_events:
      - action: start
        event: mode_hostage_started
# 66second frenzy mode. All shots are +50k base. Right Ramp disables each disc. Upon the 3rd right ramp shot. Mode Complete. +1x Playfield Multiplier.
counters:
  cnt_hostage:
    starting_count: 0
    count_complete_value: 3
    start_enabled: true
    # persist_state: true
    # reset_events:
    #   slide_trapcomplete_removed, mode_razorwire_stopped, mode_drillchair_stopped, mode_quadshotgun_stopped, mode_reversebeartrap_stopped, mode_zeptest_stopped, mode_flammablejelly_stopped
    disable_on_complete: false
    count_events: ssh_right_ramp_hit
    events_when_complete: mode_hostage_complete
#disc 1 / right ramp 1
  cnt_hostage_right_ramp_1:
    starting_count: 0
    count_complete_value: 1
    start_enabled: true
    # persist_state: true
    reset_on_complete: true
    disable_on_complete: false
    count_events: logicblock_cnt_hostage_updated{value==1}
#disc 2 / right ramp 2
  cnt_hostage_right_ramp_2:
    starting_count: 0
    count_complete_value: 1
    start_enabled: true
    # persist_state: true
    reset_on_complete: true
    disable_on_complete: false
    count_events: logicblock_cnt_hostage_updated{value==2}
#disc3/ right ramp 3
  cnt_hostage_right_ramp_3:
    starting_count: 0
    count_complete_value: 1
    start_enabled: true
    # persist_state: true
    reset_on_complete: true
    disable_on_complete: false
    count_events: logicblock_cnt_hostage_updated{value==3}

shows:
  sh_hostage_on:   
    - duration: 0.2s
      lights:
        (leds): beartrap
    - duration: 0.2s
      lights:
        (leds): off
  sh_hostage_ramp_on:   
    - duration: 0.1s
      lights:
        (leds): white
    - duration: 0.2s
      lights:
        (leds): off
  sh_hostage_off:
    - duration: 0.2s
      lights:
        (leds): white

variable_player:
  sw_pops:
    score: 250000 * (current_player.pf_multiplier)
  sw_slingshot:
    score: 250000 * (current_player.pf_multiplier)
  sw_inlane:
    score: 250000 * (current_player.pf_multiplier)
  sw_outlane:
    score: 250000 * (current_player.pf_multiplier)
  sw_standup:
    score: 250000 * (current_player.pf_multiplier)
  sw_ramp:
    score: 250000 * (current_player.pf_multiplier)
  spinner_spinner_hit:
    score: 250000 * (current_player.pf_multiplier)
  sw_drop_target:
    score: 250000 * (current_player.pf_multiplier)
  sw_loop:
    score: 250000 * (current_player.pf_multiplier)
  sw_110:
    score: 250000 * (current_player.pf_multiplier)
  counter_cnt_hostage_right_ramp_1_hit:
    cnt_hostage_right_ramp_1:
      action: set
      int: (count)*250
  counter_cnt_hostage_right_ramp_2_hit:
    cnt_hostage_right_ramp_2:
      action: set
      int: (count)*250
  counter_cnt_hostage_right_ramp_3_hit:
    cnt_hostage_right_ramp_3:
      action: set
      int: (count)*250
  mode_hostage_started:
    cnt_hostage_right_ramp_1:
      int: 0
      action: set
    cnt_hostage_right_ramp_2:
      int: 0
      action: set
    cnt_hostage_right_ramp_3:
      int: 0
      action: set

show_player:
  mode_hostage_started:
    gi_on:
      show_tokens:
        color1: beartrap    
    starpost_on:
      show_tokens:
        # color1: 6E6E6E   
        color1: beartrap
      priority: 169
    flipper_on:
      show_tokens:
        color1: beartrap
    speaker_heartbeat:
      show_tokens:
        color1: beartrap
    trough_on:
      show_tokens:
        color1: beartrap
    cabinet_heartbeat:
      show_tokens:
        color1: beartrap
    topper_heartbeat:
      show_tokens:
        color1: beartrap
    sh_hostage_on:
      show_tokens:
        leds: billy, jw_insert, jet_bumper, skillshot, arrow, trap, gi, flasher, trough, discs, hmb_locks, spotlights, cabinet_minus_start
    sh_hostage_ramp_on:
      show_tokens:
        leds: right_ramp
    disc_right_chase:
      loops: -1
      speed: 10
      show_tokens:
        color1: beartrap
    disc_middle_chase:
      loops: -1
      speed: 10
      show_tokens:
        color1: beartrap
    disc_left_chase:
      loops: -1
      speed: 10
      show_tokens:
        color1: beartrap
  logicblock_cnt_hostage_updated{value==1}:
    disc_middle_chase: stop
    negative_W:
      loops: 1
      speed: 30
    sh_hostage_off:
      show_tokens:
        leds: billy, jw_insert, jet_bumper
    disc_right_chase:
      loops: -1
      speed: 10
      show_tokens:
        color1: beartrap
    disc_left_chase:
      loops: -1
      speed: 10
      show_tokens:
        color1: beartrap
    hostage_phase_1:
      loops: 0
      speed: 30
  logicblock_cnt_hostage_updated{value==2}:
    disc_middle_chase: stop
    negative_A:
      loops: 1
      speed: 30
    disc_right_chase: stop
    disc_left_chase:
      loops: -1
      speed: 10
      show_tokens:
        color1: beartrap
    hostage_phase_2:
      loops: 0
      speed: 30
    sh_hostage_off:
      show_tokens:
        leds: skillshot, arrow, trap, flasher
  mode_hostage_complete:
      disc_left_chase: stop
      disc_middle_chase: stop
      disc_right_chase: stop
  ball_ending:
      disc_left_chase: stop
      disc_middle_chase: stop
      disc_right_chase: stop

  logicblock_cnt_hostage_updated{value==3}:
    sh_hostage_off:
      show_tokens:
        leds: trough, discs, hmb_locks, spotlights, cabinet
    hostage_phase_3:
      loops: 0
      speed: 30


coil_player:
  mode_hostage_started:
    c_left_spin_disc:
      action: enable
      hold_power: 1.0
    c_middle_spin_disc:
      action: enable
      hold_power: 1.0
    c_right_spin_disc:
      action: enable
      hold_power: 1.0
  logicblock_cnt_hostage_updated{value==1}:
    c_right_spin_disc:
      action: enable
      hold_power: 1.0
    c_middle_spin_disc:
      action: off
    c_left_spin_disc:
      action: enable
      hold_power: 1.0
  logicblock_cnt_hostage_updated{value==2}:
    c_right_spin_disc:
      action: off
    c_middle_spin_disc:
      action: off
    c_left_spin_disc:
      action: enable
      hold_power: 1.0
  logicblock_cnt_hostage_updated{value==3}:
    c_right_spin_disc:
      action: off
    c_middle_spin_disc:
      action: off
    c_left_spin_disc:
      action: off
  ball_ending:
    c_right_spin_disc:
      action: off
    c_middle_spin_disc:
      action: off
    c_left_spin_disc:
      action: off

slides:
  sl_mode_hostage01:
    widgets:
    - type: video
      video: mode_hostage01 
      width: 1366
      height: 768

slide_player:
  mode_hostage_started: 
    sl_mode_hostage01:
      priority: 500
      expire: 76s
     
widgets:
   w_hostageUI:
    - type: image
      image: BottomFrame
      y: 85
      # x: 1
      z: 2
#player 1 widget
    - type: text
      text: (player1|score)
      number_grouping: true  
   #   y: 36
      y: 37
      x: 252
      z: 8
      font_size: 36
      anchor_x: right
      anchor_y: bottom
      font_name: AeroMaticsDisplaRegular
      color: black
    - type: text
      text: (player1|score)
      number_grouping: true  
      y: 36
      x: 253
      z: 8
      font_size: 36
      anchor_x: right
      anchor_y: bottom
      font_name: AeroMaticsDisplaRegular
      outline_color: f0cfab
      outline_width: 2
#player 2 widget     
    - type: text
      text: (player2|score)
      number_grouping: true
      y: 37
      x: left+579
      z: 8
      font_size: 36
      anchor_x: right
      anchor_y: bottom
      font_name: AeroMaticsDisplaRegular
      color: black
    - type: text
      text: (player2|score)
      number_grouping: true
      y: 36
      x: left+580
      z: 7
      font_size: 36
      anchor_x: right
      anchor_y: bottom
      font_name: AeroMaticsDisplaRegular
      outline_color: f0cfab
      outline_width: 2
#player 3 widget
    - type: Text
      text: (player3|score)
      number_grouping: true   
      font_name: AeroMaticsDisplaRegular
      font_size: 36
      anchor_x: right
      anchor_y: bottom
      y: 37
      x: left+908
      z: 8
      color: black
    - type: Text
      text: (player3|score)
      number_grouping: true   
      font_name: AeroMaticsDisplaRegular
      font_size: 36
      anchor_x: right
      anchor_y: bottom
      y: 36
      x: left+909
      z: 7
      outline_color: f0cfab
      outline_width: 2
#player 4 widget
    - type: Text
      text: (player4|score)
      number_grouping: true       
      font_name: AeroMaticsDisplaRegular
      font_size: 36
      anchor_x: right
      anchor_y: bottom
      y: 37
      x: left+1239
      z: 8
      color: black
    - type: Text
      text: (player4|score)
      number_grouping: true       
      font_name: AeroMaticsDisplaRegular
      font_size: 36
      anchor_x: right
      anchor_y: bottom
      y: 36
      x: left+1240
      z: 7
      outline_color: f0cfab
      outline_width: 2   
      
    - type: Text
      text: 00:(player|hostage_hostage_75s_timer_tick)
      font_size: 100
      font_name: digitalclockfont
      color: red
      x: 50%
      y: 83.2%
      z: 2
    - type: rectangle
      width: 420
      height: 130
      x: 50%
      y: 84.5%
      z: 2
      corner_radius: 20
      corner_segments: 20
      color: black      
#disc 1 / right ramp 1
    - type: rectangle
      width: 0
      height: 45
      x: 15.7%
      y: 29%
      z: 3
      anchor_x: left
      corner_radius: 10
      corner_segments: 10
      color: beartrap
      animations:
        player_cnt_hostage_right_ramp_1:
         - property: width
           value: (value)           
    - type: rectangle
      width: 250
      height: 46
      x: 25%
      y: 29%
      z: 2
      color: black
      corner_radius: 10
      corner_segments: 10
#disc 2 / right ramp 2
    - type: rectangle
      width: 0
      height: 45
      x: 43.7%
      y: 29%
      z: 3
      anchor_x: left
      corner_radius: 10
      corner_segments: 10
      color: beartrap
      animations:
        player_cnt_hostage_right_ramp_2:
         - property: width
           value: (value)           
    - type: rectangle
      width: 250
      height: 46
      x: 53%
      y: 29%
      z: 2
      color: black
      corner_radius: 10
      corner_segments: 10
#disc 3 / right ramp 3
    - type: rectangle
      width: 0
      height: 45
      x: 70.7%
      y: 29%
      z: 3
      anchor_x: left
      corner_radius: 10
      corner_segments: 10
      color: beartrap
      animations:
        player_cnt_hostage_right_ramp_3:
         - property: width
           value: (value)         
    - type: rectangle
      width: 250
      height: 46
      x: 80%
      y: 29%
      z: 2
      color: black
      corner_radius: 10
      corner_segments: 10   
#current player widget
   w_current_player1:
    - type: image
      image: Player1Hacksaw
      opacity: 1.0
      y: 4
      x: 35
      z: 3
      anchor_x: left
      anchor_y: bottom
   w_current_player2:
    - type: image
      image: Player2Hacksaw
      opacity: 1.0
      y: 4
      x: left+515
      z: 3
      anchor_y: bottom  
   w_current_player3:
    - type: image
      image: Player3Hacksaw
      opacity: 1.0
      y: 4
      x: left+844
      z: 3
      anchor_y: bottom  
   w_current_player4:
    - type: image
      image: Player4Hacksaw
      opacity: 1.0
      y: 4
      x: left+1174
      z: 3
      anchor_y: bottom      

widget_player:
 player_hostage_hostage_75s_timer_tick{value==75}:  
  w_hostageUI: 
    slide: sl_mode_hostage01
    action: add
#current player widget
 e_hostage_widget{current_player.v_current_player==1}:
  w_current_player1: 
    slide: sl_mode_hostage01
    action: add
 e_hostage_widget{current_player.v_current_player==2}:
  w_current_player2: 
    slide: sl_mode_hostage01
    action: add
 e_hostage_widget{current_player.v_current_player==3}:
  w_current_player3: 
    slide: sl_mode_hostage01
    action: add
 e_hostage_widget{current_player.v_current_player==4}:
  w_current_player4: 
    slide: sl_mode_hostage01
    action: add
   
sound_player:
  mode_hostage_started:
    BaseMusic:
      action: stop
    DrillAndTapp:
      action: stop
    OutOfTime:
      action: stop
    Jonas:
      action: stop
    TheRules:
      action: stop
    FuckThisShit:
      action: stop
    HostageModeSong:
      action: play
  mode_hostage_stopping:
    HostageModeSong:
      action: stop
  s_right_ramp_score_bottom_active:
    rightrampentryaudio:
      block: true
      action: stop

event_player: 
  slide_sl_mode_hostage01_active: e_primary_mode_active
  player_hostage_hostage_75s_timer_tick{value==75}: e_hostage_widget