#config_version=6                 
mode:
  start_events: start_selection_mode, mode_cellar_complete
  stop_events: carousel_item_selected, ball_ended, stop_mode_cellar, slide_razorwire_pops_removed, slide_reversebeartrapvideo_removed, slide_drillchair_pops_removed, slide_quadshotgun_spinner_removed, slide_zeptestUI_removed,  slide_flammablejellyUI_removed
  code: mpf.modes.carousel.code.carousel.Carousel
mode_settings:
  selectable_items: 
    - razorwire
    - drillchair
    - reversebeartrap
    - quadshotgun
    - flammablejelly
    - zeptest
  select_item_events: s_action_button_active
  next_item_events: s_left_flipper_button_active
  previous_item_events: s_right_flipper_button_active

variable_player:
  carousel_razorwire_selected:
    selected_mode:
      action: set
      string: 'selection_mode_razorwire_highlighted'

  carousel_drillchair_selected:
    selected_mode:
      action: set
      string: 'selection_mode_drillchair_highlighted'
      
  carousel_reversebeartrap_selected:
    selected_mode:
      action: set
      string: 'selection_mode_reversebeartrap_highlighted'
      
  carousel_quadshotgun_selected:
    selected_mode:
      action: set
      string: 'selection_mode_quadshotgun_highlighted'
      
  carousel_flammablejelly_selected:
    selected_mode:
      action: set
      string: 'selection_mode_flammablejelly_highlighted'
      
  carousel_zeptest_selected:
    selected_mode:
      action: set
      string: 'selection_mode_zeptest_highlighted'

 
slides:
  razorwire:
    widgets:
    - type: video
      video: razorwirepuzzle
    - type: text
      text: '<               >'
      font_size: 120
      x: center
      y: center +200
      z: 1
      color: C2E3E0 
    - type: text
      x: center
      y: center -250
      z: 1
      font_size: 45
      color: C2E3E0
      text: Use the Flippers to Select Your Mode
      animations:
        pre_show_slide:
        - property: opacity
          value: 0
          duration: 1s
        - property: opacity
          value: 1
          duration: 1s
          repeat: true
#  razorwirecassette:
#    widgets:
#    - type: video
#      video: razorwirecassette
#      width: 400
#      height: 230
#      x: 50%
#      y: 10.5%
#      opacity: 0.7
#      expire: 5s
  reversebeartrap:
    widgets:
    - type: video
      video: reversebeartrappuzzle
    - type: text
      text: '<                                  >'
      font_size: 120
      x: center
      y: center +200
      z: 1
      color: C2E3E0 
    - type: text
      x: center
      y: center -250
      z: 1
      font_size: 45
      color: C2E3E0
      text: Use the Flippers to Select Your Mode
      animations:
        pre_show_slide:
        - property: opacity
          value: 0
          duration: 1s
        - property: opacity
          value: 1
          duration: 1s
          repeat: true

  flammablejelly:
    widgets:
    - type: video
      video: flammablejellypuzzle
    - type: text
      text: '<                      >'
      font_size: 120
      x: center
      y: center +200
      z: 1
      color: C2E3E0 
    - type: text
      x: center
      y: center -250
      z: 1
      font_size: 45
      color: C2E3E0
      text: Use the Flippers to Select Your Mode
      animations:
        pre_show_slide:
        - property: opacity
          value: 0
          duration: 1s
        - property: opacity
          value: 1
          duration: 1s
          repeat: true

  drillchair:
    widgets:
    - type: video
      video: drillchairpuzzle  
    - type: text
      text: '<                 >'
      font_size: 120
      x: center
      y: center +200
      z: 1
      color: C2E3E0 
    - type: text
      x: center
      y: center -250
      z: 1
      font_size: 45
      color: C2E3E0
      text: Use the Flippers to Select Your Mode
      animations:
        pre_show_slide:
        - property: opacity
          value: 0
          duration: 1s
        - property: opacity
          value: 1
          duration: 1s
          repeat: true

  quadshotgun:
    widgets:
    - type: video
      video: quadshotgunpuzzle 
    - type: text
      text: '<                                  >'
      font_size: 120
      x: center
      y: center +200
      z: 1
      color: C2E3E0
    - type: text
      x: center
      y: center -250
      z: 1
      font_size: 45
      color: C2E3E0
      text: Use the Flippers to Select Your Mode
      animations:
        pre_show_slide:
        - property: opacity
          value: 0
          duration: 1s
        - property: opacity
          value: 1
          duration: 1s
          repeat: true     
      
  zeptest:
    widgets:
    - type: video
      video: zeptestpuzzle     
    - type: text
      text: '<               >'
      font_size: 120
      x: center
      y: center +200
      z: 1
      color: C2E3E0    
    - type: text
      x: center
      y: center -250
      z: 1
      font_size: 45
      color: C2E3E0
      text: Use the Flippers to Select Your Mode
      animations:
        pre_show_slide:
        - property: opacity
          value: 0
          duration: 1s
        - property: opacity
          value: 1
          duration: 1s
          repeat: true      
      
#    - type: text
#      text: Mode
#      font_name: TrajanProRegular
#      font_size: 50
#      bold: True
#      color: yellow
#      y: 95%
#      x: 50%
#    - type: text
#      text: Razorwire
#      font_name: valium
#      font_size: 88
#      bold: True
#      y: 85%
#      x: 50%
#      color: yellow 
#      animations:
#        show_slide:
#        - property: opacity
#          value: 0
#          duration: 1.5s
#        - property: opacity
#          value: 1
#          duration: 1.5s
#          repeat: true
#    - type: image
#      image: razorwirepuzzle

#    - type: text
#      text: Mode
#      font_name: TrajanProRegular
#      font_size: 50
#      bold: True
#      color: green
#      y: 95%
#      x: 50%
#    - type: text
#      text: Reverse Bear Trap
#      font_name: valium
#      font_size: 88
#      bold: True
#      y: 85%
#      x: 50%
#      color: green
#      animations:
#        show_slide:
#        - property: opacity
#          value: 0
#          duration: 1.5s
#        - property: opacity
#          value: 1
#          duration: 1.5s
#          repeat: true
#    - type: image
#      image: reversebeartrappuzzle
      
#    - type: text
#      text: Mode
#      font_name: TrajanProRegular
#      font_size: 50
#      bold: True
#      color: FFD21C
#      y: 95%
#      x: 50%
#    - type: text
#      text: Flammable Jelly
#      font_name: valium
#      font_size: 88
#      bold: True
#      y: 85%
#      x: 50%
#      color: FFD21C
#      animations:
#        show_slide:
#        - property: opacity
#          value: 0
#          duration: 1.5s
#        - property: opacity
#          value: 1
#          duration: 1.5s
#          repeat: true
#    - type: image
#      image: flammablejellypuzzle
      
#    - type: text
#      text: Mode
#      font_name: TrajanProRegular
#      font_size: 50
#      bold: True
#      color: CD7F32
#      y: 95%
#      x: 50%
#    - type: text
#      text: Drill Chair
#      font_name: valium
#      font_size: 88
#      bold: True
#      y: 85%
#      x: 50%
#      color: CD7F32
#      animations:
#        show_slide:
#        - property: opacity
#          value: 0
#          duration: 1.5s
#        - property: opacity
#          value: 1
#          duration: 1.5s
#          repeat: true
#    - type: image
#      image: drillchairpuzzle
      
#    - type: text
#      text: Mode
#      font_name: TrajanProRegular
#      font_size: 50
#      bold: True
#      color: 5B6065
#      y: 95%
#      x: 50%
#    - type: text
#      text: Quadruple Shotgun Hallway
#      font_name: valium
#      font_size: 88
#      bold: True
#      y: 85%
#      x: 50%
#      color: 5B6065
#      animations:
#        show_slide:
#        - property: opacity
#          value: 0
#          duration: 1.5s
#        - property: opacity
#          value: 1
#          duration: 1.5s
#          repeat: true
#    - type: image
#      image: quadshotgunpuzzle
      
#    - type: text
#      text: Mode
#      font_name: TrajanProRegular
#      font_size: 50
#      bold: True
#      color: 57669E
#      y: 95%
#      x: 50%
#    - type: text
#      text: Zep's Test
#      font_name: valium
#      font_size: 88
#      bold: True
#      y: 85%
#      x: 50%
#      color: 57669E
#      animations:
#        show_slide:
#        - property: opacity
#          value: 0
#          duration: 1.5s
#        - property: opacity
#          value: 1
#          duration: 1.5s
#          repeat: true
#    - type: image
#      image: zeptestpuzzle

#add logic later to remove after selected. temp. on a 15s timer 
slide_player:
  selection_mode_razorwire_highlighted: 
#    razorwirecassette:
#      priority: 410
    razorwire:
      priority: 400
#      expire: 10s
  selection_mode_reversebeartrap_highlighted: 
    reversebeartrap:
      priority: 400
#      expire: 10s
  selection_mode_flammablejelly_highlighted: 
    flammablejelly:
      priority: 400
#      expire: 10s
  selection_mode_drillchair_highlighted: 
    drillchair:
      priority: 400
#      expire: 10s
  selection_mode_quadshotgun_highlighted: 
    quadshotgun:
      priority: 400
#      expire: 10s
  selection_mode_zeptest_highlighted: 
    zeptest:
      priority: 400
#      expire: 10s
#  carousel_mission2_highlighted: select_mission2
#  carousel_mission3_highlighted: select_mission3
