#config_version=6                   
mode:
  start_events: logicblock_trap_select_qualify_counter_complete
  stop_events: carousel_item_selected, ball_ended, mode_razorwire_started, mode_reversebeartrap_started, mode_drillchair_started, mode_quadshotgun_started, mode_zeptest_started, mode_flammablejelly_started, mode_jigsaw_multiball_started, mode_hacksaw_multiball_started, mode_shackle_multiball_started
  restart_on_next_ball: true
  priority: 184
  code: mpf.modes.carousel.code.carousel.Carousel
mode_settings:
  selectable_items: 
    - drillchair
    - razorwire
    - quadshotgun
    - flammablejelly    
    - zeptest
    - reversebeartrap
  select_item_events: s_action_button_active
  next_item_events: s_left_flipper_button_active
  previous_item_events: s_right_flipper_button_active

variable_player:
  carousel_razorwire_selected:
    selected_mode:
      action: set
      string: 'selection_mode_razorwire_highlighted'

  carousel_drillchair_selected:
    selected_mode:
      action: set
      string: 'selection_mode_drillchair_highlighted'
      
  carousel_reversebeartrap_selected:
    selected_mode:
      action: set
      string: 'selection_mode_reversebeartrap_highlighted'
      
  carousel_quadshotgun_selected:
    selected_mode:
      action: set
      string: 'selection_mode_quadshotgun_highlighted'
      
  carousel_flammablejelly_selected:
    selected_mode:
      action: set
      string: 'selection_mode_flammablejelly_highlighted'
      
  carousel_zeptest_selected:
    selected_mode:
      action: set
      string: 'selection_mode_zeptest_highlighted'

 
slides:
  razorwire:
    widgets:
    - type: video
      video: razorwirepuzzle
    - type: text
      text: '<               >'
      font_size: 120
      x: center
      y: center +200
      z: 1
      color: C2E3E0 
    - type: text
      x: center
      y: center -250
      z: 1
      font_size: 45
      color: C2E3E0
      text: Use the Flippers to Select Your Mode
      animations:
        pre_show_slide:
        - property: opacity
          value: 0
          duration: 1s
        - property: opacity
          value: 1
          duration: 1s
          repeat: true
#  razorwirecassette:
#    widgets:
#    - type: video
#      video: razorwirecassette
#      width: 400
#      height: 230
#      x: 50%
#      y: 10.5%
#      opacity: 0.7
#      expire: 5s
  reversebeartrap:
    widgets:
    - type: video
      video: reversebeartrappuzzle
    - type: text
      text: '<                                  >'
      font_size: 120
      x: center
      y: center +200
      z: 1
      color: C2E3E0 
    - type: text
      x: center
      y: center -250
      z: 1
      font_size: 45
      color: C2E3E0
      text: Use the Flippers to Select Your Mode
      animations:
        pre_show_slide:
        - property: opacity
          value: 0
          duration: 1s
        - property: opacity
          value: 1
          duration: 1s
          repeat: true

  flammablejelly:
    widgets:
    - type: video
      video: flammablejellypuzzle
    - type: text
      text: '<                      >'
      font_size: 120
      x: center
      y: center +200
      z: 1
      color: C2E3E0 
    - type: text
      x: center
      y: center -250
      z: 1
      font_size: 45
      color: C2E3E0
      text: Use the Flippers to Select Your Mode
      animations:
        pre_show_slide:
        - property: opacity
          value: 0
          duration: 1s
        - property: opacity
          value: 1
          duration: 1s
          repeat: true

  drillchair:
    widgets:
    - type: video
      video: drillchairpuzzle  
    - type: text
      text: '<                 >'
      font_size: 120
      x: center
      y: center +200
      z: 1
      color: C2E3E0 
    - type: text
      x: center
      y: center -250
      z: 1
      font_size: 45
      color: C2E3E0
      text: Use the Flippers to Select Your Mode
      animations:
        pre_show_slide:
        - property: opacity
          value: 0
          duration: 1s
        - property: opacity
          value: 1
          duration: 1s
          repeat: true

  quadshotgun:
    widgets:
    - type: video
      video: quadshotgunpuzzle 
    - type: text
      text: '<                                  >'
      font_size: 120
      x: center
      y: center +200
      z: 1
      color: C2E3E0
    - type: text
      x: center
      y: center -250
      z: 1
      font_size: 45
      color: C2E3E0
      text: Use the Flippers to Select Your Mode
      animations:
        pre_show_slide:
        - property: opacity
          value: 0
          duration: 1s
        - property: opacity
          value: 1
          duration: 1s
          repeat: true     
      
  zeptest:
    widgets:
    - type: video
      video: zeptestpuzzle     
    - type: text
      text: '<               >'
      font_size: 120
      x: center
      y: center +200
      z: 1
      color: C2E3E0    
    - type: text
      x: center
      y: center -250
      z: 1
      font_size: 45
      color: C2E3E0
      text: Use the Flippers to Select Your Mode
      animations:
        pre_show_slide:
        - property: opacity
          value: 0
          duration: 1s
        - property: opacity
          value: 1
          duration: 1s
          repeat: true      

slide_player:
  selection_mode_razorwire_highlighted: 
#    razorwirecassette:
#      priority: 410
    razorwire:
      priority: 400
#      expire: 10s
  selection_mode_reversebeartrap_highlighted: 
    reversebeartrap:
      priority: 400
#      expire: 10s
  selection_mode_flammablejelly_highlighted: 
    flammablejelly:
      priority: 400
#      expire: 10s
  selection_mode_drillchair_highlighted: 
    drillchair:
      priority: 400
#      expire: 10s
  selection_mode_quadshotgun_highlighted: 
    quadshotgun:
      priority: 400
#      expire: 10s
  selection_mode_zeptest_highlighted: 
    zeptest:
      priority: 400
#      expire: 10s
#  carousel_mission2_highlighted: select_mission2
#  carousel_mission3_highlighted: select_mission3

shows:
  razorwire:
    - duration: 0.3s
      lights:
        (leds): razorwire
    - duration: 0.3s
      lights:
        (leds): off
  reversebeartrap:
    - duration: 0.3s
      lights:
        (leds): beartrap
    - duration: 0.3s
      lights:
        (leds): off
  flammablejelly:
    - duration: 0.3s
      lights:
        (leds): jelly
    - duration: 0.3s
      lights:
        (leds): off
  drillchair:
    - duration: 0.3s
      lights:
        (leds): drillchair
    - duration: 0.3s
      lights:
        (leds): off
  quadshotgun:
    - duration: 0.3s
      lights:
        (leds): shotgun
    - duration: 0.3s
      lights:
        (leds): off
  zeptest:
    - duration: 0.3s
      lights:
        (leds): zepstest
    - duration: 0.3s
      lights:
        (leds): off
  ActionOff:
    - duration: 2s
      lights:
        (leds): off

show_player:
  selection_mode_razorwire_highlighted:
    razorwire:
      show_tokens:
        leds: l_action_button, l_razorwire_mode, top_bumper
      loops: -1
    ActionOff:
      show_tokens:
        leds: l_beartrap_mode, l_jelly_mode, l_drillchair_mode, l_quadshotgun_mode, l_zeptest_mode, bottom_bumper, l_right_standup_arrow, shotgun_flasher, skillshot, standup
      loops: -1
  selection_mode_reversebeartrap_highlighted:
    reversebeartrap:
      show_tokens:
        leds: l_action_button, l_beartrap_mode, standup
      loops: -1
    ActionOff:
      show_tokens:
        leds: l_razorwire_mode, l_jelly_mode, l_drillchair_mode, l_quadshotgun_mode, l_zeptest_mode, jet_bumper, l_right_standup_arrow, shotgun_flasher, skillshot
      loops: -1
  selection_mode_flammablejelly_highlighted:
    flammablejelly:
      show_tokens:
        leds: l_action_button, l_jelly_mode, l_right_standup_arrow
      loops: -1
    ActionOff:
      show_tokens:
        leds: l_razorwire_mode, l_beartrap_mode, l_drillchair_mode, l_quadshotgun_mode, l_zeptest_mode, jet_bumper, shotgun_flasher, skillshot, l_left_standup_arrow, l_left_standup_right_ramp_arrow, l_right_standup_right_ramp_arrow
      loops: -1
  selection_mode_drillchair_highlighted:
    drillchair:
      show_tokens:
        leds: l_action_button, l_drillchair_mode, bottom_bumper
      loops: -1
    ActionOff:
      show_tokens:
        leds: l_razorwire_mode, l_beartrap_mode, l_jelly_mode, l_quadshotgun_mode, l_zeptest_mode, top_bumper, l_right_standup_arrow, shotgun_flasher, skillshot, standup
      loops: -1
  selection_mode_quadshotgun_highlighted:
    quadshotgun:
      show_tokens:
        leds: l_action_button, l_quadshotgun_mode, shotgun_flasher
      loops: -1
    ActionOff:
      show_tokens:
        leds: l_razorwire_mode, l_beartrap_mode, l_jelly_mode, l_drillchair_mode, l_zeptest_mode, jet_bumper, l_right_standup_arrow, skillshot, standup
      loops: -1
  selection_mode_zeptest_highlighted:
    zeptest:
      show_tokens:
        leds: l_action_button , l_zeptest_mode, skillshot
      loops: -1
    ActionOff:
      show_tokens:
        leds: l_razorwire_mode, l_beartrap_mode, l_jelly_mode, l_drillchair_mode, l_quadshotgun_mode, jet_bumper, l_right_standup_arrow, shotgun_flasher, standup
      loops: -1
  selection_mode_razorwire_selected:
    ActionOff:
      show_tokens:
        leds: l_action_button, top_bumper, l_razorwire_mode, l_beartrap_mode, l_jelly_mode, l_drillchair_mode, l_quadshotgun_mode, l_zeptest_mode, bottom_bumper, l_right_standup_arrow, shotgun_flasher, skillshot, standup
      loops: -1
  selection_mode_reversebeartrap_selected:
    ActionOff:
      show_tokens:
        leds: l_action_button, top_bumper, l_razorwire_mode, l_beartrap_mode, l_jelly_mode, l_drillchair_mode, l_quadshotgun_mode, l_zeptest_mode, bottom_bumper, l_right_standup_arrow, shotgun_flasher, skillshot, standup
      loops: -1
  selection_mode_flammablejelly_selected:
    ActionOff:
      show_tokens:
        leds: l_action_button, top_bumper, l_razorwire_mode, l_beartrap_mode, l_jelly_mode, l_drillchair_mode, l_quadshotgun_mode, l_zeptest_mode, bottom_bumper, l_right_standup_arrow, shotgun_flasher, skillshot, l_left_loop_arrow
      loops: -1
  selection_mode_drillchair_selected:
    ActionOff:
      show_tokens:
        leds: l_action_button, top_bumper, l_razorwire_mode, l_beartrap_mode, l_jelly_mode, l_drillchair_mode, l_quadshotgun_mode, l_zeptest_mode, bottom_bumper, l_right_standup_arrow, shotgun_flasher, skillshot, l_left_loop_arrow
      loops: -1
  selection_mode_quadshotgun_selected:
    ActionOff:
      show_tokens:
        leds: l_action_button, top_bumper, l_razorwire_mode, l_beartrap_mode, l_jelly_mode, l_drillchair_mode, l_quadshotgun_mode, l_zeptest_mode, bottom_bumper, l_right_standup_arrow, shotgun_flasher, skillshot, l_left_loop_arrow
      loops: -1
  selection_mode_zeptest_selected:
    ActionOff:
      show_tokens:
        leds: l_action_button, top_bumper, l_razorwire_mode, l_beartrap_mode, l_jelly_mode, l_drillchair_mode, l_quadshotgun_mode, l_zeptest_mode, bottom_bumper, l_right_standup_arrow, shotgun_flasher, skillshot, l_left_loop_arrow
      loops: -1
  mode_selection_mode_started:
      disc_left_chase: stop
      disc_middle_chase: stop
      disc_right_chase: stop

sound_player:
  selection_mode_razorwire_highlighted:
    ModeQualifiedShootScoop:
      action: stop
    FlammableJellyPreview:
      action: stop
    QuadShotgunPreview:
      action: stop
    ZepsTestPreview:
      action: stop
    DrillChairPreview:
      action: stop
    ReverseBearTrapPreview:
      action: stop
    RazorWirePreview:
      action: play
      loops: -1
  selection_mode_flammablejelly_highlighted:
    ModeQualifiedShootScoop:
      action: stop
    RazorWirePreview:
      action: stop
    QuadShotgunPreview:
      action: stop
    ZepsTestPreview:
      action: stop
    DrillChairPreview:
      action: stop
    ReverseBearTrapPreview:
      action: stop
    FlammableJellyPreview:
      action: play
      loops: -1
  selection_mode_quadshotgun_highlighted:
    ModeQualifiedShootScoop:
      action: stop
    RazorWirePreview:   
      action: stop
    FlammableJellyPreview:
      action: stop
    ZepsTestPreview:
      action: stop
    DrillChairPreview:
      action: stop
    ReverseBearTrapPreview:
      action: stop
    QuadShotgunPreview:
      action: play
      loops: -1
  selection_mode_zeptest_highlighted:
    ModeQualifiedShootScoop:
      action: stop
    RazorWirePreview:
      action: stop
    FlammableJellyPreview:
      action: stop
    QuadShotgunPreview:
      action: stop
    DrillChairPreview:
      action: stop
    ReverseBearTrapPreview:
      action: stop
    ZepsTestPreview:
      action: play
      loops: -1
  selection_mode_drillchair_highlighted:
    ModeQualifiedShootScoop:
      action: stop
    RazorWirePreview:
      action: stop
    FlammableJellyPreview:
      action: stop
    QuadShotgunPreview:
      action: stop
    ZepsTestPreview:
      action: stop
    ReverseBearTrapPreview:
      action: stop
    DrillChairPreview:
      action: play
      loops: -1
  selection_mode_reversebeartrap_highlighted:
    ModeQualifiedShootScoop:
      action: stop
    RazorWirePreview:
      action: stop
    FlammableJellyPreview:
      action: stop
    QuadShotgunPreview:
      action: stop
    ZepsTestPreview:
      action: stop
    DrillChairPreview:
      action: stop
    ReverseBearTrapPreview:
      action: play
      loops: -1

  selection_mode_razorwire_selected:
    FlammableJellyPreview:
      action: stop
    QuadShotgunPreview:
      action: stop
    ZepsTestPreview:
      action: stop
    RazorWirePreview:
      action: stop
    DrillChairPreview:
      action: stop
    ReverseBearTrapPreview:
      action: stop
  selection_mode_flammablejelly_selected:
    FlammableJellyPreview:
      action: stop
    QuadShotgunPreview:
      action: stop
    ZepsTestPreview:
      action: stop
    RazorWirePreview:
      action: stop
    DrillChairPreview:
      action: stop
    ReverseBearTrapPreview:
      action: stop
  selection_mode_quadshotgun_selected:
    FlammableJellyPreview:
      action: stop
    QuadShotgunPreview:
      action: stop
    ZepsTestPreview:
      action: stop
    RazorWirePreview:
      action: stop
    DrillChairPreview:
      action: stop
    ReverseBearTrapPreview:
      action: stop
  selection_mode_zeptest_selected:
    FlammableJellyPreview:
      action: stop
    QuadShotgunPreview:
      action: stop
    ZepsTestPreview:
      action: stop
    RazorWirePreview:
      action: stop
    DrillChairPreview:
      action: stop
    ReverseBearTrapPreview:
      action: stop
  selection_mode_drillchair_selected:
    FlammableJellyPreview:
      action: stop
    QuadShotgunPreview:
      action: stop
    ZepsTestPreview:
      action: stop
    RazorWirePreview:
      action: stop
    DrillChairPreview:
      action: stop
    ReverseBearTrapPreview:
      action: stop
  selection_mode_reversebeartrap_selected:
    FlammableJellyPreview:
      action: stop
    QuadShotgunPreview:
      action: stop
    ZepsTestPreview:
      action: stop
    RazorWirePreview:
      action: stop
    DrillChairPreview:
      action: stop
    ReverseBearTrapPreview:
      action: stop