#config_version=6
##! mode: saw_qualify
mode:
  start_events: ball_starting, mode_razorwire_stopped, mode_drillchair_stopped, mode_flammablejelly_stopped, mode_quadshotgun_stopped, mode_reversebeartrap_stopped, mode_zeptest_stopped, mode_hacksaw_multiball_stopped, mode_jigsaw_multiball_stopped, mode_shackle_multiball_stopped, mode_make_your_choice_hurryup_stopped, mode_jigsaw_multiball_complete, mode_hacksaw_multiball_complete, mode_shackle_multiball_complete
  stop_events: mode_trap_select_started, mode_make_your_choice_hurryup_started, multiball_mb_jigsaw_started, multiball_mb_hacksaw_started, multiball_mb_shackle_started
  priority: 180

shots:
  shot_left_return_lane:
    advance_events: shot_left_return_lane_sp_saw_qualify_lit_hit
    switches: s_left_inlane
    profile: sp_saw_qualify
    show_tokens:
      leds: l_left_return_lane
    control_events:
      - events: ball_starting
        state: 2
    delay_switch:
      s_right_ramp_score_top: 5s
  shot_left_loop:
    advance_events: shot_left_loop_sp_saw_qualify_lit_hit
    reset_events: slide_trapcomplete_removed, mode_razorwire_stopped, mode_drillchair_stopped, mode_quadshotgun_stopped, mode_reversebeartrap_stopped, mode_zeptest_stopped, mode_flammablejelly_stopped
    switches: s_left_loop_bottom, s_left_loop_top
    profile: sp_saw_qualify
    show_tokens:
      leds: l_left_loop_arrow
  shot_left_standup:
    advance_events: shot_left_standup_sp_saw_qualify_lit_hit  
    reset_events: slide_trapcomplete_removed, sg_saw_reset_complete, mode_razorwire_stopped, mode_drillchair_stopped, mode_quadshotgun_stopped, mode_reversebeartrap_stopped, mode_zeptest_stopped, mode_flammablejelly_stopped    
    switches: s_left_standup
    profile: sp_saw_qualify
    show_tokens:
      leds: l_left_standup_arrow
  shot_inner_loop:
    advance_events: shot_inner_loop_sp_saw_qualify_lit_hit  
    reset_events: slide_trapcomplete_removed, sg_saw_reset_complete, mode_razorwire_stopped, mode_drillchair_stopped, mode_quadshotgun_stopped, mode_reversebeartrap_stopped, mode_zeptest_stopped, mode_flammablejelly_stopped 
    switches: s_inner_loop
    profile: sp_saw_qualify
    show_tokens:
      leds: l_inner_loop_arrow
  shot_left_standup_rightramp:
    advance_events: shot_left_standup_rightramp_sp_saw_qualify_lit_hit  
    reset_events: slide_trapcomplete_removed, sg_saw_reset_complete, mode_razorwire_stopped, mode_drillchair_stopped, mode_quadshotgun_stopped, mode_reversebeartrap_stopped, mode_zeptest_stopped, mode_flammablejelly_stopped 
    switches: s_left_standup_right_ramp
    profile: sp_saw_qualify
    show_tokens:
      leds: l_left_standup_right_ramp_arrow
  shot_right_standup_rightramp:
    advance_events: shot_right_standup_rightramp_sp_saw_qualify_lit_hit
    reset_events: slide_trapcomplete_removed, sg_saw_reset_complete, mode_razorwire_stopped, mode_drillchair_stopped, mode_quadshotgun_stopped, mode_reversebeartrap_stopped, mode_zeptest_stopped, mode_flammablejelly_stopped   
    switches: s_right_standup_right_ramp
    profile: sp_saw_qualify
    show_tokens:
      leds: l_right_standup_right_ramp_arrow
  shot_right_loop:
    advance_events: shot_right_loop_sp_saw_qualify_lit_hit
    reset_events: slide_trapcomplete_removed, sg_saw_reset_complete, mode_razorwire_stopped, mode_drillchair_stopped, mode_quadshotgun_stopped, mode_reversebeartrap_stopped, mode_zeptest_stopped, mode_flammablejelly_stopped    
    switches: s_right_loop_bottom, s_right_loop_top
    profile: sp_saw_qualify
    show_tokens:
      leds: l_right_loop_arrow
  shot_right_standup:
    advance_events: shot_right_standup_sp_saw_qualify_lit_hit
    reset_events: slide_trapcomplete_removed, sg_saw_reset_complete, mode_razorwire_stopped, mode_drillchair_stopped, mode_quadshotgun_stopped, mode_reversebeartrap_stopped, mode_zeptest_stopped, mode_flammablejelly_stopped   
    switches: s_right_standup
    profile: sp_saw_qualify
    show_tokens:
      leds: l_right_standup_arrow


shot_profiles:
  sp_saw_qualify:
    advance_on_hit: false
    states:
      - name: lit
        show: "sh_shot_on"           # a default show to turn of the led. change if you want to do something on unlit shots
      - name: collected
        show: "off"               # a default show to turn of the led. change if you want to do something on unlit shots
      - name: subtract
        show: "sh_shot_subtract"      # our show to indicate an lit shot
    state_names_to_not_rotate: subtract


shot_groups:
  sg_saw_qualify:
    shots: shot_left_return_lane, shot_left_loop, shot_left_standup, shot_inner_loop, shot_left_standup_rightramp, shot_right_standup_rightramp, shot_right_loop, shot_right_standup
  sg_saw_reset:
    shots: shot_left_loop, shot_left_standup, shot_inner_loop, shot_left_standup_rightramp, shot_right_standup_rightramp, shot_right_loop, shot_right_standup


shows:
  sh_shot_on:    # define our show to indicate the state
    - duration: 0.3s
      lights:
        (leds): white
    - duration: 0.3s
      lights:
        (leds): off
  sh_shot_subtract:    # define our show to indicate the state
    - duration: -1      # this show step will run permanently
      lights:     # turn the light purple
        (leds): red
  sh_shot_hit:    # define our show to communicate success to the player
    - duration: 1s      # this show step lasts 1s
        # add sounds here or videos
        # add scoring here
      shows:      # run another (built-in) show to flash the light
        flash_color:
          show_tokens:
            color: white
            leds: (leds)
          speed: 4

  sh_saw_qualify_complete:    # define our show to communicate success on completing all shots
    - duration: 1s
        # add scoring, sounds and video
      shows:
        flash_color:
          priority: 10     # higher priority as the shots
          show_tokens:
            color: red
            leds: l_left_return_lane, l_left_standup_arrow, l_left_loop_arrow, l_inner_loop_arrow, l_left_standup_right_ramp_arrow, l_right_standup_right_ramp_arrow, l_right_loop, l_right_standup_arrow
          speed: 4

show_player:
   # play a show once a each shot is lit
  shot_left_return_lane_hit{state=="lit"}:
    sh_shot_hit:
      show_tokens:
        leds: l_left_standup_arrow
      loops: 1
  shot_left_loop_hit{state=="lit"}:
    sh_shot_hit:
      show_tokens:
        leds: l_left_loop_arrow
      loops: 1
  shot_left_standup_hit{state=="lit"}:
    sh_shot_hit:
      show_tokens:
        leds: l_left_standup_arrow
      loops: 1
  shot_inner_loop_hit{state=="lit"}:
    sh_shot_hit:
      show_tokens:
        leds: l_inner_loop_arrow
      loops: 1
  shot_left_standup_rightramp_hit{state=="lit"}:
    sh_shot_hit:
      show_tokens:
        leds: l_left_standup_right_ramp_arrow
      loops: 1
  shot_right_standup_rightramp_hit{state=="lit"}:
    sh_shot_hit:
      show_tokens:
        leds: l_right_standup_right_ramp_arrow
      loops: 1
  shot_right_loop_hit{state=="lit"}:
    sh_shot_hit:
      show_tokens:
        leds: l_right_loop_arrow
      loops: 1
  shot_right_standup_hit{state=="lit"}:
    sh_shot_hit:
      show_tokens:
        leds: l_right_standup_arrow
      loops: 1
   # play a show when the group completes
  sg_saw_qualify_complete{state=="lit"}:
    sh_saw_qualify_complete:
      loops: 0

event_player:
  sg_saw_qualify_subtract_hit{device.counters.cnt_saw_qualify.value > 0}:
    - e_subtract_a_saw_letter
  logicblock_cnt_negative_shot_counter_updated{value==1}:
    - e_negative_saw_letter_1|3.75s
  logicblock_cnt_negative_shot_counter_updated{value==2}:
    - e_negative_saw_letter_2|3.75s    
  logicblock_cnt_negative_shot_counter_updated{value==3}:
    - e_negative_saw_letter_3|3.75s
counters:
  cnt_saw_qualify:
    starting_count: 0
    count_complete_value: 3
    enable_events: enable_qualify
    disable_events: disable_qualify
    start_enabled: true
    persist_state: true
    reset_events:
      slide_trapcomplete_removed, mode_razorwire_stopped, mode_drillchair_stopped, mode_quadshotgun_stopped, mode_reversebeartrap_stopped, mode_zeptest_stopped, mode_flammablejelly_stopped
    disable_on_complete: false
    count_events: sg_saw_qualify_lit_hit
    control_events:
      - event: e_subtract_a_saw_letter
        action: subtract
        value: 1

slides:    
  s_collect:
    widgets:
    - type: video
      video: s_collect   
  sa_collect:
    widgets:
    - type: video
      video: sa_collect 
  saw_collect:
    widgets:
    - type: video
      video: saw_collect
  sa_subtract:
    widgets:
    - type: video
      video: sa_subtract
  s_subtract:
    widgets:
    - type: video
      video: s_subtract   
  s_negativelettervideo:
    widgets:
    - type: video
      video: CircularSawTunnel
    
slide_player:
  logicblock_cnt_saw_qualify_updated{value==1}:
    s_collect:
      priority: 190
      expire: 3s
  logicblock_cnt_saw_qualify_updated{value==2}:
    sa_collect:
      priority: 190
      expire: 3s
  #saw_qualify_complete:
  #  saw_collect:
  #    priority: 200
  #    expire: 3s         
  logicblock_cnt_negative_shot_counter_updated{value==1}:
    s_negativelettervideo:
      action: play
      priority: 200
      expire: 3.8s
  e_negative_saw_letter_1:
    sa_subtract:
      priority: 195
      expire: 3s
  logicblock_cnt_negative_shot_counter_updated{value==2}:
    s_negativelettervideo:
      action: play
      priority: 200
      expire: 3.8s
  e_negative_saw_letter_2:
    s_subtract:
      priority: 196
      expire: 3s
  #logicblock_cnt_negative_shot_counter_updated{value==3}:
  #  s_negativelettervideo:
  #    action: play
  #    priority: 200
  #    expire: 3.8s
#sound_player:
#  logicblock_cnt_saw_qualify_updated{value==1}:
#    SawLetterS:
#      action: play
#      block: true      
#  logicblock_cnt_saw_qualify_updated{value==2}:
#    SawLetterA:
#      action: play     
#      block: true      
#  logicblock_cnt_saw_qualify_updated{value==3}:
#    SawLetterW:
#      action: play
#      block: true      
#  sg_saw_qualify_subtract_hit{device.counters.cnt_saw_qualify.value==2}:
#    SawLetterNegative:
#      action: play
#      block: true      
#  sg_saw_qualify_subtract_hit{device.counters.cnt_saw_qualify.value==1}:
#    SawLetterNegative:
#      action: play
#      block: true            
