#config_version=6
##! mode: hacksaw_multiball_qualify

mode:
  start_events: startmode_hacksaw_multiball_qualify
  priority: 160

accruals:
  hacksaw_mb_qualify:
    events:
      - s_left_standup_right_ramp_active
      - s_right_standup_right_ramp_active
    reset_on_complete: true
    persist_state: true

variable_player:
  mode_hacksaw_multiball_started:
    score: 3000000

slides:
  HacksawMB:
    widgets:
      - type: video
        video: HacksawMB

slide_player:
  mode_hacksaw_multiball_started:
    HacksawMB:
      priority: 500
      expire: 6s

event_player:
  logicblock_hacksaw_mb_qualify_hit{step==1}:
    - event_hacksaw_mb_qualify_hit_one
  logicblock_hacksaw_mb_qualify_hit{step==2}:
    - event_hacksaw_mb_qualify_hit_two

shows:
  hacksaw_mb_qualify_hit_ready_show:
    - duration: -1
      shows:
        flash_color:
          show_tokens:
            color: green
            leds: (leds)
          speed: 4
  hacksaw_mb_qualify_hit_qualified_show:
    - duration: -1
      lights:
        (leds): green
  hacksaw_mb_show_end:
    - duration: -1
      lights:
        (leds): off

show_player:
  event_hacksaw_mb_qualify_hit_one{device.counters.hacksaw_multiball_qualify.value == 0}:
    hacksaw_mb_qualify_hit_ready_show:
      show_tokens:
        leds: l_hmb_lock_1
  event_hacksaw_mb_qualify_hit_two{device.counters.hacksaw_multiball_qualify.value == 0}:
    hacksaw_mb_qualify_hit_qualified_show:
      show_tokens:
        leds: l_hmb_lock_1
  event_hacksaw_mb_qualify_hit_one{device.counters.hacksaw_multiball_qualify.value == 1}:
    hacksaw_mb_qualify_hit_ready_show:
      show_tokens:
        leds: l_hmb_lock_2
  event_hacksaw_mb_qualify_hit_two{device.counters.hacksaw_multiball_qualify.value == 1}:
    hacksaw_mb_qualify_hit_qualified_show:
      show_tokens:
        leds: l_hmb_lock_2
  event_hacksaw_mb_qualify_hit_one{device.counters.hacksaw_multiball_qualify.value == 2}:
    hacksaw_mb_qualify_hit_ready_show:
      show_tokens:
        leds: l_hmb_lock_3
  event_hacksaw_mb_qualify_hit_two{device.counters.hacksaw_multiball_qualify.value == 2}:
    hacksaw_mb_qualify_hit_qualified_show:
      show_tokens:
        leds: l_hmb_lock_3
  mode_hacksaw_multiball_stopped:
    hacksaw_mb_show_end:
      show_tokens:
        leds: l_hmb_lock_1,l_hmb_lock_2,l_hmb_lock_3
