#config_version=6
##! mode: hacksaw_multiball_qualify

mode:
  start_events: startmode_hacksaw_multiball_qualify, mode_hacksaw_multiball_stopped, mode_jigsaw_multiball_stopped, mode_shackle_multiball_stopped, mode_jigsaw_multiball_complete, mode_hacksaw_multiball_complete, mode_shackle_multiball_complete
  # startmode_hacksaw_multiball_qualify, mode_razorwire_stopped, mode_drillchair_stopped, mode_flammablejelly_stopped, mode_quadshotgun_stopped, mode_reversebeartrap_stopped, mode_zeptest_stopped, mode_hacksaw_multiball_stopped, mode_jigsaw_multiball_stopped, mode_shackle_multiball_stopped, mode_make_your_choice_hurryup_stopped, mode_jigsaw_multiball_complete, mode_hacksaw_multiball_complete, mode_shackle_multiball_complete, mode_survival_instinct_stopped, mode_survival_instinct_complete
  stop_events: multiball_mb_shackle_started, multiball_mb_hacksaw_started, multiball_mb_jigsaw_started, mode_bonus_started
  # mode_selection_mode_started, mode_make_your_choice_hurryup_started, multiball_mb_jigsaw_started, multiball_mb_hacksaw_started, multiball_mb_shackle_started, mode_razorwire_started, mode_drillchair_started, mode_flammablejelly_started, mode_quadshotgun_started, mode_reversebeartrap_started, mode_zeptest_started, mode_survival_instinct_started

  priority: 183 

accruals:
  acc_hacksaw_mb_qualify:
    events:
      - s_left_standup_right_ramp_active
      - s_right_standup_right_ramp_active
    reset_on_complete: false
    persist_state: true
    disable_on_complete: false
    reset_events: multiball_lock_mbl_hacksaw_locked_ball

multiball_locks:
  mbl_hacksaw:
    debug: true
    balls_to_lock: 3
    balls_to_replace: 2
    lock_devices: bd_hacksaw
    enable_events: logicblock_acc_hacksaw_mb_qualify_complete
    disable_events: multiball_lock_mbl_hacksaw_locked_ball
    locked_ball_counting_strategy: physical_only 
#    priority: 300
    #reset_all_counts_events: multiball_lock_mbl_hacksaw_full 
      #disable_events: sg_lockshot_complete{state=="unlit"}
    #reset_count_for_current_player_events: multiball_lock_mbl_hacksaw_full

counters:
  cnt_hacksaw_mb_counter:
    starting_count: 0
    count_complete_value: 3
    enable_events: 
    disable_events: 
    start_enabled: true
    persist_state: true
    reset_on_complete: true
    disable_on_complete: false   
    count_events: multiball_lock_mbl_hacksaw_locked_ball

variable_player:
  logicblock_cnt_hacksaw_mb_counter_hit:
    hacksaw_mb_lock_counter:
      action: set
      int: (count)
  logicblock_hacksaw_multiball_qualify_complete:
    hacksaw_mb_lock_counter:
      action: set
      int: 0



shows:
  sh_hacksaw_mb_qualify_hit_ready:
    - duration: -1
      shows:
        flash_color:
          show_tokens:
            color: color_hacksaw_mb
            leds: (leds)
          speed: 4
  sh_hacksaw_mb_qualify_hit_locked:
    - duration: -1
      lights:
        (leds): color_hacksaw_mb
  sh_hacksaw_mb_end:
    - duration: -1
      lights:
        (leds): off
  sh_hacksaw_mb_qualify_hit:
    - duration: 0.3s
      lights:
        (leds): color_hacksaw_mb
    - duration: 0.3s
      lights:
        (leds): off

sound_player:
  e_hacksaw_mb_qualify_hit_one:
    LockIsLit:
      action: play
  slide_sl_Hacksaw_locked_1_active:
    Ball1Locked:
      action: play
  slide_sl_Hacksaw_locked_2_active:
    Ball2Locked:
      action: play

show_player:
  logicblock_acc_hacksaw_mb_qualify_complete{device.multiball_locks.mbl_hacksaw.locked_balls == 0}:
    sh_hacksaw_mb_qualify_hit_ready:
      show_tokens:
        leds: l_hmb_lock_1
  multiball_lock_mbl_hacksaw_locked_ball{device.multiball_locks.mbl_hacksaw.locked_balls == 1}:
    sh_hacksaw_mb_qualify_hit_locked:
      show_tokens:
        leds: l_hmb_lock_1
    hacksaw_mb_lock:
      loops: 0
      speed: 30
  logicblock_acc_hacksaw_mb_qualify_complete{device.multiball_locks.mbl_hacksaw.locked_balls == 1}:
    sh_hacksaw_mb_qualify_hit_ready:
      show_tokens:
        leds: l_hmb_lock_2
  multiball_lock_mbl_hacksaw_locked_ball{device.multiball_locks.mbl_hacksaw.locked_balls == 2}:
    sh_hacksaw_mb_qualify_hit_locked:
      show_tokens:
        leds: l_hmb_lock_1, l_hmb_lock_2
    hacksaw_mb_lock:
      loops: 0
      speed: 30
  logicblock_acc_hacksaw_mb_qualify_complete{device.multiball_locks.mbl_hacksaw.locked_balls == 2}:
    sh_hacksaw_mb_qualify_hit_ready:
      show_tokens:
        leds: l_hmb_lock_3
  multiball_lock_mbl_hacksaw_lock_locked_ball{device.multiball_locks.mbl_hacksaw.locked_balls == 3}:
    sh_hacksaw_mb_qualify_hit_locked:
      show_tokens:
        leds: l_hmb_lock_1, l_hmb_lock_2, l_hmb_lock_3
    hacksaw_mb_lock:
      loops: 0
      speed: 30
  multiball_mb_hacksaw_ended:
    sh_hacksaw_mb_end:
      show_tokens:
        leds: l_hmb_lock_1,l_hmb_lock_2,l_hmb_lock_3
  logicblock_acc_hacksaw_mb_qualify_hit{step==0}:
    sh_hacksaw_mb_qualify_hit:
      show_tokens:
        leds: l_left_standup_right_ramp_arrow
      speed: 4
      loops: 5
  logicblock_acc_hacksaw_mb_qualify_hit{step==1}:
    sh_hacksaw_mb_qualify_hit:
      show_tokens:
        leds: l_right_standup_right_ramp_arrow
      speed: 4
      loops: 5

slides:
  sl_Hacksaw_locked_1:
    widgets:
    - type: video
      video: hacksaw_lock1
      width: 1366
      height: 768 
  sl_Hacksaw_locked_2:
    widgets:
    - type: video
      video: hacksaw_lock2
      width: 1366
      height: 768 
  sl_Hacksaw_locked_3:
    widgets:
    - type: video
      video: hacksaw_lock3
      width: 1366
      height: 768 

slide_player:
  multiball_lock_mbl_hacksaw_locked_ball{device.multiball_locks.mbl_hacksaw.locked_balls == 1}:
    sl_Hacksaw_locked_1:
      priority: 500
      expire: 3s
  multiball_lock_mbl_hacksaw_locked_ball{device.multiball_locks.mbl_hacksaw.locked_balls == 2}:
    sl_Hacksaw_locked_2:
      priority: 500
      expire: 3s
  multiball_lock_mbl_hacksaw_lock_locked_ball{device.multiball_locks.mbl_hacksaw.locked_balls == 3}:
    sl_Hacksaw_locked_3:
      priority: 500
      expire: 3s