#config_version=6
##! mode: hacksaw_multiball_qualify

mode:
  start_events: startmode_hacksaw_multiball_qualify
  priority: 160

accruals:
  hacksaw_mb_qualify:
    events:
      - s_left_standup_right_ramp_active
      - s_right_standup_right_ramp_active
    reset_on_complete: true
    persist_state: true

variable_player:
  mode_jigsaw_multiball_started:
    score: 3000000

slides:
  JigsawMB:
    widgets:
      - type: video
        video: JigsawMB

slide_player:
  mode_jigsaw_multiball_started:
    JigsawMB:
      priority: 500
      expire: 6s

event_player:
  logicblock_jigsaw_mb_qualify_hit{step==1}:
    - event_jigsaw_mb_qualify_hit_one
  logicblock_jigsaw_mb_qualify_hit{step==2}:
    - event_jigsaw_mb_qualify_hit_two

shows:
  hacksaw_mb_qualify_hit_ready_show:
    - duration: -1
      shows:
        flash_color:
          show_tokens:
            color: orange
            leds: (leds)
          speed: 4
  hacksaw_mb_qualify_hit_qualified_show:
    - duration: -1
      lights:
        (leds): orange
  hacksaw_mb_show_end:
    - duration: -1
      lights:
        (leds): off

show_player:
  event_jigsaw_mb_qualify_hit_one{device.counters.jigsaw_multiball_qualify.value == 0}:
    hacksaw_mb_qualify_hit_ready_show:
      show_tokens:
        leds: l_left_ramp_triangle3
  event_jigsaw_mb_qualify_hit_two{device.counters.jigsaw_multiball_qualify.value == 0}:
    hacksaw_mb_qualify_hit_qualified_show:
      show_tokens:
        leds: l_left_ramp_triangle3
  event_jigsaw_mb_qualify_hit_one{device.counters.jigsaw_multiball_qualify.value == 1}:
    hacksaw_mb_qualify_hit_ready_show:
      show_tokens:
        leds: l_left_ramp_triangle2
  event_jigsaw_mb_qualify_hit_two{device.counters.jigsaw_multiball_qualify.value == 1}:
    hacksaw_mb_qualify_hit_qualified_show:
      show_tokens:
        leds: l_left_ramp_triangle3, l_left_ramp_triangle2
  event_jigsaw_mb_qualify_hit_one{device.counters.jigsaw_multiball_qualify.value == 2}:
    hacksaw_mb_qualify_hit_ready_show:
      show_tokens:
        leds: l_left_ramp_triangle1
  event_jigsaw_mb_qualify_hit_two{device.counters.jigsaw_multiball_qualify.value == 2}:
    hacksaw_mb_qualify_hit_qualified_show:
      show_tokens:
        leds: l_left_ramp_triangle3, l_left_ramp_triangle2, l_left_ramp_triangle1
  mode_jigsaw_multiball_stopped:
    hacksaw_mb_show_end:
      show_tokens:
        leds: l_left_ramp_triangle1, l_left_ramp_triangle2, l_left_ramp_triangle3
