#config_version=6
mode:
  start_events: mode_base_started
  stop_events: ball_ended
  priority: 99

shots:
  sh_select_mode:
    switch: s_right_scoop
    disable_events: e_primary_mode_active, start_jigsaw_multiball, start_hacksaw_multiball, start_shackle_multiball
    enable_events: logicblock_cnt_saw_qualify_complete

  shot_drillchair_button:
    advance_events: minimode_spinners_complete
    switches: s_action_button
    profile: sp_drillchair
    disable_events: mode_drillchair_stopped, mode_drillchair_complete, ball_ended, ball_will_end
    enable_events: mode_drillchair_started
    show_tokens:
      leds: l_action_button
    control_events:
      - events: minimode_spinners_complete
        state: 1
      - events: shot_drillchair_button_sp_drillchair_lit_hit
        state: 0
      - events: mode_drillchair_stopped
        state: 0
      - events: mode_drillchair_complete
        state: 0
  shot_razorwire_button:
    advance_events: minimode_loops_complete
    switches: s_action_button
    profile: sp_razorwire
    disable_events: mode_razorwire_stopped, mode_razorwire_complete, ball_ended, ball_will_end
    enable_events: mode_razorwire_started
    show_tokens:
      leds: l_action_button
    control_events:
      - events: minimode_loops_complete
        state: 1
      - events: shot_razorwire_button_sp_razorwire_lit_hit
        state: 0
      - events: mode_razorwire_stopped
        state: 0
      - events: mode_razorwire_complete
        state: 0
  shot_reversebeartrap_button:
    advance_events: minimode_ramps_complete
    switches: s_action_button
    profile: sp_reversebeartrap
    disable_events: mode_reversebeartrap_stopped, mode_reversebeartrap_complete, ball_ended, ball_will_end
    enable_events: mode_reversebeartrap_started
    show_tokens:
      leds: l_action_button
    control_events:
      - events: minimode_ramps_complete
        state: 1
      - events: shot_reversebeartrap_button_sp_reversebeartrap_lit_hit
        state: 0
      - events: mode_reversebeartrap_stopped
        state: 0
      - events: mode_reversebeartrap_complete
        state: 0

shot_profiles:
  sp_drillchair:
    advance_on_hit: false
    states:
      - name: drillchair_off
        show: "off"               # a default show to turn of the led. change if you want to do something on unlit shots
      - name: lit
        show: "sh_drillchair_ready"        # a default show to turn of the led. change if you want to do something on unlit shots 
        priority: 200
  sp_razorwire:
    advance_on_hit: false
    states:
      - name: razorwire_off
        show: "off"               # a default show to turn of the led. change if you want to do something on unlit shots
      - name: lit
        show: "sh_razorwire_ready"        # a default show to turn of the led. change if you want to do something on unlit shots 
        priority: 200
  sp_reversebeartrap:
    advance_on_hit: false
    states:
      - name: reversebeartrap_off
        show: "off"               # a default show to turn of the led. change if you want to do something on unlit shots
      - name: lit
        show: "sh_reversebeartrap_ready"        # a default show to turn of the led. change if you want to do something on unlit shots 
        priority: 200

shows:
  sh_drillchair_ready:
    - duration: 0.3s
      lights:
        (leds): drillchair
    - duration: 0.3s
      lights:
        (leds): off
  sh_razorwire_ready:
    - duration: 0.3s
      lights:
        (leds): razorwire
    - duration: 0.3s
      lights:
        (leds): off
  sh_reversebeartrap_ready:
    - duration: 0.3s
      lights:
        (leds): beartrap
    - duration: 0.3s
      lights:
        (leds): off
  sh_item_used:
    - duration: -1
      lights:
        (leds): (color1)

variable_player:
#drillchair mode item used
  shot_drillchair_button_sp_drillchair_lit_hit:
#    score: 123456    
    bonus_handguns: -1
    value_type: int   
    handguns_used:
      int: 1
      action: set
#razorwire mode item used
  shot_razorwire_button_sp_razorwire_lit_hit:
    bonus_hacksaws: -1
    value_type: int   
    hacksaws_used:
      int: 1
      action: set
#reversebeartrap mode item used
  shot_reversebeartrap_button_sp_reversebeartrap_lit_hit:
    bonus_keys: -1
    value_type: int   
    keys_used:
      int: 1
      action: set

 # track modes completed for wizard mode qualifications -- player_modes_completed
  mode_drillchair_complete:
    modes_completed:
      int: 1
      action: add
    drillchair_complete:
      int: 2
      action: set
  mode_flammablejelly_complete:
    modes_completed:
      int: 1
      action: add
  mode_quadshotgun_complete:
    modes_completed:
      int: 1
      action: add
  mode_razorwire_complete:
    modes_completed:
      int: 1
      action: add
  mode_reversebeartrap_complete:
    modes_completed:
      int: 1
      action: add
  mode_zeptest_complete:
    modes_completed:
      int: 1
      action: add

# puzzle pieces collected
  mode_puzzle_hurryup_complete:
    puzzle_pieces:
      int: 1
      action: add
  razorwire_puzzle_complete:
    razorwire_puzzle:
      int: 1
      action: add
  drillchair_puzzle_complete:
    drillchair_puzzle:
      int: 1
      action: add
  zeptest_puzzle_complete:
    zeptest_puzzle:
      int: 1
      action: add
  flammablejelly_puzzle_complete:
    flammablejelly_puzzle:
      int: 1
      action: add
  quadshotgun_puzzle_complete:
    quadshotgun_puzzle:
      int: 1
      action: add

# modes attempted for mini wizard mode -- player_modes_attempted
  mode_drillchair_started:
    modes_attempted:
      int: 1
      action: add
  mode_flammablejelly_started:
    modes_attempted:
      int: 1
      action: add
  mode_quadshotgun_started:
    modes_attempted:
      int: 1
      action: add
  mode_razorwire_started:
    modes_attempted:
      int: 1
      action: add
  mode_reversebeartrap_started:
    modes_attempted:
      int: 1
      action: add
  mode_zeptest_started:
    modes_attempted:
      int: 1
      action: add

  logicblock_acc_make_your_choice_qualify_hit:
    choice_hurryup_hits:
      int: 1
      action: add

# set qualification requirement to mode quadshotgun
# 1 = default . 2 = mode_drillchair_complete
  #slide_base_slide_main_created:
  #  drillchair_complete:
  #    int: 1
  #    action: set

counters:
  mystery_qualify:
    starting_count: 0
    count_complete_value: 5
    start_enabled: true
    persist_state: true
    reset_on_complete: true
    disable_on_complete: false
    events_when_complete: start_mystery_mode
    enable_events: mode_base_started, mode_drillchair_stopped, mode_flammablejelly_stopped, mode_quadshotgun_stopped, mode_razorwire_stopped, mode_reversebeartrap_stopped, mode_zeptest_stopped
    disable_events: multiball_active, mode_selection_mode_started 
    reset_events: sh_select_mode_hit
    count_events: sw_lower_drop_target

  random_switch:
    starting_count: 0
    count_complete_value: 5000
    enable_events: enable_qualify
    disable_events: disable_qualify
    start_enabled: true
#    persist_state: true
    reset_on_complete: true
    events_when_complete: random_switch_complete
    count_events: sw_pops, sw_standup, sw_inlane, sw_spinner, sw_ramp, sw_loop, sw_drop_target

show_player:
  shot_drillchair_button_sp_drillchair_lit_hit:
    sh_item_used:
      show_tokens:
        leds: l_jw_gun
        color1: off
      priority: 200
  shot_razorwire_button_sp_razorwire_lit_hit:
    sh_item_used:
      show_tokens:
        leds: l_jw_hacksaw
        color1: off
      priority: 200
  shot_reversebeartrap_button_sp_reversebeartrap_lit_hit:
    sh_item_used:
      show_tokens:
        leds: l_jw_key
        color1: off
      priority: 200