#config_version=6
mode:
  start_events: mode_base_started
  stop_events: ball_ended
  priority: 99

shots:
  sh_select_mode:
    switch: s_right_scoop
    disable_events: e_primary_mode_active, start_jigsaw_multiball, start_hacksaw_multiball, start_shackle_multiball
    enable_events: logicblock_cnt_saw_qualify_complete

  shot_drillchair_button:
    advance_events: minimode_spinners_complete
    switches: s_action_button
    profile: sp_drillchair
    disable_events: mode_drillchair_stopped, mode_drillchair_complete, ball_ended, ball_will_end
    enable_events: mode_drillchair_started
    show_tokens:
      leds: l_action_button
    control_events:
      - events: minimode_spinners_complete
        state: 1
      - events: shot_drillchair_button_sp_drillchair_lit_hit
        state: 0
      - events: mode_drillchair_stopped
        state: 0
      - events: mode_drillchair_complete
        state: 0
  shot_razorwire_button:
    advance_events: minimode_loops_complete
    switches: s_action_button
    profile: sp_razorwire
    disable_events: mode_razorwire_stopped, mode_razorwire_complete, ball_ended, ball_will_end
    enable_events: mode_razorwire_started
    show_tokens:
      leds: l_action_button
    control_events:
      - events: minimode_loops_complete
        state: 1
      - events: shot_razorwire_button_sp_razorwire_lit_hit
        state: 0
      - events: mode_razorwire_stopped
        state: 0
      - events: mode_razorwire_complete
        state: 0
  shot_reversebeartrap_button:
    advance_events: minimode_ramps_complete
    switches: s_action_button
    profile: sp_reversebeartrap
    disable_events: mode_reversebeartrap_stopped, mode_reversebeartrap_complete, ball_ended, ball_will_end
    enable_events: mode_reversebeartrap_started
    show_tokens:
      leds: l_action_button
    control_events:
      - events: minimode_ramps_complete
        state: 1
      - events: shot_reversebeartrap_button_sp_reversebeartrap_lit_hit
        state: 0
      - events: mode_reversebeartrap_stopped
        state: 0
      - events: mode_reversebeartrap_complete
        state: 0
  shot_quadshotgun_button:
    advance_events: minimode_pops_complete
    switches: s_action_button
    profile: sp_quadshotgun
    disable_events: mode_quadshotgun_stopped, mode_quadshotgun_complete, ball_ended, ball_will_end
    enable_events: mode_quadshotgun_started
    show_tokens:
      leds: l_action_button
    control_events:
      - events: minimode_pops_complete
        state: 1
      - events: shot_quadshotgun_button_sp_quadshotgun_lit_hit
        state: 0
      - events: mode_quadshotgun_stopped
        state: 0
      - events: mode_quadshotgun_complete
        state: 0
  shot_flammablejelly_button:
    advance_events: minimode_standups_complete
    switches: s_action_button
    profile: sp_flammablejelly
    disable_events: mode_flammablejelly_stopped, mode_flammablejelly_complete, ball_ended, ball_will_end
    enable_events: mode_flammablejelly_started
    show_tokens:
      leds: l_action_button
    control_events:
      - events: minimode_standups_complete
        state: 1
      - events: shot_flammablejelly_button_sp_flammablejelly_lit_hit
        state: 0
      - events: mode_flammablejelly_stopped
        state: 0
      - events: mode_flammablejelly_complete
        state: 0
  shot_zeptest_button:
    advance_events: minimode_drops_complete
    switches: s_action_button
    profile: sp_zeptest
    disable_events: mode_zeptest_stopped, mode_zeptest_complete, ball_ended, ball_will_end
    enable_events: mode_zeptest_started
    show_tokens:
      leds: l_action_button
    control_events:
      - events: minimode_drops_complete
        state: 1
      - events: shot_zeptest_button_sp_zeptest_lit_hit
        state: 0
      - events: mode_zeptest_stopped
        state: 0
      - events: mode_zeptest_complete
        state: 0
  shot_outlane_button:
    advance_events: minimode_scoops_complete
    switches: s_action_button
    profile: sp_outlane_button
    show_tokens:
      leds: l_action_button
    control_events:
      - events: minimode_scoops_complete
        state: 1
      - events: shot_outlane_button_sp_outlane_button_lit_hit
        state: 0
  shot_add_a_ball_button:
    advance_events: minimode_inlanes_complete
    switches: s_action_button
    profile: sp_add_a_ball_button
    disable_events: mode_hacksaw_multiball_stopped, mode_jigsaw_multiball_stopped, mode_shackle_multiball_stopped, ball_ended, ball_will_end
    enable_events: mode_hacksaw_multiball_started, mode_jigsaw_multiball_started, mode_shackle_multiball_started
    show_tokens:
      leds: l_action_button
    control_events:
      - events: minimode_inlanes_complete
        state: 1
      - events: shot_add_a_ball_button_sp_add_a_ball_button_lit_hit
        state: 0

shot_profiles:
  sp_drillchair:
    advance_on_hit: false
    states:
      - name: drillchair_off
        show: "off"               # a default show to turn of the led. change if you want to do something on unlit shots
      - name: lit
        show: "sh_drillchair_ready"        # a default show to turn of the led. change if you want to do something on unlit shots 
        priority: 200
  sp_razorwire:
    advance_on_hit: false
    states:
      - name: razorwire_off
        show: "off" 
      - name: lit
        show: "sh_razorwire_ready"    
        priority: 200
  sp_reversebeartrap:
    advance_on_hit: false
    states:
      - name: reversebeartrap_off
        show: "off" 
      - name: lit
        show: "sh_reversebeartrap_ready"    
        priority: 200
  sp_quadshotgun:
    advance_on_hit: false
    states:
      - name: quadshotgun_off
        show: "off" 
      - name: lit
        show: "sh_quadshotgun_ready"    
        priority: 200
  sp_flammablejelly:
    advance_on_hit: false
    states:
      - name: flammablejelly_off
        show: "off" 
      - name: lit
        show: "sh_flammablejelly_ready"    
        priority: 200
  sp_zeptest:
    advance_on_hit: false
    states:
      - name: zeptest_off
        show: "off" 
      - name: lit
        show: "sh_zeptest_ready"    
        priority: 200
  sp_outlane_button:
    advance_on_hit: false
    states:
      - name: outlane_button_off
        show: "off" 
      - name: lit
        show: "sh_outlane_button_ready"    
        priority: 200
  sp_add_a_ball_button:
    advance_on_hit: false
    states:
      - name: add_a_ball_button_off
        show: "off" 
      - name: lit
        show: "sh_add_a_ball_button_ready"    
        priority: 200

shows:
  sh_drillchair_ready:
    - duration: 0.3s
      lights:
        (leds): drillchair
    - duration: 0.3s
      lights:
        (leds): off
  sh_razorwire_ready:
    - duration: 0.3s
      lights:
        (leds): razorwire
    - duration: 0.3s
      lights:
        (leds): off
  sh_reversebeartrap_ready:
    - duration: 0.3s
      lights:
        (leds): beartrap
    - duration: 0.3s
      lights:
        (leds): off
  sh_quadshotgun_ready:
    - duration: 0.3s
      lights:
        (leds): shotgun
    - duration: 0.3s
      lights:
        (leds): off
  sh_flammablejelly_ready:
    - duration: 0.3s
      lights:
        (leds): jelly
    - duration: 0.3s
      lights:
        (leds): off
  sh_zeptest_ready:
    - duration: 0.3s
      lights:
        (leds): zeptest
    - duration: 0.3s
      lights:
        (leds): off
  sh_outlane_button_ready:
    - duration: 0.3s
      lights:
        (leds): drillchair
    - duration: 0.3s
      lights:
        (leds): off
  sh_add_a_ball_button_ready:
    - duration: 0.3s
      lights:
        (leds): razorwire
    - duration: 0.3s
      lights:
        (leds): off
  sh_item_used:
    - duration: -1
      lights:
        (leds): (color1)

variable_player:
#drillchair mode item used
  shot_drillchair_button_sp_drillchair_lit_hit:
#    score: 123456    
    bonus_handguns: -1
    value_type: int   
    handguns_used:
      int: 1
      action: set
#razorwire mode item used
  shot_razorwire_button_sp_razorwire_lit_hit:
    bonus_hacksaws: -1
    value_type: int   
    hacksaws_used:
      int: 1
      action: set
#reversebeartrap mode item used
  shot_reversebeartrap_button_sp_reversebeartrap_lit_hit:
    bonus_keys: -1
    value_type: int   
    keys_used:
      int: 1
      action: set
#quadshotgun mode item used
  shot_quadshotgun_button_sp_quadshotgun_lit_hit:
    bonus_gears: -1
    value_type: int   
    gears_used:
      int: 1
      action: set
#flammablejelly mode item used
  shot_flammablejelly_button_sp_flammablejelly_lit_hit:
    bonus_candles: -1
    value_type: int   
    candles_used:
      int: 1
      action: set
    candle_multiplier:
      int: 3
      action: set
#zeptest mode item used
  shot_zeptest_button_sp_zeptest_lit_hit:
    bonus_syringes: -1
    value_type: int   
    syringes_used:
      int: 1
      action: set
  shot_outlane_button_sp_outlane_button_lit_hit:
    bonus_bathtubs: -1
    value_type: int
  shot_add_a_ball_button_sp_add_a_ball_button_lit_hit:
    bonus_taperecorders: -1
    value_type: int

 # track modes completed for wizard mode qualifications -- player_modes_completed
  mode_drillchair_complete:
    modes_completed:
      int: 1
      action: add
    drillchair_mode_complete:
      int: 1
      action: set
    drillchair_complete:
      int: 2
      action: set
  mode_flammablejelly_complete:
    modes_completed:
      int: 1
      action: add
    flammablejelly_mode_complete:
      int: 1
      action: set
  mode_quadshotgun_complete:
    modes_completed:
      int: 1
      action: add
    quadshotgun_mode_complete:
      int: 1
      action: set
  mode_razorwire_complete:
    modes_completed:
      int: 1
      action: add
    razorwire_mode_complete:
      int: 1
      action: set
  mode_reversebeartrap_complete:
    modes_completed:
      int: 1
      action: add
    reversebeartrap_mode_complete:
      int: 1
      action: set
  mode_zeptest_complete:
    modes_completed:
      int: 1
      action: add
    zeptest_mode_complete:
      int: 1
      action: set
  multiball_mb_survival_instinct_ended:
    modes_completed:
      int: 1
      action: add
    survival_instinct_mode_complete:
      int: 1
      action: set
  mode_the_key_to_freedom_complete:
    modes_completed:
      int: 1
      action: add
    the_key_to_freedom_mode_complete:
      int: 1
      action: set

# puzzle pieces collected
  mode_puzzle_hurryup_complete:
    puzzle_pieces:
      int: 1
      action: add
  razorwire_puzzle_complete:
    razorwire_puzzle:
      int: 1
      action: add
  drillchair_puzzle_complete:
    drillchair_puzzle:
      int: 1
      action: add
  zeptest_puzzle_complete:
    zeptest_puzzle:
      int: 1
      action: add
  flammablejelly_puzzle_complete:
    flammablejelly_puzzle:
      int: 1
      action: add
  quadshotgun_puzzle_complete:
    quadshotgun_puzzle:
      int: 1
      action: add

# modes attempted for mini wizard mode -- player_modes_attempted
  mode_drillchair_started:
    modes_attempted:
      int: 1
      action: add
    drillchair_attempted:
      int: 1
      action: set
  mode_flammablejelly_started:
    modes_attempted:
      int: 1
      action: add
    flammablejelly_attempted:
      int: 1
      action: set
    candle_multiplier:
      int: 1
      action: set
  mode_quadshotgun_started:
    modes_attempted:
      int: 1
      action: add
    quadshotgun_attempted:
      int: 1
      action: set
  mode_razorwire_started:
    modes_attempted:
      int: 1
      action: add
    razorwire_attempted:
      int: 1
      action: set
  mode_reversebeartrap_started:
    modes_attempted:
      int: 1
      action: add
    reversebeartrap_attempted:
      int: 1
      action: set
  mode_zeptest_started:
    modes_attempted:
      int: 1
      action: add
    zeptest_attempted:
      int: 1
      action: set

  logicblock_acc_make_your_choice_qualify_hit:
    choice_hurryup_hits:
      int: 1
      action: add

# set qualification requirement to mode quadshotgun
# 1 = default . 2 = mode_drillchair_complete
  #slide_base_slide_main_created:
  #  drillchair_complete:
  #    int: 1
  #    action: set

counters:
  mystery_qualify:
    starting_count: 0
    count_complete_value: 5
    start_enabled: true
    persist_state: true
    reset_on_complete: true
    disable_on_complete: false
    events_when_complete: start_mystery_mode
    enable_events: mode_base_started, mode_drillchair_stopped, mode_flammablejelly_stopped, mode_quadshotgun_stopped, mode_razorwire_stopped, mode_reversebeartrap_stopped, mode_zeptest_stopped, mode_survival_instinct_stopped, mode_puzzle_hurryup_stopped, mode_make_your_choice_hurryup_stopped, mode_hacksaw_multiball_stopped, mode_jigsaw_multiball_stopped, mode_shackle_multiball_stopped
    disable_events: multiball_active, mode_selection_mode_started, mode_hacksaw_multiball_started, mode_jigsaw_multiball_started, mode_shackle_multiball_started
    reset_events: sh_select_mode_hit
    count_events: sw_lower_drop_target

  random_switch:
    starting_count: 0
    count_complete_value: 5000
    enable_events: enable_qualify
    disable_events: disable_qualify
    start_enabled: true
#    persist_state: true
    reset_on_complete: true
    events_when_complete: random_switch_complete
    count_events: sw_pops, sw_standup, sw_inlane, sw_spinner, sw_ramp, sw_loop, sw_drop_target

show_player:
  shot_drillchair_button_sp_drillchair_lit_hit:
    sh_item_used:
      show_tokens:
        leds: l_jw_gun
        color1: off
      priority: 200
  shot_razorwire_button_sp_razorwire_lit_hit:
    sh_item_used:
      show_tokens:
        leds: l_jw_hacksaw
        color1: off
      priority: 200
  shot_reversebeartrap_button_sp_reversebeartrap_lit_hit:
    sh_item_used:
      show_tokens:
        leds: l_jw_key
        color1: off
      priority: 200
  shot_quadshotgun_button_sp_quadshotgun_lit_hit:
    sh_item_used:
      show_tokens:
        leds: l_jw_gears
        color1: off
      priority: 200
  shot_flammablejelly_button_sp_flammablejelly_lit_hit:
    sh_item_used:
      show_tokens:
        leds: l_jw_candle
        color1: off
      priority: 200
  shot_zeptest_button_sp_zeptest_lit_hit:
    sh_item_used:
      show_tokens:
        leds: l_jw_syringe
        color1: off
      priority: 200
  shot_outlane_button_sp_outlane_button_lit_hit:
    sh_item_used:
      show_tokens:
        leds: l_jw_bathtub
        color1: off
      priority: 200
  shot_add_a_ball_button_sp_add_a_ball_button_lit_hit:
    sh_item_used:
      show_tokens:
        leds: l_jw_taperecorder
        color1: off
      priority: 200