#config_version=5                 
mode:
#  start_events: mode_cellar_complete, stop_mode_cellar, stop_cellar_qualify_counter
  start_events: selection_mode_razorwire_selected
  stop_events: stop_mode_razorwire, ball_ended, player_razorwire_60s_timer_tick{value < 1}
 
sequences:
  razorwire:
    events:
      - razorwire_pops_complete
      - upper_drop_target_hit
      - left_ramp_hit
    reset_on_complete: false
    events_when_complete: mode_razorwire_complete, stop_mode_razorwire
 
timers:
  60s_timer:
    start_value: 69
    end_value: 0
    direction: down
    control_events:
      - action: start
        event: mode_razorwire_started

counters:
  razorwire_pops_counter:
    starting_count: 0
    count_complete_value: 25
    enable_events: enable_qualify
    disable_events: disable_qualify
    start_enabled: true
#    persist_state: true
    reset_on_complete: false
#    events_when_complete: mode_razorwire_complete, stop_mode_razorwire
    events_when_complete: razorwire_pops_complete   
    count_events: upper_l_pop_hit, upper_r_pop_hit, upper_b_pop_hit

shots:
  upper_l_pop:
    switch: s_left_top_jet_bumper
  upper_r_pop:
    switch: s_right_top_jet_bumper
  upper_b_pop:
    switch: s_lower_top_jet_bumper 

#shot_groups:
#  spinner:
#    shots: spinner
    

variable_player:
  upper_l_pop_hit:
    score: 2150
  upper_r_pop_hit:
    score: 2150
  upper_b_pop_hit:
    score: 2150
  counter_razorwire_pops_counter_hit:
    razorwire_pops_counter:
      action: set
      int: (count)*27.5
    razorwire_visual_pops_counter:
      action: set
      int: (count)
    
       
  timer_your_timer_tick:
    60s_timer:
      int: device.timers.your_timer.ticks_remaining
      action: set
 
slides:
  razorwirevideo:
    widgets:
    - type: video
      video: razorwirevideo  
      
  razorwire_pops:
    widgets:
    - type: Text
      text: Aim for the Upper Pop Bumpers!
      font_name: TrajanProRegular
      font_size: 75
      color: 65fe08
      
    - type: image
      image: hacksawUI
      opacity: 0.5
      y: 1
      x: 1
      anchor_x: left
      anchor_y: bottom
    - type: text
      text: (score)
      number_grouping: true
      y: 16
      x: 25
      font_size: 36
      anchor_x: left
      anchor_y: bottom
      font_name: TrajanProRegular
      color: 65fe08
      
    - type: Text
      text: 00:(player|razorwire_60s_timer_tick)
      font_size: 100
      font_name: digitalclockfont
      color: red
      x: 50%
      y: 83.2%
    - type: rectangle
      width: 420
      height: 130
      x: 50%
      y: 84.5%
      corner_radius: 20
      corner_segments: 20
      color: black
      
    - type: rectangle
      width: 0
      height: 45
      x: 25%
      y: 180
      anchor_x: left
      corner_radius: 10
      corner_segments: 10
      color: 65fe08
      animations:
        player_razorwire_pops_counter:
         - property: width
           value: (value)           
    - type: rectangle
      width: 685
      height: 46
      x: 50%
      y: 180
      color: black
      corner_radius: 10
      corner_segments: 10
      
#    - type: Text
#      text: Seconds Left
#      font_size: 50
#      font_name: TrajanProRegular
#      color: 65fe08
#      x: 825
#      y: 85%
    - type: Text
# work on displaying the count of spins
      text: (player|razorwire_visual_pops_counter) / 25 Pops Hit
      font_size: 50
      font_name: TrajanProRegular
      color: 65fe08
      y: 35%
    - type: Text
      text: You Have 60 Seconds To Hit 25 Pop Bumpers!
      color: yellow
      font_name: TrajanProRegular
      font_size: 35
      y: 15%
      animations:
       pre_show_slide:
        - property: opacity
          value: 0
          duration: 1s
        - property: opacity
          value: 1
          duration: 1s
          repeat: true
    - type: image
      image: razorwireimg
      opacity: 0.65
    transition:
     type: fade
     duration: 0.2s
 

  razorwire_phase2:
    widgets:
    - type: Text
      text: "- X Marks The Spot ..."
      font_name: TrajanProRegular
      font_size: 52
      x: 425
      y: 62%
      color: 65fe08       
    - type: Text
      text: "- Hit The Left Ramp To Escape"
      font_size: 52
      font_name: TrajanProRegular
      color: 65fe08 
      x: 552
      y: 52%
    - type: Text
      text: " & Complete The Trap"
      font_size: 52
      font_name: TrajanProRegular
      color: 65fe08 
      x: 452
      y: 46%
      
    - type: image
      image: hacksawUI
      opacity: 0.5
      y: 1
      x: 1
      anchor_x: left
      anchor_y: bottom
    - type: text
      text: (score)
      number_grouping: true
      y: 16
      x: 25
      font_size: 36
      anchor_x: left
      anchor_y: bottom
      font_name: TrajanProRegular
      color: 65fe08
      
    - type: Text
      text: 00:(player|razorwire_60s_timer_tick)
      font_size: 100
      font_name: digitalclockfont
      color: red
      x: 50%
      y: 83.2%
    - type: rectangle
      width: 420
      height: 130
      x: 50%
      y: 84.5%
      corner_radius: 20
      corner_segments: 20
      color: black
                
    - type: image
      image: razorwireimg
      opacity: 0.4
    transition:
     type: fade
     duration: 0.2s

#shots:
#  spinner:
#    switch: s_spinner

      
slide_player:
  mode_razorwire_started: 
    razorwirevideo:
      priority: 500
      expire: 8.7s
  slide_razorwirevideo_removed: 
    razorwire_pops:
      priority: 400
      expire: 66.5s
  razorwire_pops_complete:
    razorwire_phase2:
      priority: 405
      expire: 60.5s
 
widgets:
   rw_shot_update2:
    - type: Text
      text: X
      color: ad1400
      x: 5.5%
      y: 62%
      font_size: 70
      font_name: TrajanProRegular
   rw_shot_update3:
    - type: Text
      text: X
      color: ad1400
      x: 5.5%
      y: 52%
      font_size: 70
      font_name: TrajanProRegular
 
widget_player:
 logicblock_razorwire_hit{step==2}: 
  rw_shot_update2:
    slide: razorwire_phase2
 logicblock_razorwire_hit{step==3}: 
  rw_shot_update3:
    slide: razorwire_phase2


#EK added 

show_player:
  mode_razorwire_started:     
    gi_on:
      show_tokens:
        color1: 46eb34
  upper_l_pop_hit:
      attract_flash_all:
        loops: 1
        speed: 10
        show_tokens:
          color1: 46eb34
  #    flash_token:
  #      loops: 5
  #      speed: 20
  #      show_tokens:
  #        led: l_left_top_bumper
  #        color1: 46eb34
  upper_r_pop_hit:
      attract_flash_all:
        loops: 1
        speed: 10
        show_tokens:
          color1: ffffff
#      flash_token:
#        loops: 5
#        speed: 20
#        show_tokens:
#          led: l_right_top_bumper
#          color1: 46eb34
  upper_b_pop_hit:
      rw_white_sweeps:
        loops: 0
        speed: 30
#      flash_token:
#        loops: 5
#        speed: 20
#        show_tokens:
#          led: l_lower_top_bumper
#          color1: 46eb34
  razorwire_pops_complete:
      top_drop_chase:
        loops: -1
        speed: 20
        show_tokens:
          color1: red

      gi_flicker:
        loops: -1
        speed: 20
        show_tokens:
          color1: ffffff

  upper_drop_target_hit:
      attract_flash_all:
        loops: 1
        speed: 10
        show_tokens:
          color1: ffffff
      top_drop_chase: stop



