#config_version=6                 
mode:
  start_events: selection_mode_razorwire_selected
  stop_events: stop_mode_razorwire, ball_ended, ball_will_end, player_razorwire_60s_timer_tick{value < 1}
  priority: 181
 
sequences:
  razorwire:
    events:
      - razorwire_pops_complete
      - drop_target_dt_upper_drop1_down
      - ssh_left_ramp_hit
    reset_on_complete: false
    events_when_complete: mode_razorwire_complete, stop_mode_razorwire
 
timers:
  60s_timer:
    start_value: 73
    end_value: 0
    direction: down
    control_events:
      - action: start
        event: mode_razorwire_started

counters:
  razorwire_pops_counter:
    starting_count: 0
    count_complete_value: 25
    enable_events: enable_qualify
    disable_events: disable_qualify
    start_enabled: true
#    persist_state: true
    reset_on_complete: false
#    events_when_complete: mode_razorwire_complete, stop_mode_razorwire
    events_when_complete: razorwire_pops_complete   
    count_events: upper_l_pop_hit, upper_r_pop_hit, upper_b_pop_hit

shots:
  upper_l_pop:
    switch: s_left_top_jet_bumper
  upper_r_pop:
    switch: s_right_top_jet_bumper
  upper_b_pop:
    switch: s_lower_top_jet_bumper 

#shot_groups:
#  spinner:
#    shots: spinner
    

variable_player:
  logicblock_razorwire_hit{step==1}:
    score: 1000000
  logicblock_razorwire_hit{step==2}:
    score: 1000000
  mode_razorwire_complete:
    score: 6500000 
  counter_razorwire_pops_counter_hit:
    razorwire_pops_counter:
      action: set
      int: (count)*27.5
    razorwire_visual_pops_counter:
      action: set
      int: (count)
    
       
  timer_your_timer_tick:
    60s_timer:
      int: device.timers.your_timer.ticks_remaining
      action: set
 
slides:
  razorwirevideo:
    widgets:
    - type: video
      video: razorwirevideo  
  XMarksTheSpotVideo:
    widgets:
    - type: video
      video: XMarksTheSpotVideo
      
  razorwire_pops:
    widgets:
    - type: Text
      text: Aim for the Upper Pop Bumpers!
      font_name: TrajanProRegular
      font_size: 75
      outline_color: black
      outline_width: 7
      color: 65fe08
      
    - type: image
      image: hacksawUI
      opacity: 0.5
      y: 1
      x: 1
      anchor_x: left
      anchor_y: bottom
    - type: text
      text: (score)
      number_grouping: true
      y: 16
      x: 25
      font_size: 36
      anchor_x: left
      anchor_y: bottom
      font_name: TrajanProRegular
      color: 65fe08
      
    - type: Text
      text: 00:(player|razorwire_60s_timer_tick)
      font_size: 100
      font_name: digitalclockfont
      color: red
      x: 50%
      y: 83.2%
    - type: rectangle
      width: 420
      height: 130
      x: 50%
      y: 84.5%
      corner_radius: 20
      corner_segments: 20
      color: black
      
    - type: rectangle
      width: 0
      height: 45
      x: 25%
      y: 180
      anchor_x: left
      corner_radius: 10
      corner_segments: 10
      color: 65fe08
      animations:
        player_razorwire_pops_counter:
         - property: width
           value: (value)           
    - type: rectangle
      width: 685
      height: 46
      x: 50%
      y: 180
      color: black
      corner_radius: 10
      corner_segments: 10
      
#    - type: Text
#      text: Seconds Left
#      font_size: 50
#      font_name: TrajanProRegular
#      color: 65fe08
#      x: 825
#      y: 85%
    - type: Text
# work on displaying the count of spins
      text: (player|razorwire_visual_pops_counter) / 25 Pops Hit
      font_size: 50
      font_name: TrajanProRegular
      outline_color: black
      outline_width: 7
      color: 65fe08
      y: 35%
    - type: Text
      text: You Have 60 Seconds To Hit 25 Pop Bumpers!
      color: yellow
      font_name: TrajanProRegular
      font_size: 35
      y: 15%
      animations:
       pre_show_slide:
        - property: opacity
          value: 0
          duration: 1s
        - property: opacity
          value: 1
          duration: 1s
          repeat: true
    - type: image
      image: razorwireimg
      opacity: 0.65
    transition:
     type: fade
     duration: 0.2s
 

  razorwire_phase2:
    widgets:
    #- type: Text
    #  text: "- X Marks The Spot ..."
    #  font_name: TrajanProRegular
    #  font_size: 52
    #  x: 425
    #  y: 62%
    #  color: 65fe08       
    #- type: Text
    #  text: "- Hit The Left Ramp To Escape"
    #  font_size: 52
    #  font_name: TrajanProRegular
    #  color: 65fe08 
    #  x: 552
    #  y: 52%
    #- type: Text
    #  text: " & Complete The Trap"
    #  font_size: 52
    #  font_name: TrajanProRegular
    #  color: 65fe08 
    #  x: 452
    #  y: 46%
      
    - type: image
      image: hacksawUI
      opacity: 0.5
      y: 1
      x: 1
      anchor_x: left
      anchor_y: bottom
    - type: text
      text: (score)
      number_grouping: true
      y: 16
      x: 25
      font_size: 36
      anchor_x: left
      anchor_y: bottom
      font_name: TrajanProRegular
      color: 65fe08
      
    - type: Text
      text: 00:(player|razorwire_60s_timer_tick)
      font_size: 100
      font_name: digitalclockfont
      color: red
      x: 50%
      y: 83.2%
    - type: rectangle
      width: 420
      height: 130
      x: 50%
      y: 84.5%
      corner_radius: 20
      corner_segments: 20
      color: black
                
    - type: image
      image: razorwireimg
      opacity: 0.4
    transition:
     type: fade
     duration: 0.2s

#shots:
#  spinner:
#    switch: s_spinner
slide_player:
  mode_razorwire_started: 
    razorwirevideo:
      priority: 500
      expire: 12.7s
  slide_razorwirevideo_removed: 
    razorwire_pops:
      priority: 400
      expire: 70.5s
  razorwire_pops_complete:
    XMarksTheSpotVideo:
      priority: 406
      expire: 2.1s
    razorwire_phase2:
      priority: 405
      expire: 60.5s
# backup removal test
  ball_will_end:
    razorwire_pops:
      priority: 505
      expire: 0.1s
    razorwire_phase2:
      priority: 505
      expire: 0.1s
 
widgets:
   rw_shot_update2:
    #- type: Text
    #  text: X
    #  color: ad1400
    #  x: 5.5%
    #  y: 62%
    #  font_size: 70
    #  font_name: TrajanProRegular
    - type: Text
      text: " X Marks The Spot ..."
      font_name: TrajanProRegular
      font_size: 80
      outline_color: black
      outline_width: 7
      x: 50%
      y: 62%
      z: 1
      color: 65fe08       
      animations:
        add_to_slide:
          - property: y
            value: 62%
            duration: 2.1s
          - property: opacity
            value: 0
          - property: opacity
            value: 1
            duration: 1000ms
            timing: after_previous
   #rw_shot_update3:
   # - type: Text
   #   text: X
   #   color: ad1400
   #   x: 5.5%
   #   y: 52%
   #   font_size: 70
   #   font_name: TrajanProRegular

   rw_shot_update3:
    - type: Text
      text: " Hit The Left Ramp To Escape"
      font_size: 80
      font_name: TrajanProRegular
      outline_color: black
      outline_width: 7
      color: 65fe08 
      x: 50%
      y: 62%
      z: 1
      animations:
        add_to_slide:
          - property: opacity
            value: 0
          - property: opacity
            value: 1
            duration: 1000ms
            timing: after_previous
    - type: Text
      text: " & Complete The Trap"
      font_size: 80
      font_name: TrajanProRegular
      outline_color: black
      outline_width: 7
      color: 65fe08 
      x: 50%
      y: 48%
      z: 1
      animations:
        add_to_slide:
          - property: opacity
            value: 0
          - property: opacity
            value: 1
            duration: 1000ms
            timing: after_previous

widget_player:
 logicblock_razorwire_hit{step==1}: 
  rw_shot_update2:
    slide: razorwire_phase2
    action: add
 logicblock_razorwire_hit{step==2}: 
  rw_shot_update2:
    slide: razorwire_phase2
    action: remove
  rw_shot_update3:
    slide: razorwire_phase2
    action: add

shows:
  razorwire_pops_progress:    
    - duration: -1      
      lights:    
        (leds): (color1)
#EK added 

show_player:
  mode_razorwire_started:     
    gi_on:
      show_tokens:
        color1: razorwire
  upper_l_pop_hit:
      attract_flash_all:
        loops: 1
        speed: 10
        show_tokens:
          color1: razorwire
  #    flash_token:
  #      loops: 5
  #      speed: 20
  #      show_tokens:
  #        led: l_left_top_bumper
  #        color1: 46eb34
  upper_r_pop_hit:
      attract_flash_all:
        loops: 1
        speed: 10
        show_tokens:
          color1: ffffff
#      flash_token:
#        loops: 5
#        speed: 20
#        show_tokens:
#          led: l_right_top_bumper
#          color1: 46eb34
  upper_b_pop_hit:
      rw_white_sweeps:
        loops: 0
        speed: 30
#      flash_token:
#        loops: 5
#        speed: 20
#        show_tokens:
#          led: l_lower_top_bumper
#          color1: 46eb34
  #razorwire_pops_complete:
  #    top_drop_chase:
  #      loops: -1
  #      speed: 20
  #      show_tokens:
  #        color1: red

      gi_flicker:
        loops: -1
        speed: 20
        show_tokens:
          color1: ffffff

  upper_drop_target_hit:
      attract_flash_all:
        loops: 1
        speed: 10
        show_tokens:
          color1: ffffff
      top_drop_chase: stop
# pops progress
  logicblock_razorwire_pops_counter_hit{count==1}:
      razorwire_pops_progress:
        loops: -1
        show_tokens:
          leds: l_lower_top_bumper_1, l_left_top_bumper_1, l_right_top_bumper_1
          color1: razorwire
  logicblock_razorwire_pops_counter_hit{count==4}:
      razorwire_pops_progress:
        loops: -1
        show_tokens:
          leds: l_lower_top_bumper_1, l_left_top_bumper_1, l_right_top_bumper_1, l_lower_top_bumper_2, l_left_top_bumper_2, l_right_top_bumper_2, l_lower_top_bumper_16, l_left_top_bumper_16, l_right_top_bumper_16
          color1: razorwire
  logicblock_razorwire_pops_counter_hit{count==7}:
      razorwire_pops_progress:
        loops: -1
        show_tokens:
          leds: l_lower_top_bumper_1, l_left_top_bumper_1, l_right_top_bumper_1, l_lower_top_bumper_2, l_left_top_bumper_2, l_right_top_bumper_2, l_lower_top_bumper_16, l_left_top_bumper_16, l_right_top_bumper_16, l_lower_top_bumper_3, l_left_top_bumper_3, l_right_top_bumper_3, l_lower_top_bumper_15, l_left_top_bumper_15, l_right_top_bumper_15
          color1: razorwire
  logicblock_razorwire_pops_counter_hit{count==10}:
      razorwire_pops_progress:
        loops: -1
        show_tokens:
          leds: l_lower_top_bumper_1, l_left_top_bumper_1, l_right_top_bumper_1, l_lower_top_bumper_2, l_left_top_bumper_2, l_right_top_bumper_2, l_lower_top_bumper_16, l_left_top_bumper_16, l_right_top_bumper_16, l_lower_top_bumper_3, l_left_top_bumper_3, l_right_top_bumper_3, l_lower_top_bumper_15, l_left_top_bumper_15, l_right_top_bumper_15, l_lower_top_bumper_4, l_left_top_bumper_4, l_right_top_bumper_4, l_lower_top_bumper_14, l_left_top_bumper_14, l_right_top_bumper_14
          color1: razorwire
  logicblock_razorwire_pops_counter_hit{count==13}:
      razorwire_pops_progress:
        loops: -1
        show_tokens:
          leds: l_lower_top_bumper_1, l_left_top_bumper_1, l_right_top_bumper_1, l_lower_top_bumper_2, l_left_top_bumper_2, l_right_top_bumper_2, l_lower_top_bumper_16, l_left_top_bumper_16, l_right_top_bumper_16, l_lower_top_bumper_3, l_left_top_bumper_3, l_right_top_bumper_3, l_lower_top_bumper_15, l_left_top_bumper_15, l_right_top_bumper_15, l_lower_top_bumper_4, l_left_top_bumper_4, l_right_top_bumper_4, l_lower_top_bumper_14, l_left_top_bumper_14, l_right_top_bumper_14, l_lower_top_bumper_5, l_left_top_bumper_5, l_right_top_bumper_5, l_lower_top_bumper_13, l_left_top_bumper_13, l_right_top_bumper_13
          color1: razorwire
  logicblock_razorwire_pops_counter_hit{count==16}:
      razorwire_pops_progress:
        loops: -1
        show_tokens:
          leds: l_lower_top_bumper_1, l_left_top_bumper_1, l_right_top_bumper_1, l_lower_top_bumper_2, l_left_top_bumper_2, l_right_top_bumper_2, l_lower_top_bumper_16, l_left_top_bumper_16, l_right_top_bumper_16, l_lower_top_bumper_3, l_left_top_bumper_3, l_right_top_bumper_3, l_lower_top_bumper_15, l_left_top_bumper_15, l_right_top_bumper_15, l_lower_top_bumper_4, l_left_top_bumper_4, l_right_top_bumper_4, l_lower_top_bumper_14, l_left_top_bumper_14, l_right_top_bumper_14, l_lower_top_bumper_5, l_left_top_bumper_5, l_right_top_bumper_5, l_lower_top_bumper_13, l_left_top_bumper_13, l_right_top_bumper_13
          color1: razorwire
  logicblock_razorwire_pops_counter_hit{count==19}:
      razorwire_pops_progress:
        loops: -1
        show_tokens:
          leds: l_lower_top_bumper_1, l_left_top_bumper_1, l_right_top_bumper_1, l_lower_top_bumper_2, l_left_top_bumper_2, l_right_top_bumper_2, l_lower_top_bumper_16, l_left_top_bumper_16, l_right_top_bumper_16, l_lower_top_bumper_3, l_left_top_bumper_3, l_right_top_bumper_3, l_lower_top_bumper_15, l_left_top_bumper_15, l_right_top_bumper_15, l_lower_top_bumper_4, l_left_top_bumper_4, l_right_top_bumper_4, l_lower_top_bumper_14, l_left_top_bumper_14, l_right_top_bumper_14, l_lower_top_bumper_5, l_left_top_bumper_5, l_right_top_bumper_5, l_lower_top_bumper_13, l_left_top_bumper_13, l_right_top_bumper_13, l_lower_top_bumper_7, l_left_top_bumper_7, l_right_top_bumper_7, l_lower_top_bumper_11, l_left_top_bumper_11, l_right_top_bumper_11
          color1: razorwire
  logicblock_razorwire_pops_counter_hit{count==22}:
      razorwire_pops_progress:
        loops: -1
        show_tokens:
          leds: l_lower_top_bumper_1, l_left_top_bumper_1, l_right_top_bumper_1, l_lower_top_bumper_2, l_left_top_bumper_2, l_right_top_bumper_2, l_lower_top_bumper_16, l_left_top_bumper_16, l_right_top_bumper_16, l_lower_top_bumper_3, l_left_top_bumper_3, l_right_top_bumper_3, l_lower_top_bumper_15, l_left_top_bumper_15, l_right_top_bumper_15, l_lower_top_bumper_4, l_left_top_bumper_4, l_right_top_bumper_4, l_lower_top_bumper_14, l_left_top_bumper_14, l_right_top_bumper_14, l_lower_top_bumper_5, l_left_top_bumper_5, l_right_top_bumper_5, l_lower_top_bumper_13, l_left_top_bumper_13, l_right_top_bumper_13, l_lower_top_bumper_7, l_left_top_bumper_7, l_right_top_bumper_7, l_lower_top_bumper_11, l_left_top_bumper_11, l_right_top_bumper_11, l_lower_top_bumper_8, l_left_top_bumper_8, l_right_top_bumper_8, l_lower_top_bumper_10, l_left_top_bumper_10, l_right_top_bumper_10
          color1: razorwire
  logicblock_razorwire_pops_counter_hit{count==25}:
      razorwire_pops_progress:
        loops: -1
        show_tokens:
          leds: top_bumper
          color1: razorwire
  logicblock_razorwire_hit{step==1}:
      top_drop_chase:
        loops: -1
        speed: 20
        show_tokens:
          color1: razorwire
  logicblock_razorwire_hit{step==2}:
      left_ramp_chase:
        loops: -1
        speed: 5
        show_tokens:
          color1: razorwire
      top_drop_chase:
        loops: -1
        show_tokens:
          color1: off

sound_pools:
  razorwire_mode_sound_pool:
    load: preload
    type: random
    track: sfx
    sounds:
      - RW1
      - RW2
      - RW3
      - RW6
      - RW7
      - RW8
      - RW9
      - RW10
      - RW11
      - RW12
      - RW13
      - RW14

sound_player:
  mode_razorwire_started:
    RazorwireIntro:
      action: play
    RWModeStart:
      delay: 4s
      action: play 
  player_razorwire_60s_timer_tick{value < 1}:
    RWModeStart:
      action: stop

  sw_bottom_pops:
    razorwire_mode_sound_pool:
      action: play
      block: true
  sw_slingshot:
    razorwire_mode_sound_pool:
      action: play
      block: true    
  sw_standup:
    razorwire_mode_sound_pool:
      action: play
      block: true
  sw_right_return_lane:
    razorwire_mode_sound_pool:
      action: play
      block: true
  sw_lower_drop_target:
    razorwire_mode_sound_pool:
      action: play
      block: true

event_player: 
  slide_razorwire_pops_active: e_primary_mode_active
