#config_version=6
##! mode: jigsaw_multiball_qualify

mode:
  start_events: startmode_jigsaw_multiball_qualify
  priority: 150

sequences:
  seq_jigsaw_mb_qualify:
    events:
      - s_middle_standup_active
      - ssh_left_ramp_hit
    reset_on_complete: true
    disable_on_complete: false
    persist_state: true

#TODO need a player variable to store this counter between balls
counters:
  cnt_jigsaw_mb_qualify:
    starting_count: 0
    count_complete_value: 3
    start_enabled: true
    persist_state: true
    reset_on_complete: false
    count_events: logicblock_seq_jigsaw_mb_qualify_complete

event_player:
  logicblock_seq_jigsaw_mb_qualify_hit{step==1}:
    - e_jigsaw_mb_qualify_hit_one
  logicblock_seq_jigsaw_mb_qualify_hit{step==2}:
    - e_jigsaw_mb_qualify_hit_two

shows:
  sh_jigsaw_mb_qualify_hit_ready:
    - duration: -1
      shows:
        flash_color:
          show_tokens:
            color: color_jigsaw_mb
            leds: (leds)
          speed: 4
  sh_jigsaw_mb_qualify_hit_qualified:
    - duration: -1
      lights:
        (leds): color_jigsaw_mb
  sh_jigsaw_mb_end:
    - duration: -1
      lights:
        (leds): off

show_player:
  e_jigsaw_mb_qualify_hit_one{device.counters.cnt_jigsaw_mb_qualify.value == 0}:
    sh_jigsaw_mb_qualify_hit_ready:
      show_tokens:
        leds: l_left_ramp_triangle3
  e_jigsaw_mb_qualify_hit_two{device.counters.cnt_jigsaw_mb_qualify.value == 0}:
    sh_jigsaw_mb_qualify_hit_qualified:
      show_tokens:
        leds: l_left_ramp_triangle3
  e_jigsaw_mb_qualify_hit_one{device.counters.cnt_jigsaw_mb_qualify.value == 1}:
    sh_jigsaw_mb_qualify_hit_ready:
      show_tokens:
        leds: l_left_ramp_triangle2
  e_jigsaw_mb_qualify_hit_two{device.counters.cnt_jigsaw_mb_qualify.value == 1}:
    sh_jigsaw_mb_qualify_hit_qualified:
      show_tokens:
        leds: l_left_ramp_triangle3, l_left_ramp_triangle2
  e_jigsaw_mb_qualify_hit_one{device.counters.cnt_jigsaw_mb_qualify.value == 2}:
    sh_jigsaw_mb_qualify_hit_ready:
      show_tokens:
        leds: l_left_ramp_triangle1
  e_jigsaw_mb_qualify_hit_two{device.counters.cnt_jigsaw_mb_qualify.value == 2}:
    sh_jigsaw_mb_qualify_hit_qualified:
      show_tokens:
        leds: l_left_ramp_triangle3, l_left_ramp_triangle2, l_left_ramp_triangle1
  multiball_mb_jigsaw_ended:
    sh_jigsaw_mb_end:
      show_tokens:
        leds: l_left_ramp_triangle1, l_left_ramp_triangle2, l_left_ramp_triangle3
