#config_version=6
##! mode: jigsaw_multiball_qualify

mode:
  start_events: startmode_jigsaw_multiball_qualify, mode_hacksaw_multiball_stopped, mode_jigsaw_multiball_stopped, mode_shackle_multiball_stopped, mode_jigsaw_multiball_complete, mode_hacksaw_multiball_complete, mode_shackle_multiball_complete, mode_lil_billy_stopped, mode_the_key_to_freedom_stopped, mode_survival_instinct_stopped
  # startmode_jigsaw_multiball_qualify, mode_razorwire_stopped, mode_drillchair_stopped, mode_flammablejelly_stopped, mode_quadshotgun_stopped, mode_reversebeartrap_stopped, mode_zeptest_stopped, mode_hacksaw_multiball_stopped, mode_jigsaw_multiball_stopped, mode_shackle_multiball_stopped, mode_make_your_choice_hurryup_stopped, mode_jigsaw_multiball_complete, mode_hacksaw_multiball_complete, mode_shackle_multiball_complete, mode_survival_instinct_stopped, mode_survival_instinct_complete
  stop_events: multiball_mb_shackle_started, multiball_mb_hacksaw_started, multiball_mb_jigsaw_started, mode_bonus_started, mode_lil_billy_started, mode_the_key_to_freedom_started, mode_survival_instinct_started
  # mode_selection_mode_started, mode_make_your_choice_hurryup_started, multiball_mb_jigsaw_started, multiball_mb_hacksaw_started, multiball_mb_shackle_started, mode_razorwire_started, mode_drillchair_started, mode_flammablejelly_started, mode_quadshotgun_started, mode_reversebeartrap_started, mode_zeptest_started, mode_make_your_choice_hurryup_started, mode_survival_instinct_started
  priority: 183

sequences:
  seq_jigsaw_mb_qualify:
    events:
      - s_middle_standup_active
      - ssh_left_ramp_hit
    reset_on_complete: true
    disable_on_complete: false
    persist_state: true

#TODO need a player variable to store this counter between balls
counters:
  cnt_jigsaw_mb_qualify:
    starting_count: 0
    count_complete_value: 3
    start_enabled: true
    persist_state: true
    reset_on_complete: false
    count_events: logicblock_seq_jigsaw_mb_qualify_complete
    events_when_complete: logicblock_jigsaw_multiball_qualify_complete
    control_events:
      - event: e_mystery_mb_lock
        action: add
        value: 1

  cnt_jigsaw_mb_qualify_lights:
    starting_count: 0
    count_complete_value: 6
    start_enabled: true
    persist_state: true
    reset_on_complete: true
    count_events: e_jigsaw_mb_qualify_hit_one, e_jigsaw_mb_qualify_hit_two 
    reset_events: logicblock_jigsaw_multiball_qualify_complete
    control_events:
      - event: e_mystery_mb_lock
        action: add
        value: 2

  cnt_jigsaw_mb_lock1:
    starting_count: 0
    count_complete_value: 1
    start_enabled: true
    persist_state: true
    events_when_complete: e_jigsaw_lock1
    count_events: logicblock_cnt_jigsaw_mb_qualify_updated{value==1}

  cnt_jigsaw_mb_lock2:
    starting_count: 0
    count_complete_value: 1
    start_enabled: true
    persist_state: true
    events_when_complete: e_jigsaw_lock2
    count_events: logicblock_cnt_jigsaw_mb_qualify_updated{value==2}

variable_player:
  logicblock_cnt_jigsaw_mb_qualify_hit:
    jigsaw_mb_lock_counter:
      action: set
      int: (count)
  logicblock_jigsaw_multiball_qualify_complete:
    jigsaw_mb_lock_counter:
      action: set
      int: 0

event_player:
  logicblock_seq_jigsaw_mb_qualify_hit{step==1}:
    - e_jigsaw_mb_qualify_hit_one
  logicblock_seq_jigsaw_mb_qualify_hit{step==2}:
    - e_jigsaw_mb_qualify_hit_two

shows:
  sh_jigsaw_mb_qualify_hit_ready:
    - duration: -1
      shows:
        flash_color:
          show_tokens:
            color: color_hacksaw_mb
            leds: (leds)
          speed: 4
  sh_jigsaw_mb_qualify_hit_qualified:
    - duration: -1
      lights:
        (leds): color_hacksaw_mb
  sh_jigsaw_mb_end:
    - duration: -1
      lights:
        (leds): off
  sh_jigsaw_mb_qualify_hit:
    - duration: 0.3s
      lights:
        (leds): color_hacksaw_mb
    - duration: 0.3s
      lights:
        (leds): off

show_player:
  logicblock_cnt_jigsaw_mb_qualify_lights_updated{device.counters.cnt_jigsaw_mb_qualify_lights.value == 1}:
    jigsaw_mb_qualify_ready:
      speed: 4
      priority: 183
  logicblock_cnt_jigsaw_mb_qualify_lights_updated{device.counters.cnt_jigsaw_mb_qualify_lights.value == 2}:
    jigsaw_mb_qualify_ready: stop
    sh_jigsaw_mb_qualify_hit_qualified:
      show_tokens:
        leds: l_left_ramp_triangle3
      priority: 184
    shackle_mb_lock:
      loops: 0
      speed: 30  
  logicblock_cnt_jigsaw_mb_qualify_lights_updated{device.counters.cnt_jigsaw_mb_qualify_lights.value == 3}:
    jigsaw_mb_qualify_ready:
      speed: 4
      priority: 183
    sh_jigsaw_mb_qualify_hit_qualified:
      show_tokens:
        leds: l_left_ramp_triangle3
      priority: 184
  logicblock_cnt_jigsaw_mb_qualify_lights_updated{device.counters.cnt_jigsaw_mb_qualify_lights.value == 4}:
    jigsaw_mb_qualify_ready: stop
    sh_jigsaw_mb_qualify_hit_qualified:
      show_tokens:
        leds: l_left_ramp_triangle3, l_left_ramp_triangle2
      priority: 184
    shackle_mb_lock:
      loops: 0
      speed: 30
  logicblock_cnt_jigsaw_mb_qualify_lights_updated{device.counters.cnt_jigsaw_mb_qualify_lights.value == 5}:
    jigsaw_mb_qualify_ready:
      speed: 4
      priority: 183
    sh_jigsaw_mb_qualify_hit_qualified:
      show_tokens:
        leds: l_left_ramp_triangle3, l_left_ramp_triangle2
      priority: 184
  logicblock_cnt_jigsaw_mb_qualify_lights_updated{device.counters.cnt_jigsaw_mb_qualify_lights.value == 6}:
    jigsaw_mb_qualify_ready: stop
    sh_jigsaw_mb_qualify_hit_qualified:
      show_tokens:
        leds: l_left_ramp_triangle3, l_left_ramp_triangle2, l_left_ramp_triangle1
      priority: 184
  multiball_mb_jigsaw_ended:
    sh_jigsaw_mb_end:
      show_tokens:
        leds: l_left_ramp_triangle1, l_left_ramp_triangle2, l_left_ramp_triangle3
      priority: 184
  e_jigsaw_mb_qualify_hit_one:
    sh_jigsaw_mb_qualify_hit:
      show_tokens:
        leds: bear_flasher
      speed: 4
      loops: 5
    shackle_mb_lock:
      loops: 0
      speed: 30

  logicblock_cnt_jigsaw_mb_qualify_updated{value==1}:
    sh_jigsaw_mb_qualify_hit_qualified:
      show_tokens:
        leds: l_left_ramp_triangle3    
  logicblock_cnt_jigsaw_mb_qualify_updated{value==2}:
    sh_jigsaw_mb_qualify_hit_qualified:
      show_tokens:
        leds: l_left_ramp_triangle3, l_left_ramp_triangle2

sound_player:
  e_jigsaw_mb_qualify_hit_one:
    LockIsLit:
      action: play
  slide_sl_Jigsaw_locked_1_active:
    Ball1Locked:
      action: play
  slide_sl_Jigsaw_locked_2_active:
    Ball2Locked:
      action: play

slides:
  sl_Jigsaw_locked_1:
    widgets:
    - type: video
      video: jigsaw_lock1
      width: 1366
      height: 768 
  sl_Jigsaw_locked_2:
    widgets:
    - type: video
      video: jigsaw_lock2
      width: 1366
      height: 768 
  #sl_Jigsaw_locked_3:
  #  widgets:
  #  - type: video
  #    video: jigsaw_lock3
  #    width: 1366
  #    height: 768 

slide_player:
  e_jigsaw_lock1:
    sl_Jigsaw_locked_1:
      priority: 500
      expire: 3s
  e_jigsaw_lock2:
    sl_Jigsaw_locked_2:
      priority: 500
      expire: 3s
  #logicblock_cnt_jigsaw_mb_qualify_updated{value==3}:
  #  sl_Jigsaw_locked_3:
  #    priority: 500
  #    expire: 3s