#config_version=6                 
mode:
  start_events: selection_mode_reawakening_selected
  stop_events: stop_mode_reawakening, mode_reawakening_complete, ball_ended, ball_will_end, s_right_scoop_active{current_player.reawakening_phaseone_completed==1 and current_player.reawakening_apprentice_selected==1}, s_right_scoop_active{current_player.reawakening_phaseone_completed==1 and current_player.reawakening_survivor_selected==1}
  priority: 184
  restart_on_next_ball: true
  code: mpf.modes.carousel.code.carousel.Carousel
mode_settings:
#two version of each slide. image split down middle. one side is highlighted. another copy is the right side highlighted.
  selectable_items: 
    - phaseone_apprentice{current_player.reawakening_phaseone_attempted==1}
    - phaseone_survivor{current_player.reawakening_phaseone_attempted==1}
  select_item_events: s_action_button_active
  next_item_events: s_left_flipper_button_active
  previous_item_events: s_right_flipper_button_active

variable_player:
  carousel_phaseone_apprentice_selected:
    selected_mode:
      action: set
      string: 'selection_mode_phaseone_apprentice_highlighted'
  carousel_phaseone_survivor_selected:
    selected_mode:
      action: set
      string: 'selection_mode_phaseone_survivor_highlighted'
  logicblock_apprentice_phaseone_hit:
    score: 7500000
  logicblock_survivor_phaseone_hit:  
    score: 7500000
# final wizard mode
# 3 tier - choose your own adventure
# back to scoop each tier completion to choose next path/decision

# *********      logicblock_apprentice_phaseone_complete and logicblock_survivor_phaseone_complete need to add to light right scoop and select p2

# phase 1 - mode select
# left = apprentice - revisit each of the traps and clean up potential evidence left behind.
#                     Hit puzzle pieces left to right. 20 second timer after you hit each shot or it reverts back a step.
#                     After collect 5th piece. Back to lit scoop to choose phase 2 options.
# right = survivor  - you've survived the trap but now you must escape the building to find your "key to freedom". 
#                     shoot stand ups left to right while alternating shots to X drop target to navigate out of the building. 
#                     Upon hitting last X marks the spot, go back to lit scoop to choose phase 2 options.

# phase 2 
# apprentice left option - abduction - assist in abduncting next game subjects
# apprentice right option - stage the game - assist in staging next set of games

# survivor left option - Clue .. collect clues to track down jigsaw
# survivor right option - Aid - assist in savings others

# phase 3
# apprentice - let the games begin.. dodge interuptions and see games go according to plan
# survivor - final showdown - showdown with confronting jigsaw

# accruals:
#   acc_apprentice_phaseone:
#     events:
#       - shot_reawakening_drillchair_sp_reawakening_phaseone_lit_hit
#       - shot_reawakening_zeptest_sp_reawakening_phaseone_lit_hit  
#       - shot_reawakening_razorwire_sp_reawakening_phaseone_lit_hit
#       - shot_reawakening_flammablejelly_sp_reawakening_phaseone_lit_hit
#       - shot_reawakening_quadshotgun_sp_reawakening_phaseone_lit_hit
#     reset_on_complete: false
#     persist_state: true
#     disable_on_complete: true

sequences:
  apprentice_phaseone:
    events:
      - shot_reawakening_drillchair_sp_reawakening_phaseone_lit_hit
      - shot_reawakening_zeptest_sp_reawakening_phaseone_lit_hit  
      - shot_reawakening_razorwire_sp_reawakening_phaseone_lit_hit
      - shot_reawakening_flammablejelly_sp_reawakening_phaseone_lit_hit
      - shot_reawakening_quadshotgun_sp_reawakening_phaseone_lit_hit
    reset_on_complete: false
    persist_state: true
    disable_on_complete: true

  survivor_phaseone:
    events:
      - shot_reawakening_left_standup_sp_reawakening_phaseone_lit_hit
      - shot_reawakening_upper_drop_sp_reawakening_phaseone_lit_hit 
      - shot_reawakening_left_standup_right_ramp_sp_reawakening_phaseone_lit_hit
      - shot_reawakening_upper_drop_sp_reawakening_phaseone_lit_hit 
      - shot_reawakening_right_standup_right_ramp_sp_reawakening_phaseone_lit_hit 
      - shot_reawakening_upper_drop_sp_reawakening_phaseone_lit_hit 
      - shot_reawakening_right_standup_sp_reawakening_phaseone_lit_hit
      - shot_reawakening_upper_drop_sp_reawakening_phaseone_lit_hit 
    reset_on_complete: false
    persist_state: true
    disable_on_complete: true

timers:
  phaseone_apprentice_timer:
    start_value: 0
    end_value: 22
    direction: up
    control_events:
      - action: start
#update to when opening slide ends  
        event: reawakening_phaseone_apprentice_selected
      - action: reset
        event: shot_reawakening_razorwire_sp_reawakening_phaseone_lit_hit
      - action: reset
        event: shot_reawakening_drillchair_sp_reawakening_phaseone_lit_hit
      - action: reset
        event: shot_reawakening_zeptest_sp_reawakening_phaseone_lit_hit
      - action: reset
        event: shot_reawakening_flammablejelly_sp_reawakening_phaseone_lit_hit
      - action: reset   
        event: e_reawakening_phaseone_shot_reset
      - action: stop
        event: shot_reawakening_quadshotgun_sp_reawakening_phaseone_lit_hit
        
        
event_player: 
  player_reawakening_phaseone_apprentice_timer_tick{value==20}: e_reawakening_phaseone_shot_reset
  e_reawakening_phaseone_shot_reset{device.sequences.apprentice_phaseone.value==1}: e_reawakening_phaseone_a_zeptest_reset
  e_reawakening_phaseone_shot_reset{device.sequences.apprentice_phaseone.value==2}: e_reawakening_phaseone_a_razorwire_reset
  e_reawakening_phaseone_shot_reset{device.sequences.apprentice_phaseone.value==3}: e_reawakening_phaseone_a_flammablejelly_reset
  e_reawakening_phaseone_shot_reset{device.sequences.apprentice_phaseone.value==4}: e_reawakening_phaseone_a_quadshotgun_reset



shot_profiles:
 sp_reawakening_phaseone:
   advance_on_hit: false
   states:
     - name: reawakening_p1_off
       show: "off"  
     - name: lit
       show: "sh_reawakening_p1a_ready"

shows:
  sh_reawakening_p1a_ready:
   - duration: 0.15s
     lights:
       (leds): beartrap
   - duration: 0.15s
     lights:
       (leds): off
  sh_reawakening_p1a_ready_alt:
   - duration: 0.15s
     lights:
       (leds): beartrap
   - duration: 0.15s
     lights:
       (leds): off
  reawakening_mode_lit:
    - duration: .5s
      lights:
        (leds): razorwire
    - duration: .5s
      lights:
        (leds): off

show_player:
  logicblock_trap_select_qualify_counter_updated{enabled==True}:
    reawakening_mode_lit:
      show_tokens:
        leds: l_mode_scoop
      loops: -1

  logicblock_apprentice_phaseone_complete:
    reawakening_mode_lit:
      show_tokens:
        leds: l_mode_scoop
      loops: -1
  logicblock_survivor_phaseone_complete:
    reawakening_mode_lit:
      show_tokens:
        leds: l_mode_scoop
      loops: -1
  s_right_scoop_active{current_player.reawakening_phaseone_completed==1 and current_player.reawakening_apprentice_selected==1}:
    off:
      show_tokens:
        leds: l_mode_scoop
  s_right_scoop_active{current_player.reawakening_phaseone_completed==1 and current_player.reawakening_survivor_selected==1}:
    off:
      show_tokens:
        leds: l_mode_scoop
  logicblock_apprentice_phaseone_hit:
      gi_die_hurryup_intro:
        loops: 0
        speed: 45
        priority: 190
  logicblock_survivor_phaseone_hit:  
      gi_die_hurryup_intro:
        loops: 0
        speed: 45
        priority: 190
shots:
#phase one apprentice
  shot_reawakening_drillchair:
    switches: s_left_bottom_jet_bumper, s_right_bottom_jet_bumper, s_upper_bottom_jet_bumper
    profile: sp_reawakening_phaseone
    show_tokens:
      leds: drill_flasher
    control_events:
      - events: reawakening_phaseone_apprentice_selected
        state: 1
      - events: shot_reawakening_drillchair_sp_reawakening_phaseone_lit_hit
        state: 0
      - events: e_reawakening_phaseone_a_zeptest_reset
        state: 1
      - events: logicblock_quadshotgun_reset_counter_hit{hits==4}
        state: 1
  shot_reawakening_zeptest:
    switches: s_lower_bank_drop_target_opto_upper, s_lower_bank_drop_target_opto_middle, s_lower_bank_drop_target_opto_lower
    profile: sp_reawakening_phaseone
    show_tokens:
      leds: zep_flasher
    control_events:
      - events: shot_reawakening_drillchair_sp_reawakening_phaseone_lit_hit
        state: 1
      - events: shot_reawakening_zeptest_sp_reawakening_phaseone_lit_hit
        state: 0
      - events: e_reawakening_phaseone_a_zeptest_reset
        state: 0
      - events: e_reawakening_phaseone_a_razorwire_reset
        state: 1
      - events: logicblock_quadshotgun_reset_counter_hit{hits==3}
        state: 1
      - events: logicblock_quadshotgun_reset_counter_hit{hits==4}
        state: 0
  shot_reawakening_razorwire:
    switches: s_left_top_jet_bumper, s_right_top_jet_bumper, s_lower_top_jet_bumper
    profile: sp_reawakening_phaseone
    show_tokens:
      leds: razorwire_flasher
    control_events:
      - events: shot_reawakening_zeptest_sp_reawakening_phaseone_lit_hit
        state: 1
      - events: shot_reawakening_razorwire_sp_reawakening_phaseone_lit_hit
        state: 0
      - events: e_reawakening_phaseone_a_razorwire_reset
        state: 0
      - events: e_reawakening_phaseone_a_flammablejelly_reset
        state: 1
      - events: logicblock_quadshotgun_reset_counter_hit{hits==2}
        state: 1
      - events: logicblock_quadshotgun_reset_counter_hit{hits==3}
        state: 0
  shot_reawakening_flammablejelly:
    switches: s_middle_standup
    profile: sp_reawakening_phaseone
    show_tokens:
      leds: bear_flasher
    control_events:
      - events: shot_reawakening_razorwire_sp_reawakening_phaseone_lit_hit
        state: 1
      - events: shot_reawakening_flammablejelly_sp_reawakening_phaseone_lit_hit
        state: 0
      - events: e_reawakening_phaseone_a_flammablejelly_reset
        state: 0
      - events: logicblock_quadshotgun_reset_counter_hit{hits==1}
        state: 1
      - events: logicblock_quadshotgun_reset_counter_hit{hits==2}
        state: 0
  shot_reawakening_quadshotgun:
    switches: s_spinner
    profile: sp_reawakening_phaseone
    show_tokens:
      leds: shotgun_flasher
    control_events:
      - events: shot_reawakening_flammablejelly_sp_reawakening_phaseone_lit_hit
        state: 1
      - events: shot_reawakening_quadshotgun_sp_reawakening_phaseone_lit_hit
        state: 0
      - events: e_reawakening_phaseone_a_quadshotgun_reset
        state: 0
#phase one survivor
  shot_reawakening_left_standup:
    switches: s_left_standup
    profile: sp_reawakening_phaseone
    show_tokens:
      leds: l_left_standup_arrow
    control_events:
      - events: reawakening_phaseone_survivor_selected
        state: 1
      - events: shot_reawakening_left_standup_sp_reawakening_phaseone_lit_hit
        state: 0
  shot_reawakening_upper_drop:
    switches: s_upper_bank_drop_target_opto
    profile: sp_reawakening_phaseone
    show_tokens:
      leds: billy
    control_events:
      - events: logicblock_survivor_phaseone_hit{step==1}
        state: 1
      - events: logicblock_survivor_phaseone_hit{step==3}
        state: 1
      - events: logicblock_survivor_phaseone_hit{step==5}
        state: 1
      - events: logicblock_survivor_phaseone_hit{step==7}
        state: 1
      - events: shot_reawakening_upper_drop_sp_reawakening_phaseone_lit_hit 
        state: 0
  shot_reawakening_left_standup_right_ramp:
    switches: s_left_standup_right_ramp
    profile: sp_reawakening_phaseone
    show_tokens:
      leds: l_left_standup_right_ramp_arrow
    control_events:
      - events: logicblock_survivor_phaseone_hit{step==2}
        state: 1
      - events: shot_reawakening_left_standup_right_ramp_sp_reawakening_phaseone_lit_hit
        state: 0
  shot_reawakening_right_standup_right_ramp:
    switches: s_right_standup_right_ramp
    profile: sp_reawakening_phaseone
    show_tokens:
      leds: l_right_standup_right_ramp_arrow
    control_events:
      - events: logicblock_survivor_phaseone_hit{step==4}
        state: 1
      - events: shot_reawakening_right_standup_right_ramp_sp_reawakening_phaseone_lit_hit
        state: 0
  shot_reawakening_right_standup:
    switches: s_right_standup
    profile: sp_reawakening_phaseone
    show_tokens:
      leds: l_right_standup_arrow
    control_events:
      - events: logicblock_survivor_phaseone_hit{step==6}
        state: 1
      - events: shot_reawakening_right_standup_sp_reawakening_phaseone_lit_hit
        state: 0


counters:
  quadshotgun_reset_counter:
    starting_count: 0
    count_complete_value: 6
    start_enabled: true
    persist_state: true
    reset_on_complete: false
    count_events: e_reawakening_phaseone_a_quadshotgun_reset

slides:
  mode_reawakening_p1a:
    widgets:
    - type: video
      video: mode_reawakening_p1a
  mode_reawakening_p1s:
    widgets:
    - type: video
      video: mode_reawakening_p1s
slide_player:
  reawakening_phaseone_apprentice_highlighted: 
    mode_reawakening_p1a:
      priority: 400
  reawakening_phaseone_survivor_highlighted:
    mode_reawakening_p1s:
      priority: 400   
  reawakening_phaseone_apprentice_selected: 
    mode_reawakening_p1a:      
      action: remove
    mode_reawakening_p1s:      
      action: remove
  reawakening_phaseone_survivor_selected: 
    mode_reawakening_p1s:      
      action: remove
    mode_reawakening_p1a:      
      action: remove