#config_version=6                 
mode:
  start_events: startmode_make_your_choice_hurryup
  stop_events: mode_make_your_choice_hurryup_complete, stop_mode_make_your_choice_hurryup, ball_ended, ball_will_end, player_make_your_choice_hurryup_t_make_your_choice_timer_tick{value < 1}, logicblock_acc_make_your_choice_qualify_complete, logicblock_trap_select_qualify_counter_complete, mode_selection_mode_started, multiball_mb_jigsaw_started, multiball_mb_hacksaw_started, multiball_mb_shackle_started, mode_razorwire_started, mode_drillchair_started, mode_flammablejelly_started, mode_quadshotgun_started, mode_reversebeartrap_started, mode_zeptest_started
  priority: 185

  # Spell D-I-E / S-A-W (3 drop target bank) in sequential order to start this hurry up mode.
  # hit X marks the spot to lock in value.
  # orbits the remaining duration to cash in value

accruals:
  acc_make_your_choice_qualify:
    events:
      - drop_target_dt_upper_drop1_down
      - ssh_leftloop_hit
      - ssh_rightloop_hit
      - sw_inner_loop
    reset_on_complete: true
    disable_on_complete: false

timers:
  t_make_your_choice_timer:
    start_value: 25
    end_value: 0
    direction: down
    control_events:
      - action: start
        event: mode_make_your_choice_hurryup_started
  t_make_your_choice_value_timer:
    start_value: 200
    end_value: 0
    direction: down
    tick_interval: 0.1s
    control_events:
      - action: start
        event: mode_make_your_choice_hurryup_started
      - action: stop
        event: drop_target_dt_upper_drop1_down

variable_player:
  mode_make_your_choice_hurryup_started:
    hurryup_value:
      int: 0
      action: set
  player_make_your_choice_hurryup_t_make_your_choice_value_timer_tick:
    hurryup_value_countdown:
      int: 75123 * device.timers.t_make_your_choice_value_timer.ticks
      action: set
  logicblock_acc_make_your_choice_qualify_hit{step==1}:
    score: (75123 * device.timers.t_make_your_choice_value_timer.ticks) * (current_player.pf_multiplier)
  logicblock_acc_make_your_choice_qualify_hit{step==2}:
    score: (75123 * device.timers.t_make_your_choice_value_timer.ticks) * (current_player.pf_multiplier)
  logicblock_acc_make_your_choice_qualify_hit{step==3}:
    score: (75123 * device.timers.t_make_your_choice_value_timer.ticks) * (current_player.pf_multiplier)
  make_your_choice_value_locked:
    hurryup_value:
      int: 75123 * device.timers.t_make_your_choice_value_timer.ticks
      action: set
  logicblock_acc_make_your_choice_qualify_complete:
    score: (100000 * device.timers.t_make_your_choice_value_timer.ticks) * (current_player.pf_multiplier)

counters:
  cnt_hurryup:
    starting_count: 0
    count_complete_value: 1
    start_enabled: true
    events_when_complete: make_your_choice_value_locked  
    count_events: drop_target_dt_upper_drop1_down

widgets:
  w_make_your_choice_UI:
    - type: Text
      text: 00:(player|make_your_choice_hurryup_t_make_your_choice_timer_tick)
      font_size: 50
      font_name: digitalclockfont
      color: red
      x: 8.5%
      y: 60.2%
      z: 7
    - type: rectangle
      width: 210
      height: 65
      x: 8.5%
      y: 61.5%
      z: 7
      corner_radius: 20
      corner_segments: 20
      color: black        
    - type: text
      text: Make Your Choice
      x: 8.5%
      y: 55.5%
      z: 7
      font_size: 25
      font_name: AeroMaticsDisplaRegular
      outline_color: black
      outline_width: 3
  w_hurryup_instructions_p1:
    - type: text
      text: Hit X Marks the Spot to Lock in Value
      x: 50%
      y: 45%
      z: 7
      font_size: 50
      font_name: AeroMaticsDisplaRegular    
      outline_color: black
      outline_width: 5
      animations:
        add_to_slide:
          - property: opacity
            value: 0
            duration: 0.5s
          - property: opacity
            value: 1
            duration: 0.5s
            repeat: true
  w_hurryup_instructions_p2:
    - type: text
      text: Cash in the Hurry-Up Value at the Orbits
      x: 50%
      y: 45%
      z: 7
      font_size: 50
      font_name: AeroMaticsDisplaRegular   
      outline_color: black
      outline_width: 5
      #animations:
      #  add_to_slide:
      #    - property: opacity
      #      value: 0
      #      duration: 1s
      #    - property: opacity
      #      value: 1
      #      duration: 1s
      #      repeat: true
  w_hurryup_value:
    - type: text
      #text: (player|make_your_choice_hurryup_t_make_your_choice_value_timer_tick) 
      text: (player|hurryup_value)
      number_grouping: true 
      x: 50%
      y: 35%
      z: 7
      font_size: 90
      font_name: Mustkill     
      outline_color: black
      outline_width: 7
      animations:
        add_to_slide:
          - property: opacity
            value: 0
            duration: 1s
          - property: opacity
            value: 1
            duration: 1s
            repeat: true
  w_hurryup_value_countdown:
    - type: text
      #text: (player|make_your_choice_hurryup_t_make_your_choice_value_timer_tick) 
      text: (player|hurryup_value_countdown)
      number_grouping: true 
      x: 50%
      y: 35%
      z: 7
      font_size: 90
      font_name: Mustkill     
      outline_color: black
      outline_width: 7

widget_player:
  mode_make_your_choice_hurryup_started: 
    w_make_your_choice_UI:
      slide: base_slide_main
      action: add
    w_hurryup_instructions_p1:
      slide: base_slide_main
      action: add
    w_hurryup_value_countdown:
      slide: base_slide_main
      action: add
  make_your_choice_value_locked:
    w_hurryup_value:
      slide: base_slide_main
      action: add
    w_hurryup_instructions_p1:
      action: remove
    w_hurryup_instructions_p2:
      slide: base_slide_main
      action: add

shots:
  shot_left_loop_hurryup:
    advance_events: logicblock_acc_make_your_choice_qualify_hit{step==1}
    switches: s_left_loop_bottom, s_left_loop_top
    profile: sp_make_your_choice_qualify
    show_tokens:
      leds: l_left_loop_arrow
    control_events:
      - events: mode_make_your_choice_hurryup_started
        state: 0
      - events: make_your_choice_value_locked
        state: 1
      - events: logicblock_acc_make_your_choice_qualify_hit{step==1}
        state: 0
  shot_inner_loop_hurryup:
    advance_events: logicblock_acc_make_your_choice_qualify_hit{step==3}
    switches: s_inner_loop
    profile: sp_make_your_choice_qualify
    show_tokens:
      leds: l_inner_loop_arrow
    control_events:
      - events: mode_make_your_choice_hurryup_started
        state: 0
      - events: make_your_choice_value_locked
        state: 1
      - events: logicblock_acc_make_your_choice_qualify_hit{step==3}
        state: 0
  shot_right_loop_hurryp:
    advance_events: logicblock_acc_make_your_choice_qualify_hit{step==2}    
    switches: s_right_loop_bottom, s_right_loop_top
    profile: sp_make_your_choice_qualify
    show_tokens:
      leds: l_right_loop_arrow
    control_events:
      - events: mode_make_your_choice_hurryup_started
        state: 0
      - events: make_your_choice_value_locked
        state: 1
      - events: logicblock_acc_make_your_choice_qualify_hit{step==2}
        state: 0

shot_profiles:
  sp_make_your_choice_qualify:
    advance_on_hit: false
    states:
      - name: hurryup_off
        show: "off"               # a default show to turn of the led. change if you want to do something on unlit shots
      - name: lit
        show: "sh_hurryup_ready"        # a default show to turn of the led. change if you want to do something on unlit shots
      - name: collected
        show: "sh_hurryup_collected"    # a default show to turn of the led. change if you want to do something on unlit shots
      - name: collected_hit
        show: "sh_hurryup_collected_hit"

event_player:
  mode_make_your_choice_hurryup_started: e_gi_dim|0.55s

shows:
  sh_hurryup_ready:
    - duration: -1
      shows:
        flash_token:
          show_tokens:
            color1: beartrap
            led: (leds)
          speed: 15
  sh_hurryup_collected_hit:
    - duration: 1s
      shows:
        flash_token:
          show_tokens:
            color1: razorwire
            led: (leds)
          speed: 3
          loops: 2
          priority: 170
  sh_hurryup_collected:
    - duration: 1s
      shows:
        flash_token_2:
          show_tokens:
            color1: beartrap
            led: starpost
          speed: 15
          loops: 0
          priority: 170
  #sh_make_yourchoice_end:
  #  - duration: -1
  #    lights:
  #      (leds): off

show_player:
  mode_make_your_choice_hurryup_started:
      top_drop_chase:
        loops: -1
        speed: 14
        show_tokens:
          color1: beartrap
      gi_die_hurryup_intro:
        loops: 0
        speed: 45
      mode_fail:
        loops: 0
        speed: 30
  e_gi_dim:
      gi_on:
        show_tokens:
          color1: 8f8f8f    
  make_your_choice_value_locked:
      top_drop_chase:
        loops: -1
        show_tokens:
          color1: off
      die_hurryup_explode:
        loops: 0
        speed: 30
      sh_hurryup_ready:
        show_tokens:
          leds: orbit
  logicblock_acc_make_your_choice_qualify_hit{step==1}:
      sh_hurryup_collected_hit:
        show_tokens:
          leds: l_left_loop_arrow
        loops: 0
      sh_hurryup_collected:
        loops: 0
  logicblock_acc_make_your_choice_qualify_hit{step==2}:
      sh_hurryup_collected_hit:
        show_tokens:
          leds: l_right_loop_arrow
        loops: 0
      sh_hurryup_collected:
        loops: 0
  logicblock_acc_make_your_choice_qualify_hit{step==3}:
      sh_hurryup_collected_hit:
        show_tokens:
          leds: l_inner_loop_arrow
        loops: 0
      sh_hurryup_collected:
        loops: 0

sound_player:
  mode_make_your_choice_hurryup_started:
    BaseMusic:
      action: stop    
    LiveOrDieHurryup:
      priority: 202
      block: true
      action: play
  logicblock_acc_make_your_choice_qualify_hit{step==1}:
    MakeYourChoice1:
      priority: 200
      block: true
      action: play
  logicblock_acc_make_your_choice_qualify_hit{step==2}:
    MakeYourChoice2:
      priority: 200
      block: true
      action: play
  logicblock_acc_make_your_choice_qualify_hit{step==3}:
    MakeYourChoice3:
      priority: 200
      block: true
      action: play
  mode_make_your_choice_hurryup_stopping:
    LiveOrDieHurryup:
      action: stop

