#config_version=6                 
mode:
  start_events: startmode_make_your_choice_hurryup
  stop_events: mode_make_your_choice_hurryup_complete, stop_mode_make_your_choice_hurryup, ball_ended, ball_will_end, player_make_your_choice_hurryup_t_make_your_choice_timer_tick{value < 1}
  priority: 120

  # Spell D-I-E / S-A-W (3 drop target bank) in sequential order to start this hurry up mode.
  # hit X marks the spot to lock in value.
  # orbits the remaining duration to cash in value
timers:
  t_make_your_choice_timer:
    start_value: 20
    end_value: 0
    direction: down
    control_events:
      - action: start
        event: mode_make_your_choice_hurryup_started
  t_make_your_choice_value_timer:
    start_value: 200
    end_value: 0
    direction: down
    tick_interval: 0.1s
    control_events:
      - action: start
        event: mode_make_your_choice_hurryup_started

variable_player:
  t_make_your_choice_timer:
    t_make_your_choice_timer:
      int: device.timers.t_make_your_choice_timer.ticks_remaining
      action: set

counters:
  cnt_hurryup:
    starting_count: 0
    count_complete_value: 1
    start_enabled: true
    events_when_complete: make_your_choice_value_locked  
    count_events: drop_target_dt_upper_drop1_down

widgets:
  make_your_choice_UI:
    - type: Text
      text: 00:(player|make_your_choice_hurryup_t_make_your_choice_timer_tick)
      font_size: 50
      font_name: digitalclockfont
      color: red
      x: 8.5%
      y: 83.2%
      z: 7
    - type: rectangle
      width: 210
      height: 65
      x: 8.5%
      y: 84.5%
      z: 7
      corner_radius: 20
      corner_segments: 20
      color: black        
    - type: rectangle
      width: 342
      height: 23
      x: 8.5%
      y: 90
      z: 7
      color: black
      corner_radius: 10
      corner_segments: 10
    - type: text
      text: Make Your Choice
      x: 8.5%
      y: 78.5%
      z: 7
      font_size: 25
      font_name: Skilt Gothic W04 Thin     
      outline_color: black
      outline_width: 5
widget_player:
  mode_make_your_choice_hurryup_started: 
    make_your_choice_UI:
      slide: base_slide_main
      action: add

show_player:
  mode_make_your_choice_hurryup_started:
      top_drop_chase:
        loops: -1
        speed: 20
        show_tokens:
          color1: beartrap
  drop_target_dt_upper_drop1_down:
      top_drop_chase:
        loops: -1
        show_tokens:
          color1: off