#config_version=6                 
mode:
  start_events: selection_mode_the_key_to_freedom_selected
  stop_events: stop_mode_the_key_to_freedom, ball_ended, ball_will_end
  priority: 181


counters:
  cnt_key_to_freedom_p1_counter:
    starting_count: 0
    count_complete_value: 16
    enable_events: mode_the_key_to_freedom_started
    disable_events: key_to_freedom_p1_complete #, logicblock_razorwire_phase2_updated{enabled==True}
    start_enabled: true
#    persist_state: true
#    reset_on_complete: false
    events_when_complete: key_to_freedom_p1_complete  
    count_events: sw_lower_drop_target

variable_player:
  counter_cnt_key_to_freedom_p1_counter_hit:
    key_to_freedom_p1_counter:
      action: set
      int: (count)*120
      # should be for 5 hits on center drops to bash zep

widgets:
   w_razorwireUI:
    - type: image
      image: hacksawUI
      opacity: 1.0
      y: 1
      x: 1
      z: 2
      anchor_x: left
      anchor_y: bottom
    - type: text
      text: (score)
      number_grouping: true
      y: 16
      x: 25
      z: 2
      font_size: 36
      anchor_x: left
      anchor_y: bottom
      font_name: TrajanProRegular
      color: 65fe08
    - type: rectangle
      width: 0
      height: 45
      x: 25%
      y: 180
      z: 2
      anchor_x: left
      corner_radius: 10
      corner_segments: 10
      color: beartrap
      animations:
        player_cnt_key_to_freedom_p1_counter:
         - property: width
           value: (value)           
    - type: rectangle
      width: 685
      height: 46
      x: 50%
      y: 180
      z: 2
      color: black
      corner_radius: 10
      corner_segments: 10
    # - type: Text
    #   text: 00:(player|razorwire_60s_timer_tick)
    #   font_size: 100
    #   font_name: digitalclockfont
    #   color: red
    #   x: 50%
    #   y: 83.2%
    #   z: 2
    # - type: rectangle
    #   width: 420
    #   height: 130
    #   x: 50%
    #   y: 84.5%
    #   z: 2
    #   corner_radius: 20
    #   corner_segments: 20
    #   color: black     