#config_version=6                 
mode:
  start_events: selection_mode_thekeytofreedom_selected
  stop_events: stop_mode_the_key_to_freedom, ball_ended, ball_will_end
  priority: 181

sequences:
  thekeytofreedom:
    events:
      - key_to_freedom_p1_complete
      - key_to_freedom_p2_complete
      - key_to_freedom_p3_complete
      - key_to_freedom_p4_complete
    reset_on_complete: false
#    persist_state: true
    disable_events: mode_the_key_to_freedom_complete
    events_when_complete: mode_the_key_to_freedom_complete, stop_mode_the_key_to_freedom

counters:
  cnt_key_to_freedom_p1_counter:
    starting_count: 0
    count_complete_value: 10
    enable_events: mode_the_key_to_freedom_started
    disable_events: key_to_freedom_p1_complete
    start_enabled: true
#    persist_state: true
#    reset_on_complete: false
    events_when_complete: key_to_freedom_p1_complete  
    count_events: sw_standup

variable_player:
  counter_cnt_key_to_freedom_p1_counter_hit:
    key_to_freedom_p1_counter:
      action: set
      int: (count)*69
      # 10 hits to break off toilet lid
  counter_cnt_key_to_freedom_p2_counter_hit:
    key_to_freedom_p2_counter:
      action: set
      int: (count)*12
      # 50 switch hits to attack zep
  counter_cnt_key_to_freedom_p3_counter_hit:
    key_to_freedom_p3_counter:
      action: set
      int: (count)*240
      # 5 puzzle pieces to finish off zep
  logicblock_thekeytofreedom_hit{step==1}:
    score: 7500000
  logicblock_thekeytofreedom_hit{step==2}:
    score: 8500000
  logicblock_thekeytofreedom_hit{step==3}:
    score: 9500000

slides:
  mode_thekeytofreedom01:
    widgets:
    - type: video
      video: mode_thekeytofreedom01
      width: 1366
      height: 768     
  mode_thekeytofreedom02:
    widgets:
    - type: video
      video: mode_thekeytofreedom02
      width: 1366
      height: 768     
  mode_thekeytofreedom03:
    widgets:
    - type: video
      video: mode_thekeytofreedom03
      width: 1366
      height: 768     

widgets:
   w_thekeytofreedomUI:
    - type: image
      image: hacksawUI
      opacity: 1.0
      y: 1
      x: 1
      z: 2
      anchor_x: left
      anchor_y: bottom
    - type: text
      text: (score)
      number_grouping: true
      y: 16
      x: 25
      z: 2
      font_size: 36
      anchor_x: left
      anchor_y: bottom
      font_name: TrajanProRegular
      color: beartrap
    - type: rectangle
      width: 0
      height: 45
      x: 25%
      y: 180
      z: 3
      anchor_x: left
      corner_radius: 10
      corner_segments: 10
      color: beartrap
      animations:
        player_key_to_freedom_p1_counter:
         - property: width
           value: (value)           
    - type: rectangle
      width: 685
      height: 46
      x: 50%
      y: 180
      z: 2
      color: black
      corner_radius: 10
      corner_segments: 10

widget_player:
 logicblock_thekeytofreedom_updated{value==0}: 
   w_thekeytofreedomUI:
     slide: mode_thekeytofreedom01
     action: add    
 logicblock_thekeytofreedom_updated{value==1}: 
   w_thekeytofreedomUI:
     slide: mode_thekeytofreedom02
     action: add    
 logicblock_thekeytofreedom_updated{value==2}: 
   w_thekeytofreedomUI:
     slide: mode_thekeytofreedom03
     action: add    

slide_player:
  mode_the_key_to_freedom_started: 
    mode_thekeytofreedom01:
      priority: 400
#      expire: 8s
  logicblock_thekeytofreedom_updated{value==1}:
    mode_thekeytofreedom02:
      priority: 401
#      expire: 120s
    mode_thekeytofreedom01:
     action: remove
  logicblock_thekeytofreedom_updated{value==2}:
    mode_thekeytofreedom03:
      priority: 401
#      expire: 120s
    mode_thekeytofreedom02:
     action: remove