#config_version=6                 
mode:
  start_events: selection_mode_reversebeartrap_selected
  stop_events: stop_mode_reversebeartrap, ball_ended, ball_will_end, player_reversebeartrap_120s_reversebeartrap_timer_tick{value < 1}
 
sequence_shots:
  leftloop_leftramp:
    switch_sequence: s_left_loop_bottom, s_left_loop_top, s_enter_left_ramp, s_left_ramp_score_bottom, s_left_ramp_score_top
    sequence_timeout: 6s
  rightramp_rightloop:
    switch_sequence: s_right_ramp_score_bottom, s_right_ramp_score_top, s_right_loop_bottom, s_right_loop_top
    sequence_timeout: 6s 
 
 
sequences:
  reversebeartrap:
    events:
      - leftloop_leftramp_hit
      - rightramp_rightloop_hit
      - shot_left_standup_hit
      - shot_left_standup_rightramp_hit
      - shot_right_standup_rightramp_hit
      - shot_right_standup_hit
      - upper_drop_target_hit
    reset_on_complete: false
    events_when_complete: mode_reversebeartrap_complete, stop_mode_reversebeartrap

timers:
  120s_reversebeartrap_timer:
    start_value: 129
    end_value: 0
    direction: down
    control_events:
      - action: start
        event: mode_reversebeartrap_started

#counters:
#  razorwire_spinner_counter:
#    starting_count: 0
#    count_complete_value: 30
#    enable_events: enable_qualify
#    disable_events: disable_qualify
#    start_enabled: true
#    reset_on_complete: false
#    events_when_complete: mode_razorwire_complete, stop_mode_razorwire
#    count_events: spinner_hit
    

variable_player:
  logicblock_reversebeartrap_hit{step==1}:
    score: 500000
  logicblock_reversebeartrap_hit{step==2}:
    score: 1000000
  logicblock_reversebeartrap_hit{step==6}:
    score: 2000000
  mode_reversebeartrap_complete:
    score: 5000000
       
  timer_your_timer_tick:
    120s_reversebeartrap_timer:
      int: device.timers.your_timer.ticks_remaining
      action: set     
 
slides:
  reversebeartrapvideo:
    widgets:
    - type: video
      video: reversebeartrapvideo 
      width: 1366
      height: 768      
      
  reversebeartrapUI:
   widgets:
#    - type: Text
#      text: Shoot The Spinners!
#      font_name: TrajanProRegular
#      font_size: 75
#      color: 65fe08
    - type: image
      image: hacksawUI
      opacity: 0.5
      y: 1
      x: 1
      anchor_x: left
      anchor_y: bottom
    - type: text
      text: (score)
      number_grouping: true
      y: 16
      x: 25
      font_size: 36
      anchor_x: left
      anchor_y: bottom
      font_name: TrajanProRegular
      color: F5FBFF
    - type: Text
      text: (player|reversebeartrap_120s_reversebeartrap_timer_tick) Seconds Left
      font_size: 55
      font_name: TrajanProRegular
      color: E5F3FD
      y: 90%

#    - type: Text
#      text: 00:(player|reversebeartrap_120s_reversebeartrap_timer_tick)
#      font_size: 100
#      font_name: digitalclockfont
#      color: red
#      x: 50%
#      y: 83.2%
#    - type: rectangle
#      width: 420
#      height: 130
#      x: 50%
#      y: 84.5%
#      corner_radius: 20
#      corner_segments: 20
#      color: black
      
    - type: Text
# work on displaying the count of spins
      text: "To Find the Key:"
      font_size: 42
      font_name: TrajanProRegular
      color: AECCE4
      x: 275
      y: 75%
      
    - type: Text
      text: "- Combo the Left Loop into the Left Ramp"
      font_size: 32
      font_name: TrajanProRegular
      color: BDD5E7
      x: 480
      y: 68%
      
    - type: Text
      text: "- Combo the Right Ramp into the Right Loop"
      font_size: 32
      font_name: TrajanProRegular
      color: BDD5E7
      x: 510
      y: 62%
      
    - type: Text
      text: "- Hit the 4 Stand-ups in Order Left to Right"
      font_size: 32
      font_name: TrajanProRegular
      color: BDD5E7
      x: 500
      y: 56%
      
    - type: Text
      text: "- X marks the Spot to Find the Key"
      font_size: 32
      font_name: TrajanProRegular
      color: BDD5E7
      x: 408
      y: 50%      
      
    - type: Text
      text: "You Have 120 Seconds To Find The Key & Earn Your Salvation"
      color: D1E5F4
      font_name: TrajanProRegular
      font_size: 35
      y: 90
      animations:
       pre_show_slide:
        - property: opacity
          value: 0
          duration: 1s
        - property: opacity
          value: 1
          duration: 1s
          repeat: true
    - type: image
      image: reversebeartrap
      opacity: 0.45
#      width: 1366
#      height: 768 
#    transition:
#     type: fade
#     duration: 0.2s

widgets:
   rbt_shot_update1:
    - type: Text
      text: X
      color: ad1400
      x: 4%
      y: 68%
      font_size: 50
      font_name: TrajanProRegular
   rbt_shot_update2:
    - type: Text
      text: X
      color: ad1400
      x: 4%
      y: 62%
      font_size: 50
      font_name: TrajanProRegular
   rbt_shot_update6:
    - type: Text
      text: X
      color: ad1400
      x: 4%
      y: 56%
      font_size: 50
      font_name: TrajanProRegular
    
 
widget_player:
 logicblock_reversebeartrap_hit{step==1}: 
  rbt_shot_update1:
    slide: reversebeartrapUI
 logicblock_reversebeartrap_hit{step==2}: 
  rbt_shot_update2:
    slide: reversebeartrapUI
 logicblock_reversebeartrap_hit{step==6}: 
  rbt_shot_update6:
    slide: reversebeartrapUI
   

slide_player:
  mode_reversebeartrap_started: 
    reversebeartrapvideo:
      priority: 500
      expire: 8s
  slide_reversebeartrapvideo_removed: 
    reversebeartrapUI:
      priority: 400
      expire: 126.5s
  logicblock_reversebeartrap_hit{step==6}:
    XMarksTheSpotVideo:
      priority: 406
      expire: 2.1s      
  
#  logicblock_reversebeartrap_hit:
#    ShotUpdated:
#      priority: 400
      
