#config_version=6

mode:
  start_events: ball_starting
  stop_events: game_ending
  priority: 100

sound_pools:
  razorwirepops:
    load: preload
    type: random
    track: sfx
    sounds:
      - UpPops1
      - UpPops2
      - UpPops3
      - UpPops4

  drillchairpops:
    load: preload
    type: random
    track: sfx
    sounds:
      - LowerPops1
      - LowerPops2
      - LowerPops3
      - LowerPops4
      - LowerPops5
      - LowerPops6
      - LowerPops7
      - LowerPops8
      - LowerPops9
      - LowerPops10
      - LowerPops11
      - LowerPops12
      - LowerPops13
      - LowerPops14
      - LowerPops15
      - LowerPops16
      - LowerPops17

  lowerdropsaudio:
    load: preload
    type: random
    track: sfx
    sounds:
      - TapeCassetteDrop-Sound1
      - TapeCassetteDrop-Sound2
      - TapeCassetteDrop-Sound3
      - TapeCassetteDrop-Sound4
      - TapeCassetteDrop-Sound5
      - TapeCassetteDrop-Sound6
      - TapeCassetteDrop-Sound7
      - TapeCassetteDrop-Sound8
      - TapeCassetteDrop-Sound9
      - TapeCassetteDrop-Sound10
      
  loopsaudio:
    load: preload
    type: random
    track: sfx
    sounds:
      - OrbitWoosh
      - OrbitWoosh4
      - OrbitWoosh6
      
  slingsaudio:
    load: preload
    type: random
    track: sfx
    sounds:
      - LSling1
      - LSling2
      - LSling3
      - LSling4
      - LSling5
      - LSling6
      - RSling1
      - RSling2
      - RSling3
 
  standupaudio:
    load: preload
    type: random
    track: sfx
    sounds:
      - DropsCameraShutter1
      - DropsCameraShutter2
      - DropsCameraShutter3
      - DropsCameraShutter4
      - DropsCameraShutter5
  startbutton:
    load: preload
    type: random
    track: sfx
    sounds:
      - LowPainTolerance
      - FlipperFingers
#      - MakeFunOfMyMask
      - PlungeTheBall
      - RiseAndShine
      - YouMayBegin
  randomswitch:
    load: preload
    type: random
    track: sfx
    sounds:
      - SawOffFoot
      - RampsGranted
      - ProveToMe
      - PatheticScore
      - Lungs
      - Mistakes
      - Lube
      - Lies
      - LifePurpose
      - ISeeYou
      - EndItAllNow
      - ExistanceForGranted      
 
sound_player:
  mode_music_player_started:
    HelloZeppPt1:
      action: stop
  mode_game_stopping:
    initials:
      action: stop
  mode_high_score_started:
    BaseMusic:
      action: stop

  ball_save_default_saving_ball:
    HeHelpedMe:
      action: play
  ball_ending{current_player.ball==3}:
    GameOver:
      action: play

  mode_base_started{current_player.ball == 1 and player==1}:
    1playerGame:
      action: play
  mode_base_started:
    startbutton:
      delay: 2.5s
      action: play
      events_when_played: Que_BaseMusic
  Que_BaseMusic:
    BaseMusic:
      delay: 5s
      action: play
      loops: -1
  # mode_bonus_stopped{current_player.ball == 1 or current_player.ball == 2}:
  #   BaseMusic:
  #     delay: 5s
  #     action: play
  #     loops: -1

  mode_base_stopped:
    BaseMusic:
      action: stop
      events_when_played: StopModeQualifiedShootScoop
  StopModeQualifiedShootScoop:
    ModeQualifiedShootScoop:
      action: stop

  mode_selection_mode_started:
    BaseMusic:
      action: stop  
    ModeQualifiedShootScoop:
      action: stop

  player_adding{game.num_players==2}:
    2PlayerGame:
      action: play  
    startbutton:
      delay: 2.5s
      action: play      
  player_adding{game.num_players==3}:
    3PlayerGame:
      action: play  
    startbutton:
      delay: 2.5s
      action: play      
  player_adding{game.num_players==4}:
    4PlayerGame:
      action: play   
    startbutton:
      delay: 2.5s
      action: play  
    
  drop_target_bank_upper_dropbank_down:
    SingleDropGlassBreak:
      action: play 
      
  sw_top_pops:
    razorwirepops:
      action: play
      block: true
  sw_bottom_pops:
    drillchairpops:
      action: play
      block: true
  sw_slingshot:
    slingsaudio:
      action: play
      block: true    
  spinner_spinner_hit:
    Spinner3:
      action: play
      block: true
  sw_standup:
    standupaudio:
      action: play
      block: true
  ssh_left_orbit_hit:
    LeftOrbit:
      action: play
      block: true
  ssh_right_orbit_hit:
    RightOrbit:
      action: play
      block: true
  s_right_outlane_active:
    TortureScream:
      action: play
      block: true
  s_left_outlane_active:
    TortureScream:
      action: play
      block: true
  #shot_left_outlane_hit{state=="lit"}:
  #  StillAlive:
  #    action: play
  #    block: true
  #shot_right_outlane_hit{state=="lit"}:
  #  StillAlive:
  #    action: play
  #    block: true

  sw_right_return_lane:
    Gore_Neck_Break:
      action: play
      block: true
  sw_lower_drop_target:
    lowerdropsaudio:
      action: play
      block: true
    
  logicblock_random_switch_hit{hits==29}:  
    randomswitch:
      action: play   
  logicblock_random_switch_hit{hits==58}:  
    randomswitch:
      action: play
  logicblock_random_switch_hit{hits==87}:  
    randomswitch:
      action: play
  logicblock_random_switch_hit{hits==116}:  
    randomswitch:
      action: play
  logicblock_random_switch_hit{hits==145}:  
    randomswitch:
      action: play
  logicblock_random_switch_hit{hits==174}:  
    randomswitch:
      action: play
  logicblock_random_switch_hit{hits==203}:  
    randomswitch:
      action: play
  logicblock_random_switch_hit{hits==232}:  
    randomswitch:
      action: play
  logicblock_random_switch_hit{hits==261}:  
    randomswitch:
      action: play
  logicblock_random_switch_hit{hits==290}:  
    randomswitch:
      action: play
  logicblock_random_switch_hit{hits==319}:  
    randomswitch:
      action: play
  logicblock_random_switch_hit{hits==348}:  
    randomswitch:
      action: play
  logicblock_random_switch_hit{hits==377}:  
    randomswitch:
      action: play
  logicblock_random_switch_hit{hits==406}:  
    randomswitch:
      action: play
  logicblock_random_switch_hit{hits==435}:  
    randomswitch:
      action: play      
  logicblock_random_switch_hit{hits==464}:  
    randomswitch:
      action: play  
  logicblock_random_switch_hit{hits==493}:  
    randomswitch:
      action: play  
  logicblock_random_switch_hit{hits==522}:  
    randomswitch:
      action: play  
  logicblock_random_switch_hit{hits==551}:  
    randomswitch:
      action: play  
  logicblock_random_switch_hit{hits==580}:  
    randomswitch:
      action: play  
  logicblock_random_switch_hit{hits==609}:  
    randomswitch:
      action: play  
  logicblock_random_switch_hit{hits==638}:  
    randomswitch:
      action: play  
  logicblock_random_switch_hit{hits==667}:  
    randomswitch:
      action: play  
  logicblock_random_switch_hit{hits==696}:  
    randomswitch:
      action: play  
  logicblock_random_switch_hit{hits==725}:  
    randomswitch:
      action: play  

 # razorwire mode
  mode_razorwire_complete:
    trapcomplete:
      action: play
    RWModeStart:
      action: stop 
    BaseMusic:
      delay: 10s
      action: play
      loops: -1   
  player_razorwire_60s_timer_tick{value < 1}:
    RazorWireFail:
      action: play
  mode_razorwire_stopped:
    BaseMusic:
      delay: 3s
      action: play
      loops: -1 
      
 # drillchair mode     
  mode_drillchair_complete:
    trapcomplete:
      action: play
    drillchair:
      action: stop
    DrillChairModeStart:
      action: stop
    BaseMusic:
      delay: 10s
      action: play
      loops: -1      
  mode_drillchair_stopped:
    DrillChairModeStart:
      action: stop
    BaseMusic:
      delay: 3s
      action: play
      loops: -1      

# reversebeartrap mode
  mode_reversebeartrap_complete:
    trapcomplete:
      action: play
    ReverseBearTrapModeStart:
      action: stop
    BaseMusic:
      delay: 10s
      action: play
      loops: -1      
  player_reversebeartrap_120s_reversebeartrap_timer_tick{value < 1}:
    ReverseBearTrapFail:
      action: play
  mode_reversebeartrap_stopped:
    BaseMusic:
      delay: 3s
      action: play
      loops: -1      

# quadshotgun mode  
  mode_quadshotgun_complete:
    trapcomplete:
      action: play
    QuadShotgunModeStart:
      action: stop
    BaseMusic:
      delay: 10s
      action: play
      loops: -1      
  player_quadshotgun_quadshotgun_60s_timer_tick{value == 1}:
    QuadShotgunFail:
      action: play
  mode_quadshotgun_stopped:
    BaseMusic:
      delay: 3s
      action: play
      loops: -1
      
# zeptest mode
  mode_zeptest_complete:
    trapcomplete:
      action: play
    ZepsTestModeStart:
      action: stop
    BaseMusic:
      delay: 10s
      action: play
      loops: -1           
  mode_zeptest_stopped:
    BaseMusic:
      delay: 3s
      action: play
      loops: -1
 
# flammable jelly mode      
  mode_flammablejelly_complete:
    trapcomplete:
      action: play  
    FlammableJellyModeStart:
      action: stop
    BaseMusic:
      delay: 10s
      action: play
      loops: -1             
  player_flammablejelly_60s_flammablejelly_timer_tick{value < 1}:
    FlammableJellyFail:
      action: play
  mode_flammablejelly_stopped:
    BaseMusic:
      delay: 3s
      action: play
      loops: -1

  sg_saw_qualify_subtract_hit{device.counters.cnt_saw_qualify.value==1}:
    SawLetterNegative:
      action: play   
  sg_saw_qualify_subtract_hit{device.counters.cnt_saw_qualify.value==2}:
    SawLetterNegative:
      action: play

# stop all mode music at beginning of mode_bonus
  mode_bonus_started:
    QuadShotgunModeStart:
      action: stop
    drillchair:
      action: stop
    FlammableJellyModeStart:
      action: stop
    RWModeStart:
      action: stop
    ReverseBearTrapModeStart:
      action: stop
    ZepsTestModeStart:
      action: stop      
    BaseMusic:
      action: stop