#config_version=6

mode:
  start_events: ball_starting
  stop_events: game_ending
  priority: 200

sound_pools:
  razorwirepops:
    load: preload
    type: random
    track: sfx
    sounds:
      - UpPops1
      - UpPops2
      - UpPops3
      - UpPops4

  drillchairpops:
    load: preload
    type: random
    track: sfx
    sounds:
      - LowerPops1
      - LowerPops2
      - LowerPops3
      - LowerPops4
      - LowerPops5
      - LowerPops6
      - LowerPops7
      - LowerPops8
      - LowerPops9
      - LowerPops10
      - LowerPops11
      - LowerPops12
      - LowerPops13
      - LowerPops14
      - LowerPops15
      - LowerPops16
      - LowerPops17

  lowerdropsaudio:
    load: preload
    type: random
    track: sfx
    sounds:
      - TapeCassetteDrop-Sound1
      - TapeCassetteDrop-Sound2
      - TapeCassetteDrop-Sound3
      - TapeCassetteDrop-Sound4
      - TapeCassetteDrop-Sound5
      - TapeCassetteDrop-Sound6
      - TapeCassetteDrop-Sound7
      - TapeCassetteDrop-Sound8
      - TapeCassetteDrop-Sound9
      - TapeCassetteDrop-Sound10
      
  loopsaudio:
    load: preload
    type: random
    track: sfx
    sounds:
      - OrbitWoosh
      - OrbitWoosh4
      - OrbitWoosh6
      
  slingsaudio:
    load: preload
    type: random
    track: sfx
    sounds:
      - LSling1
      - LSling2
      - LSling3
      - LSling4
      - LSling5
      - LSling6
      - RSling1
      - RSling2
      - RSling3
 
  standupaudio:
    load: preload
    type: random
    track: sfx
    sounds:
      - DropsCameraShutter1
      - DropsCameraShutter2
      - DropsCameraShutter3
      - DropsCameraShutter4
      - DropsCameraShutter5
  startbutton:
    load: preload
    type: random_force_next
    track: voice
    simultaneous_limit: 1
    stealing_method: newest
    sounds:
      - LowPainTolerance
      - FlipperFingers
#      - MakeFunOfMyMask
      - PlungeTheBall
      - RiseAndShine
      - YouMayBegin
      - ReBirth
      - TheDevil
  randomswitch:
    load: preload
    type: random_force_next
    track: voice
    sounds:
      - SawOffFoot
      - RampsGranted
      - ProveToMe
      - PatheticScore
      - Lungs
      - Mistakes
      - Lube
      - Lies
      - LifePurpose
      - ISeeYou
      - EndItAllNow
      - ExistanceForGranted    
      - CardsYourDealt
      - Alive
# items collected      
  antidote_collected:
    load: preload
    type: random_force_next
    track: voice
    sounds:
      - Antidote6
      - Antidote1
      - Antidote2
      - Antidote3
      - Antidote4
      - Antidote5
  bathtub_collected: 
    load: preload
    type: random_force_next
    track: voice
    sounds:
      - Bathtub6
      - Bathtub1
      - Bathtub2
      - Bathtub3
      - Bathtub4
      - Bathtub5
  candle_collected:     
    load: preload
    type: random_force_next
    track: voice
    sounds:
      - Candle6
      - Candle1
      - Candle2
      - Candle3
      - Candle4
      - Candle5  
  gears_collected:  
    load: preload
    type: random_force_next
    track: voice
    sounds:
      - Gears6
      - Gears1
      - Gears2
      - Gears3
      - Gears4
      - Gears5  
  hacksaw_collected:
    load: preload
    type: random_force_next
    track: voice
    sounds:
      - Hacksaw6
      - Hacksaw1
      - Hacksaw2
      - Hacksaw3
      - Hacksaw4
      - Hacksaw5  
  handgun_collected:
    load: preload
    type: random_force_next
    track: voice
    sounds:
      - Gun6
      - Gun1
      - Gun2
      - Gun3
      - Gun4
      - Gun5
  key_collected:
    load: preload
    type: random_force_next
    track: voice
    sounds:
      - Key6
      - Key1
      - Key2
      - Key3
      - Key4
      - Key5
  taperecorder_collected:
    load: preload
    type: random_force_next
    track: voice
    sounds:
      - TapeRecorder6
      - TapeRecorder1
      - TapeRecorder2
      - TapeRecorder3
      - TapeRecorder4
      - TapeRecorder5
  hacksaw_mb_start:
    load: preload
    type: random_force_next
    track: voice
    sounds:
      - HacksawMultiballStart1
      - HacksawMultiballStart2   
  ModeLit:
    load: preload
    type: random_force_next
    track: voice
    sounds:
      - ModeIsLit1
      - ModeIsLit2
      - ModeIsLit3
      - ModeIsLit4
      - ModeIsLit5
      - ModeIsLit6
      - ModeIsLit7
      - ModeIsLit8
      - ModeIsLit9
      - ModeIsLit10
  PuzzlePiece:
    load: preload
    type: random_force_next
    track: voice
    sounds:
      - PuzzlePiece1
      - PuzzlePiece2
      - PuzzlePiece3
      - PuzzlePiece4
      - PuzzlePiece5
      - PuzzlePiece6
  Jackpot:
    load: preload
    type: random_force_next
    track: voice
    sounds:
      - Jackpot1
      - Jackpot2
      - Jackpot3
      - Jackpot4
      - Jackpot5
  LockIsLit:
    load: preload
    type: random_force_next
    track: voice
    sounds:
      - LockIsLit1
      - LockIsLit2
      - LockIsLit3
      - LockIsLit4
  Ball1Locked:
    load: preload
    type: random_force_next
    track: voice
    sounds:
      - Ball1Locked1
      - Ball1Locked2
  Ball2Locked:
    load: preload
    type: random_force_next
    track: voice
    sounds:
      - Ball2Locked1
      - Ball2Locked2
      - Ball2Locked3
  SuperJackpot:
    load: preload
    type: random_force_next
    track: voice
    sounds:
      - SuperJackpot
      - SuperJackpot3
      - SuperJackpot5
  ActionButton:
    load: preload
    type: random_force_next
    track: voice
    sounds:
      - AB1
      - AB2
      - AB3
      - AB4
      - AB5
      - AB6
      - AB7
      - AB8
      - AB9
      - AB10
      - AB11
      - AB12
      - AB13
      - AB14
      - AB15

sound_player:
  mode_music_player_started:
    Shithole:
      action: stop
  mode_game_stopping:
    initials:
      action: stop
  mode_high_score_started:
    BaseMusic:
      action: stop

  ball_save_default_saving_ball:
    HeHelpedMe:
      action: play
  ball_will_end{current_player.ball==3}:
    GameOver:
      action: play
#turn puzzle music off if drain during mode
  e_puzzle_music_off1:
    PuzzlePieceHurryUp:
      action: stop
  e_puzzle_music_off2:
    PuzzlePieceHurryUp:
      action: stop

  mode_base_started{current_player.ball == 1 and player==1 and is_extra_ball==False}:
    1playerGame:
      action: play
  mode_base_started:
    startbutton:
      delay: 2.5s
      action: play
      events_when_played: Que_BaseMusic
  Que_BaseMusic:
    BaseMusic:
      delay: 5s
      action: play
      loops: -1
  # mode_bonus_stopped{current_player.ball == 1 or current_player.ball == 2}:
  #   BaseMusic:
  #     delay: 5s
  #     action: play
  #     loops: -1

  mode_base_stopped:
    BaseMusic:
      action: stop
      events_when_played: StopModeQualifiedShootScoop
  StopModeQualifiedShootScoop:
    ModeQualifiedShootScoop:
      action: stop

  mode_selection_mode_started:
    BaseMusic:
      action: stop  
    ModeQualifiedShootScoop:
      action: stop

  player_adding{game.num_players==2}:
    #2PlayerGame:
    #  action: play  
    startbutton:
      delay: 2.5s
      action: play      
  player_adding{game.num_players==3}:
    #3PlayerGame:
    #  action: play  
    startbutton:
      delay: 2.5s
      action: play      
  player_adding{game.num_players==4}:
    #4PlayerGame:
    #  action: play   
    startbutton:
      delay: 2.5s
      action: play  
    
  drop_target_bank_upper_dropbank_down:
    SingleDropGlassBreak:
      action: play 
      
  sw_top_pops:
    razorwirepops:
      action: play
      block: true
  sw_bottom_pops:
    drillchairpops:
      action: play
      block: true
  sw_slingshot:
    slingsaudio:
      action: play
      block: true    
  spinner_spinner_hit:
    Spinner3:
      action: play
      block: true
  sw_standup:
    standupaudio:
      action: play
      block: true
  ssh_left_orbit_hit:
    LeftOrbit:
      action: play
      block: true
  ssh_right_orbit_hit:
    RightOrbit:
      action: play
      block: true
  sw_110:
    slingsaudio:
      action: play
      block: true   
  shot_left_outlane_hit{state=="ball_save_not_ready"}:
    #TortureScream:
    refined_billy_laugh:
      action: play
      block: true
  shot_right_outlane_hit{state=="ball_save_not_ready"}:
    #TortureScream:
    refined_billy_laugh:
      action: play
      block: true
  shot_left_outlane_hit{state=="lit"}:
    StillAlive:
      action: play
      block: true
  shot_right_outlane_hit{state=="lit"}:
    StillAlive:
      action: play
      block: true

  sw_right_return_lane:
    Gore_Neck_Break:
      action: play
      block: true
  sw_lower_drop_target:
    lowerdropsaudio:
      action: play
      block: true
    
  logicblock_random_switch_hit{hits==75}:  
    randomswitch:
      action: play   
  logicblock_random_switch_hit{hits==150}:  
    randomswitch:
      action: play
  logicblock_random_switch_hit{hits==225}:  
    randomswitch:
      action: play
  logicblock_random_switch_hit{hits==300}:  
    randomswitch:
      action: play
  logicblock_random_switch_hit{hits==375}:  
    randomswitch:
      action: play
  logicblock_random_switch_hit{hits==450}:  
    randomswitch:
      action: play
  logicblock_random_switch_hit{hits==525}:  
    randomswitch:
      action: play
  logicblock_random_switch_hit{hits==600}:  
    randomswitch:
      action: play
  logicblock_random_switch_hit{hits==675}:  
    randomswitch:
      action: play
  logicblock_random_switch_hit{hits==750}:  
    randomswitch:
      action: play
  logicblock_random_switch_hit{hits==825}:  
    randomswitch:
      action: play
  logicblock_random_switch_hit{hits==900}:  
    randomswitch:
      action: play
  logicblock_random_switch_hit{hits==975}:  
    randomswitch:
      action: play
  logicblock_random_switch_hit{hits==1050}:  
    randomswitch:
      action: play
  logicblock_random_switch_hit{hits==1125}:  
    randomswitch:
      action: play      
  logicblock_random_switch_hit{hits==1200}:  
    randomswitch:
      action: play  
  logicblock_random_switch_hit{hits==1275}:  
    randomswitch:
      action: play  
  logicblock_random_switch_hit{hits==1350}:  
    randomswitch:
      action: play  
  logicblock_random_switch_hit{hits==1425}:  
    randomswitch:
      action: play  
  logicblock_random_switch_hit{hits==1500}:  
    randomswitch:
      action: play  
  logicblock_random_switch_hit{hits==1575}:  
    randomswitch:
      action: play  
  logicblock_random_switch_hit{hits==1650}:  
    randomswitch:
      action: play  
  logicblock_random_switch_hit{hits==1725}:  
    randomswitch:
      action: play  
  logicblock_random_switch_hit{hits==1800}:  
    randomswitch:
      action: play  
  logicblock_random_switch_hit{hits==1875}:  
    randomswitch:
      action: play  

  selection_mode_razorwire_highlighted:
    ModeHighlightedRazorWire:
      max_queue_time: 500ms
      action: play
  selection_mode_reversebeartrap_highlighted:
    ModeHighlightedReverseBearTrap:
      max_queue_time: 500ms
      action: play
  selection_mode_flammablejelly_highlighted: 
    ModeHighlightedFlammableJelly:
      max_queue_time: 500ms
      action: play
  selection_mode_drillchair_highlighted: 
    ModeHighlightedDrillChair:
      max_queue_time: 500ms
      action: play
  selection_mode_quadshotgun_highlighted: 
    ModeHighlightedQuadShotgun:
      max_queue_time: 500ms
      action: play
  selection_mode_zeptest_highlighted: 
    ModeHighlightedZepsTest:
      max_queue_time: 500ms
      action: play

# trap modes are lit/qualified
  mode_trap_select_started:
    ModeLit:
      action: play

# multiball audio
  multiball_mb_hacksaw_started:
    hacksaw_mb_start:
      action: play
  multiball_mb_shackle_started:
    ShackleMultiball:
      action: play
  multiball_mb_jigsaw_started:
    JigsawMultiballStart1:
      action: play

 # razorwire mode
  mode_razorwire_complete:
    trapcomplete:
      action: play
    RWModeStart:
      action: stop 
    BaseMusic:
      delay: 10s
      action: play
      loops: -1   
  player_razorwire_60s_timer_tick{value < 1}:
    RazorWireFail:
      action: play
  mode_razorwire_stopped:
    BaseMusic:
      delay: 3s
      action: play
      loops: -1 
      
 # drillchair mode     
  mode_drillchair_complete:
    trapcomplete:
      action: play
    DrillChairIntro:
      action: stop
    DrillChairModeStart:
      action: stop
    BaseMusic:
      delay: 10s
      action: play
      loops: -1      
  player_drillchair_drillchair_60s_timer_tick{value < 1}:
    DrillChairFail:
      action: play
  mode_drillchair_stopped:
    DrillChairModeStart:
      action: stop
    BaseMusic:
      delay: 3s
      action: play
      loops: -1      

# reversebeartrap mode
  mode_reversebeartrap_complete:
    trapcomplete:
      action: play
    ReverseBearTrapModeStart:
      action: stop
    BaseMusic:
      delay: 10s
      action: play
      loops: -1      
  player_reversebeartrap_120s_reversebeartrap_timer_tick{value < 1}:
    ReverseBearTrapFail:
      action: play
  mode_reversebeartrap_stopped:
    BaseMusic:
      delay: 3s
      action: play
      loops: -1      

# quadshotgun mode  
  mode_quadshotgun_complete:
    trapcomplete:
      action: play
    QuadShotgunModeStart:
      action: stop
    BaseMusic:
      delay: 10s
      action: play
      loops: -1      
  player_quadshotgun_quadshotgun_60s_timer_tick{value == 1}:
    QuadShotgunFail:
      action: play
  mode_quadshotgun_stopped:
    BaseMusic:
      delay: 3s
      action: play
      loops: -1
      
# zeptest mode
  mode_zeptest_complete:
    trapcomplete:
      action: play
    ZepsTestModeStart:
      action: stop
    BaseMusic:
      delay: 10s
      action: play
      loops: -1           
  mode_zeptest_stopped:
    BaseMusic:
      delay: 3s
      action: play
      loops: -1
 
# flammable jelly mode      
  mode_flammablejelly_complete:
    trapcomplete:
      action: play  
    FlammableJellyModeStart:
      action: stop
    BaseMusic:
      delay: 10s
      action: play
      loops: -1             
  player_flammablejelly_60s_flammablejelly_timer_tick{value < 1}:
    FlammableJellyFail:
      action: play
  mode_flammablejelly_stopped:
    BaseMusic:
      delay: 3s
      action: play
      loops: -1

  sg_saw_qualify_subtract_hit{device.counters.cnt_saw_qualify.value==1}:
    SawLetterNegative:
      action: play   
  sg_saw_qualify_subtract_hit{device.counters.cnt_saw_qualify.value==2}:
    SawLetterNegative:
      action: play

  minimode_drops_complete:
    antidote_collected:
      action: play
  minimode_scoops_complete: 
    bathtub_collected:
      action: play
  minimode_standups_complete: 
    candle_collected:
      action: play
  minimode_pops_complete: 
    gears_collected:
      action: play
  minimode_loops_complete:
    hacksaw_collected:
      action: play
  minimode_spinners_complete:
    handgun_collected:
      action: play
  minimode_ramps_complete:
    key_collected:
      action: play
  minimode_inlanes_complete:
    taperecorder_collected:
      action: play

##puzzle hurryup
#  e_puzzle_music_start:
#    PuzzlePieceHurryUp:
#      #delay: 2s
#      action: play
#    BaseMusic:
#      action: stop
  player_puzzle_hurryup_t_puzzle_timer_tick{value < 1}:
    PuzzlePieceHurryUp:
     action: stop
    BaseMusic:
      action: play
#puzzle collected
  mode_puzzle_hurryup_complete:
    PuzzlePiece:
      action: play
    #PuzzlePieceHurryUp:
    #  action: stop

#action button pressed
  shot_drillchair_button_sp_drillchair_lit_hit:
    ActionButton:
      action: play
  shot_razorwire_button_sp_razorwire_lit_hit:
    ActionButton:
      action: play
  shot_reversebeartrap_button_sp_reversebeartrap_lit_hit:
    ActionButton:
      action: play
  shot_quadshotgun_button_sp_quadshotgun_lit_hit:
    ActionButton:
      action: play
  shot_flammablejelly_button_sp_flammablejelly_lit_hit:
    ActionButton:
      action: play
  shot_zeptest_button_sp_zeptest_lit_hit:
    ActionButton:
      action: play

#make your choice hurry up
  # mode_make_your_choice_hurryup_started:
  #   LiveOrDieHurryup:
  #     action: play
  #   BaseMusic:
  #     action: stop
  player_make_your_choice_hurryup_t_make_your_choice_timer_tick{value < 1}:
    LiveOrDieHurryup:
      action: stop
    BaseMusic:
      action: play
# stop all mode music at beginning of mode_bonus
  mode_bonus_started:
    QuadShotgunModeStart:
      action: stop
    DrillChairModeStart:
      action: stop
    FlammableJellyModeStart:
      action: stop
    RWModeStart:
      action: stop
    ReverseBearTrapModeStart:
      action: stop
    ZepsTestModeStart:
      action: stop      
    BaseMusic:
      action: stop

#event_player: 
#  slide_base_slide_main_active: e_puzzle_music_off1|0.83s
#  e_puzzle_music_off1: e_puzzle_music_off2|0.1s