#config_version=5

mode:
  start_events: ball_starting
  stop_events: game_ending
  priority: 100


#sound_player:
#  mode_attract_started:
#    themesong:
#      action: play
#      loops: -1
#  mode_attract_stopped:
#    themesong:
#      action: stop