#config_version=6                 
mode:
  start_events: selection_mode_flammablejelly_selected
  stop_events: stop_mode_flammablejelly, ball_ended, player_flammablejelly_60s_flammablejelly_timer_tick{value < 1}
 
sequences:
  flammablejelly:
    events:
      - shot_right_standup_hit
      - shot_inner_loop_hit
      - shot_left_standup_hit
      - shot_right_loop_hit
      - upper_drop_target_hit     
    reset_on_complete: false
    events_when_complete: mode_flammablejelly_complete, stop_mode_flammablejelly

timers:
  60s_flammablejelly_timer:
    start_value: 70
    end_value: 0
    direction: down
    control_events:
      - action: start
        event: mode_flammablejelly_started
        
variable_player:
  logicblock_flammablejelly_hit{step==1}:
    score: 500000
  logicblock_flammablejelly_hit{step==2}:
    score: 1000000
  logicblock_flammablejelly_hit{step==3}:
    score: 1000000
  logicblock_flammablejelly_hit{step==4}:
    score: 1000000    
  mode_flammablejelly_complete:
    score: 5000000      
  timer_your_timer_tick:
    60s_flammablejelly_timer:
      int: device.timers.your_timer.ticks_remaining
      action: set        
    
slides:
  flammablejellyvideo:
    widgets:
    - type: video
      video: flammablejellyvideo 
      width: 1366
      height: 768      
      
  flammablejellyUI:
   widgets:
    - type: image
      image: hacksawUI
      opacity: 0.5
      y: 1
      x: 1
      anchor_x: left
      anchor_y: bottom
    - type: text
      text: (score)
      number_grouping: true
      y: 16
      x: 25
      font_size: 36
      anchor_x: left
      anchor_y: bottom
      font_name: TrajanProRegular
      color: FFA500
    - type: Text
      text: (player|flammablejelly_60s_flammablejelly_timer_tick) Seconds Left
      font_size: 55
      font_name: TrajanProRegular
      color: FFF700
      y: 90%
      
    - type: Text
      text: "To Find the Safe Combination:"
      font_size: 42
      font_name: TrajanProRegular
      color: FFD800
      x: 400
      y: 75%    
    - type: Text
      text: "- The First Digit is the Rightmost Stand Up"
      font_size: 32
      font_name: TrajanProRegular
      color: FFBF00
      x: 500
      y: 68%   
    - type: Text
      text: "- The Next Digit is Hidden Within the Loops"
      font_size: 32
      font_name: TrajanProRegular
      color: FFBF00
      x: 510
      y: 62%   
    - type: Text
      text: "- The Third Digit is in the Stand Ups"
      font_size: 32
      font_name: TrajanProRegular
      color: FFBF00
      x: 435
      y: 56%    
    - type: Text
      text: "- The Last Digit is Found in Another Loop"
      font_size: 32
      font_name: TrajanProRegular
      color: FFBF00
      x: 486
      y: 50%           
    - type: Text
      text: "- X marks the Spot to Input the Digits into the Safe"
      font_size: 32
      font_name: TrajanProRegular
      color: FFBF00
      x: 576
      y: 44%         
      
    - type: Text
      text: "You Have 60 Seconds To Solve the Safe Combination"
      color: FFD800
      font_name: TrajanProRegular
      font_size: 35
      y: 145
      animations:
       pre_show_slide:
        - property: opacity
          value: 0
          duration: 1s
        - property: opacity
          value: 1
          duration: 1s
          repeat: true       
    - type: image
      image: flammablejelly
      opacity: 0.45
#      width: 1366
#      height: 768 
#    transition:
#     type: fade
#     duration: 0.2s

widgets:
   flammablejelly_shot_update1:
    - type: Text
      text: X
      color: ad1400
      x: 4%
      y: 68%
      font_size: 50
      font_name: TrajanProRegular
   flammablejelly_shot_update2:
    - type: Text
      text: X
      color: ad1400
      x: 4%
      y: 62%
      font_size: 50
      font_name: TrajanProRegular
   flammablejelly_shot_update3:
    - type: Text
      text: X
      color: ad1400
      x: 4%
      y: 56%
      font_size: 50
      font_name: TrajanProRegular
   flammablejelly_shot_update4:
    - type: Text
      text: X
      color: ad1400
      x: 4%
      y: 50%
      font_size: 50
      font_name: TrajanProRegular      
    
 
widget_player:
 logicblock_flammablejelly_hit{step==1}: 
  flammablejelly_shot_update1:
    slide: flammablejellyUI
 logicblock_flammablejelly_hit{step==2}: 
  flammablejelly_shot_update2:
    slide: flammablejellyUI
 logicblock_flammablejelly_hit{step==3}: 
  flammablejelly_shot_update3:
    slide: flammablejellyUI
 logicblock_flammablejelly_hit{step==4}: 
  flammablejelly_shot_update4:
    slide: flammablejellyUI   

slide_player:
  mode_flammablejelly_started: 
    flammablejellyvideo:
      priority: 500
      expire: 10s
  slide_flammablejellyvideo_removed: 
    flammablejellyUI:
      priority: 400
      expire: 60.5s
  logicblock_flammablejelly_hit{step==4}:
    XMarksTheSpotVideo:
      priority: 406
      expire: 2.1s      

show_player:
  logicblock_flammablejelly_hit{step==4}:
      top_drop_chase:
        loops: -1
        speed: 20
        show_tokens:
          color1: red



