#config_version=6                 
mode:
  start_events: selection_mode_flammablejelly_selected
  stop_events: stop_mode_flammablejelly, ball_ended, ball_ending, ball_will_end, player_flammablejelly_60s_flammablejelly_timer_tick{value < 1}
  priority: 184
 
ball_saves:
  bs_flammablejelly:
    active_time: 5s
    hurry_up_time: 2s
#    grace_period: 2s
#    enable_events: mode_base_started
#    disable_events2: ball_save_default_disabled
    timer_start_events: player_flammablejelly_60s_flammablejelly_timer_tick{value==60}
    early_ball_save_events: sw_outlane, s_trough6_active
    auto_launch: true
    balls_to_save: 1

sequences:
  flammablejelly:
    events:
      - s_right_standup_active
      - sw_loop
      - s_left_standup_active
      #- sw_loop
      - drop_target_dt_upper_drop1_down    
    reset_on_complete: false
    persist_state: true
    disable_events: mode_flammablejelly_complete
    events_when_complete: mode_flammablejelly_complete, stop_mode_flammablejelly

timers:
  60s_flammablejelly_timer:
    start_value: 70
    end_value: 0
    direction: down
    control_events:
      - event: mode_flammablejelly_started
        action: start
      - event: shot_flammablejelly_button_sp_flammablejelly_lit_hit
        action: set_tick_interval
        value: 0.59
      - event: e_stop_candle
        action: set_tick_interval
        value: 1
      #- action: add
      #  value: 30
      #  event: shot_flammablejelly_button_sp_flammablejelly_lit_hit
  flammablejelly_3x_timer:
    start_value: 30
    end_value: 0
    direction: down
    control_events:
      - action: start
        event: shot_flammablejelly_button_sp_flammablejelly_lit_hit
        
variable_player:
  logicblock_flammablejelly_hit{step==1}:
    score: (500000 * current_player.candle_multiplier) * (current_player.pf_multiplier)
  logicblock_flammablejelly_hit{step==2}:
    score: (1000000 * current_player.candle_multiplier) * (current_player.pf_multiplier)
  logicblock_flammablejelly_hit{step==3}:
    score: (1000000 * current_player.candle_multiplier) * (current_player.pf_multiplier)
  #logicblock_flammablejelly_hit{step==4}:
  #  score: 1000000    
  mode_flammablejelly_complete:
    score: (5000000 + (current_player.candles_used * 3000000)) * (current_player.pf_multiplier)   
  timer_your_timer_tick:
    60s_flammablejelly_timer:
      int: device.timers.your_timer.ticks_remaining
      action: set      
    flammablejelly_3x_timer:
      int: device.timers.your_timer.ticks_remaining
      action: set    
# candle action button
  shot_flammablejelly_button_sp_flammablejelly_lit_hit:
    candle_multiplier:
      int: 3
      action: set  
  timer_flammablejelly_3x_timer_stopped:
    candle_multiplier:
      int: 1
      action: set
    
slides:
  flammablejellyvideo:
    widgets:
    - type: video
      video: flammablejellyvideo 
      width: 1366
      height: 768
  sl_mode_flammablejelly01:
    widgets:
    - type: video
      video: mode_flammablejelly01 
      width: 1366
      height: 768
  sl_mode_flammablejelly02:
    widgets:
    - type: video
      video: mode_flammablejelly02
      width: 1366
      height: 768
  sl_mode_flammablejelly03:
    widgets:
    - type: video
      video: mode_flammablejelly03
      width: 1366
      height: 768
  sl_mode_flammablejelly04:
    widgets:
    - type: video
      video: mode_flammablejelly04
      width: 1366
      height: 768
  FlammableJellyModeShot1:
    widgets:
    - type: video
      video: FlammableJellyModeShot1
      width: 1366
      height: 768
      
  flammablejellyUI:
   widgets:
    - type: Text
      text: "To Find the Safe Combination:"
      font_size: 50
      font_name: TrajanProRegular
      outline_color: black
      outline_width: 7
      color: FFD800
      x: 50%
      y: 62%  
      z: 1
    - type: image
      image: hacksawUI
      opacity: 0.5
      y: 1
      x: 1
      anchor_x: left
      anchor_y: bottom
    - type: text
      text: (score)
      number_grouping: true
      y: 16
      x: 25
      font_size: 36
      anchor_x: left
      anchor_y: bottom
      font_name: TrajanProRegular
      color: FFA500
    - type: Text
      text: (player|flammablejelly_60s_flammablejelly_timer_tick) Seconds Left
      font_size: 55
      font_name: TrajanProRegular
      color: FFF700
      y: 90%     
    - type: Text
      text: "You Have 60 Seconds To Solve the Safe Combination"
      color: FFD800
      font_name: TrajanProRegular
      font_size: 35
      y: 145
      animations:
       pre_show_slide:
        - property: opacity
          value: 0
          duration: 1s
        - property: opacity
          value: 1
          duration: 1s
          repeat: true       
    - type: image
      image: flammablejelly
      opacity: 0.45
#      width: 1366
#      height: 768 
#    transition:
#     type: fade
#     duration: 0.2s

widgets:
   w_flammablejellyUI:
    - type: image
      image: hacksawUI
      opacity: 1.0
      y: 1
      x: 1
      z: 2
      anchor_x: left
      anchor_y: bottom
    - type: text
      text: (score)
      number_grouping: true
      y: 16
      x: 25
      z: 2
      font_size: 36
      anchor_x: left
      anchor_y: bottom
      font_name: TrajanProRegular
      color: FFA500
    - type: Text
      text: 00:(player|flammablejelly_60s_flammablejelly_timer_tick)
      font_size: 100
      font_name: digitalclockfont
      color: red
      x: 50%
      y: 83.2%
      z: 2
    - type: rectangle
      width: 420
      height: 130
      x: 50%
      y: 84.5%
      z: 2
      corner_radius: 20
      corner_segments: 20
      color: black

   flammablejelly_shot_update1:            
    - type: Text
      text: " The First Digit is the Rightmost Stand Up"
      font_size: 50
      font_name: TrajanProRegular
      outline_color: black
      outline_width: 7
      color: FFBF00
      x: 50%
      y: 48%   
      z: 1
      animations:
        add_to_slide:
          - property: opacity
            value: 0
          - property: opacity
            value: 1
            duration: 1000ms
            timing: after_previous
   flammablejelly_shot_update2:  
    - type: Text
      text: " The Next Digit is Hidden Within the Orbits"
      font_size: 50
      font_name: TrajanProRegular
      outline_color: black
      outline_width: 7
      color: FFBF00
      x: 50%
      y: 48%   
      z: 1
      animations:
        add_to_slide:
          - property: opacity
            value: 0
          - property: opacity
            value: 1
            duration: 1000ms
            timing: after_previous
   flammablejelly_shot_update3:  
    - type: Text
      text: " The Third Digit is the Leftmost Stand Up"
      font_size: 50
      font_name: TrajanProRegular
      outline_color: black
      outline_width: 7
      color: FFBF00
      x: 50%
      y: 48%  
      z: 1
      animations:
        add_to_slide:
          - property: opacity
            value: 0
          - property: opacity
            value: 1
            duration: 1000ms
            timing: after_previous      
   #flammablejelly_shot_update4:  
   # - type: Text
   #   text: " The Last Digit is Found in the Orbits"
   #   font_size: 50
   #   font_name: TrajanProRegular
   #   outline_color: black
   #   outline_width: 7
   #   color: FFBF00
   #   x: 50%
   #   y: 48%           
   #   z: 1
   #   animations:
   #     add_to_slide:
   #       - property: opacity
   #         value: 0
   #       - property: opacity
   #         value: 1
   #         duration: 1000ms
   #         timing: after_previous
   flammablejelly_shot_update5:  
    - type: Text
      text: " X marks the Spot to Input"
      font_size: 50
      font_name: TrajanProRegular
      outline_color: black
      outline_width: 7
      color: FFBF00
      x: 50%
      y: 48%         
      z: 1
      animations:
        add_to_slide:
          - property: opacity
            value: 0
          - property: opacity
            value: 1
            duration: 1000ms
            timing: after_previous   
    - type: Text
      text: " the Digits into the Safe"
      font_size: 50
      font_name: TrajanProRegular
      outline_color: black
      outline_width: 7
      color: FFBF00
      x: 50%
      y: 40%         
      z: 1
      animations:
        add_to_slide:
          - property: opacity
            value: 0
          - property: opacity
            value: 1
            duration: 1000ms
            timing: after_previous 
   w_candle_button:
    - type: image
      image: CandleButtonImg
      x: 95%
      y: 20%
      z: 2     
    - type: Text
      text: (player|flammablejelly_flammablejelly_3x_timer_tick)
      font_size: 30
      font_name: Mustkill
      outline_color: black
      outline_width: 7
      color: FFBF00
      x: 88%
      y: 8%   
      z: 2
    - type: Text
      text: 3X
      font_size: 45
      font_name: Mustkill
      outline_color: black
      outline_width: 7
      color: FFBF00
      x: 88%
      y: 3%      
      z: 2
    
 
widget_player:
 player_flammablejelly_60s_flammablejelly_timer_tick{value==60}: 
  w_flammablejellyUI:
    slide: sl_mode_flammablejelly01
    action: add
 logicblock_flammablejelly_updated{value==1}:
  w_flammablejellyUI:
    slide: sl_mode_flammablejelly02
    action: add
 logicblock_flammablejelly_updated{value==2}:
  w_flammablejellyUI:
    slide: sl_mode_flammablejelly03
    action: add
 slide_sl_mode_flammablejelly04_active:
  w_flammablejellyUI:
    slide: sl_mode_flammablejelly04
    action: add
 # flammablejelly_shot_update4:
 #   slide: flammablejellyUI
 #   action: add
 #logicblock_flammablejelly_hit{step==4}: 
 # flammablejelly_shot_update4:
 #   slide: flammablejellyUI
 #   action: remove
  flammablejelly_shot_update5:
    slide: flammablejellyUI      
    action: add
 shot_flammablejelly_button_sp_flammablejelly_lit_hit:
  w_candle_button:
    slide: sl_mode_flammablejelly01
    action: add
 slide_sl_mode_flammablejelly02_active{current_player.candles_used==1}:
   w_candle_button:
     slide: sl_mode_flammablejelly02
     action: add
 slide_sl_mode_flammablejelly03_active{current_player.candles_used==1}:
   w_candle_button:
     slide: sl_mode_flammablejelly03
     action: add
 slide_sl_mode_flammablejelly04_active{current_player.candles_used==1}:
   w_candle_button:
     slide: sl_mode_flammablejelly04
     action: add
 timer_flammablejelly_3x_timer_stopped:
  w_candle_button:
    slide: sl_mode_flammablejelly01
    action: remove
 e_jelly_3x_slide02_off:
  w_candle_button:
    slide: sl_mode_flammablejelly02
    action: remove
 e_jelly_3x_slide03_off:
  w_candle_button:
    slide: sl_mode_flammablejelly03
    action: remove
 e_jelly_3x_slide04_off:
  w_candle_button:
    slide: sl_mode_flammablejelly04
    action: remove

slide_player:
  mode_flammablejelly_started: 
    flammablejellyvideo:
      priority: 500
      expire: 10s
  slide_flammablejellyvideo_removed: 
    sl_mode_flammablejelly01:
      priority: 400
      expire: 60.5s
  logicblock_flammablejelly_updated{value==1}:
    sl_mode_flammablejelly01:
     action: remove
    sl_mode_flammablejelly02:
      priority: 400
      expire: 60.5s
  logicblock_flammablejelly_updated{value==2}:
    sl_mode_flammablejelly02:
     action: remove
    sl_mode_flammablejelly03:
      priority: 400
      expire: 60.5s
  #logicblock_flammablejelly_hit{step==4}:
  logicblock_flammablejelly_updated{value==3}:
    sl_mode_flammablejelly03:
     action: remove
    XMarksTheSpotVideo:
      priority: 406
      expire: 2.1s    
    sl_mode_flammablejelly04:
      priority: 400
      expire: 60.5s
  ball_save_bs_flammablejelly_saving_ball:
    ballsavevideo:
      action: play
      priority: 400
      expire: 5s
  logicblock_flammablejelly_hit{step==1}:
    FlammableJellyModeShot1:
      action: play
      priority: 401
      expire: 2.4s
  logicblock_flammablejelly_hit{step==2}:
    FlammableJellyModeShot1:
      action: play
      priority: 401
      expire: 2.4s

shows:
  sh_flammablejelly_ballsave:
    - duration: 0.5s
      lights:
        (leds): drillchair
    - duration: 0.5s
      lights:
        (leds): off
  sh_flammablejelly_ballsave_end:
    - duration: -1
      lights:
        (leds): off  
  flammablejelly_progress_p1:    
    - duration: 1s
      lights:
        (leds): (color1)
    - duration: 1s
      lights:
        (leds): off
  flammablejelly_progress_p2:    
    - duration: 1s
      lights:
        (leds): (color1)
    - duration: 1s
      lights:
        (leds): off
  flammablejelly_mode:
    - duration: 0.15s
      lights:
        (leds): jelly
    - duration: 0.15s
      lights:
        (leds): off

show_player:
  player_flammablejelly_60s_flammablejelly_timer_tick{value==62}:
    mystery_flash:
      loops: 0
      speed: 5
      show_tokens:
        led: l_mystery_scoop
        color1: white

  player_flammablejelly_60s_flammablejelly_timer_tick{value==60}:
    sh_flammablejelly_ballsave:
      show_tokens:
        leds: l_live_again
      loops: 4
  ball_save_bs_flammablejelly_disabled:
    sh_flammablejelly_ballsave_end:
      show_tokens:
        leds: l_live_again
      loops: -1
#mode progress lights
  logicblock_flammablejelly_updated{value==0}:
      flammablejelly_progress_p1:
        loops: -1
        show_tokens:
          leds: l_right_standup_arrow
          color1: jelly
  logicblock_flammablejelly_updated{value==1}:
      fire_starposts:
        loops: 1
        speed: 20
        priority: 170
      speaker_flammable_jelly:
        loops: 1
        speed: 20
      flammablejelly_progress_p1:
        loops: -1
        show_tokens:
          leds: l_right_standup_arrow
          color1: off
      flammablejelly_progress_p2:
        loops: -1
        show_tokens:
          leds: orbit
          color1: jelly
  logicblock_flammablejelly_updated{value==2}:
      fire_starposts:
        loops: 1
        speed: 20
        priority: 170
      speaker_flammable_jelly:
        loops: 1
        speed: 20
      flammablejelly_progress_p2:
        loops: -1
        show_tokens:
          leds: orbit
          color1: off
      fire_top_pops:
        loops: -1
        speed: 30
      flammablejelly_progress_p1:
        loops: -1
        show_tokens:
          leds: l_left_standup_arrow
          color1: jelly
  #logicblock_flammablejelly_hit{step==3}:
      #fire_starposts:
      #  loops: 1
      #  speed: 20
      #  priority: 170
      #flammablejelly_progress_p1:
      #  loops: -1
      #  show_tokens:
      #    leds: l_left_standup_arrow
      #    color1: off
      #flammablejelly_progress_p2:
      #  loops: -1
      #  show_tokens:
      #    leds: orbit
      #    color1: jelly
  logicblock_flammablejelly_updated{value==3}:
      top_drop_chase:
        loops: -1
        speed: 14
        show_tokens:
          color1: jelly
      fire_starposts:
        loops: 1
        speed: 20
        priority: 170
      speaker_flammable_jelly:
        loops: 1
        speed: 20
      fire_top_pops:
        loops: -1
        speed: 30
      flammablejelly_progress_p1:
        loops: -1
        show_tokens:
          leds: l_left_standup_arrow
          color1: off
  #logicblock_flammablejelly_hit{step==4}:
  #    fire_starposts:
  #      loops: 1
  #      speed: 20
  #      priority: 170
  #    top_drop_chase:
  #      loops: -1
  #      speed: 14
  #      show_tokens:
  #        color1: jelly
  #    flammablejelly_progress_p2:
  #      loops: -1
  #      show_tokens:
  #        leds: orbit
  #        color1: off
  #    fire_bottom_pops:
  #      loops: -1
  #      speed: 30

  mode_flammablejelly_started:    
    flipper_on:
      show_tokens:
        color1: jelly
    starpost_on:
      show_tokens:
        color1: 6E6E6E   
      priority: 169  
    gi_on:
      show_tokens:
        color1: jelly
    flammablejelly_mode:
      show_tokens:
        leds: l_jelly_mode   
    speaker_heartbeat:
      show_tokens:
        color1: jelly
    trough_on:
      show_tokens:
        color1: jelly
    cabinet_heartbeat:
      show_tokens:
        color1: jelly
    topper_heartbeat:
      show_tokens:
        color1: jelly

  player_flammablejelly_60s_flammablejelly_timer_tick{value==50}:
    speaker_heartbeat:
      speed: 2
      show_tokens:
        color1: jelly
  player_flammablejelly_60s_flammablejelly_timer_tick{value==40}:
    speaker_heartbeat:
      speed: 3
      show_tokens:
        color1: jelly
  player_flammablejelly_60s_flammablejelly_timer_tick{value==30}:
    speaker_heartbeat:
      speed: 4
      show_tokens:
        color1: jelly
  player_flammablejelly_60s_flammablejelly_timer_tick{value==20}:
    speaker_heartbeat:
      speed: 5
      show_tokens:
        color1: jelly
  player_flammablejelly_60s_flammablejelly_timer_tick{value==10}:
    speaker_heartbeat:
      speed: 6
      show_tokens:
        color1: jelly
  player_flammablejelly_60s_flammablejelly_timer_tick{value==5}:
    speaker_heartbeat:
      speed: 9
      show_tokens:
        color1: jelly

  player_flammablejelly_60s_flammablejelly_timer_tick{value < 1}:
    fire_starposts: stop
    fire_top_pops: stop
    fire_bottom_pops: stop
    flipper_on: stop
    speaker_heartbeat: stop
    cabinet_heartbeat: stop
    topper_heartbeat: stop

sound_pools:
  flammablejelly_mode_sound_pool:
    load: preload
    type: random
    track: sfx
    sounds:
      - FJ1
      - FJ2
      - FJ3
      - FJ4
      - FJ5
      - FJ6
      - FJ7
      - FJ8
      - FJ9

sound_player:
  mode_flammablejelly_started:
    FlammableJellyIntro:
      action: play
  player_flammablejelly_60s_flammablejelly_timer_tick{value==61}:
    FlammableJellyModeStart:
      action: play        
  player_flammablejelly_60s_flammablejelly_timer_tick{value < 1}:
    FlammableJellyModeStart:
      action: stop

  sw_top_pops:
    flammablejelly_mode_sound_pool:
      action: play
      block: true
  sw_bottom_pops:
    flammablejelly_mode_sound_pool:
      action: play
      block: true
  sw_slingshot:
    flammablejelly_mode_sound_pool:
      action: play
      block: true    
  sw_standup:
    flammablejelly_mode_sound_pool:
      action: play
      block: true
  sw_right_return_lane:
    flammablejelly_mode_sound_pool:
      action: play
      block: true
  sw_lower_drop_target:
    flammablejelly_mode_sound_pool:
      action: play
      block: true

event_player: 
  slide_sl_mode_flammablejelly01_active: e_primary_mode_active
  mode_flammablejelly_stopping{mode.shackle_multiball.active==True}: e_mode_qualify_disabled|0.5s
  mode_flammablejelly_stopping{mode.jigsaw_multiball.active==True}: e_mode_qualify_disabled|0.5s
  mode_flammablejelly_stopping{mode.hacksaw_multiball.active==True}: e_mode_qualify_disabled|0.5s
  shot_flammablejelly_button_sp_flammablejelly_lit_hit: e_stop_candle|20s, e_start_candle_multiplier|10s
  timer_flammablejelly_3x_timer_stopped:
    - e_jelly_3x_slide02_off|0.3s
    - e_jelly_3x_slide03_off|0.6s
    - e_jelly_3x_slide04_off|0.9s