#config_version=6                 
mode:
  start_events: selection_mode_flammablejelly_selected
  stop_events: stop_mode_flammablejelly, ball_ended, ball_ending, ball_will_end, player_flammablejelly_60s_flammablejelly_timer_tick{value < 1}
  priority: 110
 
sequences:
  flammablejelly:
    events:
      - s_right_standup_active
      - sw_loop
      - s_left_standup_active
      - sw_loop
      - drop_target_dt_upper_drop1_down    
    reset_on_complete: false
    events_when_complete: mode_flammablejelly_complete, stop_mode_flammablejelly

timers:
  60s_flammablejelly_timer:
    start_value: 70
    end_value: 0
    direction: down
    control_events:
      - action: start
        event: mode_flammablejelly_started
        
variable_player:
  logicblock_flammablejelly_hit{step==1}:
    score: 500000
  logicblock_flammablejelly_hit{step==2}:
    score: 1000000
  logicblock_flammablejelly_hit{step==3}:
    score: 1000000
  logicblock_flammablejelly_hit{step==4}:
    score: 1000000    
  mode_flammablejelly_complete:
    score: 5000000      
  timer_your_timer_tick:
    60s_flammablejelly_timer:
      int: device.timers.your_timer.ticks_remaining
      action: set        
    
slides:
  flammablejellyvideo:
    widgets:
    - type: video
      video: flammablejellyvideo 
      width: 1366
      height: 768      
      
  flammablejellyUI:
   widgets:
    - type: Text
      text: "To Find the Safe Combination:"
      font_size: 50
      font_name: TrajanProRegular
      outline_color: black
      outline_width: 7
      color: FFD800
      x: 50%
      y: 62%  
      z: 1
    - type: image
      image: hacksawUI
      opacity: 0.5
      y: 1
      x: 1
      anchor_x: left
      anchor_y: bottom
    - type: text
      text: (score)
      number_grouping: true
      y: 16
      x: 25
      font_size: 36
      anchor_x: left
      anchor_y: bottom
      font_name: TrajanProRegular
      color: FFA500
    - type: Text
      text: (player|flammablejelly_60s_flammablejelly_timer_tick) Seconds Left
      font_size: 55
      font_name: TrajanProRegular
      color: FFF700
      y: 90%     
    - type: Text
      text: "You Have 60 Seconds To Solve the Safe Combination"
      color: FFD800
      font_name: TrajanProRegular
      font_size: 35
      y: 145
      animations:
       pre_show_slide:
        - property: opacity
          value: 0
          duration: 1s
        - property: opacity
          value: 1
          duration: 1s
          repeat: true       
    - type: image
      image: flammablejelly
      opacity: 0.45
#      width: 1366
#      height: 768 
#    transition:
#     type: fade
#     duration: 0.2s

widgets:
   flammablejelly_shot_update1:            
    - type: Text
      text: " The First Digit is the Rightmost Stand Up"
      font_size: 50
      font_name: TrajanProRegular
      outline_color: black
      outline_width: 7
      color: FFBF00
      x: 50%
      y: 48%   
      z: 1
      animations:
        add_to_slide:
          - property: opacity
            value: 0
          - property: opacity
            value: 1
            duration: 1000ms
            timing: after_previous
   flammablejelly_shot_update2:  
    - type: Text
      text: " The Next Digit is Hidden Within the Orbits"
      font_size: 50
      font_name: TrajanProRegular
      outline_color: black
      outline_width: 7
      color: FFBF00
      x: 50%
      y: 48%   
      z: 1
      animations:
        add_to_slide:
          - property: opacity
            value: 0
          - property: opacity
            value: 1
            duration: 1000ms
            timing: after_previous
   flammablejelly_shot_update3:  
    - type: Text
      text: " The Third Digit is the Leftmost Stand Up"
      font_size: 50
      font_name: TrajanProRegular
      outline_color: black
      outline_width: 7
      color: FFBF00
      x: 50%
      y: 48%  
      z: 1
      animations:
        add_to_slide:
          - property: opacity
            value: 0
          - property: opacity
            value: 1
            duration: 1000ms
            timing: after_previous      
   flammablejelly_shot_update4:  
    - type: Text
      text: " The Last Digit is Found in the Orbits"
      font_size: 50
      font_name: TrajanProRegular
      outline_color: black
      outline_width: 7
      color: FFBF00
      x: 50%
      y: 48%           
      z: 1
      animations:
        add_to_slide:
          - property: opacity
            value: 0
          - property: opacity
            value: 1
            duration: 1000ms
            timing: after_previous
   flammablejelly_shot_update5:  
    - type: Text
      text: " X marks the Spot to Input"
      font_size: 50
      font_name: TrajanProRegular
      outline_color: black
      outline_width: 7
      color: FFBF00
      x: 50%
      y: 48%         
      z: 1
      animations:
        add_to_slide:
          - property: opacity
            value: 0
          - property: opacity
            value: 1
            duration: 1000ms
            timing: after_previous   
    - type: Text
      text: " the Digits into the Safe"
      font_size: 50
      font_name: TrajanProRegular
      outline_color: black
      outline_width: 7
      color: FFBF00
      x: 50%
      y: 40%         
      z: 1
      animations:
        add_to_slide:
          - property: opacity
            value: 0
          - property: opacity
            value: 1
            duration: 1000ms
            timing: after_previous   
    
 
widget_player:
 logicblock_flammablejelly_updated{value==0}: 
  flammablejelly_shot_update1:
    slide: flammablejellyUI
    action: add
 logicblock_flammablejelly_hit{step==1}: 
  flammablejelly_shot_update1:
    slide: flammablejellyUI
    action: remove
  flammablejelly_shot_update2:
    slide: flammablejellyUI
    action: add
 logicblock_flammablejelly_hit{step==2}: 
  flammablejelly_shot_update2:
    slide: flammablejellyUI
    action: remove
  flammablejelly_shot_update3:
    slide: flammablejellyUI
    action: add
 logicblock_flammablejelly_hit{step==3}: 
  flammablejelly_shot_update3:
    slide: flammablejellyUI
    action: remove
  flammablejelly_shot_update4:
    slide: flammablejellyUI
    action: add
 logicblock_flammablejelly_hit{step==4}: 
  flammablejelly_shot_update4:
    slide: flammablejellyUI
    action: remove
  flammablejelly_shot_update5:
    slide: flammablejellyUI      
    action: add

slide_player:
  mode_flammablejelly_started: 
    flammablejellyvideo:
      priority: 500
      expire: 10s
  slide_flammablejellyvideo_removed: 
    flammablejellyUI:
      priority: 400
      expire: 60.5s
  logicblock_flammablejelly_hit{step==4}:
    XMarksTheSpotVideo:
      priority: 406
      expire: 2.1s      

show_player:
  logicblock_flammablejelly_hit{step==4}:
      top_drop_chase:
        loops: -1
        speed: 20
        show_tokens:
          color1: red

  mode_flammablejelly_started:     
    gi_on:
      show_tokens:
        color1: jelly

sound_pools:
  flammablejelly_mode_sound_pool:
    load: preload
    type: random
    track: sfx
    sounds:
      - FJ1
      - FJ2
      - FJ3
      - FJ4
      - FJ5
      - FJ6
      - FJ7
      - FJ8
      - FJ9

sound_player:
  mode_flammablejelly_started:
    flammablejelly:
      action: play
    FlammableJellyModeStart:
      delay: 10s
      action: play        
  player_flammablejelly_60s_flammablejelly_timer_tick{value < 1}:
    FlammableJellyModeStart:
      action: stop

  sw_top_pops:
    flammablejelly_mode_sound_pool:
      action: play
      block: true
  sw_bottom_pops:
    flammablejelly_mode_sound_pool:
      action: play
      block: true
  sw_slingshot:
    flammablejelly_mode_sound_pool:
      action: play
      block: true    
  sw_standup:
    flammablejelly_mode_sound_pool:
      action: play
      block: true
  sw_right_return_lane:
    flammablejelly_mode_sound_pool:
      action: play
      block: true
  sw_lower_drop_target:
    flammablejelly_mode_sound_pool:
      action: play
      block: true

event_player: 
  slide_flammablejellyUI_active: e_primary_mode_active