#config_version=5                 
mode:
  start_events: selection_mode_drillchair_selected
  stop_events: stop_mode_drillchair, mode_drillchair_complete, ball_ended
 
timers:
  drillchair_60s_timer:
    start_value: 69
    end_value: 0
    direction: down
    control_events:
      - action: start
        event: mode_drillchair_started

counters:
  drillchair_spinner_counter:
    starting_count: 0
    count_complete_value: 30
    enable_events: enable_qualify
    disable_events: disable_qualify
    start_enabled: true
#    persist_state: true
    reset_on_complete: false
    events_when_complete: mode_drillchair_complete, stop_mode_drillchair
    count_events: spinner_hit
 

#shot_groups:
#  spinner:
#    shots: spinner
    

variable_player:
  spinner_hit:
    score: 20
  counter_drillchair_spinner_counter_hit:
    drillchair_spinner_counter:
      action: set
      int: (count)*23
    drillchair_visual_spinner_counter:
      action: set
      int: (count)
       
  timer_your_timer_tick:
    drillchair_60s_timer:
      int: device.timers.your_timer.ticks_remaining
      action: set
 
slides:
  drillchairvideo:
    widgets:
    - type: video
      video: drillchairvideo  
      
  drillchair_spinner:
    widgets:
    - type: Text
      text: Shoot The Spinners!
      font_name: TrajanProRegular
      font_size: 75
      color: d8d8d8
      
    - type: image
      image: hacksawUI
      opacity: 0.5
      y: 1
      x: 1
      anchor_x: left
      anchor_y: bottom
    - type: text
      text: (score)
      number_grouping: true
      y: 16
      x: 25
      font_size: 36
      anchor_x: left
      anchor_y: bottom
      font_name: TrajanProRegular
      color: d8d8d8
      
    - type: Text
      text: 00:(player|drillchair_drillchair_60s_timer_tick)
      font_size: 100
      font_name: digitalclockfont
      color: red
      x: 50%
      y: 83.2%
    - type: rectangle
      width: 420
      height: 130
      x: 50%
      y: 84.5%
      corner_radius: 20
      corner_segments: 20
      color: black
      
    - type: rectangle
      width: 0
      height: 45
      x: 25%
      y: 180
      anchor_x: left
      corner_radius: 10
      corner_segments: 10
      color: 940008
      animations:
        player_drillchair_spinner_counter:
         - property: width
           value: (value)           
    - type: rectangle
      width: 685
      height: 46
      x: 50%
      y: 180
      color: black
      corner_radius: 10
      corner_segments: 10
      
#    - type: Text
#      text: Seconds Left
#      font_size: 50
#      font_name: TrajanProRegular
#      color: 65fe08
#      x: 825
#      y: 85%
    - type: Text
# work on displaying the count of spins
      text: (player|drillchair_visual_spinner_counter) / 30 Spins
      font_size: 50
      font_name: TrajanProRegular
      color: d8d8d8
      y: 35%
    - type: Text
      text: You Have 60 Seconds To Hit 30 Spins
      color: 940008
      font_name: TrajanProRegular
      font_size: 35
      y: 17%
      animations:
       pre_show_slide:
        - property: opacity
          value: 0
          duration: 1s
        - property: opacity
          value: 1
          duration: 1s
          repeat: true
    - type: image
      image: drillchairimg
      opacity: 0.65
    transition:
     type: fade
     duration: 0.2s
  
#shots:
#  spinner:
#    switch: s_spinner

      
slide_player:
  mode_drillchair_started: 
    drillchairvideo:
      priority: 500
      expire: 8.7s
  slide_drillchairvideo_removed: 
    drillchair_spinner:
      priority: 400
      expire: 66.5s
