#config_version=6                 
mode:
  start_events: selection_mode_quadshotgun_selected
  stop_events: stop_mode_quadshotgun, mode_quadshotgun_complete, ball_ended, ball_will_end, player_quadshotgun_quadshotgun_60s_timer_tick{value < 1}
  priority: 181
 
sequences:
  quadshotgun_phase2:
    events:
      - ssh_left_orbit_hit
    reset_on_complete: false
    persist_state: true
    enable_events: quadshotgun_spinner_complete
    disable_events: mode_quadshotgun_complete
    events_when_complete: mode_quadshotgun_complete, stop_mode_quadshotgun
 
timers:
  quadshotgun_60s_timer:
    start_value: 68
    end_value: 0
    direction: down
    control_events:
      - action: start
        event: mode_quadshotgun_started

counters:
  quadshotgun_spinner_counter:
    starting_count: 0
    count_complete_value: 25
    enable_events: mode_quadshotgun_started
    disable_events: quadshotgun_spinner_complete, logicblock_quadshotgun_phase2_updated{enabled==True}
#    start_enabled: true
    persist_state: true
    reset_on_complete: false
    events_when_complete: quadshotgun_spinner_complete 
    count_events: spinner_spinner_hit

#shots:
#  spinner:
#    switch: s_spinner   

variable_player:
  quadshotgun_spinner_complete:
    score: 2500000
  mode_quadshotgun_complete:
    score: 6000000 
  counter_quadshotgun_spinner_counter_hit:
    quadshotgun_spinner_counter:
      action: set
      int: (count)*28
    quadshotgun_visual_spinner_counter:
      action: set
      int: (count)
       
  timer_your_timer_tick:
    quadshotgun_60s_timer:
      int: device.timers.your_timer.ticks_remaining
      action: set
 
slides:
  quadshotgunvideo:
    widgets:
    - type: video
      video: quadshotgunvideo  
      width: 1366
      height: 768      
      
  quadshotgun_spinner:
    widgets:
    - type: Text
      text: Rip the Spinner!
      font_name: TrajanProRegular
      font_size: 75
      outline_color: black
      outline_width: 7
      color: d8d8d8
      animations:
        add_to_slide:
          - property: opacity
            value: 0
          - property: opacity
            value: 1
            duration: 1000ms
            timing: after_previous
      
    - type: image
      image: hacksawUI
      opacity: 0.5
      y: 1
      x: 1
      anchor_x: left
      anchor_y: bottom
    - type: text
      text: (score)
      number_grouping: true
      y: 16
      x: 25
      font_size: 36
      anchor_x: left
      anchor_y: bottom
      font_name: TrajanProRegular
      color: "006ee6"
      
    - type: Text
      text: 00:(player|quadshotgun_quadshotgun_60s_timer_tick)
      font_size: 100
      font_name: digitalclockfont
      color: red
      x: 50%
      y: 83.2%
    - type: rectangle
      width: 420
      height: 130
      x: 50%
      y: 84.5%
      corner_radius: 20
      corner_segments: 20
      color: black
      
    - type: rectangle
      width: 0
      height: 45
      x: 25%
      y: 180
      anchor_x: left
      corner_radius: 10
      corner_segments: 10
      color: "006ee6"
      animations:
        player_quadshotgun_spinner_counter:
         - property: width
           value: (value)           
    - type: rectangle
      width: 685
      height: 46
      x: 50%
      y: 180
      color: black
      corner_radius: 10
      corner_segments: 10
      
#    - type: Text
#      text: Seconds Left
#      font_size: 50
#      font_name: TrajanProRegular
#      color: 65fe08
#      x: 825
#      y: 85%
    - type: Text
      text: (player|quadshotgun_visual_spinner_counter) / 25 spins
      font_size: 50
      font_name: TrajanProRegular
      outline_color: black
      outline_width: 7
      color: d8d8d8
      y: 35%
    - type: Text
      text: You Have 60 Seconds To Hit 25 Spins!
      color: "006ee6"
      font_name: TrajanProRegular
      font_size: 35
      y: 17%
      animations:
       pre_show_slide:
        - property: opacity
          value: 0
          duration: 1s
        - property: opacity
          value: 1
          duration: 1s
          repeat: true
    - type: image
      image: quadshotgunimg
      opacity: 0.65
    transition:
     type: fade
     duration: 0.2s
 
  quadshotgun_phase2:
    widgets:     
    - type: Text
      text: " Hit The Left Orbit To Escape"
      font_size: 80
      font_name: TrajanProRegular
      outline_color: black
      outline_width: 7
      color: d8d8d8 
      x: 50%
      y: 62%
      animations:
        add_to_slide:
          - property: opacity
            value: 0
          - property: opacity
            value: 1
            duration: 1000ms
            timing: after_previous
    - type: Text
      text: " & Complete The Trap"
      font_size: 80
      font_name: TrajanProRegular
      outline_color: black
      outline_width: 7
      color: d8d8d8
      x: 50%
      y: 48%
      animations:
        add_to_slide:
          - property: opacity
            value: 0
          - property: opacity
            value: 1
            duration: 1000ms
            timing: after_previous
      
    - type: image
      image: hacksawUI
      opacity: 0.5
      y: 1
      x: 1
      anchor_x: left
      anchor_y: bottom
    - type: text
      text: (score)
      number_grouping: true
      y: 16
      x: 25
      font_size: 36
      anchor_x: left
      anchor_y: bottom
      font_name: TrajanProRegular
      color: "006ee6"
      
    - type: Text
      text: 00:(player|quadshotgun_quadshotgun_60s_timer_tick)
      font_size: 100
      font_name: digitalclockfont
      color: red
      x: 50%
      y: 83.2%
    - type: rectangle
      width: 420
      height: 130
      x: 50%
      y: 84.5%
      corner_radius: 20
      corner_segments: 20
      color: black
                
    - type: image
      image: quadshotgunimg
      opacity: 0.4
    transition:
     type: fade
     duration: 0.2s


      
slide_player:
  mode_quadshotgun_started: 
    quadshotgunvideo:
      priority: 500
      expire: 7.8s 
  slide_quadshotgunvideo_removed:  
    quadshotgun_spinner:
      priority: 400
      expire: 64.5s
  quadshotgun_spinner_complete:
    quadshotgun_phase2:
      priority: 405
      expire: 64.5s
  logicblock_quadshotgun_phase2_updated{enabled==True}:
    quadshotgun_phase2:
      priority: 405
      expire: 64.5s
      
#widgets:
#   quadshotgun_shot_update2:
#    - type: Text
#      text: X
#      color: "006ee6"
#      x: 5.5%
#      y: 52%
#      font_size: 70
#      font_name: TrajanProRegular

 
#widget_player:
# logicblock_quadshotgun_hit{step==2}: 
#  quadshotgun_shot_update2:
#    slide: quadshotgun_phase2


#EK added 
shows:
  quadshotgun_progress:    
    - duration: 1s
      lights:
        (leds): (color1)
    - duration: 1s
      lights:
        (leds): off
  quadshotgun_mode:
    - duration: 0.15s
      lights:
        (leds): shotgun
    - duration: 0.15s
      lights:
        (leds): off

show_player:
  mode_quadshotgun_started:     
    gi_on:
      show_tokens:
        color1: shotgun
    quadshotgun_mode:
      show_tokens:
        leds: l_quadshotgun_mode
    starpost_on:
      show_tokens:
        color1: 6E6E6E   
      priority: 169
    speaker_heartbeat:
      show_tokens:
        color1: shotgun
    flipper_on:
      show_tokens:
        color1: shotgun
    trough_on:
      show_tokens:
        color1: shotgun
    cabinet_heartbeat:
      show_tokens:
        color1: shotgun
    topper_heartbeat:
      show_tokens:
        color1: shotgun

#  player_quadshotgun_quadshotgun_60s_timer_tick{value == 67}: 
  logicblock_quadshotgun_spinner_counter_updated{value<20}:
    flash_token:
      loops: -1
      speed: 8
      show_tokens:
        led: l_right_loop_arrow
        color1: shotgun

  player_quadshotgun_quadshotgun_60s_timer_tick{value==50}: 
    speaker_heartbeat:
      speed: 2
      show_tokens:
        color1: shotgun
  player_quadshotgun_quadshotgun_60s_timer_tick{value==40}: 
    speaker_heartbeat:
      speed: 3
      show_tokens:
        color1: shotgun
  player_quadshotgun_quadshotgun_60s_timer_tick{value==30}: 
    flash_token:
      loops: -1
      speed: 16
      show_tokens:
        led: l_right_loop_arrow
        color1: shotgun     
    speaker_heartbeat:
      speed: 4
      show_tokens:
        color1: shotgun
  player_quadshotgun_quadshotgun_60s_timer_tick{value==20}: 
    speaker_heartbeat:
      speed: 5
      show_tokens:
        color1: shotgun
  player_quadshotgun_quadshotgun_60s_timer_tick{value==10}: 
    speaker_heartbeat:
      speed: 6
      show_tokens:
        color1: shotgun
  player_quadshotgun_quadshotgun_60s_timer_tick{value==5}: 
    speaker_heartbeat:
      speed: 9
      show_tokens:
        color1: shotgun

  player_quadshotgun_quadshotgun_60s_timer_tick{value == 1}: 
    shotgun_blast:
      speed: 20

  spinner_hit:
    flash_token:
      loops: 2
      speed: 8
      show_tokens:
        led: l_shotgun_flasher_4
        color1: shotgun

  quadshotgun_spinner_complete:
      flash_token:
        loops: -1
        show_tokens:
          leds: l_right_loop_arrow
          color1: off
      quadshotgun_progress:
        loops: -1
        show_tokens:
          leds: l_left_loop_arrow
          color1: shotgun
  logicblock_quadshotgun_phase2_updated{enabled==True}:
      flash_token:
        show_tokens:
          leds: l_right_loop_arrow
          color1: off
      quadshotgun_progress:
        loops: -1
        show_tokens:
          leds: l_left_loop_arrow
          color1: shotgun

    

  logicblock_quadshotgun_spinner_counter_hit{count==1}:
      starpost_cycle:
        loops: 1
        speed: 20
        show_tokens:
          color1: shotgun
        priority: 170  
      shotgun_blast_top_pops:
        loops: 0
        speed: 30
  logicblock_quadshotgun_spinner_counter_hit{count==6}:
      starpost_cycle:
        loops: 1
        speed: 20
        show_tokens:
          color1: shotgun
        priority: 170  
      shotgun_blast_top_pops:
        loops: 0
        speed: 30
  logicblock_quadshotgun_spinner_counter_hit{count==12}:
      starpost_cycle:
        loops: 1
        speed: 20
        show_tokens:
          color1: shotgun
        priority: 170  
      shotgun_blast_top_pops:
        loops: 0
        speed: 30
  logicblock_quadshotgun_spinner_counter_hit{count==19}:
      starpost_cycle:
        loops: 1
        speed: 20
        show_tokens:
          color1: shotgun
        priority: 170  
      shotgun_blast_top_pops:
        loops: 0
        speed: 30

sound_pools:
  quadshotgun_mode_sound_pool:
    load: preload
    type: random
    track: sfx
    sounds:
      - QS1
      - QS2
      - QS3
      - QS4
      - QS5
      - QS7

  quadshotgun_gears_sound_pool:
    load: preload
    type: random
    track: sfx
    sounds:
      - MoleDrillGears8
      - MoleDrillGears30
      - MoleDrillGears36

sound_player:
  mode_quadshotgun_started:
    QuadShotgunIntro:
      action: play
    QuadShotgunModeStart:
      delay: 6.3s
      action: play
  player_quadshotgun_quadshotgun_60s_timer_tick{value < 1}:
    QuadShotgunModeStart:
      action: stop

  sw_top_pops:
    quadshotgun_gears_sound_pool:
      action: play
      block: true
  sw_bottom_pops:
    quadshotgun_gears_sound_pool:
      action: play
      block: true
  sw_slingshot:
    quadshotgun_mode_sound_pool:
      action: play
      block: true    
  sw_standup:
    quadshotgun_mode_sound_pool:
      action: play
      block: true
  sw_right_return_lane:
    quadshotgun_mode_sound_pool:
      action: play
      block: true
  sw_lower_drop_target:
    quadshotgun_mode_sound_pool:
      action: play
      block: true

   
event_player: 
  slide_quadshotgun_spinner_active: e_primary_mode_active