#config_version=6
##! mode: shackle_multiball

mode:
  start_events: logicblock_shackle_multiball_qualify_complete
  stop_events: stop_mode_shackle_multiball, mode_shackle_multiball_complete, multiball_mb_shackle_ended
  priority: 182

#multiball_locks:
#  mbl_shackle:
#    #debug: true
#    balls_to_lock: 2
#    lock_devices: bd_top_saucer
#    enable_events: logicblock_acc_shackle_mb_qualify_complete
#      #disable_events: sg_lockshot_complete{state=="unlit"}
#      #reset_count_for_current_player_events: multiball_lock_sword_multiball_lock_full

multiballs:
  mb_shackle:
    ball_count: 2
    shoot_again: 10s
    start_events: start_shackle_multiball
    add_a_ball_events: shot_add_a_ball_button_sp_add_a_ball_button_lit_hit
    ball_locks: bd_top_saucer
    # replace_balls_in_play: true
timers:
  t_shackle_value_timer:
    start_value: 300
    end_value: 0
    direction: down
    tick_interval: 0.1s
    control_events:
      - action: start
        event: multiball_mb_shackle_started
      - action: stop
        event: drop_target_dt_upper_drop1_down

variable_player:
  #multiball_mb_shackle_started:
    #score: 3000000
  shot_shackle_left_loop_sp_shackle_mb_lit_hit:
    score: (1000000 + (device.timers.t_shackle_value_timer.ticks * 5331)) * (current_player.pf_multiplier)
  shot_shackle_left_standup_sp_shackle_mb_lit_hit:
    score: (1000000 + (device.timers.t_shackle_value_timer.ticks * 5331)) * (current_player.pf_multiplier)
  shot_shackle_left_standup_rightramp_sp_shackle_mb_lit_hit:
    score: (1000000 + (device.timers.t_shackle_value_timer.ticks * 5331)) * (current_player.pf_multiplier)
  shot_shackle_right_standup_rightramp_sp_shackle_mb_lit_hit:
    score: (1000000 + (device.timers.t_shackle_value_timer.ticks * 5331)) * (current_player.pf_multiplier)
  shot_shackle_right_loop_sp_shackle_mb_lit_hit:
    score: (1000000 + (device.timers.t_shackle_value_timer.ticks * 5331)) * (current_player.pf_multiplier)
  shot_shackle_right_standup_sp_shackle_mb_lit_hit:
    score: (1000000 + (device.timers.t_shackle_value_timer.ticks * 5331)) * (current_player.pf_multiplier)

  shot_shackle_superjackpot1_sp_shackle_mb_lit_hit:
    score: (1000000 + (device.timers.t_shackle_value_timer.ticks * 5331 * 3)) * (current_player.pf_multiplier) 
  shot_shackle_superjackpot2_sp_shackle_mb_lit_hit:
    score: (1000000 + (device.timers.t_shackle_value_timer.ticks * 5331 * 3)) * (current_player.pf_multiplier) 

  player_shackle_multiball_t_shackle_value_timer_tick:
    shackle_value_countdown:
      int: 1000000 + (device.timers.t_shackle_value_timer.ticks * 5331)
      action: set

  multiball_mb_shackle_started:
    shackle_value:
      int: 0
      action: set
    shackle_super_value:
      int: 0
      action: set
  shackle_value_locked:
    shackle_value:
      int: 1000000 + (device.timers.t_shackle_value_timer.ticks * 5331)
      action: set
    shackle_super_value:
      int: 1000000 + (device.timers.t_shackle_value_timer.ticks * 5331 * 3) 
      action: set
  
counters:
  cnt_shackle_mb_jackpot_p1:
    starting_count: 0
    count_complete_value: 6
    enable_events: slide_sl_ShackleMB_active
#    persist_state: true
    reset_on_complete: true
    disable_on_complete: false   
    count_events: shot_shackle_left_loop_sp_shackle_mb_lit_hit, shot_shackle_left_standup_sp_shackle_mb_lit_hit, shot_shackle_left_standup_rightramp_sp_shackle_mb_lit_hit, shot_shackle_right_standup_rightramp_sp_shackle_mb_lit_hit, shot_shackle_right_loop_sp_shackle_mb_lit_hit, shot_shackle_right_standup_sp_shackle_mb_lit_hit
    events_when_complete: shackle_mb_jackpot_p1_complete

# currently set to jackpot set + super + jackpot set + super
  cnt_shackle_phase_tracking:
    starting_count: 0
    count_complete_value: 2
    start_enabled: true
    events_when_complete: shackle_phase2
    count_events: sg_shackle_p1_lit_complete

  cnt_shackle_jackpot:
    starting_count: 0
    count_complete_value: 1
    start_enabled: true
    events_when_complete: shackle_value_locked  
    count_events: drop_target_dt_upper_drop1_down

slides:
  sl_ShackleMB:
    widgets:
    - type: video
      video: shackleMB
      width: 1366
      height: 768 
  sl_ShackleMB_Jackpot:
    widgets:
    - type: video
      video: jackpot_shackle
  sl_ShackleMB_SuperJackpot:
    widgets:
    - type: video
      video: superjackpot_shackle

slide_player:
  multiball_mb_shackle_started:
    sl_ShackleMB:
      priority: 600
      expire: 7s
  sg_shackle_p1_lit_hit:
    sl_ShackleMB_Jackpot:
      priority: 600
      expire: 2.2s
  shot_shackle_superjackpot1_sp_shackle_mb_lit_hit:
    sl_ShackleMB_SuperJackpot:
      priority: 600
      expire: 2.2s
  shot_shackle_superjackpot2_sp_shackle_mb_lit_hit:
    sl_ShackleMB_SuperJackpot:
      priority: 600
      expire: 2.2s

show_player:
  multiball_mb_shackle_started:
    disc_right_chase:
      loops: -1
      speed: 10
      show_tokens:
        color1: beartrap
    disc_middle_chase:
      loops: -1
      speed: 10
      show_tokens:
        color1: beartrap
    disc_left_chase:
      loops: -1
      speed: 10
      show_tokens:
        color1: beartrap

    top_drop_chase:
      loops: -1
      speed: 14
      show_tokens:
        color1: beartrap
  shackle_value_locked:
    top_drop_chase: stop

  shot_add_a_ball_button_sp_add_a_ball_button_lit_hit:
    disc_middle_add_a_ball:
      loops: 3
      speed: 10
    speaker_extra_ball_left:
      loops: 3
      speed: 10
    speaker_extra_ball_right:
      loops: 3
      speed: 10


  sg_shackle_p1_lit_hit:
    colorwash_opposite_glitter:
      speed: 20

  mode_shackle_multiball_complete:
      disc_left_chase: stop
      disc_middle_chase: stop
      disc_right_chase: stop
  ball_ending:
      disc_left_chase: stop
      disc_middle_chase: stop
      disc_right_chase: stop
  shackle_mb_jackpot_p1_complete:
      top_drop_chase:
        loops: -1
        speed: 20
        show_tokens:
          color1: beartrap
  shot_shackle_superjackpot1_sp_shackle_mb_lit_hit:
      top_drop_chase:
        loops: -1
        show_tokens:
          color1: off
      colorwash_opposite_glitter:
        speed: 20
  shot_shackle_superjackpot2_sp_shackle_mb_lit_hit:
      top_drop_chase:
        loops: -1
        show_tokens:
          color1: off
      colorwash_opposite_glitter:
        speed: 20
  e_jackpot_show_off:
      colorwash_opposite_glitter: stop
  
  stop_mode_shackle_multiball: 
    w_shackle_multiball: stop
  start_shackle_multiball:
    mb_ballsave:
      loops: 9
coil_player:
  multiball_mb_shackle_started:
    c_left_spin_disc:
      action: enable
      hold_power: 1.0
    c_middle_spin_disc:
      action: enable
      hold_power: 1.0
    c_right_spin_disc:
      action: enable
      hold_power: 1.0
  mode_shackle_multiball_complete:
    c_right_spin_disc:
      action: off
    c_middle_spin_disc:
      action: off
    c_left_spin_disc:
      action: off
  ball_ending:
    c_right_spin_disc:
      action: off
    c_middle_spin_disc:
      action: off
    c_left_spin_disc:
      action: off

shots:
  shot_shackle_left_loop:
    reset_events: mode_shackle_multiball_stopped, player_turn_stopped, player_turn_ended
    switches: s_left_loop_bottom, s_left_loop_top
    profile: sp_shackle_mb
    show_tokens:
      leds: l_left_loop_arrow
    control_events:
      - events: ball_starting
        state: 0
      - events: shackle_value_locked
        state: 1
      - events: shot_shackle_left_loop_sp_shackle_mb_lit_hit
        state: 0
      - events: shot_shackle_superjackpot1_sp_shackle_mb_lit_hit
        state: 1
  shot_shackle_left_standup:
    reset_events: mode_shackle_multiball_stopped, player_turn_stopped, player_turn_ended
    switches: s_left_standup
    profile: sp_shackle_mb
    show_tokens:
      leds: l_left_standup_arrow
    control_events:
      - events: ball_starting
        state: 0
      - events: shackle_value_locked
        state: 1
      - events: shot_shackle_left_standup_sp_shackle_mb_lit_hit
        state: 0
      - events: shot_shackle_superjackpot1_sp_shackle_mb_lit_hit
        state: 1
  shot_shackle_left_standup_rightramp:
    reset_events: mode_shackle_multiball_stopped, player_turn_stopped, player_turn_ended
    switches: s_left_standup_right_ramp
    profile: sp_shackle_mb
    show_tokens:
      leds: l_left_standup_right_ramp_arrow
    control_events:
      - events: ball_starting
        state: 0
      - events: shackle_value_locked
        state: 1
      - events: shot_shackle_left_standup_rightramp_sp_shackle_mb_lit_hit
        state: 0
      - events: shot_shackle_superjackpot1_sp_shackle_mb_lit_hit
        state: 1
  shot_shackle_right_standup_rightramp:
    reset_events: mode_shackle_multiball_stopped, player_turn_stopped, player_turn_ended
    switches: s_right_standup_right_ramp
    profile: sp_shackle_mb
    show_tokens:
      leds: l_right_standup_right_ramp_arrow
    control_events:
      - events: ball_starting
        state: 0
      - events: shackle_value_locked
        state: 1
      - events: shot_shackle_right_standup_rightramp_sp_shackle_mb_lit_hit
        state: 0
      - events: shot_shackle_superjackpot1_sp_shackle_mb_lit_hit
        state: 1
  shot_shackle_right_loop:
    reset_events: mode_shackle_multiball_stopped, player_turn_stopped, player_turn_ended
    switches: s_right_loop_bottom, s_right_loop_top
    profile: sp_shackle_mb
    show_tokens:
      leds: l_right_loop_arrow
    control_events:
      - events: ball_starting
        state: 0
      - events: shackle_value_locked
        state: 1
      - events: shot_shackle_right_loop_sp_shackle_mb_lit_hit
        state: 0
      - events: shot_shackle_superjackpot1_sp_shackle_mb_lit_hit
        state: 1
  shot_shackle_right_standup:
    reset_events: mode_shackle_multiball_stopped, player_turn_stopped, player_turn_ended
    switches: s_right_standup
    profile: sp_shackle_mb
    show_tokens:
      leds: l_right_standup_arrow
    control_events:
      - events: ball_starting
        state: 0
      - events: shackle_value_locked
        state: 1
      - events: shot_shackle_right_standup_sp_shackle_mb_lit_hit
        state: 0
      - events: shot_shackle_superjackpot1_sp_shackle_mb_lit_hit
        state: 1
  shot_shackle_superjackpot1:
    reset_events: mode_shackle_multiball_stopped, player_turn_stopped, player_turn_ended
    switches: s_upper_bank_drop_target_opto
    profile: sp_shackle_mb
    control_events:
      - events: ball_starting
        state: 0
      - events: shackle_value_locked
        state: 1
      - events: shot_shackle_superjackpot1_sp_shackle_mb_lit_hit
        state: 0
  shot_shackle_superjackpot2:
    reset_events: mode_shackle_multiball_stopped, player_turn_stopped, player_turn_ended
    switches: s_upper_bank_drop_target_opto
    profile: sp_shackle_mb
    control_events:
      - events: ball_starting
        state: 0
      - events: shackle_phase2
        state: 1
      - events: shot_shackle_superjackpot2_sp_shackle_mb_lit_hit
        state: 0

shot_profiles:
  sp_shackle_mb:
    advance_on_hit: false
    states:
      - name: shackle_not_ready
        show: "sh_shackle_not_ready"
      - name: lit
        show: "sh_shackle_on"           # a default show to turn of the led. change if you want to do something on unlit shots
      #- name: collected
      #  show: "sh_shackle_off"               # a default show to turn of the led. change if you want to do something on unlit shots

shot_groups:
  sg_shackle_p1:
    shots: shot_shackle_left_loop, shot_shackle_left_standup, shot_shackle_left_standup_rightramp, shot_shackle_right_standup_rightramp, shot_shackle_right_loop, shot_shackle_right_standup


shows:
  sh_shackle_on:    # define our show to indicate the state
    - duration: 0.3s
      lights:
        (leds): beartrap
    - duration: 0.3s
      lights:
        (leds): off
  sh_shackle_not_ready:    # define our show to indicate the state
    - duration: 0.3s
      lights:
        (leds): off

sound_player:
  sg_shackle_p1_lit_hit:
    Jackpot:
      action: play
  shot_shackle_superjackpot1_sp_shackle_mb_lit_hit:
    SuperJackpot:
      action: play

widgets:
  w_shackle_multiball:
    - type: Text
      text: Shackle Multiball - Shoot RED ARROWS to collect JACKPOTS
      color: black
      x: 50%
      y: 92%
      z: 2
      font_size: 40
      font_name: AeroMaticsDisplaRegular
      outline_color: white
      outline_width: 1
  w_shackle_multiball_value:
    - type: text
      text: (player|shackle_value)
      number_grouping: true 
      x: 50%
      y: 28%
      z: 7
      font_size: 90
      font_name: Mustkill     
      outline_color: black
      outline_width: 7
  w_shackle_multiball_SuperJackpot_value:
    - type: text
      text: (player|shackle_super_value) 
      number_grouping: true 
      x: 50%
      y: 28%
      z: 7
      font_size: 90
      font_name: Mustkill     
      outline_color: black
      outline_width: 7

  w_shackle_value:
    - type: text
      text: X Marks the Spot to lock in Jackpot Value
      x: 50%
      y: 45%
      z: 7
      font_size: 50
      font_name: Mustkill     
      outline_color: black
      outline_width: 7
    - type: text
      text: (player|shackle_value_countdown)
      number_grouping: true 
      x: 50%
      y: 35%
      z: 7
      font_size: 110
      font_name: Mustkill     
      outline_color: black
      outline_width: 7
      #animations:
      #  add_to_slide:
      #    - property: opacity
      #      value: 0
      #      duration: 1s
      #    - property: opacity
      #      value: 1
      #      duration: 1s
      #      repeat: true
  w_shackle_value_locked:
    - type: text
      text: Jackpot Value Locked
      x: 50%
      y: 45%
      z: 7
      font_size: 50
      font_name: Mustkill     
      outline_color: black
      outline_width: 7
    - type: text
      text: (player|shackle_value_countdown)
      number_grouping: true 
      x: 50%
      y: 35%
      z: 7
      font_size: 110
      font_name: Mustkill     
      outline_color: black
      outline_width: 7

widget_player:
  multiball_mb_shackle_started:
    w_shackle_multiball:
      slide: base_slide_main
      action: add
    w_shackle_value:
      slide: base_slide_main
      action: add
  stop_mode_shackle_multiball:
    w_shackle_multiball:
      action: remove
    w_shackle_value:
      action: remove
  mode_shackle_multiball_complete:
    w_shackle_multiball:  
      action: remove
    w_shackle_value:
      action: remove  
  ball_ended:
    w_shackle_multiball:
      action: remove
    w_shackle_value:
      action: remove
  shackle_value_locked:
    w_shackle_value:
      action: remove
    w_shackle_value_locked:
      slide: base_slide_main
      action: add

  stop_shackle_jackpot_widget:
    w_shackle_value_locked:
      action: remove

  sg_shackle_p1_lit_hit:
    w_shackle_multiball_value:
      slide: sl_ShackleMB_Jackpot
      action: add
  #stop_jackpot_widget:
  #  w_shackle_multiball_value:
  #    action: remove
  #  w_shackle_multiball_SuperJackpot_value:
  #    action: remove
  shot_shackle_superjackpot1_sp_shackle_mb_lit_hit:
    w_shackle_multiball_SuperJackpot_value:
      slide: sl_ShackleMB_SuperJackpot
      action: add  

event_player:
  mode_shackle_multiball_started: 
    - start_shackle_multiball|0.3s
    - e_mb_mode_active
  shackle_value_locked: stop_shackle_jackpot_widget|2s
  sg_shackle_p1_lit_hit: stop_jackpot_widget|2.3s, e_jackpot_show_off|1s
  shot_shackle_superjackpot1_sp_shackle_mb_lit_hit: stop_jackpot_widget|3s, e_jackpot_show_off|1s
  shot_shackle_superjackpot2_sp_shackle_mb_lit_hit: e_jackpot_show_off|1s
  mode_shackle_multiball_stopping: e_mb_mode_stopping