#config_version=6
##! mode: shackle_multiball

mode:
  start_events: startmode_shackle_multiball
  stop_events: stop_mode_shackle_multiball, mode_shackle_multiball_complete
  priority: 175

multiball_locks:
  mbl_shackle:
    #debug: true
    balls_to_lock: 2
    lock_devices: bd_top_saucer
    enable_events: logicblock_acc_shackle_mb_qualify_complete
      #disable_events: sg_lockshot_complete{state=="unlit"}
      #reset_count_for_current_player_events: multiball_lock_sword_multiball_lock_full

multiballs:
  mb_shackle:
    ball_count: 2
    shoot_again: 15s
    start_events: multiball_lock_mbl_shackle_full
    ball_locks: bd_top_saucer
    # replace_balls_in_play: true

variable_player:
  #multiball_mb_shackle_started:
    #score: 3000000

slides:
  sl_ShackleMB:
    widgets:
    - type: video
      video: shackleMB
      width: 1366
      height: 768 

slide_player:
  multiball_mb_shackle_started:
    sl_ShackleMB:
      priority: 600
      expire: 7s

show_player:
  multiball_mb_shackle_started:
    disc_right_chase:
      loops: -1
      speed: 10
      show_tokens:
        color1: beartrap
    disc_middle_chase:
      loops: -1
      speed: 10
      show_tokens:
        color1: beartrap
    disc_left_chase:
      loops: -1
      speed: 10
      show_tokens:
        color1: beartrap
  mode_shackle_multiball_complete:
      disc_left_chase: stop
      disc_middle_chase: stop
      disc_right_chase: stop
  ball_ending:
      disc_left_chase: stop
      disc_middle_chase: stop
      disc_right_chase: stop
coil_player:
  multiball_mb_shackle_started:
    c_left_spin_disc:
      action: enable
      hold_power: 1.0
    c_middle_spin_disc:
      action: enable
      hold_power: 1.0
    c_right_spin_disc:
      action: enable
      hold_power: 1.0
  mode_shackle_multiball_complete:
    c_right_spin_disc:
      action: off
    c_middle_spin_disc:
      action: off
    c_left_spin_disc:
      action: off
  ball_ending:
    c_right_spin_disc:
      action: off
    c_middle_spin_disc:
      action: off
    c_left_spin_disc:
      action: off